### ISSUE TITLE
Messaging service is not running

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#7855] opened 2021-09-20 06:56 UTC
**Describe the bug**

It seems we are closing the resources not in the correct order. We still accept or want to send an response but the message service is closed concurrently and the sending fails and causes on error on closing the Broker.

Occurred 10 times in two error groups within `1.2.0-alpha2`

Error groups:

 * https://console.cloud.google.com/errors/CJeh5tGzv8X1Rg?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911
 * https://console.cloud.google.com/errors/CKKJ762u3J3ZUw?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

**To Reproduce**

I assume run the service and close the broker.

**Expected behavior**

No error, correct sequence of closing resources.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Messaging service is not running.
at io.camunda.zeebe.transport.impl.AtomixClientTransportAdapter.tryToSend (AtomixClientTransportAdapter.java:105)
at io.camunda.zeebe.transport.impl.AtomixClientTransportAdapter.lambda$handleResponse$7 (AtomixClientTransportAdapter.java:206)
at io.camunda.zeebe.util.sched.ActorJob.invoke (ActorJob.java:76)
at io.camunda.zeebe.util.sched.ActorJob.execute (ActorJob.java:39)
at io.camunda.zeebe.util.sched.ActorTask.execute (ActorTask.java:122)
at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask (ActorThread.java:94)
at io.camunda.zeebe.util.sched.ActorThread.doWork (ActorThread.java:78)
at io.camunda.zeebe.util.sched.ActorThread.run (ActorThread.java:191)
```

</p>
</details>

**Environment:**

 - Zeebe Version: 1.2.0-alpha2

**Comment by Zelldon** [comment] 2021-09-20 06:59
Error message introduce via https://github.com/camunda-cloud/zeebe/pull/7568

**Comment by Zelldon** [comment] 2021-09-20 07:01
related https://github.com/camunda-cloud/zeebe/issues/5521

**Comment by Zelldon** [comment] 2021-10-06 12:14
@pihme do you think this is solved due to recent refactorings?

**Comment by pihme** [comment] 2021-10-06 12:38
@Zelldon No I don't. The order of atomix and embedded gateway has not changed by the refactoring. One thing I wonder is whether this occurred in the Broker or in a Standalone Gateway. Do you know where it occurred?

In terms of macro-order of shutdown steps this should not happen.
 
It could happen if either shutdown of the actor does not cancel all subsequent planned tasks. Or it could happen if it is possible to schedule new tasks after an actor has been shutdown.

**Comment by pihme** [comment] 2022-01-17 15:48
Reoccurred recently:

Logs:
```
D 2022-01-16T09:29:16.098476Z Closing Broker-0 [6/10]: embedded gateway closed in 15 ms 
I 2022-01-16T09:29:16.098659Z Closing Broker-0 [7/10]: cluster services 
D 2022-01-16T09:29:16.098802Z Closing Broker-0 [7/10]: cluster services closed in 0 ms 
I 2022-01-16T09:29:16.098978Z Closing Broker-0 [8/10]: subscription api 
D 2022-01-16T09:29:16.102018Z Closing Broker-0 [8/10]: subscription api closed in 2 ms 
I 2022-01-16T09:29:16.102259Z Closing Broker-0 [9/10]: command api transport and handler 
I 2022-01-16T09:29:16.232428Z Stopped 
D 2022-01-16T09:29:16.233107Z Closing Broker-0 [9/10]: command api transport and handler closed in 131 ms 
I 2022-01-16T09:29:16.233481Z Closing Broker-0 [10/10]: Migrated Startup Steps 
D 2022-01-16T09:29:16.235563Z Shutdown was called with context: io.camunda.zeebe.broker.bootstrap.BrokerStartupContextImpl@36539fa 
I 2022-01-16T09:29:16.235975Z Shutdown Cluster Services (Creation) 
I 2022-01-16T09:29:16.238984Z Stopped 
I 2022-01-16T09:29:16.240144Z Stopped 
I 2022-01-16T09:29:16.241539Z 0 - Member deactivated: Member{id=0, address=zeebe-0.zeebe-broker-service.0bbb3676-e3ad-445b-891e-0e1350800e41-zeebe.svc.cluster.local:26502, properties={brokerInfo=EADJAAAAAwAAAAAAAgAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGlfAAAAemVlYmUtMC56ZWViZS1icm9rZXItc2VydmljZS4wYmJiMzY3Ni1lM2FkLTQ0NWItODkxZS0wZTEzNTA4MDBlNDEtemVlYmUuc3ZjLmNsdXN0ZXIubG9jYWw6MjY1MDEFAAIBAAAAAQIAAAABDAAABQAAADEuMi45BQACAQAAAAECAAAAAQ==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}} 
I 2022-01-16T09:29:16.241947Z Stopped 
I 2022-01-16T09:29:16.242539Z Local node Member{id=0, address=zeebe-0.zeebe-broker-service.0bbb3676-e3ad-445b-891e-0e1350800e41-zeebe.svc.cluster.local:26502, properties={brokerInfo=EADJAAAAAwAAAAAAAgAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGlfAAAAemVlYmUtMC56ZWViZS1icm9rZXItc2VydmljZS4wYmJiMzY3Ni1lM2FkLTQ0NWItODkxZS0wZTEzNTA4MDBlNDEtemVlYmUuc3ZjLmNsdXN0ZXIubG9jYWw6MjY1MDEFAAIBAAAAAQIAAAABDAAABQAAADEuMi45BQACAQAAAAECAAAAAQ==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}} left the bootstrap servide 
I 2022-01-16T09:29:16.243398Z Stopped cluster membership service for member Member{id=0, address=zeebe-0.zeebe-broker-service.0bbb3676-e3ad-445b-891e-0e1350800e41-zeebe.svc.cluster.local:26502, properties={brokerInfo=EADJAAAAAwAAAAAAAgAAAAMAAAADAAAAAAABCgAAAGNvbW1hbmRBcGlfAAAAemVlYmUtMC56ZWViZS1icm9rZXItc2VydmljZS4wYmJiMzY3Ni1lM2FkLTQ0NWItODkxZS0wZTEzNTA4MDBlNDEtemVlYmUuc3ZjLmNsdXN0ZXIubG9jYWw6MjY1MDEFAAIBAAAAAQIAAAABDAAABQAAADEuMi45BQACAQAAAAECAAAAAQ==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}} 
E 2022-01-16T09:29:18.270930Z Expected to handle gRPC request, but an unexpected error occurred 
E 2022-01-16T09:29:18.272130Z Expected to handle gRPC request, but an unexpected error occurred 
E 2022-01-16T09:29:18.273074Z Expected to handle gRPC request, but an unexpected error occurred 
I 2022-01-16T09:29:18.362961Z Stopped 
I 2022-01-16T09:29:18.363819Z Stopped 
I 2022-01-16T09:29:18.365121Z Shutdown monitoring services 
D 2022-01-16T09:29:18.366707Z Finished shutdown process 
D 2022-01-16T09:29:18.367117Z Closing Broker-0 [10/10]: Migrated Startup Steps closed in 2134 ms 
I 2022-01-16T09:29:18.367404Z Closing Broker-0 succeeded. Closed 10 steps in 2419 ms. 
I 2022-01-16T09:29:18.367629Z Broker shut down. 
D 2022-01-16T09:29:18.367920Z Closing actor thread ground 'Broker-0-zb-fs-workers' 
D 2022-01-16T09:29:18.368650Z Closing actor thread ground 'Broker-0-zb-actors' 
D 2022-01-16T09:29:18.369899Z Closing actor thread ground 'Broker-0-zb-actors': closed successfully 
D 2022-01-16T09:29:18.369957Z Closing actor thread ground 'Broker-0-zb-fs-workers': closed successfully 
```

**Comment by Zelldon** [comment] 2022-07-06 09:42
This happened again on our benchmark week 27

https://console.cloud.google.com/errors/detail/CJ-difGB-LXsAg;service=zeebe;version=medic-cw-27-56ad2b36c8-benchmark;time=P7D?project=zeebe-io

**Comment by korthout** [comment] 2022-07-19 08:45
Happened again on benchmark week 27 ([newly reported error](https://console.cloud.google.com/errors/detail/CK6Khe-c7YzlFw;service=zeebe;version=medic-cw-27-56ad2b36c8-benchmark;time=P7D?project=zeebe-io)) with a different stacktrace. 

This time because of `AtomixClientTransportAdapter.lambda$sendRequestInternal$2` instead of `AtomixClientTransportAdapter.lambda$handleResponse$7`.

**Comment by Zelldon** [comment] 2022-12-29 07:05
Last seen: 1 day ago.

**Comment by oleschoenburg** [comment] 2023-03-08 07:27
Happened again on 8.1.8: https://console.cloud.google.com/errors/detail/CK6Khe-c7YzlFw;service=zeebe;time=P7D?project=camunda-cloud-240911

**Comment by Zelldon** [comment] 2023-08-17 07:54
Happened in [zeebe:8.0.19-SNAPSHOT-stable-8.0-c326e93b](https://console.cloud.google.com/errors/detail/CKKJ762u3J3ZUw;service=zeebe;version=8.0.19-SNAPSHOT-stable-8.0-c326e93b;time=P7D?project=camunda-saas-int-chaos)

https://console.cloud.google.com/errors/detail/CKKJ762u3J3ZUw;service=zeebe;time=P7D?project=camunda-saas-int-chaos

**Comment by deepthidevaki** [comment] 2023-09-01 07:07
Observed in 8.2.12

Root cause analysis:

The error message originates in `AtomixClientTransportAdapter`. This is created in Gateway BrokerClient

https://github.com/camunda/zeebe/blob/18657c586a1974f6bb3ce3f86c1e16359458050d/gateway/src/main/java/io/camunda/zeebe/gateway/impl/broker/BrokerClientImpl.java#L64

But never closed by it
https://github.com/camunda/zeebe/blob/0945c3088629e5a72b260778c104418afb113b08/gateway/src/main/java/io/camunda/zeebe/gateway/impl/broker/BrokerClientImpl.java#L70-L87

Fix:
Messaging service is only closed after BrokerClient (I guess so because the lifecycle is managed by Spring, so the dependency order should be preserved). So closing `AtomixClientTransportAdapter` when closing `BrokerClientImpl` should ensure that no request are send after it is closed.

**Comment by oleschoenburg** [comment] 2023-09-29 12:38
Observed again on 8.1.16: https://console.cloud.google.com/errors/detail/CK6Khe-c7YzlFw;service=zeebe;time=P7D?project=camunda-saas-int-chaos

**Comment by megglos** [comment] 2023-10-05 12:05
ZDP-Triage:
- mostly noise during shutdown
- maybe the close is not sync

**Closed** 2024-05-06 12:42 UTC
Labels: kind/bug, scope/broker, severity/low, component/transport, version:8.2.13, version:8.1.16, version:8.3.0-alpha5, version:8.3.0-alpha6, version:8.3.0, component/zeebe
