### ISSUE TITLE
IllegalStateException: Unexpected position

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#8017] opened 2021-10-18 12:21 UTC
**Describe the bug**
Observed in benchmark logs: https://console.cloud.google.com/errors/CLrc5aeIuMGltQE?service=zeebe-broker&version=medic-cw-41-7667b0460f-benchmark&time=P7D&project=zeebe-io

**Expected behavior**
Append positions are increasing

**Log/Stacktrace**
<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Unexpected position 1086007669 was encountered after position 1086007688 when appending positions <1086007669, 1086007669>.
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:564) ~[zeebe-atomix-cluster-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$8(LeaderRole.java:544) ~[zeebe-atomix-cluster-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:174) ~[zeebe-atomix-utils-1.3.0-SNAPSHOT.jar:1.3.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
```

</p>
</details>

<details><summary>Log (edited after improved filters)</summary>
 <p>

```
I 2021-10-17T01:41:11.771635Z Registering Partition Manager 
I 2021-10-17T01:41:11.773890Z Starting partitions 
I 2021-10-17T01:41:11.918718Z Startup RocksDB metric timer 
I 2021-10-17T01:41:11.922529Z Transition to LEADER on term 11 requested. 
I 2021-10-17T01:41:11.927453Z Transition to LEADER on term 11 starting 
I 2021-10-17T01:41:11.927890Z Transition to LEADER on term 11 - transitioning LogStorage 
I 2021-10-17T01:41:11.930549Z Transition to LEADER on term 11 - transitioning LogStream 
I 2021-10-17T01:41:11.937782Z Transition to LEADER on term 11 - transitioning ZeebeDb 
I 2021-10-17T01:41:12.201144Z Transition to LEADER on term 11 - transitioning QueryService 
I 2021-10-17T01:41:12.310182Z Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@18dd4970)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@2bcbbdbf, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@118fd8ff, configuration: Configuration(false)] 
I 2021-10-17T01:41:12.588183Z Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@6a0407a2)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@1c619b4a, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@7f4b498b, configuration: Configuration(false)] 
I 2021-10-17T01:41:12.621276Z Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@6c4262dd)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@657c74ed, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@4ef1b6c6, configuration: Configuration(false)] 
I 2021-10-17T01:41:12.636419Z Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@50903979)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@7f21aa8b, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@4966149c, configuration: Configuration(false)] 
I 2021-10-17T01:41:12.718749Z Transition to LEADER on term 11 - transitioning SnapshotDirector 
I 2021-10-17T01:41:12.722093Z Transition to LEADER on term 11 - transitioning ExporterDirector 
I 2021-10-17T01:41:12.737572Z Transition to LEADER on term 11 completed 
I 2021-10-17T01:41:13.134470Z Exporter opened 
I 2021-10-17T01:41:23.333110Z Transition to LEADER on term 11 requested. 
I 2021-10-17T01:41:23.334843Z Received cancel signal for transition to LEADER on term 11 
I 2021-10-17T01:41:23.335228Z Prepare transition from LEADER on term 11 to LEADER 
I 2021-10-17T01:41:23.336866Z Prepare transition from LEADER on term 11 to LEADER - preparing ExporterDirector 
I 2021-10-17T01:41:23.392685Z Exporter closed 
I 2021-10-17T01:41:23.395144Z Prepare transition from LEADER on term 11 to LEADER - preparing SnapshotDirector 
I 2021-10-17T01:41:23.396075Z Prepare transition from LEADER on term 11 to LEADER - preparing StreamProcessor 
I 2021-10-17T01:41:23.397199Z Prepare transition from LEADER on term 11 to LEADER - preparing QueryService 
I 2021-10-17T01:41:23.397998Z Prepare transition from LEADER on term 11 to LEADER - preparing ZeebeDb 
I 2021-10-17T01:41:23.398558Z Prepare transition from LEADER on term 11 to LEADER - preparing LogStream 
I 2021-10-17T01:41:23.399108Z Close appender for log stream logstream-raft-partition-partition-3 
I 2021-10-17T01:41:23.400582Z On closing logstream logstream-raft-partition-partition-3 close 2 readers 
I 2021-10-17T01:41:23.401274Z Prepare transition from LEADER on term 11 to LEADER - preparing LogStorage 
I 2021-10-17T01:41:23.401704Z Preparing transition from LEADER on term 11 completed 
I 2021-10-17T01:41:23.401975Z Transition to LEADER on term 11 starting 
I 2021-10-17T01:41:23.402222Z Transition to LEADER on term 11 - transitioning LogStorage 
I 2021-10-17T01:41:23.402542Z Transition to LEADER on term 11 - transitioning LogStream 
I 2021-10-17T01:41:23.403172Z Transition to LEADER on term 11 - transitioning ZeebeDb 
I 2021-10-17T01:41:23.593930Z Transition to LEADER on term 11 - transitioning QueryService 
I 2021-10-17T01:41:23.594982Z Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@50ed27e0)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@43f52161, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@2b507500, configuration: Configuration(false)] 
I 2021-10-17T01:41:23.597066Z Transition to LEADER on term 11 - transitioning StreamProcessor 
I 2021-10-17T01:41:23.654596Z Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@13c66f76)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@17a28661, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@3f8c8fae, configuration: Configuration(false)] 
I 2021-10-17T01:41:23.656527Z Recovered state of partition 3 from snapshot at position 1085365200 
I 2021-10-17T01:41:23.657138Z Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@5962379b)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@79ff5e1e, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@7aed4ece, configuration: Configuration(false)] 
I 2021-10-17T01:41:23.658241Z Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@21475fc2)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@69d17a9e, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@6a5dc614, configuration: Configuration(false)] 
I 2021-10-17T01:41:23.659171Z Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@7a566eaf)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@61748768, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@3130452, configuration: Configuration(false)] 
I 2021-10-17T01:41:23.661025Z Processor starts replay of events. [snapshot-position: 1085365200, replay-mode: PROCESSING] 
I 2021-10-17T01:41:23.661527Z Transition to LEADER on term 11 - transitioning SnapshotDirector 
I 2021-10-17T01:41:23.662001Z Transition to LEADER on term 11 - transitioning ExporterDirector 
I 2021-10-17T01:41:23.666777Z Transition to LEADER on term 11 completed 
I 2021-10-17T01:41:23.671723Z Exporter opened 
W 2021-10-17T01:41:35.505218Z RaftServer{raft-partition-partition-3} - AppendRequest{term=11, leader=1, prevLogIndex=404325129, prevLogTerm=10, entries=0, commitIndex=404325146} to 2 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2021-10-17T01:41:48.005003Z RaftServer{raft-partition-partition-3} - AppendRequest{term=11, leader=1, prevLogIndex=404325129, prevLogTerm=10, entries=0, commitIndex=404325146} to 2 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
W 2021-10-17T01:42:00.505714Z RaftServer{raft-partition-partition-3} - AppendRequest{term=11, leader=1, prevLogIndex=404325129, prevLogTerm=10, entries=0, commitIndex=404325146} to 2 failed: java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message 
I 2021-10-17T01:42:06.241077Z Processor finished replay at event position 1086007688 
I 2021-10-17T01:42:06.243217Z Starting processing of migration tasks (use LogLevel.DEBUG for more details) ...  
I 2021-10-17T01:42:06.252733Z Skipping ProcessMessageSubscriptionSentTimeMigration migration (1/2).  It was determined it does not need to run right now. 
I 2021-10-17T01:42:06.253428Z Skipping MessageSubscriptionSentTimeMigration migration (2/2).  It was determined it does not need to run right now. 
I 2021-10-17T01:42:06.253641Z Completed processing of migration tasks (use LogLevel.DEBUG for more details) ...  
E 2021-10-17T01:42:06.267481Z Failed to append block with last event position 1086007669. 
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud, Benchmarks 
 - Zeebe Version: Medic Benchmark CW41

**Comment by npepinpe** [comment] 2021-10-20 07:36
Let's first solve https://github.com/camunda-cloud/zeebe/issues/7862 which is already scheduled to be worked on soon, and leave this one in the back log. Both issues seem similar enough, and affect the same versions. Once we root cause the previous one, we can then decide if it makes sense to close this one here or investigate as well.

**Comment by Zelldon** [comment] 2022-12-29 07:11
Haven't occurred since a long time

**Closed by Zelldon** 2022-12-29 07:11 UTC
Labels: kind/bug, severity/low, area/observability
