### ISSUE TITLE
Save/extract error code, error message to variables in Error Catch Boundary Event

### ISSUE THREAD

**Issue by ceefour** [camunda/zeebe#4337] opened 2020-04-20 20:45 UTC
**Is your feature request related to a problem? Please describe.**
Currently when error is caught, errorCode and errorMessage are discarded and cannot be saved to variable.

**Describe the solution you'd like**
In Error Catch Boundary Event, save errorCode and errorMessage (and desirably, a custom object similar to regular worker results) to variable, probably similar to/improve [how Camunda/Camunda Modeler implemented it](https://forum.camunda.org/t/error-message-of-bpmn-error-from-external-task/5519/5?u=ceefour):

![image](https://user-images.githubusercontent.com/24123/79798081-a1195300-8382-11ea-8303-78f2262c4bce.png)

I myself think that error code+message+variables should be one object like it's usual in the REST/Spring Boot REST world (however this will drift from Camunda as Camunda treats errorCode and errorMessage separately, and does not have error results variables):

```json
{
 "error": "com.mycompany.http.BadRequestException",
 "message": "JSON parse error: Unrecognized token 'three': was expecting ('true', 'false' or 'null'); nested exception is com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'aaa': was expecting ('true', 'false' or 'null')\n at [Source: java.io.PushbackInputStream@cba7ebc; line: 4, column: 17]",
 "timestamp": "2019-03-05T04:02:30.627Z",

 "status": 400,
 "exception": "org.springframework.http.converter.HttpMessageNotReadableException",
 "path": "/birds"
}
```

In my opinion the ideal mechanism is: (sorry for asking too much)

1. Worker can throw error code, error message, and optionally an object/dict containing variables (above example: `status`, `exception`, and `path`, and can nest objects like usual)
2. These will be merged into one error object containing `error`, `message`, `timestamp` (autogenerated), and additional variables.
3. In the BPMN file, if user wants to save the error object, user sets "Error variable" in Zeebe Modeler, e.g. `error`. The next tasks will be able to get the that error object and perform any logic, or it can also do gateway just like ordinary variables, etc.
4. `timestamp` in ISO 8601 format with millisecond precision and UTC time zone. (ISO8601 is strict and avoids ambiguity when interpreting timestamp)
5. when catching error, it's possible to use wildcard for `error` code, each segment separated by `.`. For example, the Boundary Event can catch `com.mycompany.http.*` or even `*`.

I realize above points expand the scope on what's originally requested. The most priority one in this case is supporting the error code, error message, and the custom variables, before the additional features.

**Describe alternatives you've considered**
Alternative is to use interrupting message catch boundary event, but is semantically different and behavior is different when uncaught.

**Additional context**
Related to: #3497, #3801.

**Comment by saig0** [comment] 2020-04-21 04:17
@ceefour, thank you for raising this up!

Please describe your use case in detail that you want to solve with this feature. 

What about providing additional variables with the error event (similar to message variables)? Would this solve your use case? See also #4080.

**Comment by ceefour** [comment] 2020-04-21 06:22
@saig0 Wow, you even expanded my request! Ok, I edited my description to detail how I would like this to happen. I realize it's only my opinion, but from your response I see that you're not afraid to break new boundaries (pun intended) on the error boundary event ^_^ Zeebe has high potential to be "a better Camunda" in some ways :smile:

**Comment by saig0** [comment] 2020-04-22 05:49
Thanks for adding the additional context :+1: 

I think the variables are the most important part of the request. Using the variables, it's is possible to provide additional context to the error like the timestamp, error code and error message.

**Comment by ceefour** [comment] 2020-04-22 07:03
@saig0 Yes I agree. Probably the special one is `error` code as it's read by the workflow to know which error to catch.

**Comment by Orygin** [comment] 2021-02-09 12:16
Hello, sorry to unearth this, but is there any update? I think this should be a core feature of the engine.

How can we manage errors and their messages in the meantime?
There is no way to get the info needed to process correctly the errors that might be thrown out.

**Comment by saig0** [comment] 2021-02-10 05:32
> How can we manage errors and their messages in the meantime?
There is no way to get the info needed to process correctly the errors that might be thrown out.

Yes. As a workaround, you could use message (boundary) events instead. So, instead of failing the job, you would publish a message with the client. I know that it is not the same semantic but should work in general.

**Comment by xlegalles** [comment] 2021-08-16 07:38
If I can add a kind of use case/usability of such an addition, this is the one of .newCreateInstanceCommand().withResult(): this API is simply not usable with Error Catch Boundary Event because there is no variable to describe that it has terminated with an error.
Ok, there is a workaround by removing all  Error Catch Boundary Event and adding gateways with specific variables (manual error handling) but I'm sure you agree this is not an ideal solution.

**Comment by delarasfer** [comment] 2022-04-06 12:38
I'm throwing a newThrowErrorCommand with errocode but I can't update the job variables at this point as I can when using newCompleteCommand. Any idea for doing this? If I can update the variables I can create a new one with the error message.

Thanks.

**Comment by skayliu** [comment] 2022-10-24 09:56
Hi, @saig0, As discuss in [https://github.com/camunda/zeebe/issues/9404#issuecomment-1274264402](https://github.com/camunda/zeebe/issues/9404#issuecomment-1274264402).

> I suggest that the job fail command sets the variables only locally. No option to set global variables.

So, We do the same(`sets the variables only locally`) for throw error, right?

**Comment by korthout** [comment] 2022-11-28 10:40
@saig0 Can you please clarify why you reopened this issue?

**Comment by saig0** [comment] 2022-11-29 13:46
@korthout I reopened the issue because you mentioned that the PR #10882 should not close this issue. 

Are we able to store the error code and the error message?
Or, is this covered by another issue? 

I'm a bit confused about the expected solution for this issue and for #9473. Maybe, you could adjust the issue description to distinguish the cases. :sweat_smile:

**Comment by korthout** [comment] 2022-11-30 09:50
Thanks @saig0, I've discussed the differences in https://github.com/camunda/zeebe/issues/9473#issuecomment-1331890468.

If you agree, and @ceefour doesn't object, I'll try to clarify the issue description.

**Comment by korthout** [comment] 2022-12-13 16:41
I don't want to mess up @ceefour's description. So I'd rather just describe our understanding of it once more here:

Allow specifying specific variable names for the `errorCode` and `errorMessage` in the process model (BPMN). The specified variables will be created with as values the error code and error message provided along with the thrown error, respectively.

For example, `errorCodeVariable: 'errCode'` would end up creating a process variable named `errCode` with as value the thrown error's error code. This is similar to the multi-instance [input element variable](https://docs.camunda.io/docs/components/modeler/bpmn/multi-instance/#defining-the-collection-to-iterate-over).

----

There's a secondary concept described in this issue that I'm taking out of scope: throw errors as an object (i.e. context) including an error code, error message and other variables as properties. This may be useful, but I don't think this is the issue's essence. In addition, it could be difficult to change how errors are thrown. So let's keep that out of scope. @ceefour, if you consider this an important part, please create a separate issue for it.

**Comment by lzgabel** [comment] 2022-12-13 18:31
> Allow specifying specific variable names for the errorCode and errorMessage in the process model (BPMN). The specified variables will be created with as values the error code and error message provided along with the thrown error, respectively.

Hi @korthout. Sorry to bother you, please let me know if the above description is the final conclusion to solve this issue. If yes, please assign this task to me, and I'll submit a PR soon. 🙇

**Comment by korthout** [comment] 2022-12-14 09:36
Thanks @lzgabel I'll discuss it with the team, and let you know as soon as possible

**Comment by korthout** [comment] 2022-12-14 14:20
@lzgabel 👍 Confirmed by team that this would be useful as described.

>will face the same problem as https://github.com/camunda/zeebe/issues/11001

Hmm, yes. We may have to take the same approach that is currently there. It's fine to solve that problem separately in #11001. It's also great if you see a way to do it correctly here immediately. Either way is fine with me.

**Closed** 2023-01-19 14:38 UTC
Labels: kind/feature, support, area/ux, area/bpmn-support, component/engine

**Comment by remcowesterhoud** [comment] 2023-08-10 09:19
@korthout I notice that you reverted the PR that closed this issue. Do we need to reopen this one?

**Comment by korthout** [comment] 2023-08-11 08:46
Good question @remcowesterhoud

It does not have to be reopened as it has been replaced by:
- #11459
