### ISSUE TITLE
Supports all errors caught by error start events or boundary events

### ISSUE THREAD

**Issue by lzgabel** [camunda/zeebe#11126] opened 2022-11-29 09:42 UTC
**Is your feature request related to a problem? Please describe.**
* Any errors thrown from `Task A` can be handled in the workflow by catching it on an event subprocess.

<img width="492" alt="image" src="https://user-images.githubusercontent.com/24605947/204488239-42419b5a-18c3-4e2d-8557-214a570d3edf.png">

* Any errors thrown from `Task A` can be handled in the workflow by catching it on boundary events.
<img width="368" alt="image" src="https://user-images.githubusercontent.com/24605947/204492191-f5e0145a-26d7-493a-827c-6a4f349bff93.png">

**Describe the solution you'd like**
* If `errorRef` is omitted or `errorCode` of referenced error is omitted, the event start event or boundary event is triggered by any error event.

**Comment by lzgabel** [comment] 2022-11-29 09:48
👋  Hi @remcowesterhoud, @saig0. Any thoughts?

**Comment by saig0** [comment] 2022-11-29 13:38
This issue is a duplicate of #5881. Closing the other issue in favor of this one.

The use case is valid and we would like to support it. :+1: 

The feature to catch any error will be most valuable if we can pass the error code and the error message (and variables) of the caught error. Otherwise, we may miss some important context information. See the related issues: #9473 and #4337.

**Comment by lzgabel** [comment] 2022-11-29 17:09
> If a start event has no escalationRef or escalationCode of referenced escalation then another event sub-process with an escalation start event in the same scope is not supported.

❓ Hi @saig0. For error events, do we need to be consistent with the validation logic for escalation events.

At present, couldn't find the relevant definition in the docs. With manual testing, the current behavior of C7 allows deploying multiple omitted `errorRef` or `errorCode` (But only one will be triggered).

<img width="751" alt="image" src="https://user-images.githubusercontent.com/24605947/204593378-2784abac-d90f-48b6-b883-6e6e27e9a210.png">

**Comment by saig0** [comment] 2022-11-30 12:34
@lzgabel we can be more strict about it. Since only one error/escalation event without an `error code`/`escalation code` can be triggered, we should allow only one of these events. Other error/escalation events with `error code`/`escalation code` are supported.

**Closed** 2022-12-15 08:37 UTC
Labels: kind/feature
