### ISSUE TITLE
 NPE: Cannot invoke `ExecutableActivity.getFlowScope()` because `innerActivity` is null 

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#9400] opened 2022-05-18 06:43 UTC
**Describe the bug**

While deploying a BPMN resource, transforming a multi-instance activity fails with a NPE.

The deployment is rejected with the following rejection message:

```
Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'diagram_1.bpmn': Cannot invoke "io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableActivity.getFlowScope()" because "innerActivity" is null
```

The following process causes the issue:

![image](https://user-images.githubusercontent.com/4305769/190059007-a05daf23-b506-45e9-a6c5-40766a724c8b.png)

But, I'm able to deploy this process:

![image](https://user-images.githubusercontent.com/4305769/190058931-51f289b9-b3d3-411f-be57-c7b8d49cc7e5.png)

The only difference between the processes is multi-instance activity. If the multi-instance activity is in the first pool (i.e. the first process in the XML) then I can deploy the process successfully. Otherwise, the deployment fails. 

**To Reproduce**

1. deploy the process: [issue-9400.bpmn](https://github.com/camunda/zeebe/files/9562679/issue-9400.bpmn.txt) (with the correct file extension `.bpmn`)
2. verify that the deployment is rejected

**Expected behavior**

I can deploy a process that contains multiple pools with a multi-instance activity.

I can execute and complete an instance of this process.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
2022-09-14 04:09:21.842 ERROR 1 --- [   -zb-actors-2] io.camunda.zeebe.broker.process          : Unexpected error while processing resource 'carPolicyRequestProcess-init.bpmn'

java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableActivity.getFlowScope()" because "innerActivity" is null
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.MultiInstanceActivityTransformer.transform(MultiInstanceActivityTransformer.java:53) ~[zeebe-workflow-engine-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.MultiInstanceActivityTransformer.transform(MultiInstanceActivityTransformer.java:29) ~[zeebe-workflow-engine-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.0.5.jar:8.0.5]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:61) ~[zeebe-bpmn-model-8.0.5.jar:8.0.5]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:117) ~[zeebe-workflow-engine-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.transformResource(BpmnResourceTransformer.java:69) ~[zeebe-workflow-engine-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:120) ~[zeebe-workflow-engine-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:97) ~[zeebe-workflow-engine-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:100) ~[zeebe-workflow-engine-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$3(ProcessingStateMachine.java:300) ~[zeebe-workflow-engine-8.0.4.jar:8.0.4]
	at org.camunda.community.eze.db.EzeDbTransaction.run(EzeDbTransaction.kt:34) ~[eze-1.0.2.jar:1.0.2]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:290) ~[zeebe-workflow-engine-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:253) ~[zeebe-workflow-engine-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:213) ~[zeebe-workflow-engine-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:189) ~[zeebe-workflow-engine-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-8.0.4.jar:8.0.4]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.4.jar:8.0.4]
```

</p>
</details>

Archived Logs: https://drive.google.com/file/d/1VarHjCc-XQZ6bZz7PUE4MmdDy0pQ5Xt9/view?usp=sharing

**Environment:**

- Zeebe Version: 8.0.1

**Comment by korthout** [comment] 2022-05-18 08:31
@oleschoenburg Can you add links to the reported error and the related logs?

**Comment by oleschoenburg** [comment] 2022-05-18 08:56
@korthout I've updated the description and archived the logs :+1:

**Comment by saig0** [comment] 2022-05-20 11:55
I'm closing this issue for now. We're unable to reproduce the issue. The problem is what we would need the BPMN process.

If anyone observe this issue again then please reopen the issue and provide the BPMN process.

**Comment by ecuriotto** [comment] 2022-09-13 15:11
I've just got the issue in this diagram.
If I split the two pools in two separated diagrams it works perfectly.
Thanks

[carPolicyRequestProcess-init.bpmn.zip](https://github.com/camunda/zeebe/files/9558415/carPolicyRequestProcess-init.bpmn.zip)

**Comment by saig0** [comment] 2022-09-14 04:19
@ecuriotto thank you for providing your input. :+1: 

I was able to reproduce the issue with the given process. :heavy_check_mark:

**Comment by skayliu** [comment] 2022-11-02 13:27
Hi, @saig0 @oleschoenburg, I found out the reason, when there are more than one process in a collaboration definition, use `context.getCurrentProcess()` to get the innerActivity could be null, so we just need to find the right process for it.

**Closed** 2022-11-09 15:07 UTC
Labels: kind/bug, scope/broker, severity/low, hacktoberfest, area/ux
