### ISSUE TITLE
BpmnModelException: Collection expected to have <1> entry but has <0>

### ISSUE THREAD

**Issue by falko** [camunda/zeebe#8521] opened 2022-01-04 22:00 UTC
**Describe the bug**

The attached BPMN model produces a deployment error without saying what the real issue is.

zbctl output
```
Error: rpc error: code = InvalidArgument desc = Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'2 - Vacation Request Part4 - Trisotech-CamundaCloud3.bpmn': Collection expected to have <1> entry but has <0>
```
This issue has been discovered during the dry runs for the upcoming demo of the BPMN Model Interchange Working Group during the OMG Technical Meeting on March 21-25, 2022 in Reston, VA, USA.

**To Reproduce**

[2 - Vacation Request Part4 - Trisotech-CamundaCloud3.bpmn.txt](https://github.com/camunda-cloud/zeebe/files/7810592/2.-.Vacation.Request.Part4.-.Trisotech-CamundaCloud3.bpmn.txt)

```sh
zbctl deploy --insecure "2 - Vacation Request Part4 - Trisotech-CamundaCloud3.bpmn"
```

**Expected behavior**
A clear and concise description of what was wrong with the model ideally with id and name of the element that causes it so that I can find it in the modeler.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
2022-01-04 15:46:20.442 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] ERROR
      io.camunda.zeebe.broker.process - Unexpected error while processing resource '2 - Vacation Request Part4 - Trisotech-CamundaCloud3.bpmn'
io.camunda.zeebe.model.bpmn.BpmnModelException: Collection expected to have <1> entry but has <0>
	at io.camunda.zeebe.model.bpmn.impl.QueryImpl.singleResult(QueryImpl.java:77) ~[zeebe-bpmn-model-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.MessageTransformer.transform(MessageTransformer.java:39) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.MessageTransformer.transform(MessageTransformer.java:21) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:61) ~[zeebe-bpmn-model-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:108) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:123) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:96) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:100) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$2(ProcessingStateMachine.java:263) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:253) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:221) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextEvent(ProcessingStateMachine.java:192) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:184) ~[zeebe-workflow-engine-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:95) [zeebe-util-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.3.0-alpha1.jar:1.3.0-alpha1]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:192) [zeebe-util-1.3.0-alpha1.jar:1.3.0-alpha1]
```

</p>
</details>

**Environment:**
 - OS: Ubuntu 21.10 Kernel 5.13.0-22-generic
 - Zeebe Version: 1.3.0-alpha1
 - Configuration: distro defaults

**Comment by falko** [comment] 2022-01-04 22:03
Same stacktrace in 1.3.0-alpha3:
```
2022-01-04 16:02:34.508 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] ERROR
      io.camunda.zeebe.broker.process - Unexpected error while processing resource '2 - Vacation Request Part4 - Trisotech-CamundaCloud3.bpmn'
io.camunda.zeebe.model.bpmn.BpmnModelException: Collection expected to have <1> entry but has <0>
	at io.camunda.zeebe.model.bpmn.impl.QueryImpl.singleResult(QueryImpl.java:77) ~[zeebe-bpmn-model-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.MessageTransformer.transform(MessageTransformer.java:39) ~[zeebe-workflow-engine-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.MessageTransformer.transform(MessageTransformer.java:21) ~[zeebe-workflow-engine-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:61) ~[zeebe-bpmn-model-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:108) ~[zeebe-workflow-engine-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:123) ~[zeebe-workflow-engine-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:96) ~[zeebe-workflow-engine-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:100) ~[zeebe-workflow-engine-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$2(ProcessingStateMachine.java:263) ~[zeebe-workflow-engine-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:253) ~[zeebe-workflow-engine-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:221) ~[zeebe-workflow-engine-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextEvent(ProcessingStateMachine.java:192) ~[zeebe-workflow-engine-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:184) ~[zeebe-workflow-engine-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:95) [zeebe-util-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.3.0-alpha3.jar:1.3.0-alpha3]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:192) [zeebe-util-1.3.0-alpha3.jar:1.3.0-alpha3]
```

**Comment by falko** [comment] 2022-01-04 22:06
Corresponding code seems to look for message subscriptions:
https://github.com/camunda-cloud/zeebe/blob/develop/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/transformer/MessageTransformer.java#L39

**Comment by falko** [comment] 2022-01-04 22:11
However, the diagram only contains a message start event that shouldn't require a subscription, which would a correlation key:
![2 - Vacation Request Part4 - Trisotech-CamundaCloud3](https://user-images.githubusercontent.com/40038/148130782-7d9bc239-ce6a-4688-8b36-0d13cbb1ac77.png)

**Comment by falko** [comment] 2022-01-04 22:23
Okay, there are additional messages inside the XML that are not currently used. One could warn about them but this should not fail the deployment.

**Comment by falko** [comment] 2022-01-04 22:49
I removed the orphaned messaged using:
```xmlstarlet edit --inplace --ps -N bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" --delete '//bpmn:message[not(//bpmn:messageEventDefinition/@messageRef=@id)]' *3.bpmn
```
but still get the error.

**Comment by falko** [comment] 2022-01-05 03:57
The issue is caused by an empty `bpmn:extensionElements` container, which I ended up with due to working around #8229

I worked around it by removing extensionElements without child nodes using:
```sh
xmlstarlet edit --inplace --ps -N bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" --delete '//bpmn:extensionElements[not(*)]' *3.bpmn
```

**Comment by Zelldon** [comment] 2022-01-05 04:58
@saig0 is this something which you have fixed recently in the feel engine?

**Comment by saig0** [comment] 2022-01-05 08:24
> is this something which you have fixed recently in the feel engine?

It's not related to FEEL. It seems that it is caused by Zeebe's `MessageTransformer` during the deployment.

**Comment by npepinpe** [comment] 2022-01-05 09:03
Impact is mostly around usability as it's hard to figure out the error, however we expect that the likelihood here is quite low: if you're using one of the Camunda modelers, then this shouldn't happen.

**Comment by korthout** [comment] 2022-08-30 08:11
Marking priority as `later later` because:
>if you're using one of the Camunda modelers, then this shouldn't happen.

Please comment if you think this should have a higher priority.

**Comment by remcowesterhoud** [comment] 2022-12-01 08:38
Closing as dupe of #10962

**Closed by remcowesterhoud** 2022-12-01 08:38 UTC
Labels: kind/bug, good first issue, severity/low, hacktoberfest, area/ux
