### ISSUE TITLE
zbctl `8.4.0` can't send requests with authorization information

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#16015] opened 2024-01-19 15:54 UTC
**Describe the bug**

The `8.4.0` CLI client (`zbctl`) is unable to send requests with authorization information to Zeebe `8.4.0` or older (ex. `8.3.0`).

**To Reproduce**

1. Start Camunda 8 with Identity enabled (ex. [using docker-compose](https://github.com/camunda/camunda-platform?tab=readme-ov-file#using-docker-compose))
2. Download `zbctl` `8.4.0` ([link](https://github.com/camunda/zeebe/releases/tag/8.4.0))
3. Execute
```
./zbctl --address=localhost:26500 --clientId=zeebe --clientSecret=zecret --audience=zeebe-api --authzUrl=http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token --insecure status
```

**Expected behavior**

The request succeeds.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
Warning: The configured security level does not guarantee that the credentials will be confidential. If this unintentional, please enable transport security.
Error: rpc error: code = Canceled desc = failed to apply token: failed to obtain access token: oauth2: "invalid_scope" "Invalid scopes: "
```

</p>
</details>

**Environment:**
- OS:  Linux/Mac
- Zeebe Version:  `8.4.0`
- Configuration: 

Support: https://jira.camunda.com/browse/SUPPORT-19995

**Comment by abbasadel** [comment] 2024-01-22 14:03
ZPA triage:
- We think this is a regression as zbctl should be backward/future compatible. 
- We think zbctl is not compatible with the latest [updates of identity](https://github.com/camunda/camunda-docs/pull/2969)
- We think the severity is `high` since it is blocking a customer from upgrading to 8.4 with no workaround  
- We prioritise this as `upcoming` 

@koevskinikola , it is not clear to us if zbctl 8.3 is having the same issue when connecting to Zeebe 8.4. Can you comment of that.

**Comment by koevskinikola** [comment] 2024-01-23 09:49
@abbasadel zbctl `8.3.0` works as expected when connecting to Zeebe `8.4.0`. There are no issues.

**Comment by abbasadel** [comment] 2024-01-23 10:03
Thanks, @koevskinikola; based on that, I'm updating the severity to 'mid' since there is a workaround.

**Comment by kurtyy** [comment] 2024-01-23 15:04
seems not to ne related on the identity version 8.4.0. we had the same issue with identity 8.3.4 and 8.2.7. So this comes up with zbctl 8.4.0

**Comment by alekava** [comment] 2024-03-04 15:13
Hello @koevskinikola 
There is a new support ticket linked to this issue : SUPPORT-20932

**Comment by neal-dennis** [comment] 2024-04-09 00:30
Another support case affected: [SUPPORT-21088](https://jira.camunda.com/browse/SUPPORT-21088)

**Comment by megglos** [comment] 2024-04-15 13:17
might be related https://github.com/camunda/zeebe/pull/17429

**Comment by tmetzke** [comment] 2024-04-17 05:46
Did we introduce a new environment variable for the token scope in the client with `8.4.0` that we expect to be there?

**Comment by megglos** [comment] 2024-04-17 06:36
> Did we introduce a new environment variable for the token scope in the client with `8.4.0` that we expect to be there?
> 
> **Edit**:
> 
> * Looking at [feat(zeebe): zeebe client OAuth scope configuration camunda-docs#2969](https://github.com/camunda/camunda-docs/pull/2969), we introduced the env variable `ZEEBE_TOKEN_SCOPE`. If it's not set, the client sends no token scope.
> * @megglos, could this value be required now?

I suspect it depends on the oauth setup, in that case it seems the default setup requires the scope to obtain a token, thus the error if not set. I just wonder why this happens for 8.3.0 though and not 8.4.0+ 🤔 

@dlavrenuek can you help us understand if the scope is required to set for SM setups?

That means a workaround would be setting the env var and once https://github.com/camunda/zeebe/pull/17429 is merged you could also provide it via the command line.

**Comment by dlavrenuek** [comment] 2024-04-30 07:50
The scope parameter added in [here](https://github.com/camunda/zeebe/pull/15404/files#diff-c756e738c78991d60f8450296782594a21e75dbccb5dc41e1c96379115a34e73R136) should be optional. At least I can not see how the code would make it required. How does zeebectl uses the go/Java libraries and where is it's code?

When operating in a setup with Microsoft Entra ID scope must be passed to obtain a correct access token, in other setups it should be irrelevant

**Comment by megglos** [comment] 2024-04-30 10:01
@dlavrenuek so the error we see could be caused by the go client sending the scope with an empty string value although it should actually omit it? Thus the token request fails as it should either provide a valid scope value or none?

That's a good lead then, I could validate that next.

**Closed** 2024-05-02 06:39 UTC
Labels: kind/bug, scope/clients-go, severity/mid, support, component/clients, likelihood/high, component/zeebe
