### ISSUE TITLE
Benchmark for CW32 with high backpressure, at times no throughput and frequent gateway restarts

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#10059] opened 2022-08-11 10:00 UTC
The benchmark for CW32 shows severely degraded performance: http://34.77.165.228/d/NzsO1mUnk/zeebe-overview?orgId=1&var-DS_PROMETHEUS=Prometheus&var-namespace=medic-cw-32-be18e23b78-benchmark&var-pod=All&var-partition=All&from=1660132800000&to=1660212000000

Throughput is very low:
![image](https://user-images.githubusercontent.com/14032870/184108869-f70e7132-439f-4dfc-a363-0f0aa9807605.png)

Frequent restarts of Gateway:
![image](https://user-images.githubusercontent.com/14032870/184108994-c8bc0ae3-8575-4eb7-9b84-e1585b6ad925.png)

Back pressure is high:
![image](https://user-images.githubusercontent.com/14032870/184109147-2e3959c1-e3e7-417e-9d34-762dd5220520.png)

Processing shows a cliff edge:
![image](https://user-images.githubusercontent.com/14032870/184109644-e418cc90-6452-459e-b3f7-abdfd9eb9690.png)

Snapshots are growing after the cliff edge:
![image](https://user-images.githubusercontent.com/14032870/184109522-782ab0c2-e263-410b-9d28-a830e688ff62.png)

**Comment by pihme** [comment] 2022-08-11 10:13
@deepthidevaki metnioned this looks similar to #9862

**Comment by pihme** [comment] 2022-08-11 10:13
Terminated gateway nodes were restarted due to imminent node shutdown, at least the ones that I could look at

**Comment by pihme** [comment] 2022-08-11 10:15
We see a high frequency of these bugs: https://github.com/camunda/zeebe/issues/10014

This is expected, because in the commit used for the benchmark the bug was not fixed yet

**Comment by pihme** [comment] 2022-08-11 10:18
![image](https://user-images.githubusercontent.com/14032870/184112882-af077725-8272-4def-b871-64e9f7eb3b3d.png)

**Comment by pihme** [comment] 2022-08-11 11:46
Current working theory is:
- NPE https://github.com/camunda/zeebe/issues/10014 leads to stream not being handled properly
- Leads to Stream Error in in Gateway `io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place`
- Leads to memory leak in gateway
- Leads to OOM termination [https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Ar[…]imestamp=2022-08-11T11:36:27.997522150Z?project=zeebe-io](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22medic-cw-32-be18e23b78-benchmark%22%0Alabels.k8s-pod%2Fapp%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22medic-cw-32-be18e23b78-benchmark%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fpart-of%3D%22camunda-platform%22%0Aresource.labels.container_name%3D%22zeebe-gateway%22%0A%0A-sourceLocation.function%3D%22mapErrorToStatus%22%0A%0AtextPayload%3D%22Terminating%20due%20to%20java.lang.OutOfMemoryError:%20Java%20heap%20space%5Cn%22;timeRange=PT24H;cursorTimestamp=2022-08-11T11:36:27.997522150Z?project=zeebe-io)

Things not explained:
- Why did it suddenly start after running relatively smoothly for two days
- Why does it not recover? Even with low throughput?
- Why do snapshots grow?

**Comment by pihme** [comment] 2022-08-11 12:27
Had a chat with Simon. We found no explanation why gateways were being restarted more frequently after 4:00 PM August 10th and why this behavior stopped around 9:30 AM August 11th

**Comment by pihme** [comment] 2022-08-12 07:49
@Zelldon also mentioned this issue as possibly related #7095

**Comment by Zelldon** [comment] 2022-08-15 06:58
Just want to mention that it seems that now two nodes have a dead partition one

![d](https://user-images.githubusercontent.com/2758593/184590277-7410feee-6125-450d-8443-2e70ff44ac7f.png)

**Comment by korthout** [comment] 2022-08-15 09:13
>Just want to mention that it seems that now two nodes have a dead partition one

@Zelldon There are a few errors reported about this. It appears to be unrelated to the above.

**Comment by menski** [comment] 2022-08-19 09:03
We assume this was fixed by a bug fix

@oleschoenburg could you please link the corresponding issue/PR and delete the benchmark.

**Comment by oleschoenburg** [comment] 2022-08-19 10:21
Issues were caused by https://github.com/camunda/zeebe/issues/10014 which is fixed. I'll delete the benchmark.

**Closed by oleschoenburg** 2022-08-19 10:21 UTC
Labels: kind/bug, area/performance, area/reliability
