### ISSUE TITLE
Follower doesn't start with corrupted snapshot

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#7136] opened 2021-05-27 11:54 UTC
**Describe the bug**
For some reason, one follower of a three-node cluster has a corrupted snapshot. If the follower restarts then it detects that the snapshot is corrupted and shut down again.

The follower doesn't recover by itself. It requires manual interaction. 
After deleting the data of the follower, it starts again and joins the cluster.

Related issue: #6907

**To Reproduce**
It is not clear why the snapshot was corrupted. It may be related to an infrastructure issue where the volumes were unattached.

1. the snapshot was replicated from the leader ([logs](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22%0Aresource.labels.namespace_name%3D%22995d359b-4e17-482f-a538-bd756585e31e-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-1%22;timeRange=2021-05-23T11:33:08.633Z%2F2021-05-27T11:33:08.633820Z;pinnedLogId=2021-05-25T14:49:36.097674Z%2F1de9lmjg42mpjo5;cursorTimestamp=2021-05-25T14:57:41.501966111Z?authuser=0&project=camunda-cloud-240911))
2. after a restart (not gracefully), the node read the snapshot and detected that it is corrupted ([logs](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22%0Aresource.labels.namespace_name%3D%22995d359b-4e17-482f-a538-bd756585e31e-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-1%22;timeRange=2021-05-23T11:33:08.633Z%2F2021-05-27T11:33:08.633820Z;pinnedLogId=2021-05-25T14:57:47.118977Z%2Ft4vtvuf153wqh;cursorTimestamp=2021-05-25T14:57:49.327746Z?authuser=0&project=camunda-cloud-240911)) 
```
Expected snapshot /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/46497-11-46487-46488 to have checksum 1338043633, but the actual checksum is 892742735; the snapshot is most likely corrupted
```
3. the node failed to start and shut down

**Expected behavior**
The follower detects that the snapshot is corrupted but it can heal itself. For example, by purging the snapshot and receiving a new snapshot from the leader.  

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
Expected snapshot /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/46497-11-46487-46488 to have checksum 1338043633, but the actual checksum is 892742735; the snapshot is most likely corrupted
```

</p>
</details>

![image](https://user-images.githubusercontent.com/4305769/119821029-63c2b580-bef2-11eb-934a-3830c72124c2.png)

![image](https://user-images.githubusercontent.com/4305769/119820923-4aba0480-bef2-11eb-949e-d2b64bf7e430.png)

The issue was raised as part of an incident (see the [incident doc](https://docs.google.com/document/d/1NCO_5NuDcYtFUHg6-SzC768bi-msaDBVy59qWWb6cDM/edit#)). 

A dump of the data folders was stored [here](https://drive.google.com/drive/u/0/folders/1mUVGUJ0Dt0xqr2ruKV8Zv17URKQFNPRu).

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: `1.0.0`
 - Configuration: 
   - replication-factor: 3

**Comment by npepinpe** [comment] 2021-05-28 08:34
One hypothesis is it could be due to how we write snapshot chunks. We use `Files#write`, which writes the given `byte[]` in smaller chunks. This is all good and well, but nowhere could I ever find that it actually flushed the writes. Here we can see that the node shutdown soon after, so I wonder if it simply didn't flush them? I had a look into the implementation, and I checked close methods of the file channel/input stream, I checked the OpenJDK C code and saw that on Linux it uses `close`, not `fclose`, which will not flush when closing the descriptor. I assume moving the file also doesn't affect the flush, so I think it could be something related to this? But I don't know how to reproduce this since it's quite difficult to control the OS flush.

**Comment by saig0** [comment] 2021-07-06 08:53
We saw the same failure again on `1.0.1`. In two different clusters (at the same time).

[Logs Cluster 2e3e57e4*](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22%0Aresource.labels.namespace_name%3D%222e3e57e4-127f-43d9-87e2-80abeffe4474-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22%0Aresource.labels.pod_name%3D%22zeebe-0%22;timeRange=2021-07-02T15:11:36.765Z%2F2021-07-05T09:11:36.765700Z;pinnedLogId=2021-07-04T15:42:48.763504Z%2F1ca9jezg29pfvo6;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning;cursorTimestamp=2021-07-04T15:34:49.223903Z?authuser=0&project=camunda-cloud-240911)

[Logs Cluster 46baab6e*](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22%0Aresource.labels.namespace_name%3D%2246baab6e-7bcd-4cd0-8745-c3db800dd770-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22%0Aresource.labels.pod_name%3D%22zeebe-0%22;timeRange=2021-07-02T15:11:36.765Z%2F2021-07-05T09:11:36.765700Z;pinnedLogId=2021-07-04T15:42:52.287310Z%2Fezq605g2a3ri7b;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning;cursorTimestamp=2021-07-04T15:42:52.366845Z?authuser=0&project=camunda-cloud-240911)

**Comment by npepinpe** [comment] 2021-07-06 09:36
Possibly same root cause as: https://github.com/camunda-cloud/zeebe/issues/7416

**Comment by saig0** [comment] 2021-07-09 03:56
### Continue with the analysis: 
* the snapshots of the brokers in both clusters are invalid
* the snapshot directory exists and it contains the files
* **but** all files are empty (i.e. 0 bytes)
* since we don't have the snapshot of the original broker that created the snapshot, it is not clear if the problem is caused by the snapshot creation or replication 

![image](https://user-images.githubusercontent.com/4305769/125020807-cf637b00-e079-11eb-98a8-6a597ccce5d3.png)

**Comment by deepthidevaki** [comment] 2021-07-09 06:11
The fix is only https://github.com/camunda-cloud/zeebe/pull/7240 1.0.2. The state that reported by @saig0 looks similar to what we can get with out the fix.

**Comment by saig0** [comment] 2021-07-09 07:42
Thanks, @deepthidevaki :+1:  

I'm closing the issue under the assumption that #7240 fixed the problem in version `1.0.2`. 
Please reopen the issue if we see the behavior in a version `>= 1.0.2`.

**Comment by deepthidevaki** [comment] 2021-07-30 11:18
Observed again in cw-30 benchmark. 

![image](https://user-images.githubusercontent.com/1997478/127644647-6e9ef4b3-8bef-42ab-a94e-31fc92e8601d.png)

* Verified that the number of files in the snapshot is correct (from the logs). 
* The checksum read is also correct. (from the logs). 
* The snapshot was created by the same node when it was the leader. Immediately after taking the snapshot the pod stopped (No logs of shutdown => crash. non-graceful shutdown). This snapshot was replicated to a follower before shutdown without any issues.
```


2021-07-28 15:24:17.410 CEST
medic-cw-30-713f2880dd-benchmark-zeebe-2
Received all snapshot chunks (8/8) of snapshot 164127489-4-423952560-423362244. Committing snapshot.
2021-07-28 15:24:17.429 CEST
medic-cw-30-713f2880dd-benchmark-zeebe-2
Committed new snapshot 164127489-4-423952560-423362244
2021-07-28 15:26:41.611 CEST
medic-cw-30-713f2880dd-benchmark-zeebe-0
Expected snapshot /usr/local/zeebe/data/raft-partition/partitions/3/snapshots/164127489-4-423952560-423362244 to have checksum 1222676160, but the actual checksum is 3129241406; the snapshot is most likely corrupted. The startup will fail if there is no other valid snapshot and the log has been compacted.
2021-07-28 15:27:33.389 CEST
medic-cw-30-713f2880dd-benchmark-zeebe-2
Available snapshot: FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/snapshots/164127489-4-423952560-423362244, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/3/snapshots/164127489-4-423952560-423362244.checksum, checksum=1222676160, metadata=FileBasedSnapshotMetadata{index=164127489, term=4, processedPosition=423952560, exporterPosition=423362244}}
2021-07-28 15:27:33.542 CEST
medic-cw-30-713f2880dd-benchmark-zeebe-2
Recovered state from snapshot 'FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/snapshots/164127489-4-423952560-423362244, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/3/snapshots/164127489-4-423952560-423362244.checksum, checksum=1222676160, metadata=FileBasedSnapshotMetadata{index=164127489, term=4, processedPosition=423952560, exporterPosition=423362244}}'
2021-07-28 15:30:35.526 CEST
medic-cw-30-713f2880dd-benchmark-zeebe-2
Deleting previous snapshot 164127489-4-423952560-423362244


```

There is no other useful information I could gather. This snapshot has been already deleted from other nodes. So could not compare why the checksum's are different.

**Comment by bradporter-y** [comment] 2021-09-01 05:38
Hi - we are seeing a very similar issue while running 0.26.5 - in GCP/GKE with Ceph based PVCs.  


```
...
      io.zeebe.broker.system - Bootstrap Broker-2 [6/13]: cluster services
2021-08-31 20:31:11.485 [] [http-nio-0.0.0.0-9600-exec-2] INFO 
      org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-08-31 20:31:11.487 [] [http-nio-0.0.0.0-9600-exec-2] INFO 
      org.springframework.web.servlet.DispatcherServlet - Initializing Servlet 'dispatcherServlet'
2021-08-31 20:31:11.489 [] [http-nio-0.0.0.0-9600-exec-2] INFO 
      org.springframework.web.servlet.DispatcherServlet - Completed initialization in 2 ms
2021-08-31 20:31:16.387 [] [atomix-0] WARN 
      io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore - Could not load snapshot in /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/2535799-124-1629648755373-3330676-3330678
java.io.EOFException: null
	at java.io.RandomAccessFile.readInt(Unknown Source) ~[?:?]
	at java.io.RandomAccessFile.readLong(Unknown Source) ~[?:?]
	at io.zeebe.snapshots.broker.impl.SnapshotChecksum.read(SnapshotChecksum.java:34) ~[zeebe-snapshots-0.26.5.jar:0.26.5]
	at io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore.collectSnapshot(FileBasedSnapshotStore.java:132) ~[zeebe-snapshots-0.26.5.jar:0.26.5]
	at io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore.loadLatestSnapshot(FileBasedSnapshotStore.java:89) ~[zeebe-snapshots-0.26.5.jar:0.26.5]
	at io.zeebe.snapshots.broker.impl.FileBasedSnapshotStore.<init>(FileBasedSnapshotStore.java:78) ~[zeebe-snapshots-0.26.5.jar:0.26.5]
	at io.zeebe.snapshots.broker.impl.FileBasedSnapshotStoreFactory.createAndOpenNewSnapshotStore(FileBasedSnapshotStoreFactory.java:60) ~[zeebe-snapshots-0.26.5.jar:0.26.5]
	at io.zeebe.snapshots.broker.impl.FileBasedSnapshotStoreFactory.lambda$createReceivableSnapshotStore$0(FileBasedSnapshotStoreFactory.java:55) ~[zeebe-snapshots-0.26.5.jar:0.26.5]
	at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:?]
	at io.zeebe.snapshots.broker.impl.FileBasedSnapshotStoreFactory.createReceivableSnapshotStore(FileBasedSnapshotStoreFactory.java:53) ~[zeebe-snapshots-0.26.5.jar:0.26.5]
	at io.atomix.raft.partition.impl.RaftPartitionServer.buildServer(RaftPartitionServer.java:168) ~[atomix-cluster-0.26.5.jar:0.26.5]
...
```

The directory looks like:
```
ls -al 1/snapshots/
total 12
drwxr-xr-x 3 root root 4096 Aug 22 16:12 .
drwxr-xr-x 5 root root 4096 Aug 19 20:57 ..
drwxr-xr-x 2 root root 4096 Aug 22 16:12 2535799-124-1629648755373-3330676-3330678
-rw-r--r-- 1 root root    0 Aug 22 16:12 2535799-124-1629648755373-3330676-3330678.checksum

 ls -al 1/snapshots/2535799-124-1629648755373-3330676-3330678
total 8
drwxr-xr-x 2 root root 4096 Aug 22 16:12 .
drwxr-xr-x 3 root root 4096 Aug 22 16:12 ..
-rw-r--r-- 1 root root    0 Aug 22 16:12 025969.sst
-rw-r--r-- 1 root root    0 Aug 22 16:12 025972.sst
-rw-r--r-- 1 root root    0 Aug 22 16:12 025974.sst
-rw-r--r-- 1 root root    0 Aug 22 16:12 025975.sst
-rw-r--r-- 1 root root    0 Aug 22 16:12 025977.sst
-rw-r--r-- 1 root root    0 Aug 22 16:12 025978.sst
-rw-r--r-- 1 root root    0 Aug 22 16:12 025979.sst
-rw-r--r-- 1 root root    0 Aug 22 16:12 CURRENT
-rw-r--r-- 1 root root    0 Aug 22 16:12 MANIFEST-024602
-rw-r--r-- 1 root root    0 Aug 22 16:12 OPTIONS-024689
```

It seems this has been mentioned in #7240 and #7204, as well, but it isn't clear that there is a solution. 

**So, this is my upvote! ;)**

Until it is fixed, is there a mitigation/resolution strategy that anyone can suggest?  This has caused some loss that we'd rather not have!
Is the process described in:  https://github.com/camunda-cloud/zeebe/issues/6907 the "correct" approach? 

I appreciate any help.

**Comment by deepthidevaki** [comment] 2021-09-07 06:58
Hi @bradporter-y  
The state that you have described is already fixed by #7204. The reason for this was that the snapshot files were not flushed to disk. If you update to a version with this fix, and still see the same issue please report to us.

That said, we still observed issues with corrupted snapshots, but after the fix #7204 it is quite rare and we were not able to root cause it as it has happened only once.

> Until it is fixed, is there a mitigation/resolution strategy that anyone can suggest? This has caused some loss that we'd rather not have!

Disclaimer:- The following procedure risks data loss if not done carefully.
If snapshot in only one replica is corrupted, you can delete the data folder of the partition with corrupted snapshot `raft-partition/partitions/<partitionId>/` and restart the broker. Only delete the data for that partition. Before deleting the data, make sure that the other replicas of this partition is healthy and making progress, otherwise there is a risk of data loss.

**Comment by npepinpe** [comment] 2022-08-31 10:31
Has this happened again in the last year? I'm thinking we can close this, especially since we soon have more than one snapshot, so risks will be somewhat mitigated. WDYT @deepthidevaki ?

**Comment by deepthidevaki** [comment] 2022-08-31 10:54
Root cause is fixed. As you said, with more number of snapshots the risk will be mitigated. But the expected behavior : "_The follower detects that the snapshot is corrupted but it can heal itself. For example, by purging the snapshot and receiving a new snapshot from the leader_."  is not addressed yet.

**Comment by npepinpe** [comment] 2022-08-31 10:57
So far we've never really worked on automated recovery strategies in case of corruption. I think especially when it comes to purging snapshots, this could be problematic, and I would propose we tackle this as a feature in itself, so I would close this since I would expect the scope to be bigger than some random backlog issue.

**Comment by deepthidevaki** [comment] 2022-10-13 08:31
> I would propose we tackle this as a feature in itself, so I would close this since I would expect the scope to be bigger than some random backlog issue.

Closing this now.

**Closed by deepthidevaki** 2022-10-13 08:31 UTC
Labels: kind/bug, scope/broker, severity/mid, area/reliability
