### ISSUE TITLE
Possible inconsistency of job not found in DbJobState#visitJob

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#15733] opened 2023-12-28 13:08 UTC
**Description**

Now that that we have an asynchronous scheduler in the engine, it can happen that we schedule a task to visit some job state, but the job is completed or cancelled in the meantime. This leads to us visiting a non-existent job. That's safe to do, but we log the following at **error** level:

```
Expected to find job with key 221234128273, but no job found
```

It's unclear to me yet if this is a bug or if this is purely noise, primarily because the method `visitJob` is called only via the iterative methods:

- `DbJobStat#forEachTimedOutEntry`
- `DbJobState#forEachActivatableJob`
- `DbJobState#findBackedOffJobs`

Each of these methods should be called in a transaction, such that `visitJob` would also be in the same transaction, so if they did not see a job, it means the following:

- We have some broken transaction boundaries (e.g. somehow we're using two transactions here, or the other update is done in multiple, non-atomic transactions)
- We have garbage in the activatable/timed out/backed off columns for jobs which don't exist anymore.
- I'm missing something and this is fine, and we're just unnecessarily logging at the error level.

The first one is probably a high severity, or even critical bug, but the second one is more like a mid.

**Comment by korthout** [comment] 2024-01-03 12:32
ZPA triage:
- we should figure out what is going on here, this would change the severity
- let's consider it high severity first
- we can lower the severity based on the outcome of an initial investigation
- size of investigation: medium
- prio of investigation: upcoming

**Comment by aleksander-dytko** [comment] 2024-01-05 13:27
ZPA Planning: The scope for this iteration is to investigate what this bug is about.

**Comment by korthout** [comment] 2024-02-29 14:08
The team discussed the issue during mob-programming. We took this as a knowledge-sharing opportunity, as we need to understand all the aspects of this issue to root cause it.

We discussed the basics of jobs: activation with a timeout, timing out, failing, and failing with backing off. We also reviewed the need for each different method that uses the `visitJob` method and how they are used (from the Engine as the stream processor or a checker as an async scheduled task). 

One scenario was proposed but could be ruled out. It can't be the following scenario, as it wouldn't hit the logged error:
- find an expired job
- write job TIMEOUT command
- in the meantime, remove the job
- when we process the TIMEOUT command, the job has already been removed somehow

This made it clear that the problem must exist somewhere in how we visit the jobs.

We noticed something interesting about the job key field, which is reused between different column families. For example, iterating over the `deadlinesColumnFamily` would populate the job key field, and then for each entry, we overwrite (wrap) the key in the `getJob` method on visiting. This is not necessarily a problem, but if concurrency exists, this could be a race condition.

Some ideas for next time:

1. There was a bug. Jobs with incidents could be stored in the backoff column family. If a job already has an incident and is backed off, then when the incident is resolved, it could be that the job is removed, and the backoff checker could still pick up. We don't know whether this is true, but we could verify it.

2. We should investigate whether the stream processor and the checkers really have different transactions that only allow looking at data committed by transactions. As Nicolas already mentioned above.

**Comment by oleschoenburg** [comment] 2024-02-29 14:14
> We should investigate whether the stream processor and the checkers really have different transactions that only allow looking at data committed by transactions. As Nicolas already mentioned above.

Yes, this was one of the explicit design goals with #12302.
https://github.com/camunda/zeebe/blob/8453a8d157b2aa5bb8fbdb5a073debf4b78eaec5/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/TypedRecordProcessorContextImpl.java#L83-L92

**Comment by oleschoenburg** [comment] 2024-03-01 13:00
> it seems like the main point that we need to investigate is

I don't think this bug depends on incidents. If you look at the [error group](https://console.cloud.google.com/errors/detail/CKe9pf-Tqe-ZZw?project=zeebe-io) for this, it shows up in various benchmarks which (as far as I know) never have incidents. 

> @oleschoenburg I wonder if you could advise on how we could possible reproduce this issue?

Seems to be easy to reproduce in benchmarks. That's not ideal but I don't know a better way, mostly because I just don't know what's causing it.

**Comment by megglos** [comment] 2024-03-12 13:32
nice catch! That also means this error log is indeed noise then and there is no functional impact, so we need to be resilient to the case that a job might just get completed concurrently? 🤔 Can we drop severity then to low?

**Comment by oleschoenburg** [comment] 2024-03-12 13:35
We actually found this before :facepalm: https://github.com/camunda/zeebe/issues/13644

@megglos The impact for job timeouts is minimal, just a noisy log. However, @ana-vinogradova-camunda is now going through the remaining scheduled tasks to see if they could have the same problem and what the impact may be.

**Comment by megglos** [comment] 2024-03-12 13:37
> @ana-vinogradova-camunda is now going through the remaining scheduled tasks to see if they could have the same problem and what the impact may be.

makes sense, we then make sure we can handle this case gracefully in all cases + log a warn statement instead of error?

**Comment by oleschoenburg** [comment] 2024-03-12 13:43
If the impact is effectively nil, we can lower the log severity (or just remove it altogether).

I think there's still value in ensuring repeatable reads, even _if_ all scheduled tasks may be fine without. This is something easy to forget in the future and could lead to difficult to diagnose bugs (as we just saw here, I can't believe I forgot that I actually found the root cause once before...).

The impact should be fairly minimal, a snapshot can only prevent compaction as long as it's used. Scheduled tasks should not run for very long, ideally well under a second, realistically probably always <10s.

**Comment by ana-vinogradova-camunda** [comment] 2024-03-12 13:55
@oleschoenburg thank you for your help in investigating this issue!

I am looking at the remaining scheduled tasks.
It is also worth mentioning that this issue won't affect stream processing as the checkers do not modify the data.

I agree with @oleschoenburg that ensuring repeatable reads is worth implementing as it would improve maintainability and reduce number of issues like the current one (that are not that easy to troubleshoot).

**Comment by megglos** [comment] 2024-03-12 13:55
> I think there's still value in ensuring repeatable reads, even if all scheduled tasks may be fine without. This is something easy to forget in the future and could lead to difficult to diagnose bugs (as we just saw here, I can't believe I forgot that I actually found the root cause once before...).

ok this we can explore with https://github.com/camunda/zeebe/issues/13644 then?

So this issue we can close once all `*Checker` classes (or the underlying DbState calls) handle such situations gracefully?
Similar to like done here https://github.com/camunda/zeebe/blob/2a44818fbba4ccd61c710af072934931325150b8/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbTimerInstanceState.java#L98-L105 ?

**Comment by korthout** [comment] 2024-03-12 14:03
>So this issue we can close once all *Checker classes (or the underlying DbState calls) handle such situations gracefully? Similar to like done here ?

@megglos Yes, but I would favor https://github.com/camunda/zeebe/issues/13644 over this type of code. If our checkers work in a safe environment, we no longer need to code around these cases. IMO, it's the better solution.

**Closed** 2024-03-14 14:35 UTC
Labels: kind/bug, severity/high, area/reliability, area/observability, component/state, likelihood/mid, component/zeebe
