### ISSUE TITLE
PartitionListeners are notified even if the transition is cancelled causing NPE

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#13471] opened 2023-07-13 08:19 UTC
**Describe the bug**

```
INFO 2023-07-10T18:18:50.941085479Z [resource.labels.containerName: zeebe] Preparing transition from FOLLOWER on term 31 completed
INFO 2023-07-10T18:18:50.941163945Z [resource.labels.containerName: zeebe] Transition to LEADER on term 31 starting
INFO 2023-07-10T18:18:50.941238114Z [resource.labels.containerName: zeebe] Cancelling transition to LEADER on term 31
WARNING 2023-07-10T18:18:50.941635348Z [resource.labels.containerName: zeebe] Uncaught exception in Broker-1-ZeebePartition-2.
"java.lang.NullPointerException: must specify a log stream
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at io.camunda.zeebe.broker.jobstream.RemoteJobStreamErrorHandlerService.onBecomingLeader(RemoteJobStreamErrorHandlerService.java:56) ~[zeebe-broker-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.broker.system.partitions.PartitionStartupAndTransitionContextImpl.lambda$notifyListenersOfBecomingLeader$4(PartitionStartupAndTransitionContextImpl.java:164) ~[zeebe-broker-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at io.camunda.zeebe.broker.system.partitions.PartitionStartupAndTransitionContextImpl.notifyListenersOfBecomingLeader(PartitionStartupAndTransitionContextImpl.java:165) ~[zeebe-broker-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.broker.system.partitions.ZeebePartition.lambda$leaderTransition$6(ZeebePartition.java:243) ~[zeebe-broker-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:28) ~[zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT] ... 
ERROR 2023-07-10T18:18:50.942738393Z [resource.labels.containerName: zeebe] Failed to install partition 2
```

Transition to leader is cancelled (probably because there is a new leader already). But the `PartitionStartupAndTransitionContextImpl.lambda$notifyListenersOfBecomingLeader` is still invoked. Since the services were not installed, logstream is null and this causes NPE in the listener. 

Partition is inactive after that. However, the partition is still marked as healthy (See #13401) 

**Expected behavior**

Partition listeners are only invoked if the transition is successfully completed.

**Environment:**
- Zeebe Version: Observed in 8.3.0-SNAPSHOT (medic-cw-27 benchmark)

**Comment by megglos** [comment] 2023-07-13 12:05
ZDP-Triage:
- likelihood seems high - happened a couple of times in benchmarks already
- bug may exist for way longer already - it was not as visible before though
- 3-4 already existing issues might be caused by this
- workaround would be a pod restart - but hard to identify given partition is still marked as healthy

**Comment by oleschoenburg** [comment] 2023-07-18 15:43
The issue is that listeners are called when the transition completes normally and that we complete the transition normally when it is actually cancelled: https://github.com/camunda/zeebe/blob/a9d810011935b0538ed6a97cab342b72681c54a4/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/PartitionTransitionProcess.java#L66-L71

**Closed** 2023-07-21 13:00 UTC
Labels: kind/bug, severity/high
