### ISSUE TITLE
When resolving incident I can end up with negative retries

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#15437] opened 2023-11-30 13:52 UTC
**Describe the bug**

When resolving an incident (NOT_RETRIES_LEFT) without updating the retries, we can end up with retries that are negative. 

The impact is low. We can still activate the job afterward and complete it. If it fails again an incident is created as well.

**To Reproduce**

```java

  @Test
  public void shouldResolveIncidentIfJobRetriesIncreased() {
    // given
    ENGINE.job().withType(JOB_TYPE).ofInstance(processInstanceKey).fail();
    final Record<IncidentRecordValue> incidentCreatedEvent =
        RecordingExporter.incidentRecords()
            .withProcessInstanceKey(processInstanceKey)
            .withIntent(IncidentIntent.CREATED)
            .getFirst();

    // when
    //
    // ENGINE.job().ofInstance(processInstanceKey).withType(JOB_TYPE).withRetries(1).updateRetries();
    final Record<IncidentRecordValue> resolvedIncident =
        ENGINE
            .incident()
            .ofInstance(processInstanceKey)
            .withKey(incidentCreatedEvent.getKey())
            .resolve();
    ENGINE.jobs().withType(JOB_TYPE).activate();

    // then
    final Record jobEvent =
        RecordingExporter.jobRecords()
            .withIntent(JobIntent.FAILED)
            .withProcessInstanceKey(processInstanceKey)
            .getFirst();

    final Record activityEvent =
        RecordingExporter.processInstanceRecords()
            .withElementId("failingTask")
            .withIntent(ProcessInstanceIntent.ELEMENT_ACTIVATED)
            .withProcessInstanceKey(processInstanceKey)
            .getFirst();

    final Record incidentEvent =
        RecordingExporter.incidentRecords()
            .withIntent(IncidentIntent.RESOLVE)
            .withRecordKey(incidentCreatedEvent.getKey())
            .getFirst();

    final long lastPos = incidentEvent.getPosition();

    assertThat(resolvedIncident.getKey()).isGreaterThan(0);
    assertThat(resolvedIncident.getSourceRecordPosition()).isEqualTo(lastPos);

    assertThat(resolvedIncident.getValue())
        .hasErrorType(ErrorType.JOB_NO_RETRIES)
        .hasErrorMessage("No more retries left.")
        .hasBpmnProcessId("process")
        .hasProcessDefinitionKey(processDefinitionKey)
        .hasProcessInstanceKey(processInstanceKey)
        .hasElementId("failingTask")
        .hasElementInstanceKey(activityEvent.getKey())
        .hasVariableScopeKey(activityEvent.getKey());

    // and the job is activated again
    final var batchActivations =
        RecordingExporter.jobBatchRecords(JobBatchIntent.ACTIVATED)
            .filter(
                jobBatchRecordValueRecord ->
                    jobBatchRecordValueRecord.getValue().getJobs().stream()
                        .anyMatch(
                            jobRecordValue ->
                                jobRecordValue.getProcessInstanceKey() == processInstanceKey))
            .limit(2)
            .collect(Collectors.toList());
    assertThat(batchActivations).hasSize(2);
    final var secondActivationJobValue = batchActivations.get(1).getValue().getJobs().get(0);
    final var secondActivationJobKey = batchActivations.get(1).getValue().getJobKeys().get(0);

    assertThat(secondActivationJobKey).isEqualTo(jobEvent.getKey());
    assertThat(secondActivationJobValue).hasRetries(1);

    // and the job lifecycle is correct
    final List<Record> jobEvents =
        RecordingExporter.jobRecords()
            .filter(
                r ->
                    r.getKey() == jobEvent.getKey()
                        || r.getValue().getProcessInstanceKey() == processInstanceKey)
            .limit(5)
            .collect(Collectors.toList());

    assertThat(jobEvents)
        .extracting(Record::getRecordType, Record::getValueType, Record::getIntent)
        .containsExactly(
            tuple(RecordType.EVENT, ValueType.JOB, JobIntent.CREATED),
            tuple(RecordType.COMMAND, ValueType.JOB, JobIntent.FAIL),
            tuple(RecordType.EVENT, ValueType.JOB, JobIntent.FAILED),
            tuple(RecordType.COMMAND, ValueType.JOB, JobIntent.UPDATE_RETRIES),
            tuple(RecordType.EVENT, ValueType.JOB, JobIntent.RETRIES_UPDATED));
  }
```

**Expected behavior**

Either the incident command is rejected OR even better it sets the retries directly to one, so we can just skip the updateRetries step (which is weird why wee need this in the first place).

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
<pre>
--------
	['C'ommand/'E'event/'R'ejection] [valueType] [intent] - #[position]->#[source record position] K[key] - [summary of value]
	P9K999 - key; #999 - record position; "ID" element/process id; @"elementid"/[P9K999] - element with ID and key
	Keys are decomposed into partition id and per partition key (e.g. 2251799813685253 -> P1K005). If single partition, the partition is omitted.
	Long IDs are shortened (e.g. 'startEvent_5d56488e-0570-416c-ba2d-36d2a3acea78' -> 'star..acea78'
--------
C CREA      CREATE         - #04-> -1  -1 - new <process "process"> (default start)  with variables: {foo=bar}
E VAR       CREATED        - #05->#04 K04 - foo->"bar" in <process [K03]>
C PI        ACTIVATE       - #06->#04 K03 - PROCESS "process" in <process "process"[K03]>
E CREA      CREATED        - #07->#04 K05 - new <process "process"> (default start)  with variables: {foo=bar}
E PI        ACTIVATING     - #08->#04 K03 - PROCESS "process" in <process "process"[K03]>
E PI        ACTIVATED      - #09->#04 K03 - PROCESS "process" in <process "process"[K03]>
C PI        ACTIVATE       - #10->#04  -1 - START_EVENT "startEv..0e8565f" in <process "process"[K03]>
E PI        ACTIVATING     - #11->#04 K06 - START_EVENT "startEv..0e8565f" in <process "process"[K03]>
E PI        ACTIVATED      - #12->#04 K06 - START_EVENT "startEv..0e8565f" in <process "process"[K03]>
C PI        COMPLETE       - #13->#04 K06 - START_EVENT "startEv..0e8565f" in <process "process"[K03]>
E PI        COMPLETING     - #14->#04 K06 - START_EVENT "startEv..0e8565f" in <process "process"[K03]>
E PI        COMPLETED      - #15->#04 K06 - START_EVENT "startEv..0e8565f" in <process "process"[K03]>
E PI        SEQ_FLOW_TAKEN - #16->#04 K07 - SEQUENCE_FLOW "sequenc..d4d6611" in <process "process"[K03]>
C PI        ACTIVATE       - #17->#04 K08 - SERVICE_TASK "failingTask" in <process "process"[K03]>
E PI        ACTIVATING     - #18->#04 K08 - SERVICE_TASK "failingTask" in <process "process"[K03]>
E VAR       CREATED        - #19->#04 K09 - foo->"bar" in <process [K03] at [K08]>
E JOB       CREATED        - #20->#04 K10 - K10 "test" @"failingTask"[K08] 3 retries, in <process "process"[K03]> (no vars)
E PI        ACTIVATED      - #21->#04 K08 - SERVICE_TASK "failingTask" in <process "process"[K03]>
C JOB_BATCH ACTIVATE       - #22-> -1  -1 - "test" max: 1
E JOB_BATCH ACTIVATED      - #23->#22 K11 - "test" 1/1
                K10 "test" @"failingTask"[K08] 3 retries, in <process "process"[K03]> with variables: {foo=bar}
C JOB       FAIL           - #24-> -1 K10 - K10 "test" @""[ -1] -1 retries, in <process ?[?]> (no vars)
E JOB       FAILED         - #25->#24 K10 - K10 "test" @"failingTask"[K08] -1 retries, in <process "process"[K03]> (no vars)
E INCIDENT  CREATED        - #26->#24 K12 - JOB_NO_RETRIES No more retries left., joBKey: K10  @"failingTask"[K08] in <process "process"[K03]>
C INCIDENT  RESOLVE        - #27-> -1 K12 - K12
E INCIDENT  RESOLVED       - #28->#27 K12 - JOB_NO_RETRIES No more retries left., joBKey: K10  @"failingTask"[K08] in <process "process"[K03]>
C JOB_BATCH ACTIVATE       - #29-> -1  -1 - "test" max: 10
E JOB_BATCH ACTIVATED      - #30->#29 K13 - "test" 1/10
                K10 "test" @"failingTask"[K08] -1 retries, in <process "process"[K03]> with variables: {foo=bar}

-------------- Deployed Processes ----------------------

--------------- Decomposed keys (for debugging) -----------------
 -1 <-> -1
K03 <-> 2251799813685251
K04 <-> 2251799813685252
K05 <-> 2251799813685253
K06 <-> 2251799813685254
K07 <-> 2251799813685255
K08 <-> 2251799813685256
K09 <-> 2251799813685257
K10 <-> 2251799813685258
K11 <-> 2251799813685259
K12 <-> 2251799813685260
K13 <-> 2251799813685261

java.lang.AssertionError: 
Expecting retries of:
  <{"deadline":1701352163898,"timeout":-1,"worker":"","retries":-1,"retryBackoff":0,"recurringTime":-1,"type":"test","customHeaders":[packed value (length=1)],"variables":"3wAAAAGjZm9vo2Jhcg==","errorMessage":"","errorCode":"","bpmnProcessId":"process","processDefinitionVersion":1,"processDefinitionKey":2251799813685249,"processInstanceKey":2251799813685251,"elementId":"failingTask","elementInstanceKey":2251799813685256,"tenantId":"<default>"}>
to be:
  <1>
but was:
  <-1>
</pre>
</details>

**Environment:**
- Zeebe Version: all?

**Comment by Zelldon** [comment] 2023-12-01 14:21
Support related https://jira.camunda.com/browse/SUPPORT-18432

**Comment by abbasadel** [comment] 2023-12-04 14:20
ZPA triage:
- We align with the severity/low 
- Since @Zelldon provided a test case to reproduce the bug, we size it as small and priority `Later`
- This is a good onboarding issue but after improving the test case a bit for clarity for new joiners
- We making the impact medium as we see it as a "low hanging fruit"

**Comment by ana-vinogradova-camunda** [comment] 2024-04-18 09:29
Related to [I can activate a job without retries after resolving the JOB_NO_RETRIES incident ](https://github.com/camunda/zeebe/issues/16484).
There is a PR for the fix [here](https://github.com/camunda/zeebe/pull/17504) that would fix that.
However, the implementation is to reject resolve job incident command as per the above bug expected behaviour description:

`The resolve incident command should be rejected and the job should not be made activatable again.`

@megglos @Zelldon please let me know if we'd like to change the fix to set the retries directly to one.

**Comment by megglos** [comment] 2024-04-18 11:58
> so we can just skip the updateRetries step (which is weird why wee need this in the first place).

as this increases the scope and also affect docs I would suggest to create a follow-up to "automate" the updateRetries step as an improvement.

**Comment by ana-vinogradova-camunda** [comment] 2024-04-30 10:48
Fixed with [this PR](https://github.com/camunda/zeebe/pull/17504)

**Closed by ana-vinogradova-camunda** 2024-04-30 10:48 UTC
Labels: kind/bug, severity/low, support, component/engine, onboarding, impact/medium, likelihood/low, component/zeebe
