### ISSUE TITLE
Process Instance Modification Mode issue

### ISSUE THREAD

**Issue by kkk25641463** [camunda/zeebe#10742] opened 2022-10-18 07:32 UTC
**Describe the bug**
I test bpmn [example](url).
When I use "Process Instance Modification Mode" to change process instance. Zeebe service  always report error msg.And process can't cancel.
MayBe elastic dynamic_templates mode not support ?

```
        at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.1.jar:8.1.1]
2022-10-18 07:23:30.992 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN 
      io.camunda.zeebe.broker.exporter.elasticsearch - Error on exporting record with key 2251799813687139
io.camunda.zeebe.exporter.ElasticsearchExporterException: Failed to flush bulk request: [Failed to flush 1 item(s) of bulk request [type: strict_dynamic_mapping_exception, reason: mapping set to strict, dynamic introduction of [activatedElementInstanceKeys] within [value] is not allowed]]
        at io.camunda.zeebe.exporter.ElasticsearchClient.throwCollectedBulkError(ElasticsearchClient.java:188) ~[zeebe-elasticsearch-exporter-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.exporter.ElasticsearchClient.exportBulk(ElasticsearchClient.java:171) ~[zeebe-elasticsearch-exporter-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.exporter.ElasticsearchClient.flush(ElasticsearchClient.java:103) ~[zeebe-elasticsearch-exporter-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.exporter.ElasticsearchExporter.flush(ElasticsearchExporter.java:139) ~[zeebe-elasticsearch-exporter-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.exporter.ElasticsearchExporter.export(ElasticsearchExporter.java:86) ~[zeebe-elasticsearch-exporter-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$export$3(ExporterContainer.java:156) ~[zeebe-broker-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader(ThreadContextUtil.java:58) ~[zeebe-util-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader(ThreadContextUtil.java:34) ~[zeebe-util-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.export(ExporterContainer.java:155) ~[zeebe-broker-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.exportRecord(ExporterContainer.java:142) ~[zeebe-broker-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.broker.exporter.stream.ExporterDirector$RecordExporter.export(ExporterDirector.java:523) ~[zeebe-broker-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.scheduler.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[zeebe-scheduler-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.1.jar:8.1.1]
2022-10-18 07:23:35.417 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] WARN 
      io.camunda.zeebe.broker.exporter.elasticsearch - Unexpected exception occurred on periodically flushing bulk, will retry later.
io.camunda.zeebe.exporter.ElasticsearchExporterException: Failed to flush bulk request: [Failed to flush 1 item(s) of bulk request [type: strict_dynamic_mapping_exception, reason: mapping set to strict, dynamic introduction of [activatedElementInstanceKeys] within [value] is not allowed]]
        at io.camunda.zeebe.exporter.ElasticsearchClient.throwCollectedBulkError(ElasticsearchClient.java:188) ~[zeebe-elasticsearch-exporter-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.exporter.ElasticsearchClient.exportBulk(ElasticsearchClient.java:171) ~[zeebe-elasticsearch-exporter-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.exporter.ElasticsearchClient.flush(ElasticsearchClient.java:103) ~[zeebe-elasticsearch-exporter-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.exporter.ElasticsearchExporter.flush(ElasticsearchExporter.java:139) ~[zeebe-elasticsearch-exporter-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.exporter.ElasticsearchExporter.flushAndReschedule(ElasticsearchExporter.java:126) ~[zeebe-elasticsearch-exporter-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.1.jar:8.1.1]
        at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.1.jar:8.1.1]
```

**To Reproduce**

Click "Apply modifiations" button.
![111](https://user-images.githubusercontent.com/1751500/196364315-87c19432-3ade-45ba-9ddb-47c17d2b1cdc.jpg)

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: CentOS Stream 8
- Zeebe Version:  8.1.1-->
- Configuration: 
-   zeebe docker-compose.yaml

**Comment by saig0** [comment] 2022-10-18 07:35
@kkk25641463 thank you for reporting. :+1: 

This issue is a duplicate of #10732. We fixed the bug. The build a new patch release very soon. 

Closing this issue in favor of https://github.com/camunda/zeebe/issues/10732.

**Closed by saig0** 2022-10-18 07:35 UTC
Labels: kind/bug
