### ISSUE TITLE
NPE during deployment

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#11733] opened 2023-02-17 13:02 UTC
**Describe the bug**

An NPE was thrown while deploying a process with a sub process. The sub process transformer's `TransformContext` had no `currentProcess` (i.e. it was null).

Link to error: https://console.cloud.google.com/errors/detail/CISLmomymvraMw;service=zeebe;time=P7D?project=camunda-cloud-240911

I've classified it as mid because we don't know what the process look like and if there is a workaround, and the user would definitely not know how to fix this.

This may be related to: https://github.com/camunda/zeebe/issues/11392

**To Reproduce**

Since the process failed to deploy, I don't know how I could find it. We might have to contact the user for it. It happened twice in the same cluster with different processes (at least going by the file names).

**Expected behavior**

No NPE, and a sub process should always have a parent process.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.processing.deployment.model.element.ExecutableProcess.getElementById(String, java.lang.Class)" because "currentProcess" is null
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.SubProcessTransformer.transform(SubProcessTransformer.java:30) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.model.transformer.SubProcessTransformer.transform(SubProcessTransformer.java:19) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:73) ~[zeebe-bpmn-model-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:121) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$transformResource$1(BpmnResourceTransformer.java:72) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.transformResource(BpmnResourceTransformer.java:65) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:120) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:97) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:96) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:264) ~[zeebe-stream-platform-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:260) ~[zeebe-stream-platform-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:209) ~[zeebe-stream-platform-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:185) ~[zeebe-stream-platform-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.2.0-alpha4.jar:8.2.0-alpha4] 
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.2.0-alpha4
- Configuration: SaaS

**Comment by remcowesterhoud** [comment] 2023-02-17 13:15
Duplicate of #11392. The fix just barely missed the code freeze, so it still exists in alpha4.

**Closed by remcowesterhoud** 2023-02-17 13:15 UTC
Labels: kind/bug, severity/mid
