### ISSUE TITLE
Gateway crashlooping with: Failed to introspect Class

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10529] opened 2022-09-28 05:39 UTC
**Describe the bug**

Gateway doesn't start and is crash looping because of some Spring issues

```
$ kgpo
NAME                                           READY   STATUS      RESTARTS        AGE
camunda-platform-curator-27739050-lmnml        0/1     Completed   0               6m58s
elasticsearch-master-0                         1/1     Running     0               30m
elasticsearch-master-1                         1/1     Running     0               30m
elasticsearch-master-2                         1/1     Running     0               30m
timer-6c8b99d75f-fpscm                         1/1     Running     0               30m
zell-try-timer-zeebe-0                         1/1     Running     0               30m
zell-try-timer-zeebe-1                         1/1     Running     0               30m
zell-try-timer-zeebe-2                         1/1     Running     0               30m
zell-try-timer-zeebe-gateway-79fc789c4-8sbkh   0/1     Running     5 (2m1s ago)    30m
zell-try-timer-zeebe-gateway-79fc789c4-bd2z6   0/1     Running     5 (2m12s ago)   30m
zell-try-timer-zeebe-gateway-79fc789c4-wm8nk   0/1     Running     5 (2m52s ago)   30m

```

```
{"severity":"WARNING","logging.googleapis.com/sourceLocation":{"function":"refresh","file":"AbstractApplicationContext.java","line":591},"message":"Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gatewayResponsiveHealthIndicator' defined in class path resource [io/camunda/zeebe/gateway/impl/probes/health/ResponsiveHealthIndicatorAutoConfiguration.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [io.camunda.zeebe.gateway.impl.probes.health.ResponsiveHealthIndicator] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@234bef66]","serviceContext":{"service":"zeebe","version":"zell-try-timer"},"context":{"threadId":1,"threadPriority":5,"loggerName":"org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext","threadName":"main"},"timestampSeconds":1664343342,"timestampNanos":383493853}

```

**To Reproduce**

Check zell-try-timer http://34.77.165.228/d/NzsO1mUnk/zeebe-overview?orgId=1&refresh=10s&var-DS_PROMETHEUS=Prometheus&var-namespace=zell-try-timer&var-pod=All&var-partition=All in k8

Or this branch https://github.com/camunda/zeebe/tree/zell-investigate-timer-loop and run a benchmark with it.

**Expected behavior**

No issues on running the gateway.

**Log/Stacktrace**
```
Events:
  Type     Reason            Age                  From                Message
  ----     ------            ----                 ----                -------
  Warning  FailedScheduling  32m (x2 over 32m)    default-scheduler   0/33 nodes are available: 1 node(s) didn't match pod anti-affinity rules, 32 Insufficient cpu.
  Normal   TriggeredScaleUp  31m                  cluster-autoscaler  pod triggered scale-up: [{https://www.googleapis.com/compute/v1/projects/zeebe-io/zones/europe-west1-b/instanceGroups/gke-zeebe-cluster-default-pool-1f44de48-grp 33->35 (max: 128)}]
  Warning  FailedScheduling  31m                  default-scheduler   0/36 nodes are available: 2 node(s) didn't match pod anti-affinity rules, 2 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate, 32 Insufficient cpu.
  Normal   Scheduled         31m                  default-scheduler   Successfully assigned zell-try-timer/zell-try-timer-zeebe-gateway-79fc789c4-8sbkh to gke-zeebe-cluster-default-pool-1f44de48-jxpj
  Normal   Pulling           31m                  kubelet             Pulling image "gcr.io/zeebe-io/zeebe:zell-try-timer"
  Normal   Pulled            31m                  kubelet             Successfully pulled image "gcr.io/zeebe-io/zeebe:zell-try-timer" in 13.970008449s
  Normal   Created           31m                  kubelet             Created container zeebe-gateway
  Normal   Started           31m                  kubelet             Started container zeebe-gateway
  Warning  Unhealthy         72s (x317 over 30m)  kubelet             Readiness probe failed: dial tcp 10.0.34.2:26500: connect: connection refused
```

**Comment by Zelldon** [comment] 2022-09-28 06:51
On main it seems to work ? :thinking:

**Comment by Zelldon** [comment] 2022-09-28 06:58
@oleschoenburg seem to releated to my branch :/ but I don't understand why

**Comment by oleschoenburg** [comment] 2022-09-28 07:02
I can reproduce with your container. I'm now looking at the class files to see if there's anything obvious that went wrong.

**Comment by oleschoenburg** [comment] 2022-09-28 07:41
If I do a `mvn clean install` and rebuild the container on the `zell-investigate-timer-loop` branch I can't reproduce it. I guess something went wrong while building the image. As it's not reproducible (especially not on main) I'm closing this.

**Closed by oleschoenburg** 2022-09-28 07:41 UTC
Labels: kind/bug, severity/high

**Comment by npepinpe** [comment] 2022-09-28 13:23
But is this something that can happen just randomly? Do we know what happened at all?
