### ISSUE TITLE
many  ActivateJobs(RESOURCE EXHAUSTED) appear suddenly 

### ISSUE THREAD

**Issue by jerry123888** [camunda/zeebe#12911] opened 2023-05-31 11:22 UTC
Env:
Zeebe Version: 1.2.4
ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT =18
ZEEBE_BROKER_CLUSTER_CLUSTERSIZE = 18

The zeebe cluster runs well and the load is normal, the use of cpu&memory is about 20%, and no sudden increasing tasks.
But many  ActivateJobs(RESOURCE EXHAUSTED) appear suddenly:
![image](https://github.com/camunda/zeebe/assets/92800459/145785ec-987c-4092-83db-9b1e76a6939b)

And now some tasks of createInstance will be failed:
get createInstance result error: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Expected to execute the command on one of the partitions, but all failed; there are no more partitions available to retry. Please try again. If the error persists contact your zeebe operator.

At the beginning,  only two partitions(9 and 12) appear the backpressure :
![image](https://github.com/camunda/zeebe/assets/92800459/da125a03-f345-435a-bd76-a6e4422d49d9)

But as the time go on, more and more partitions also appears:
![image](https://github.com/camunda/zeebe/assets/92800459/fb16add5-c4d5-42f7-a01b-9f40e22b4e86)

My configure of backpressure is:
ZEEBE_BROKER_BACKPRESSURE_VEGAS_INITIALLIMIT=500
ZEEBE_BROKER_BACKPRESSURE_VEGAS_ALPHA=7
ZEEBE_BROKER_BACKPRESSURE_VEGAS_BETA=14

Looking forward to your reply.

**Comment by koevskinikola** [comment] 2023-07-11 11:07
Individual ZPA triage:

As the root cause for this issue is not clear, and we haven't received any response from the user that reported the problem in more than a month, I'm closing this issue.

---

Hi @jerry123888,

For questions like these, it is always better to open a help request topic on the Camunda forums: https://forum.camunda.io/. By posting on our forums, you benefit from the experience of the Camunda experts and the Camunda community.

I'm closing this issue as we aim to use the GitHub issues for development purposes only.

**Closed by koevskinikola** 2023-07-11 11:07 UTC
Labels: kind/question
