### ISSUE TITLE
ZbDbInconsistentException on muliple partitions

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9781] opened 2022-07-13 07:40 UTC
**Describe the bug**

Occurred in medic benchmark.

In partition 1
```
java.lang.RuntimeException: io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbLong{2251799933202804} in ColumnFamily EVENT_SCOPE already exists
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.lambda$replayNextEvent$4(ReplayStateMachine.java:176) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
``` 
In partition 2
```
java.lang.RuntimeException: io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbLong{4503599746363540} in ColumnFamily ELEMENT_INSTANCE_CHILD_PARENT already exists
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.lambda$replayNextEvent$4(ReplayStateMachine.java:176) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT
```
In partition 3
```
"java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.instance.ElementInstance.setState(io.camunda.zeebe.protocol.record.intent.ProcessInstanceIntent)" because "instance" is null
	at io.camunda.zeebe.streamprocessor.ReplayStateMachine.lambda$replayNextEvent$4(ReplayStateMachine.java:176) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
```

**Log/Stacktrace**

- [Link to logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-07-13T00:00:55.342752420Z;pinnedLogId=2022-07-12T23:26:54.921696097Z%2F1lo5nuv60xlcvik9;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22medic-cw-28-e1a41564e5-benchmark-zeebe-2%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.namespace_name%3D%22medic-cw-28-e1a41564e5-benchmark%22%0Aseverity%3DERROR%0Atimestamp%3D%222022-07-12T23:26:54.921696097Z%22%0AinsertId%3D%221lo5nuv60xlcvik9%22;summaryFields=jsonPayload%252Fcontext%252FpartitionId:false:32:beginning:false;timeRange=2022-07-12T22:40:24Z%2F2022-07-13T02:48:24Z?project=zeebe-io) 
- [Downloaded logs and data](https://drive.google.com/drive/folders/1klO9BJwHT4r8N-M7jzHYpzWom3g97izh)

**Comment by deepthidevaki** [comment] 2022-07-13 13:03
Did a quick look over the logs and the data.

**Hypothesis**: A command is processed and the state is updated, but it is not marked as processed in the snapshot (state and lastProcessedPosition is expected to be updated in a single transaction to avoid this specific case. So not sure how this can happen). As a result, after recovering from this snapshot, when replaying it re-applies the state which results in these exceptions.

**Observations**:

Broke-2 partition-3 role=follower takes snapshot `104460777-4-315503830-315478758
` This is the "corrupted" snapshot.

```
{"partitionId":1,"value":{"type":"benchmark-task","worker":"benchmark-worker","truncated":false,"timeout":300,"maxJobsToActivate":119,"jobKeys":[],"jobs":[]},"key":6755399559534844,"timestamp":1657667450857,"position":315503996,"valueType":"JOB_BATCH","intent":"ACTIVATED","recordType":"EVENT","rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"8.1.0","sourceRecordPosition":315503950}
```
Above record is the event of the lastProcessedPosition in the snapshot.

When the following event is replayed, it results in the exception.
```
{"partitionId":1,"value":{"version":1,"bpmnProcessId":"benchmark","processInstanceKey":6755399559534649,"parentElementInstanceKey":-1,"flowScopeKey":-1,"parentProcessInstanceKey":-1,"elementId":"benchmark","bpmnElementType":"PROCESS","processDefinitionKey":2251799813685254},"key":6755399559534649,"timestamp":1657667450858,"position":315503997,"valueType":"PROCESS_INSTANCE","intent":"ELEMENT_COMPLETING","recordType":"EVENT","rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"8.1.0","sourceRecordPosition":315503955}
{"partitionId":1,"value":{"version":1,"processDefinitionKey":2251799813685254,"bpmnElementType":"PROCESS","bpmnProcessId":"benchmark","processInstanceKey":6755399559534649,"parentElementInstanceKey":-1,"flowScopeKey":-1,"parentProcessInstanceKey":-1,"elementId":"benchmark"},"key":6755399559534649,"timestamp":1657667450858,"position":315503998,"valueType":"PROCESS_INSTANCE","intent":"ELEMENT_COMPLETED","recordType":"EVENT","rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"8.1.0","sourceRecordPosition":315503955}
```

In the snapshot the process instance does not exist.
```
> zdb instance entity 6755399559534649 -p=/home/deepthi/work/temp/error-log/zeebe-2/partitions/3/runtime
null
```

The event in the next position is the following and it's state seems to be correct:
```
{"partitionId":1,"value":{"version":1,"processDefinitionKey":2251799813685254,"parentElementInstanceKey":-1,"flowScopeKey":6755399559534687,"parentProcessInstanceKey":-1,"elementId":"task","bpmnElementType":"SERVICE_TASK","bpmnProcessId":"benchmark","processInstanceKey":6755399559534687},"key":6755399559534742,"timestamp":1657667450859,"position":315503999,"valueType":"PROCESS_INSTANCE","intent":"ELEMENT_COMPLETING","recordType":"EVENT","rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"8.1.0","sourceRecordPosition":315503958}

> zdb instance entity 6755399559534687 -p=/home/deepthi/work/temp/error-log/zeebe-2/partitions/3/runtime{"key":6755399559534687,"state":"ELEMENT_ACTIVATED","bpmnProcessId":"benchmark","processDefinitionKey":2251799813685254,"version":1,"processInstanceKey":6755399559534687,"parentElementInstanceKey":-1,"flowScopeKey":-1,"parentProcessInstanceKey":-1,"elementType":"PROCESS","elementId":"benchmark","jobKey":0,"children":[6755399559534742]}
```

Broker-2 partition-1 role=follower takes snapshot `105243226-2-318301755-318276424`. This is the corrupted snapshot.

```
zdb status -p=/home/deepthi/work/temp/error-log/zeebe-2/partitions/1/runtime
{"processingDetails":{"lastProcessedPosition":318301762},"exportingDetails":{"exporters":{"elasticsearch":318474599,"MetricsExporter":318474599},"lowestExportedPosition":318474599},"incidentDetails":{"blacklistedInstances":0,"incidents":0},"messageDetails":{"count":0,"nextDeadline":9223372036854775807,"lastDeadline":0},"processInstancesDetails":{"processInstanceCount":14,"elementInstanceCount":10},"variablesDetails":{"variablesCount":64,"maxSize":13754,"minSize":1,"avgSize":3439.75}}
```

Event of processedPosition
```
{"partitionId":1,"value":{"type":"benchmark-task","errorMessage":"","errorCode":"","processDefinitionKey":2251799813685254,"bpmnProcessId":"benchmark","processInstanceKey":2251799933202649,"elementId":"task","deadline":1657667798643,"retries":3,"retryBackoff":0,"recurringTime":-1,"processDefinitionVersion":1,"elementInstanceKey":2251799933202729,"worker":"benchmark-worker","customHeaders":{},"variables":{"zSHhpDEfpdkCgzuoI":null, ... ,"lFBmqdOZAvOpGLKfj":null}},"key":2251799933202751,"timestamp":1657667798454,"position":318301815,"valueType":"JOB","intent":"COMPLETED","recordType":"EVENT","rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"8.1.0","sourceRecordPosition":318301762}

{"partitionId":1,"value":{"processDefinitionKey":2251799813685254,"processInstanceKey":2251799933202649,"variables":{"zSHhpDEfpdkCgzuoI":null,......,"lFBmqdOZAvOpGLKfj":null},"targetElementId":"task","scopeKey":2251799933202729},"key":2251799933202825,"timestamp":1657667798454,"position":318301816,"valueType":"PROCESS_EVENT","intent":"TRIGGERING","recordType":"EVENT","rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"8.1.0","sourceRecordPosition":318301762}

{"partitionId":1,"value":{"version":1,"bpmnProcessId":"benchmark","processInstanceKey":2251799933202649,"parentElementInstanceKey":-1,"flowScopeKey":2251799933202649,"parentProcessInstanceKey":-1,"elementId":"task","bpmnElementType":"SERVICE_TASK","processDefinitionKey":2251799813685254},"key":2251799933202729,"timestamp":1657667798454,"position":318301817,"valueType":"PROCESS_INSTANCE","intent":"COMPLETE_ELEMENT","recordType":"COMMAND","rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"8.1.0","sourceRecordPosition":318301762}
```

I assume the following event resulted in the error: `Key DbLong{2251799933202804} in ColumnFamily EVENT_SCOPE already exists`. This is the next event after the above "processed events".

```
{"partitionId":1,"value":{"version":1,"bpmnElementType":"SERVICE_TASK","processDefinitionKey":2251799813685254,"bpmnProcessId":"benchmark","processInstanceKey":2251799933202736,"parentElementInstanceKey":-1,"flowScopeKey":2251799933202736,"parentProcessInstanceKey":-1,"elementId":"task"},"key":2251799933202804,"timestamp":1657667798455,"position":318301818,"valueType":"PROCESS_INSTANCE","intent":"ELEMENT_ACTIVATING","recordType":"EVENT","rejectionType":"NULL_VAL","rejectionReason":"","brokerVersion":"8.1.0","sourceRecordPosition":318301767}

```

**Comment by oleschoenburg** [comment] 2022-07-18 07:50
I believe the same happened again in more benchmark clusters. I have ~8GiB of data saved locally that I can upload if needed for debugging.

**Comment by korthout** [comment] 2022-07-18 12:44
>Hypothesis: A command is processed and the state is updated, but it is not marked as processed in the snapshot 

@deepthidevaki I think I can confirm your hypothesis:

The runtime has not updated its `lastProcessedPosition` since the snapshot
```
 zdb status -p=/Users/korthout/data/9781/zeebe-2/partitions/3/snapshots/104460777-4-315503830-315478758 | jq '.processingDetails'
{
  "lastProcessedPosition": 315503950
}

 zdb status -p=/Users/korthout/data/9781/zeebe-2/partitions/3/runtime | jq '.processingDetails'
{
  "lastProcessedPosition": 315503950
}
```

But there exist more recently processed commands on the log.

Here's an example of an event written because of processing the command at position `316537179`. There are more than 1M newer records on the log stream compared to the `"lastProcessedPosition": 315503950`.

```
zdb log search -pos=316537180 -p=/Users/korthout/data/9781/zeebe-2/partitions/3 | jq
{
  "partitionId": 1,
  "value": {
    "type": "benchmark-task",
    "timeout": 300,
    "jobKeys": [],
    "jobs": [],
    "worker": "benchmark-worker",
    "truncated": false,
    "maxJobsToActivate": 120
  },
  "key": 6755399559929446,
  "timestamp": 1657681202639,
  "intent": "ACTIVATED",
  "recordType": "EVENT",
  "rejectionType": "NULL_VAL",
  "rejectionReason": "",
  "brokerVersion": "8.1.0",
  "valueType": "JOB_BATCH",
  "sourceRecordPosition": 316537179,
  "position": 316537180
}
```

**Comment by oleschoenburg** [comment] 2022-07-18 12:49
@korthout `os-fix-snapshot-replication`. Ominously named but should be unrelated to the issue here :laughing: There are also others, see https://console.cloud.google.com/errors/detail/COC15KXI4c2ESQ?project=zeebe-io

**Comment by oleschoenburg** [comment] 2022-07-18 12:59
One thing I've noticed that stood out: In the `os-fix-snapshot-replication`cluster, after the broker starts it should log this message: 
https://github.com/camunda/zeebe/blob/49faab271674a7983eca891a60af4f29202229bb/engine/src/main/java/io/camunda/zeebe/streamprocessor/ReplayStateMachine.java#L136-L139

But for partition 1, the partition that failed, this message is never logged. It does log this though:

https://github.com/camunda/zeebe/blob/49faab271674a7983eca891a60af4f29202229bb/engine/src/main/java/io/camunda/zeebe/streamprocessor/StreamProcessor.java#L179

I don't understand how this is possible but it looks suspicious IMO.

**Comment by korthout** [comment] 2022-07-18 13:15
> I don't understand how this is possible but it looks suspicious IMO.

You're referring to the code on `main`, but I don't know what code this `os-fix-snapsht...` cluster is running. Do you know?

**Comment by oleschoenburg** [comment] 2022-07-18 13:18
@korthout Should be fairly recent, I branched this from main on friday. Don't have the exact commit though :confused:

**Comment by oleschoenburg** [comment] 2022-07-19 11:14
Found something that might be related: the new `Engine` class was only created once, in the constructor of `StreamProcessor`. This happened before(!) the stream processor started snapshot recovery. Effectively, the `Engine` didn't run on the snapshot state. This is all based on e1a41564e5.

On main (145c697eba552a13d5a313174e7c5d5f26456842), we at least call `Engine#init` after snapshot recovery which seems to to _something_ but the `eventAppliers` are still not rebuilt and appear to run on old state. To be honest, the current state of the StreamProcessor and Engine is very confusing to me but this seems like a bug. cc @pihme

**Comment by oleschoenburg** [comment] 2022-07-19 12:31
There is definitely a difference. Previously, the event appliers were [built during snapshot recovery](https://github.com/camunda/zeebe/blob/eb8cfb39ca3146c19558693be14fa1863ed0bd24/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/StreamProcessor.java#L348), then we [constructed a new instance](https://github.com/camunda/zeebe/blob/eb8cfb39ca3146c19558693be14fa1863ed0bd24/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/StreamProcessor.java#L166) of `ReplayStateMachine` which then [used the fresh event appliers](https://github.com/camunda/zeebe/blob/c49fd54d5cd17a8dd6ff937952b223d4861012bd/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ReplayStateMachine.java#L95).

Now, the event appliers are only [built when constructing](https://github.com/camunda/zeebe/blob/b5edab6f13e975757b134aa933a0be50315373d0/engine/src/main/java/io/camunda/zeebe/engine/Engine.java#L37) a new `Engine`, which happens when a `StreamProcessor` is [constructed](https://github.com/camunda/zeebe/blob/b5edab6f13e975757b134aa933a0be50315373d0/engine/src/main/java/io/camunda/zeebe/streamprocessor/StreamProcessor.java#L144), not after snapshot recovery!

**Comment by oleschoenburg** [comment] 2022-07-19 15:51
Should be fixed by https://github.com/camunda/zeebe/pull/9841 but we should definitely keep an eye on this and make sure that it doesn't (re-)appear on later benchmarks.

**Closed by oleschoenburg** 2022-07-19 15:51 UTC
Labels: kind/bug, severity/high
