### ISSUE TITLE
InstallRequestHandlingTest#shouldContinueProcessingAfterReplay

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10501] opened 2022-09-27 05:50 UTC
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once on jenkins
- Does it block your work? No
- Do we suspect that it is a real failure? Idk

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
[ERROR] io.camunda.zeebe.it.clustering.InstallRequestHandlingTest.shouldContinueProcessingAfterReplay  Time elapsed: 37.482 s  <<< FAILURE!

[2022-09-26T15:44:30.682Z] java.lang.AssertionError: 

[2022-09-26T15:44:30.682Z] 

[2022-09-26T15:44:30.682Z] Expecting actual not to be null

[2022-09-26T15:44:30.682Z] 	at io.camunda.zeebe.it.util.ZeebeAssertHelper.assertElementCompleted(ZeebeAssertHelper.java:156)

[2022-09-26T15:44:30.682Z] 	at io.camunda.zeebe.it.util.ZeebeAssertHelper.assertProcessInstanceCompleted(ZeebeAssertHelper.java:113)

[2022-09-26T15:44:30.682Z] 	at io.camunda.zeebe.it.util.ZeebeAssertHelper.assertProcessInstanceCompleted(ZeebeAssertHelper.java:108)

[2022-09-26T15:44:30.682Z] 	at io.camunda.zeebe.it.clustering.InstallRequestHandlingTest.shouldContinueProcessingAfterReplay(InstallRequestHandlingTest.java:91)

[2022-09-26T15:44:30.682Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2022-09-26T15:44:30.682Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

[2022-09-26T15:44:30.682Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2022-09-26T15:44:30.682Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

[2022-09-26T15:44:30.682Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

[2022-09-26T15:44:30.682Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

[2022-09-26T15:44:30.682Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

[2022-09-26T15:44:30.682Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

[2022-09-26T15:44:30.682Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2022-09-26T15:44:30.682Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)

[2022-09-26T15:44:30.682Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2022-09-26T15:44:30.682Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2022-09-26T15:44:30.682Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

[2022-09-26T15:44:30.682Z] 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)

[2022-09-26T15:44:30.682Z] 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)

[2022-09-26T15:44:30.682Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[2022-09-26T15:44:30.682Z] 	at java.base/java.lang.Thread.run(Thread.java:833)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda%2Fzeebe/detail/main/843/pipeline

**Comment by remcowesterhoud** [comment] 2022-09-30 07:34
Another case on Jenkins here: https://ci.zeebe.camunda.cloud/job/camunda/job/zeebe/job/main/871/

**Comment by deepthidevaki** [comment] 2022-10-06 10:41
Was not able to reproduce this. Has it ever failed in gh ci?

**Comment by oleschoenburg** [comment] 2022-10-06 10:42
I don't have proof but I'm pretty sure I saw it fail on GHA at least once :shrug:

**Comment by deepthidevaki** [comment] 2022-10-12 07:15
I will close this, as I'm not able to reproduce this. If it occurs in gha please reopen this issue and share the logs.

**Closed by deepthidevaki** 2022-10-12 07:15 UTC
Labels: kind/flake
