### ISSUE TITLE
java.lang.IllegalStateException: Invalid TEMPLATE_ID

### ISSUE THREAD

**Issue by saig0** [camunda/zeebe#12668] opened 2023-05-04 11:41 UTC
**Describe the bug**

In the broker logs, I see the following error message:

```
java.lang.IllegalStateException: Invalid TEMPLATE_ID: 1
	at io.camunda.zeebe.protocol.record.AdminRequestDecoder.wrapAndApplyHeader(AdminRequestDecoder.java:93) ~[zeebe-protocol-8.0.15-SNAPSHOT.jar:8.0.15-SNAPSHOT] 
```

The failure seems to be related to the Admin API.

**To Reproduce**

Unknown.

**Expected behavior**

No errors. :sweat_smile: 

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Invalid TEMPLATE_ID: 1
	at io.camunda.zeebe.protocol.record.AdminRequestDecoder.wrapAndApplyHeader(AdminRequestDecoder.java:93) ~[zeebe-protocol-8.0.15-SNAPSHOT.jar:8.0.15-SNAPSHOT]
	at io.camunda.zeebe.broker.transport.adminapi.ApiRequestReader.wrap(ApiRequestReader.java:29) ~[zeebe-broker-8.0.15-SNAPSHOT.jar:8.0.15-SNAPSHOT]
	at io.camunda.zeebe.broker.transport.ApiRequestHandler.handleRequest(ApiRequestHandler.java:85) ~[zeebe-broker-8.0.15-SNAPSHOT.jar:8.0.15-SNAPSHOT]
	at io.camunda.zeebe.broker.transport.ApiRequestHandler.lambda$onRequest$0(ApiRequestHandler.java:70) ~[zeebe-broker-8.0.15-SNAPSHOT.jar:8.0.15-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:72) ~[zeebe-util-8.0.15-SNAPSHOT.jar:8.0.15-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:42) ~[zeebe-util-8.0.15-SNAPSHOT.jar:8.0.15-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:125) ~[zeebe-util-8.0.15-SNAPSHOT.jar:8.0.15-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-8.0.15-SNAPSHOT.jar:8.0.15-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-8.0.15-SNAPSHOT.jar:8.0.15-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.15-SNAPSHOT.jar:8.0.15-SNAPSHOT] 
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: `8.0.15-SNAPSHOT`
- Configuration: SaaS `zeebe:release-8-1-x` cluster

**Comment by npepinpe** [comment] 2023-08-03 13:02
As we don't have the logs anymore, it hasn't happened again, and I can't reproduce it, I will close this for now.

**Closed by npepinpe** 2023-08-03 13:02 UTC
Labels: kind/bug
