### ISSUE TITLE
Flaky and duplicate test io.camunda.zeebe.it.gateway.GatewayAuthenticationIdentityIT

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#15782] opened 2024-01-04 08:59 UTC
**Summary**

https://github.com/camunda/zeebe/actions/runs/7402146297

Run failed with 
```
io.camunda.zeebe.it.gateway.GatewayAuthenticationIdentityIT
Error: Found duplicate test runs
```

There was also one flaky test in the same run. Not sure, whether this caused the duplicate test detection.

```
Run 1: GatewayAuthenticationIdentityIT.getTopologyRequestSucceedsWithValidAuthToken:203 
Expecting
  <RetriableClientFutureImpl[Failed with the following stack trace:
io.grpc.StatusRuntimeException: CANCELLED
	at io.grpc.Status.asRuntimeException(Status.java:537)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: Failed while requesting access token with status code 401 and message Unauthorized.
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsProvider.fetchCredentials(OAuthCredentialsProvider.java:162)
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsCache.computeIfMissingOrInvalid(OAuthCredentialsCache.java:100)
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsProvider.applyCredentials(OAuthCredentialsProvider.java:84)
	at io.camunda.zeebe.client.impl.ZeebeCallCredentials.lambda$applyRequestMetadata$0(ZeebeCallCredentials.java:48)
	... 3 more
]>
to be completed within 5S.
```

[Uploading test-logs.zip…]()

**Comment by nicpuppa** [comment] 2024-01-04 09:04
This is a duplicate of: https://github.com/camunda/zeebe/issues/15429 

cc @deepthidevaki

**Closed** 2024-01-04 09:05 UTC
Labels: kind/flake
