### ISSUE TITLE
Error: rpc error: code = Unavailable desc = connection closed before server preface received

### ISSUE THREAD

**Issue by sauravhaloi** [camunda/zeebe#8937] opened 2022-03-21 05:44 UTC
Hi,

I am trying to evaluate Camunda Cloud as a workflow orchestrator for which I created a trial account. 

Details on the cluster is shown below:

```
Cluster Id: d2942c14-dbdc-4777-ae44-613ec9b9822d
Created at: Mar 14, 2022, 9:50:03 AM
Region: Europe West (bru-2)
Generation: Zeebe 1.3.5
```

Client Version:
```
$ ./zbctl version
zbctl 1.3.5 (commit: 1231d975)
```

While trying to test the cluster with `zbctl` I am encountering the following error:

`Error: rpc error: code = Unavailable desc = connection closed before server preface received`

This is what I did:

```
$ export ZEEBE_ADDRESS='d2942c14-dbdc-4777-ae44-613ec9b9822d.bru-2.zeebe.camunda.io:443'
$ export ZEEBE_CLIENT_ID='OMITTED_FOR_SECURITY_REASONS'
$ export ZEEBE_CLIENT_SECRET='OMITTED_FOR_SECURITY_REASONS'
$ export ZEEBE_AUTHORIZATION_SERVER_URL='https://login.cloud.camunda.io/oauth/token'
```

I am using 

```
$ ./zbctl status
Error: rpc error: code = Unavailable desc = connection closed before server preface received
```

After bumping up the gRPC logging, this is what I see:

```
$ export GRPC_GO_LOG_SEVERITY_LEVEL=info
$ ./zbctl status
2022/03/21 05:35:45 INFO: [core] original dial target is: "d2942c14-dbdc-4777-ae44-613ec9b9822d.bru-2.zeebe.camunda.io:443"
2022/03/21 05:35:45 INFO: [core] parsed dial target is: {Scheme:d2942c14-dbdc-4777-ae44-613ec9b9822d.bru-2.zeebe.camunda.io Authority: Endpoint:443 URL:{Scheme:d2942c14-dbdc-4777-ae44-613ec9b9822d.bru-2.zeebe.camunda.io Opaque:443 User: Host: Path: RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}}
2022/03/21 05:35:45 INFO: [core] fallback to scheme "passthrough"
2022/03/21 05:35:45 INFO: [core] parsed dial target is: {Scheme:passthrough Authority: Endpoint:d2942c14-dbdc-4777-ae44-613ec9b9822d.bru-2.zeebe.camunda.io:443 URL:{Scheme:passthrough Opaque: User: Host: Path:/d2942c14-dbdc-4777-ae44-613ec9b9822d.bru-2.zeebe.camunda.io:443 RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}}
2022/03/21 05:35:45 INFO: [core] Channel authority set to "d2942c14-dbdc-4777-ae44-613ec9b9822d.bru-2.zeebe.camunda.io:443"
2022/03/21 05:35:45 INFO: [core] ccResolverWrapper: sending update to cc: {[{d2942c14-dbdc-4777-ae44-613ec9b9822d.bru-2.zeebe.camunda.io:443  <nil> <nil> 0 <nil>}] <nil> <nil>}
2022/03/21 05:35:45 INFO: [core] ClientConn switching balancer to "pick_first"
2022/03/21 05:35:45 INFO: [core] Channel switches to new LB policy "pick_first"
2022/03/21 05:35:45 INFO: [core] blockingPicker: the picked transport is not ready, loop back to repick
2022/03/21 05:35:45 INFO: [core] Subchannel Connectivity change to CONNECTING
2022/03/21 05:35:45 INFO: [core] Subchannel picks a new address "d2942c14-dbdc-4777-ae44-613ec9b9822d.bru-2.zeebe.camunda.io:443" to connect
2022/03/21 05:35:45 INFO: [core] Channel Connectivity change to CONNECTING
2022/03/21 05:35:46 INFO: [core] Subchannel Connectivity change to TRANSIENT_FAILURE
2022/03/21 05:35:46 INFO: [core] Channel Connectivity change to TRANSIENT_FAILURE
Error: rpc error: code = Unavailable desc = connection closed before server preface received
```
Connectivity to the Camunda cluster is working fine:

```
$ nc -zv d2942c14-dbdc-4777-ae44-613ec9b9822d.bru-2.zeebe.camunda.io 443
Connection to d2942c14-dbdc-4777-ae44-613ec9b9822d.bru-2.zeebe.camunda.io 443 port [tcp/https] succeeded!
```

If I run zeebe broker locally, I am able to connect using zbctl:

```
$ ./zbctl status --insecure
2022/03/21 05:18:30 INFO: [core] original dial target is: "127.0.0.1:26500"
2022/03/21 05:18:30 INFO: [core] dial target "127.0.0.1:26500" parse failed: parse "127.0.0.1:26500": first path segment in URL cannot contain colon
2022/03/21 05:18:30 INFO: [core] fallback to scheme "passthrough"
2022/03/21 05:18:30 INFO: [core] parsed dial target is: {Scheme:passthrough Authority: Endpoint:127.0.0.1:26500 URL:{Scheme:passthrough Opaque: User: Host: Path:/127.0.0.1:26500 RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}}
2022/03/21 05:18:30 INFO: [core] Channel authority set to "127.0.0.1:26500"
2022/03/21 05:18:30 INFO: [core] ccResolverWrapper: sending update to cc: {[{127.0.0.1:26500  <nil> <nil> 0 <nil>}] <nil> <nil>}
2022/03/21 05:18:30 INFO: [core] ClientConn switching balancer to "pick_first"
2022/03/21 05:18:30 INFO: [core] Channel switches to new LB policy "pick_first"
2022/03/21 05:18:30 INFO: [core] blockingPicker: the picked transport is not ready, loop back to repick
2022/03/21 05:18:30 INFO: [core] Subchannel Connectivity change to CONNECTING
2022/03/21 05:18:30 INFO: [core] Subchannel picks a new address "127.0.0.1:26500" to connect
2022/03/21 05:18:30 INFO: [core] Channel Connectivity change to CONNECTING
2022/03/21 05:18:30 INFO: [core] Subchannel Connectivity change to READY
2022/03/21 05:18:30 INFO: [core] Channel Connectivity change to READY
Cluster size: 1
Partitions count: 1
Replication factor: 1
Gateway version: 1.3.5
Brokers:
  Broker 0 - 0.0.0.0:26501
    Version: 1.3.5
    Partition 1 : Leader, Healthy
2022/03/21 05:18:30 INFO: [core] Channel Connectivity change to SHUTDOWN
2022/03/21 05:18:30 INFO: [core] Subchannel Connectivity change to SHUTDOWN
```

Any help will be highly appreciated as this error is blocking my evaluation of Camunda Cloud. 

Thanks.

**Comment by oleschoenburg** [comment] 2022-03-21 08:40
@sauravhaloi Thanks for the detailed report. My first guess is that this was a temporary connection issue as this is a trial cluster. Could you confirm whether the issue is persisting? And if so, could you also share your timezone, for example by running `date +"%Z %z"`? This would make it easier to correlate your logs with the cluster logs. Thanks!

**Comment by sauravhaloi** [comment] 2022-03-22 03:51
Thanks @oleschoenburg 
The problem still persists. Here is the output of the command you mentioned:
```
$ date +"%Z %z"
UTC +0000
```
Another thing I want to mention is that my office network uses `zscaler` and in a few forums I have read folks mentioning `grpc` have issues with MITM Proxies. Do you think the error I am encountering could be an artifact of that?

**Comment by oleschoenburg** [comment] 2022-03-22 09:08
@sauravhaloi Is there any way you could try to test the connection without going through zscaler? If you can't, I can also offer to assign myself as a support agent to you trial cluster and test the connection myself.

**Comment by sauravhaloi** [comment] 2022-03-23 06:09
Hi @oleschoenburg, I won't be able to test it without zscaler. Work device without admin access :-) It will be great if you can help test the connection. Really appreciate it. Let me know if you need anything from my end (cluster credentials etc).

**Comment by bosacky** [comment] 2022-03-24 14:57
I am experiencing the same issue. 
```bash
$ zbctl version
NPM package version: 1.3.3
zbctl 1.3.3 (commit: 7323c165)
```
```
Cluster Id: 467ab10d-6b37-4f46-872b-a9683ce8d055
Created at: Mar 23, 2022, 4:17:02 PM
Region: Europe West (bru-2)
Generation: Zeebe 1.3.5Latest version
```

```bash
$ zbctl status
Error: rpc error: code = Unavailable desc = connection closed before server preface received

$  zbctl status --insecure
2022/03/24 15:54:22 Warning: The configured security level does not guarantee that the credentials will be confidential. If this unintentional, please enable transport security.

Error: rpc error: code = Unavailable desc = connection closed before server preface received
```

**Comment by oleschoenburg** [comment] 2022-03-24 15:33
@sauravhaloi I've shortly assigned myself as support agent for your trial cluster but unfortunately that doesn't give me permission to create API client credentials and connect to the cluster. Could you either:
* invite me as a member of your organization so that I can create my own API credentials and test the connection
* create new API client credentials and share them privately with me 

You can reach me at ole.schoenburg@camunda.com.

**Comment by oleschoenburg** [comment] 2022-03-24 15:34
@bosacky Are you also behind some sort of proxy or MITM firewall?

**Comment by sauravhaloi** [comment] 2022-03-25 04:02
Hi @oleschoenburg, I have now added you as an Admin in my organization.  Please let me know if you can create your API credentials.

**Comment by oleschoenburg** [comment] 2022-03-25 08:11
@sauravhaloi Thank you! I was able to successfully connect:
```
❯ zbctl status
Cluster size: 3
Partitions count: 2
Replication factor: 3
Gateway version: 1.3.5
Brokers:
  Broker 0 - zeebe-0.zeebe-broker-service.d2942c14-dbdc-4777-ae44-613ec9b9822d-zeebe.svc.cluster.local:26501
    Version: 1.3.5
    Partition 1 : Leader, Healthy
    Partition 2 : Follower, Healthy
  Broker 1 - zeebe-1.zeebe-broker-service.d2942c14-dbdc-4777-ae44-613ec9b9822d-zeebe.svc.cluster.local:26501
    Version: 1.3.5
    Partition 1 : Follower, Healthy
    Partition 2 : Leader, Healthy
  Broker 2 - zeebe-2.zeebe-broker-service.d2942c14-dbdc-4777-ae44-613ec9b9822d-zeebe.svc.cluster.local:26501
    Version: 1.3.5
    Partition 1 : Follower, Healthy
    Partition 2 : Follower, Healthy
```

For me this confirms that this is an issue due to `zscaler` messing with gRPC connections in your network. Unfortunately, I don't think there is anything we can do on our side.

I'll close this for now but we can always reopen this, for example if @bosacky can reproduce it without a proxy or MITM firewall in the network.

**Closed by oleschoenburg** 2022-03-25 08:11 UTC
Labels: Type: Bug, Status: Needs Information

**Comment by oleschoenburg** [comment] 2022-03-25 08:13
@sauravhaloi Thanks again for letting me test on your cluster! :bow:  
Feel free to remove me from your organization again. I've deleted my client credentials already.

**Comment by Zelldon** [comment] 2022-03-25 09:50
@oleschoenburg was it intended to close this issue?

**Comment by sauravhaloi** [comment] 2022-03-26 13:14
Thank you @oleschoenburg. Really appreciate the help.
