### ISSUE TITLE
Clients can set an optional backoff time to the failed tasks.

### ISSUE THREAD

**Issue by aivinog1** [camunda/zeebe#5629] opened 2020-10-19 13:51 UTC
**Is your feature request related to a problem? Please describe.**
This is the client's part of #164. The idea is that a client (Java/Go/Zbctl) can specify an optional backoff time when sending a JobFailed command. If a backoff time is set then the job will be available after the backoff time. Otherwise, the job will be available immediately (current behavior).

**Describe the solution you'd like**
Clients can set an optional backoff time.

**Describe alternatives you've considered**
We could split this task into three for different clients.

**Comment by tfnick** [comment] 2021-04-30 08:06
this feature is useful

**Comment by aivinog1** [comment] 2021-12-19 12:36
Hey @saig0, @npepinpe! I have a question about implementation. So, when I try to use:
```java
CLIENT_RULE
        .getClient()
        .newFailCommand(jobKey)
        .retries(1)
        .retryBackoff(backoffTimeout)
        .requestTimeout(Duration.ofDays(1))
        .send()
        .join();
```
in [this test](https://github.com/camunda-cloud/zeebe/blob/develop/qa/integration-tests/src/test/java/io/camunda/zeebe/it/client/command/FailJobTest.java), the synchronous call became locked for the whole `backoffTimeout` duration. I think that this happens because we are expecting some response (`JobRecord` with a fail) and we will wait for it. I don't this that this is the right behavior but maybe I'm wrong 🤔

**Comment by npepinpe** [comment] 2022-02-18 19:04
:eyes: I wasn't really involved so far, so I'd have to look into what this means on Monday.

**Comment by B-hamza** [comment] 2022-04-25 15:32
Oh, that will be cool to set a backoff from the client on failing jobs, is there any update on this issue ? Many thanks.

**Comment by saig0** [comment] 2022-05-06 03:57
@aivinog1 do you want to continue working on the topic? 
I would like to see the feature in version `8.1` (Q3 2022). If you don't want or can't work on it then I would assign it to someone else.

**Comment by saig0** [comment] 2022-05-09 04:49
@aivinog1 I'm sorry for overseeing your question :see_no_evil:  

Do you have your changes on a branch? Please share a link. I can't reproduce the behavior otherwise. 

In general, the request waits until the response is received (when using `.send().join()`). But the processor should also send the response if a backoff is set.

**Comment by aivinog1** [comment] 2022-05-14 06:45
@saig0 Here is the test that is failing: https://github.com/aivinog1/zeebe/commit/78f67ef0d2fb1070e2a7b37d7ab47a46a7f782d6#diff-ef4fccf13ed0e32bc54cf53556fcbeb151f2c6636988f33bc7b254e0c81a4aceR78

**Comment by aivinog1** [comment] 2022-05-14 10:16
@saig0 I think that I found the problem. So I'll need to do `flush` on the `responseWriter` somehow. I've tried to add `responseWriter.flush();` like [this](https://github.com/aivinog1/zeebe/commit/0e0014048c3df31b3c1d683774411d01bbbefb71#diff-3073afbff68c0192cb96d17d45485f6e95c81a78c2b951548e8bd956f830d817R82), and it works but breaks other cases 🤔 :
```
17:05:17.324 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] ERROR io.camunda.zeebe.processor - Expected to execute side effects for record 'LoggedEvent [type=0, version=0, streamId=1, position=5, key=-1, timestamp=1652522717321, sourceEventPosition=-1] RecordMetadata{recordType=COMMAND, intentValue=255, intent=CREATE, requestStreamId=1, requestId=1, protocolVersion=3, valueType=PROCESS_INSTANCE_CREATION, rejectionType=NULL_VAL, rejectionReason=, brokerVersion=8.1.0}' successfully, but exception was thrown.
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at io.camunda.zeebe.broker.transport.commandapi.CommandResponseWriterImpl.tryWriteResponse(CommandResponseWriterImpl.java:99) ~[classes/:?]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.TypedResponseWriterImpl.flush(TypedResponseWriterImpl.java:114) ~[classes/:?]
	at io.camunda.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[classes/:?]
	at io.camunda.zeebe.util.retry.AbortableRetryStrategy.run(AbortableRetryStrategy.java:44) ~[classes/:?]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) ~[classes/:?]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[classes/:?]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[classes/:?]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:103) ~[classes/:?]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:83) ~[classes/:?]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:195) ~[classes/:?]
```
Also, I think that it works without `retryBackoff` because retries do so fast so in the end we quickly activate jobs and `flush` them.

**Comment by saig0** [comment] 2022-05-17 05:21
@aivinog1 I see. Thank you for sharing :+1: 

I was able to fix the behavior. See my commit here: https://github.com/camunda/zeebe/commit/a7195f7750670e41ac0e42da8d170ffedfed9757

**Closed** 2022-06-02 07:31 UTC
Labels: kind/feature, scope/clients-java, scope/clients-go, team/process-automation
