### ISSUE TITLE
Member address resolution is blocking the caller thread

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#13722] opened 2023-07-31 13:43 UTC
Resolving a member address to a proper `InetAddress` is blocking. With default configuration and an unresponsive DNS server, this can take 10 seconds.

This is a problem for our SWIM implementation in particular because it forces DNS resolution on every probe and runs single threaded.

Related to https://jira.camunda.com/browse/SUPPORT-17400

**Comment by megglos** [comment] 2023-08-03 12:07
ZDP-Triage:
- came up in support, user was observing occasional DEADLINE_EXCEEDED errors
- at the same time dns resolution issues could be identified as being the cause of these timeouts
- temporary mitigation was to reduce dns timeouts to => to reduce the time of blocking => timeouts will still occur but for a shorter period of time
- impacts availability of the system
- might be a low hanging fruit, could turn out more complicated though
- was affecting self-managed customers in the past already too, the timeouts lead to leader reelections

**Comment by npepinpe** [comment] 2023-08-07 08:34
What's the idea here? A single DNS resolution thread used by the messaging service, periodically resolving hostnames to avoid having to do it inline?

Although, 10 seconds to resolve DNS sounds like it was a network issue and not a Java issue :thinking:

**Comment by megglos** [comment] 2023-08-14 11:42
ZDP-Planning:
- moving to ready as it's a potential easy fix
- @oleschoenburg & @rodrigo-lourenco-lopes pair to asses it

**Comment by npepinpe** [comment] 2023-08-20 18:48
Have we tried using Netty's built-in `NameResolver` implementations? They have a `DnsNameResolver` implementation which AFAIK will do the caching and asynchronous refresh/lookup for us. So we could simply bake this into our low level Netty code, and just ignore the whole resolving of addresses everywhere else.

**Comment by oleschoenburg** [comment] 2023-08-21 07:23
Yes, that's what we are trying now, just letting Netty do the name resolution: https://github.com/camunda/zeebe/pull/13950

**Comment by npepinpe** [comment] 2023-08-21 08:09
I don't see where the NameResolver is being configured/set up, but I trust you will explain how it works when we're done :smile:

**Comment by oleschoenburg** [comment] 2023-08-21 08:19
Oh, there is one by default :D

**Comment by npepinpe** [comment] 2023-08-21 08:21
Where can you find how it's configured? We used to enforce resolving always to make sure we wouldn't run into issues where a DNS record was cached and we ended up sending messages to the wrong node. Though I can't remember the actual use case where we had problems with this, it's been way too long.

**Closed** 2023-11-03 11:37 UTC
Labels: kind/bug, severity/mid, support, component/gossip, component/transport, area/resilience
