### ISSUE TITLE
Restrict BPMN deployment/instance creation to specific users

### ISSUE THREAD

**Issue by strawhat5** [camunda/zeebe#3942] opened 2020-02-27 13:04 UTC
**Is your feature request related to a problem? Please describe.**
Currently Zeebe supports AuthN and AuthZ for gRPC communication between client and broker. But once a client is authorized, it can execute all the commands supported in proto. We have a use-case where we want to control specific commands like `newDeployCommand()` and `newCreateInstanceCommand()` to specific users and not to all the registered clients. This is required because we want the workflow deployment to happen in a controlled fashion. Since there is no Auth parameter at command level currently, any of the registered clients can go ahead and deploy their workflows, and this can cause serious issues if one of the client deploys a workflow with the same name as being used by some other client, in the same broker.

**Describe the solution you'd like**
Zeebe should provide command level access control, which should be configurable. So, if we want to restrict some of the commands like `newDeployCommand()` to certain user/user groups, we can control it through some configs like `broker.yaml`. And all of the other registered clients, without those privileged user access, will be able to use other commands like `newCompleteCommand()` but not the restricted command(s).

**Describe alternatives you've considered**
The other solution that we have thought of is similar to a side-car pattern, where we can have a reverse-proxy deployed along with all Zeebe nodes and that will validate whether the requests are coming through higher privileged users or not. But that will add extra-latency to all the requests coming to Zeebe. It would be better if we can have this as an out-of-box feature of Zeebe.

**Comment by Firestorm87** [comment] 2020-04-29 10:45
You are writing "Zeebe supports AuthN and AuthZ at client level".
Did this fit for Camunda-Cloud only, or does the standalone Zeebe also supports Client-Auth with external OAuth Providers? Can't find any documentation for that.

**Comment by strawhat5** [comment] 2020-05-02 08:15
Hi @Firestorm87 , you can find the documentation here:
https://docs.zeebe.io/operations/security.html

It has the details regarding OAuth integration.

**Comment by Firestorm87** [comment] 2020-05-02 08:44
But that Link says that Zeebe onl Supports TLS for secure the communication. But it does not Support Authorization except i would use an authenticating ReverseProxy.

So i cant find any hints that "Zeebe supports AuthN and AuthZ at client level".

**Comment by strawhat5** [comment] 2020-05-02 11:09
Yes that's right. You will have to implement your own reverse proxy as the [doc](https://docs.zeebe.io/operations/authorization.html) says:
> Note that the gateway doesn't provide any way of validating these headers, so users must implement a reverse proxy with a gRPC interceptor to validate them.

What I meant by "Zeebe supports AuthN and AuthZ at client level" is that _it supports gRPC communication to be authenticated/authorised while registering a client to Zeebe broker_. I have updated the issue to make it a bit more clear.

If you have any specific questions regarding Zeebe Authentication/Authorization, it would be better to create a separate issue for that, or you can ask the official Zeebe team on their [slack channel](https://zeebe-slack-invite.herokuapp.com/).

**Comment by npepinpe** [comment] 2020-05-18 15:41
Hi @strawhat5, anything related or resembling multi-tenancy has so far been a non-goal in Zeebe, and authentication was meant from the get go to be implemented in front of Zeebe (i.e. only supported in the client). Still, I will bring it up with our product team, let's see.

**Comment by strawhat5** [comment] 2020-05-18 18:13
I see. Got it.

I think multi-tenancy would provide us flexibility to control certain aspects in the lifecycle of a workflow. Hoping for a fruitful outcome of the discussion. :)

**Comment by ysaakpr** [comment] 2020-06-17 09:21
https://github.com/zeebe-io/zeebe/issues/3439

**Comment by Zelldon** [comment] 2022-12-23 08:36
i will close this as duplicate of https://github.com/camunda/zeebe/issues/3439

**Closed by Zelldon** 2022-12-23 08:36 UTC
Labels: kind/feature, scope/broker, blocker/stakeholder, component/engine
