### ISSUE TITLE
Recently, we have been encountering frequent occurrences of UNHEALTHY partitions in our Zeebe setup

### ISSUE THREAD

**Issue by yyc6698** [camunda/zeebe#15630] opened 2023-12-15 02:15 UTC
**Describe the bug**

Recently, we have been encountering frequent occurrences of UNHEALTHY partitions in our Zeebe setup. However, we are unsure about how to specifically investigate and pinpoint the root cause of these issues. Do you have any recommendations or best practices that could guide us in troubleshooting this problem?

**To Reproduce**

**Log/Stacktrace**

2023-12-14 16:54:37.989 [Broker-2-HealthCheckService] [Broker-2-zb-actors-0] DEBUG
      io.camunda.zeebe.broker.system - Detected 'UNHEALTHY' components. The current health status of components: [Partition-2{status=HEALTHY}, Partition-1{status=UNHEALTHY, issue=HealthIssue[message=null, throwable=null, cause=Broker-2-StreamProcessor-1{status=UNHEALTHY, issue=HealthIssue[message=actor appears blocked, throwable=null, cause=null]}]}, Partition-3{status=HEALTHY}]

actor appears blocked

**Environment:**
- OS: Linux
- Zeebe Version: 8.1.9
- Configuration:

**Comment by Zelldon** [comment] 2023-12-15 04:51
Hey @yyc6698 do you have any metrics to share? Like a screenshot of our grafana dashboard we provide?

It might be related to too many jobs, timers or messages to timeout. Earlier zeebe versions had issues with it, which has been fixed recently.


Do you thought about migrating to a newer version? Please make sure to not jump minor versions.

**Comment by yyc6698** [comment] 2023-12-15 08:06
These are my Grafana monitoring details. What's strange is that we only have 2 instances running, yet there are many export events occurring, and we keep receiving alerts about partitions being unhealthy.


![2db4969437d9855ab74f40106c570b57](https://github.com/camunda/zeebe/assets/114198805/e823c171-13df-4608-a2a8-114e44bfb805)
![7c791e396640d1e7bcceeb99b3f4df23](https://github.com/camunda/zeebe/assets/114198805/f7469fb7-fc69-4ca5-9afb-70ae28096274)
![7ed61ff12973676c0d62782d69106846](https://github.com/camunda/zeebe/assets/114198805/2a7d4a35-098e-4764-afc2-30d002acedc9)
![7fe2b999c0f570f7fb67ed8ffb7651fb](https://github.com/camunda/zeebe/assets/114198805/27c7e4d5-4432-4c3d-bd34-b20a2bdd6c5f)
![30cb8548d5fca3fe726e489dcfae8a7c](https://github.com/camunda/zeebe/assets/114198805/88285229-cf86-460f-abaa-a153144e9dab)
![44de83e127d034d8a415a5a8a37b107c](https://github.com/camunda/zeebe/assets/114198805/408ad38c-2cc2-4d51-a38a-25cd7a56f60a)
![5192130C-D7FD-431c-9C2B-DE094C0EEE5E](https://github.com/camunda/zeebe/assets/114198805/96178e80-6e34-4ac2-ae08-3da39d8d1794)
![d6c7182a5c52cc4c9d22f3883cd971b6](https://github.com/camunda/zeebe/assets/114198805/a76ed57b-38f8-40e3-bc8e-36ee367521c2)
![d7ab12000781c6a6ac04178baa279304](https://github.com/camunda/zeebe/assets/114198805/dfa1e865-7f5d-4b87-a3fc-6c70ed246cbd)
![e2b743265580c06e16d21bd3fe41552b](https://github.com/camunda/zeebe/assets/114198805/c8bcd437-e26e-4e06-8aea-a97dc5a9eb8d)
![fd4fe4b2489910445add093d6d1e898e](https://github.com/camunda/zeebe/assets/114198805/2b85904a-dacf-402e-84ba-f401720f9e2e)

**Comment by yyc6698** [comment] 2023-12-15 08:07
These are my Grafana monitoring details. What's strange is that we only have 2 instances running, yet there are many export events occurring, and we keep receiving alerts about partitions being unhealthy.

**Comment by npepinpe** [comment] 2023-12-29 13:15
We need more info before we can assign a severity/likelihood for this (i.e. triage it). Since @Zelldon already started, I've assigned the issue to you to continue getting more info. You can putting back into the inbox for planning when we have enough info to assign a severity/likelihood.

**Comment by Zelldon** [comment] 2024-01-11 13:37
Hey @yyc6698 

thanks for the details and sorry for the delay I was ooo.

What I can see is that you sending quite a lot of job activation requests, do you know the reason for this? How many workers do you have? How they are configured? Can you describe a bit more your set up?


> These are my Grafana monitoring details. What's strange is that we only have 2 instances running, yet there are many export events occurring, and we keep receiving alerts about partitions being unhealthy.

Do you mean two process instances?


What do they look like? Do you use call-activities and mult-instances? I would be happy about more details to support you here.

**Comment by yitizi** [comment] 2024-01-16 02:46
@Zelldon hi，im the colleage of @yyc6698 .Allow me to explain. You mentioned a significant number of job activation requests. Initially, we disabled the long poll feature in the gateway because it was causing a delay in notifying the worker about job activations. When we enabled long polling, the activation frequency became very low. Regarding the number of workers, we register a worker for each job type, meaning that for every user task node, we have a corresponding worker. Is there any issue with this setup?

**Comment by Zelldon** [comment] 2024-01-16 12:29
> @Zelldon hi，im the colleage of @yyc6698 .Allow me to explain. You mentioned a significant number of job activation requests. Initially, we disabled the long poll feature in the gateway because it was causing a delay in notifying the worker about job activations. When we enabled long polling, the activation frequency became very low. Regarding the number of workers, we register a worker for each job type, meaning that for every user task node, we have a corresponding worker. Is there any issue with this setup?

Thanks for the details. What does the configuration of your workers look like? What is the poll interval? You need to be aware without long-polling you will put a lot of pressure on the system since each worker will send its own job activation request, and retry if no job has been found etc. This is especially problematic if you have a small polling intervall. Long polling allows us to keep a connection open, and get notified when a new job has been created, this will be sent to the corresponding awaiting job worker, and from time to time job activation commands have been sent to renew this.

With 8.4 we released a new feature called [job push/streams](https://docs.camunda.io/docs/components/concepts/job-workers/#job-streaming) to circumvent all these problems of long job activation. See for the implementation details https://github.com/camunda/zeebe/issues/11231 I think it's worth trying for you.

**Comment by yitizi** [comment] 2024-01-17 06:59
Thanks for your advice. The default poll interval is 500 milliseconds. The reason we haven't enabled long-polling is because it appears to introduce significant delays between the gateway and broker. This delay is causing a considerable lag in job activation. While upgrading is a potential solution, the current version we are using is 8.1.9, which would require a substantial amount of work.
![image](https://github.com/camunda/zeebe/assets/33743770/b2051459-eaa0-4cf4-a812-835dd1c77861)

**Comment by Zelldon** [comment] 2024-01-17 08:12
I see, still, I recommend this as a to-do for sooner rather than later. Newer versions not only benefit of these new features, but also several fixes for stability and performance. Already in 8.2 you will see a performance boost. In another note 8.1, will soon be no longer supported (in April) which means it will not get any patch releases.

**Comment by oleschoenburg** [comment] 2024-01-18 08:33
> The reason we haven't enabled long-polling is because it appears to introduce significant delays between the gateway and broker

If you are basing this on the metrics from your screenshots: Those are misleading! The "latency" is indeed much higher but only because of long-polling. The actual latency until a job is activated should be much lower.

**Comment by Zelldon** [comment] 2024-01-18 13:33
Lets take a step back and discuss your origin issue. You wrote:

> Recently, we have been encountering frequent occurrences of UNHEALTHY partitions in our Zeebe setup. However, we are unsure about how to specifically investigate and pinpoint the root cause of these issues. Do you have any recommendations or best practices that could guide us in troubleshooting this problem?

With the following stacktrace: 

> 2023-12-14 16:54:37.989 [Broker-2-HealthCheckService] [Broker-2-zb-actors-0] DEBUG
io.camunda.zeebe.broker.system - Detected 'UNHEALTHY' components. The current health status of components: [Partition-2{status=HEALTHY}, Partition-1{status=UNHEALTHY, issue=HealthIssue[message=null, throwable=null, cause=Broker-2-StreamProcessor-1{status=UNHEALTHY, issue=HealthIssue[message=actor appears blocked, throwable=null, cause=null]}]}, Partition-3{status=HEALTHY}]

Especially the following is important:

> actor appears blocked

You need to know that we have a stream processor which processes records (commands) one by one (in later versions we introduced batching to improve this). Everytime the processing of such command is done it updates are timestamp to indicate the progress. If the progress was not updated, meaning no heartbeat given the health status will be set to unhealthy. We expect in such case for example a stuck processor or endless loop or something, which should be further investigated.

The question know of course is how can this happen. Either you have a really big state (lot of process instance) which makes processing of instances really really slow, or there is something else going on (like for example GC) or another bug, which is not clear yet.

Could you please check your disk size, your snapshot size (so we get a better understanding of your state size). Furthermore, I would like to see your GC activity and resource consumption. 

Interesting as well would be configuration of your brokers and how you set up your cluster.

**Comment by yitizi** [comment] 2024-01-30 01:07
If I activate long-polling, it causes a delay of about 4 to 5 seconds in processing a task node. In a "create order" BPMN workflow, where we wait for the result, this delay leads to HTTP timeouts and actor blocked errors. I believe this might be due to the misconfiguration of our Zeebe Broker. Initially, we set up 3 partitions in a broker, limiting it to 3 CPU cores, configuring 6 CPU threads, and 2 IO threads. We have now adjusted it to 3 CPU threads, 1 IO thread, and a limit of 5 CPU cores. This adjustment has improved the situation.

We have installed Zeebe Broker in a Kubernetes cluster with shared NFS storage, totaling 1.8TB, with about 30% available space. The snapshot size is approximately 30-50MB. Below are details about GC, heap memory pool, and CPU usage.
![image](https://github.com/camunda/zeebe/assets/33743770/4e679172-e7d3-4478-acbd-a0de734cd854)
![image](https://github.com/camunda/zeebe/assets/33743770/fc117369-5684-456a-b523-9c8d45e2754c)
![image](https://github.com/camunda/zeebe/assets/33743770/38d15715-efd2-4ac2-8892-98023d0f68db)
![image](https://github.com/camunda/zeebe/assets/33743770/368c6aa5-fa63-466f-abf0-a2742251257f)
In our development environment, there aren't many active BPMN processes, but the processing load per partition is high. We believe this is due to the low job poll interval, and we have deactivated long polling. However, certain jobs require a fast reaction for activation. Therefore, we are currently working on creating two different gateways to cater to different needs.Before we proceed with the Zeebe upgrade, we have already upgraded to version 8.1.21 now.

**Comment by Zelldon** [comment] 2024-02-02 07:57
The actual problem of your performance issues is the underlying disk type you use, to be specific we don't support NFS as a file system. There are several issues and risks related to this, it is not performant (it has likely high latency on writing and committing) and it is not safe to use, since the flush doesn't give the same guarantees as on normal disks like SSDs.  


We have an open issue to document this more https://github.com/camunda/camunda-docs/issues/2987

Action plan for you:

 1. Change your underlying storage, don't use NFS. Use a performant disk like an SSD.
 2. Upgrade to our recent release like 8.4.1
 3. Use [job streaming.](https://docs.camunda.io/docs/apis-tools/go-client/job-worker/#job-streaming) See this blog post from @npepinpe [ about more details about reducing job activation delay](https://zeebe-io.github.io/zeebe-chaos/2024/01/19/Job-Activation-Latency))


Since this issue is not a bug report, nor a feature request I will close this. If you have further issues please contact our support team (if you are a customer) otherwise I would recommend to ask in the forum https://forum.camunda.io/. Thanks.

**Closed by Zelldon** 2024-02-02 07:57 UTC
Labels: kind/question, area/observability
