### ISSUE TITLE
Process with message start event and extension element can not be deployed

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda/zeebe#11168] opened 2022-12-02 18:36 UTC
**Describe the bug**

If a process model contains a message start event and the message contains an extensionElement, it can't be deployed.

**To Reproduce**

Open this BPMN Model in the modeler and deploy to your local cluster started with docker-compose-core.yml: 
[converted-c8-start-message-example - Kopie.bpmn.txt](https://github.com/camunda/zeebe/files/10143479/converted-c8-start-message-example.-.Kopie.bpmn.txt)

**Expected behavior**

The process gets deployed as it is a valid BPMN file with the namespace for the extension included. 

**Log/Stacktrace**

Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'converted-c8-start-message-example.bpmn': Collection expected to have <1> entry but has <0> [ deploy-error ]

<details><summary>Full Stacktrace</summary>
 <p>

```
2022-12-02 19:22:57 2022-12-02 18:22:57.216 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] ERROR
2022-12-02 19:22:57       io.camunda.zeebe.broker.process - Unexpected error while processing resource 'converted-c8-start-message-example.bpmn'
2022-12-02 19:22:57 io.camunda.zeebe.model.bpmn.BpmnModelException: Collection expected to have <1> entry but has <0>
2022-12-02 19:22:57     at io.camunda.zeebe.model.bpmn.impl.QueryImpl.singleResult(QueryImpl.java:79) ~[zeebe-bpmn-model-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.engine.processing.deployment.model.transformer.MessageTransformer.transform(MessageTransformer.java:39) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.engine.processing.deployment.model.transformer.MessageTransformer.transform(MessageTransformer.java:21) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.engine.processing.deployment.model.transformation.TransformationVisitor.visit(TransformationVisitor.java:42) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.model.bpmn.traversal.TypeHierarchyVisitor.visit(TypeHierarchyVisitor.java:39) ~[zeebe-bpmn-model-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:66) ~[zeebe-bpmn-model-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.engine.processing.deployment.model.transformation.BpmnTransformer.transformDefinitions(BpmnTransformer.java:111) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.transformResource(BpmnResourceTransformer.java:69) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:120) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:97) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:98) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:261) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:257) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:206) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:182) ~[zeebe-workflow-engine-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.4.jar:8.1.4]
2022-12-02 19:22:57     at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.4.jar:8.1.4]
```

</p>
</details>

**Environment:**
- OS: Windows 10
- Zeebe Version: 8.1.4
- Configuration: https://github.com/camunda/camunda-platform/blob/main/docker-compose-core.yaml

**Additional Hints**
If you delete line 16 from the XML (Content of the extensionElement), the deployment still fails. 

If you remove the complete extensionElement from line 15 to 17, the deployment is successful.

**Comment by npepinpe** [comment] 2022-12-02 19:19
I think this is a duplicate of https://github.com/camunda/zeebe/issues/10962, which was just fixed, so it should be in the next patch releases.

**Comment by skayliu** [comment] 2022-12-03 09:42
> I think this is a duplicate of https://github.com/camunda/zeebe/issues/10962, which was just fixed, so it should be in the next patch releases.

Hi, @npepinpe, @ingorichtsmeier, I've tested the bpmn file manually, It's been fixed and wait for the next patch releases.

**Comment by Zelldon** [comment] 2022-12-03 12:19
Thanks @skayliu I will close this then

**Closed** 2022-12-03 12:19 UTC
Labels: kind/bug
