### ISSUE TITLE
TimerCatchEventTest.shouldTriggerTimer is flaky (again)

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#10978] opened 2022-11-11 06:23 UTC
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? once so far
- Does it block your work? not yet
- Do we suspect that it is a real failure? no

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Warning:  Flakes: 
Warning:  io.camunda.zeebe.engine.processing.timer.TimerCatchEventTest.shouldTriggerTimer
Error:    Run 1: TimerCatchEventTest.shouldTriggerTimer:216 
Expecting actual:
  0.152S
to be between:
  [0.1S, 0.15S]
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be omitted

Timing is different sometimes.

**Logs**

[io.camunda.zeebe.engine.processing.timer.TimerCatchEventTest-1-output.txt](https://github.com/camunda/zeebe/files/9987017/io.camunda.zeebe.engine.processing.timer.TimerCatchEventTest-1-output.txt)
[io.camunda.zeebe.engine.processing.timer.TimerCatchEventTest-2-output.txt](https://github.com/camunda/zeebe/files/9987018/io.camunda.zeebe.engine.processing.timer.TimerCatchEventTest-2-output.txt)

**Comment by oleschoenburg** [comment] 2022-11-11 07:33
Dupe of https://github.com/camunda/zeebe/issues/10272

**Comment by Zelldon** [comment] 2022-11-11 07:59
Hm it is a different test, the cause might be same true

**Comment by oleschoenburg** [comment] 2022-11-11 08:29
Oops, yeah my bad :+1:

**Closed** 2022-11-17 14:08 UTC
Labels: kind/flake
