### ISSUE TITLE
Lower log level when grpc request fails due to DNS not resolved

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#7267] opened 2021-06-14 08:14 UTC
**Description**

Found the following log in the gateway.

```
Expected to handle gRPC request, but an unexpected error occurred
 java.lang.IllegalStateException: Failed to bootstrap client (address medic-cw-23-f01b5bc83-benchmark-zeebe-2.medic-cw-23-f01b5bc83-benchmark-zeebe.medic-cw-23-f01b5bc83-benchmark.svc.cluster.local:26501 cannot be resolved)

        at io.atomix.cluster.messaging.impl.NettyMessagingService.bootstrapClient (NettyMessagingService.java:550)
        at io.atomix.cluster.messaging.impl.NettyMessagingService.openChannel (NettyMessagingService.java:534)
        at io.atomix.cluster.messaging.impl.ChannelPool.getChannel (ChannelPool.java:96)
        at io.atomix.cluster.messaging.impl.ChannelPool.lambda$getChannel$4 (ChannelPool.java:129)

    at io.atomix.utils.concurrent.OrderedFuture.whenComplete (OrderedFuture.java:294)
    at io.atomix.cluster.messaging.impl.ChannelPool.getChannel (ChannelPool.java:112)
    at io.atomix.cluster.messaging.impl.NettyMessagingService.executeOnPooledConnection (NettyMessagingService.java:414)
    at io.atomix.cluster.messaging.impl.NettyMessagingService.executeOnPooledConnection (NettyMessagingService.java:378)
    at io.atomix.cluster.messaging.impl.NettyMessagingService.sendAndReceive (NettyMessagingService.java:195)
    at io.atomix.cluster.messaging.impl.NettyMessagingService.sendAndReceive (NettyMessagingService.java:174)
    at io.atomix.cluster.messaging.MessagingService.sendAndReceive (MessagingService.java:135)
    at io.camunda.zeebe.transport.impl.AtomixClientTransportAdapter.tryToSend (AtomixClientTransportAdapter.java:148)
    at io.camunda.zeebe.transport.impl.AtomixClientTransportAdapter.lambda$sendRequestInternal$2 (AtomixClientTransportAdapter.java:86)
    at io.camunda.zeebe.util.sched.ActorControl.lambda$call$0 (ActorControl.java:136)
    at io.camunda.zeebe.util.sched.ActorJob.invoke (ActorJob.java:62)
    at io.camunda.zeebe.util.sched.ActorJob.execute (ActorJob.java:39)
    at io.camunda.zeebe.util.sched.ActorTask.execute (ActorTask.java:122)
    at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask (ActorThread.java:94)
    at io.camunda.zeebe.util.sched.ActorThread.doWork (ActorThread.java:78)
    at io.camunda.zeebe.util.sched.ActorThread.run (ActorThread.java:191)

```

This is an expected error when the broker is restarted. The broker might have been the leader for some partitions. There is a small delay between when the broker is stopped and the gateway is aware that broker is unavailable. That's why the gateway attempt to send a request to unavailable broker. 

Goals:
1. To reduce the noise it would be good to lower the log level when this happens. 
2. In addition, it might be possible to retry the request with a different partition or wait until a new leader is available.

**Comment by Zelldon** [comment] 2022-12-29 06:36
Duplicate of https://github.com/camunda/zeebe/issues/7019

**Closed by Zelldon** 2022-12-29 06:36 UTC
Labels: kind/toil, scope/broker, area/observability
