### ISSUE TITLE
Spotless apparently not configured properly

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#9117] opened 2022-04-13 05:08 UTC
**Description**

Cannot really pinpoint the exact conditions, but lately I often have spotless errors in Jenkins.

* I save my files with Idea and would assume that it applies the code style automatically.
* running `mvn clean install -DskipTests -DskipChecks` does not change any files
* running `mvn spotless:apply` results in this error: [ERROR] No plugin found for prefix 'spotless' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/peter/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]

Running `com.diffplug.spotless:spotless-maven-plugin:apply` does work. But it is a bit hard to remember

**Comment by npepinpe** [comment] 2022-04-13 05:47
@korthout could you have a look? Did we change anything recently?

**Comment by npepinpe** [comment] 2022-04-13 12:54
I just realized Nico is absent, probably for a while. As there's a workaround, I think we can wait until he's back, otherwise let me know and we can reassign.

**Comment by korthout** [comment] 2022-04-20 16:23
Considering this part:

> - running mvn spotless:apply results in this error: [ERROR] No plugin found for prefix 'spotless' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/peter/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
>
> Running com.diffplug.spotless:spotless-maven-plugin:apply does work. But it is a bit hard to remember

This is something I had been running into when setting up spotless originally, and at the time I didn't understand why `mvn spotless:apply` didn't just work. Especially, because the root project had the spotless plugin in its build plugins. 

I just played around with it a bit, and it seems the problem is related to the maven reactor. `zeebe-bom` is the first project that is executed by the maven reactor, but it does not know the spotless plugin. TBH, it does 'know' about it because the parent of the `zeebe-bom` has defined it in the pluginManagement tag, but that does not appear to be used for the plugin prefixes. To use plugins by their prefix, they need to be registered in the build plugins tag. I've opened a new PR (#9184) to fix that.

Considering this part:

>- I save my files with Idea and would assume that it applies the code style automatically.
>- running mvn clean install -DskipTests -DskipChecks does not change any files

@pihme I'd be interested to see a situation where this diff occurs between running it locally and on CI. It's hard to say what's causing this without an example. Let me know if you encounter it again, or if you can point me to a CI run where this happened. We can also pair on this if you run into it again locally.

**Closed** 2022-04-21 08:25 UTC
Labels: kind/toil, area/maintainability
