### ISSUE TITLE
NPE in QueryApiRequestHandler

### ISSUE THREAD

**Issue by pihme** [camunda/zeebe#8606] opened 2022-01-17 16:06 UTC
**Describe the bug**
Observed in benchmark: https://console.cloud.google.com/errors/CLnGzIys76Ga6wE?service=zeebe&version=medic-cw-02-e0adda46b6-benchmark&time=P30D&project=zeebe-io

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: value cannot be null
	at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:315) ~[agrona-1.14.0.jar:1.14.0]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:301) ~[agrona-1.14.0.jar:1.14.0]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:34) ~[agrona-1.14.0.jar:1.14.0]
	at io.camunda.zeebe.broker.transport.queryapi.QueryApiRequestHandler.lambda$addPartition$0(QueryApiRequestHandler.java:60) ~[zeebe-broker-1.4.0-SNAPSHOT.jar:1.4.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) ~[zeebe-util-1.4.0-SNAPSHOT.jar:1.4.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) [zeebe-util-1.4.0-SNAPSHOT.jar:1.4.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.4.0-SNAPSHOT.jar:1.4.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) [zeebe-util-1.4.0-SNAPSHOT.jar:1.4.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) [zeebe-util-1.4.0-SNAPSHOT.jar:1.4.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) [zeebe-util-1.4.0-SNAPSHOT.jar:1.4.0-SNAPSHOT]
```
</p>
</details>

**Comment by pihme** [comment] 2022-01-17 16:18
Log excerpt (heavily filtered):
```
I 2022-01-17T10:21:20.910863517Z Started 
I 2022-01-17T10:21:20.911189644Z Registering Partition Manager 
I 2022-01-17T10:21:20.913372632Z Starting partitions 
I 2022-01-17T10:21:21.070152657Z Startup LogDeletionService 
I 2022-01-17T10:21:21.070221339Z Startup LogDeletionService 
I 2022-01-17T10:21:21.071917215Z Startup RocksDB metric timer 
I 2022-01-17T10:21:21.071969092Z Startup RocksDB metric timer 
W 2022-01-17T10:21:21.078108441Z Partition-1 failed, marking it as unhealthy: Broker-1{status=UNHEALTHY, issue=Partition-2{status=UNHEALTHY, issue='Components are not yet initialized'}} 
I 2022-01-17T10:21:21.078271442Z Transition to LEADER on term 18 requested. 
I 2022-01-17T10:21:21.078280097Z Transition to LEADER on term 18 requested. 
W 2022-01-17T10:21:21.079564099Z Partition-2 failed, marking it as unhealthy: Broker-1{status=UNHEALTHY, issue=Partition-2{status=UNHEALTHY, issue='Components are not yet initialized'}} 
I 2022-01-17T10:21:21.084085899Z Transition to LEADER on term 18 starting 
I 2022-01-17T10:21:21.084120381Z Transition to LEADER on term 18 starting 
I 2022-01-17T10:21:21.085108377Z Transition to LEADER on term 18 - transitioning LogStorage 
I 2022-01-17T10:21:21.088502181Z Transition to LEADER on term 18 - transitioning LogStream 
I 2022-01-17T10:21:21.095113044Z Transition to LEADER on term 18 - transitioning ZeebeDb 
I 2022-01-17T10:21:21.095141288Z Transition to LEADER on term 18 - transitioning ZeebeDb 
I 2022-01-17T10:21:21.399758752Z Transition to LEADER on term 18 - transitioning QueryService 
I 2022-01-17T10:21:21.832446487Z Recovered state of partition 2 from snapshot at position 1160049954 
I 2022-01-17T10:21:21.839733383Z Recovered state of partition 3 from snapshot at position 1156749833 
I 2022-01-17T10:21:21.921493107Z DMN-Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.feel.impl.DefaultValueMapper@51139d69)), function-provider: org.camunda.feel.context.FunctionProvider$EmptyFunctionProvider$@194090d1, audit-loggers: List(), configuration: Configuration(false,false,false)] 
I 2022-01-17T10:21:22.002241922Z Processor starts replay of events. [snapshot-position: 1160049954, replay-mode: PROCESSING] 
I 2022-01-17T10:21:22.003749498Z Transition to LEADER on term 18 - transitioning SnapshotDirector 
W 2022-01-17T10:21:22.005078398Z Partition-2 failed, marking it as unhealthy: Broker-1{status=UNHEALTHY, issue=Partition-2{status=UNHEALTHY, issue=ZeebePartition-2{status=UNHEALTHY, issue='Initial state'}}} 
I 2022-01-17T10:21:22.007022615Z Transition to LEADER on term 18 - transitioning ExporterDirector 
I 2022-01-17T10:21:22.016176739Z Transition to LEADER on term 18 completed 
I 2022-01-17T10:21:22.023729937Z ZeebePartition-2 recovered, marking it as healthy 
W 2022-01-17T10:21:22.025619333Z Partition-2 failed, marking it as unhealthy: Broker-1{status=UNHEALTHY, issue=Partition-2{status=UNHEALTHY, issue=ZeebePartition-2{status=UNHEALTHY, issue='Initial state'}}} 
W 2022-01-17T10:21:22.026385279Z Partition-2 failed, marking it as unhealthy: Broker-1{status=UNHEALTHY, issue=Partition-2{status=UNHEALTHY, issue=ZeebePartition-2{status=UNHEALTHY, issue='Initial state'}}} 
I 2022-01-17T10:21:22.027182950Z Partition-2 recovered, marking it as healthy 
I 2022-01-17T10:21:22.363418238Z Exporter opened 
I 2022-01-17T10:21:26.120575540Z Transition to LEADER on term 16 requested. 
I 2022-01-17T10:21:26.121886500Z Transition to LEADER on term 16 starting 
I 2022-01-17T10:21:26.122224081Z Transition to LEADER on term 16 - transitioning LogStorage 
I 2022-01-17T10:21:26.122591620Z Transition to LEADER on term 16 - transitioning LogStream 
I 2022-01-17T10:21:26.123802305Z Transition to LEADER on term 16 - transitioning ZeebeDb 
I 2022-01-17T10:21:26.128798623Z RaftServer{raft-partition-partition-1}{role=LEADER} - Received greater term from 0 
I 2022-01-17T10:21:26.129285143Z RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER 
I 2022-01-17T10:21:26.146483111Z Transition to FOLLOWER on term 17 requested. 
I 2022-01-17T10:21:26.158732674Z RaftServer{raft-partition-partition-1}{role=LEADER} - Accepted VoteRequest{term=17, candidate=0, lastLogIndex=377543061, lastLogTerm=16}: candidate's log is up-to-date 
I 2022-01-17T10:21:26.161626826Z Received cancel signal for transition to LEADER on term 16 
I 2022-01-17T10:21:26.166789699Z RaftServer{raft-partition-partition-1} - Found leader 0 
I 2022-01-17T10:21:26.398196919Z Cancelling transition to LEADER on term 16 
I 2022-01-17T10:21:26.398955123Z ZeebePartition-1 recovered, marking it as healthy 
I 2022-01-17T10:21:26.400720967Z Prepare transition from LEADER on term 16 to FOLLOWER 
I 2022-01-17T10:21:26.403995265Z Prepare transition from LEADER on term 16 to FOLLOWER - preparing ExporterDirector 
I 2022-01-17T10:21:26.405370881Z Prepare transition from LEADER on term 16 to FOLLOWER - preparing SnapshotDirector 
I 2022-01-17T10:21:26.406182183Z Prepare transition from LEADER on term 16 to FOLLOWER - preparing StreamProcessor 
I 2022-01-17T10:21:26.406625999Z Prepare transition from LEADER on term 16 to FOLLOWER - preparing QueryService 
I 2022-01-17T10:21:26.406909391Z Prepare transition from LEADER on term 16 to FOLLOWER - preparing ZeebeDb 
I 2022-01-17T10:21:26.407652214Z Prepare transition from LEADER on term 16 to FOLLOWER - preparing LogStream 
I 2022-01-17T10:21:26.409203037Z Partition-1 recovered, marking it as healthy 
E 2022-01-17T10:21:26.410240921Z Uncaught exception in 'Broker-1-QueryApi' in phase 'STARTED'. Continuing with next job. 
I 2022-01-17T10:21:26.563651151Z Transition to FOLLOWER on term 17 - transitioning ZeebeDb 
I 2022-01-17T10:21:26.803319130Z Recovered state of partition 1 from snapshot at position 1155728586 
I 2022-01-17T10:21:26.812462326Z DMN-Engine created. [value-mapper: CompositeValueMapper(List(org.camunda.feel.impl.DefaultValueMapper@51139d69)), function-provider: org.camunda.feel.context.FunctionProvider$EmptyFunctionProvider$@194090d1, audit-loggers: List(), configuration: Configuration(false,false,false)] 
I 2022-01-17T10:21:26.816552071Z Processor starts replay of events. [snapshot-position: 1155728586, replay-mode: REPLAY] 
I 2022-01-17T10:21:26.816931428Z Transition to FOLLOWER on term 17 - transitioning SnapshotDirector 
I 2022-01-17T10:21:26.817723552Z Partition-1 recovered, marking it as healthy 
I 2022-01-17T10:21:26.819454832Z Transition to FOLLOWER on term 17 - transitioning ExporterDirector 
I 2022-01-17T10:21:26.821082786Z Transition to FOLLOWER on term 17 completed 
I 2022-01-17T10:21:26.823791317Z ZeebePartition-1 recovered, marking it as healthy 
I 2022-01-17T10:21:26.824641262Z Partition-1 recovered, marking it as healthy 
I 2022-01-17T10:21:26.825341684Z Partition-1 recovered, marking it as healthy 
I 2022-01-17T10:21:26.826081030Z Partition-1 recovered, marking it as healthy 
I 2022-01-17T10:21:38.281936216Z Processor finished replay, with [lastProcessedPosition: 1160161781, lastWrittenPosition: 1160161986] 
I 2022-01-17T10:21:38.286632640Z Starting processing of migration tasks (use LogLevel.DEBUG for more details) ...  
I 2022-01-17T10:21:38.291736487Z Skipping ProcessMessageSubscriptionSentTimeMigration migration (1/3).  It was determined it does not need to run right now. 
I 2022-01-17T10:21:38.292461104Z Skipping MessageSubscriptionSentTimeMigration migration (2/3).  It was determined it does not need to run right now. 
I 2022-01-17T10:21:38.292969267Z Skipping TemporaryVariableMigration migration (3/3).  It was determined it does not need to run right now. 
I 2022-01-17T10:21:38.293189569Z Completed processing of migration tasks (use LogLevel.DEBUG for more details) ...  
```

Bottom line is that it occurred during startup and apparently it was not a quick startup.

**Comment by Zelldon** [comment] 2022-12-30 14:14
Doesn't seem to happen again. I will close it for now

**Comment by saig0** [comment] 2023-05-04 11:49
I saw this error again ([2 times](https://console.cloud.google.com/errors/detail/CMvC9c6_5qu-Jg;service=zeebe;time=P7D?project=camunda-saas-int)) in version `8.2.3` on SaaS INT stage.

@megglos please decide if we want to reopen the issue.

**Comment by oleschoenburg** [comment] 2023-08-02 07:15
I think this was a duplicate of https://github.com/camunda/zeebe/issues/13471, closing for now.

**Closed by oleschoenburg** 2023-08-02 07:15 UTC
Labels: kind/bug, severity/low, area/observability
