### ISSUE TITLE
Flaky MultiTenancyOverIdentityIT

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#15827] opened 2024-01-10 08:33 UTC
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

```
Warning:  Flakes: 
Warning:  io.camunda.zeebe.it.multitenancy.MultiTenancyOverIdentityIT.shouldDenyActivateJobWhenUnauthorized
Error:    Run 1: MultiTenancyOverIdentityIT.shouldDenyActivateJobWhenUnauthorized:712 » ClientStatus
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.it.multitenancy.MultiTenancyOverIdentityIT.shouldDenyEvaluateDecisionForCustomTenant
Error:    Run 1: MultiTenancyOverIdentityIT.shouldDenyEvaluateDecisionForCustomTenant:1281 » ClientStatus
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.it.multitenancy.MultiTenancyOverIdentityIT.shouldIncrementProcessVersionPerTenant
Error:    Run 1: MultiTenancyOverIdentityIT.shouldIncrementProcessVersionPerTenant:379 » ClientStatus
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.it.multitenancy.MultiTenancyOverIdentityIT.shouldNotFindIncidentForTenantWhenUnauthorized
Error:    Run 1: MultiTenancyOverIdentityIT.shouldNotFindIncidentForTenantWhenUnauthorized:972 » ClientStatus
[INFO]   Run 2: PASS
[INFO] 
Warning:  io.camunda.zeebe.it.multitenancy.MultiTenancyOverIdentityIT.shouldNotFindJobWhenUnauthorized
Error:    Run 1: MultiTenancyOverIdentityIT.shouldNotFindJobWhenUnauthorized:882 » ClientStatus
[INFO]   Run 2: PASS
```

<details><summary>Example assertion failure</summary>
<pre>
Error:  io.camunda.zeebe.it.multitenancy.MultiTenancyOverIdentityIT.shouldDenyActivateJobWhenUnauthorized -- Time elapsed: 0.682 s <<< ERROR!
io.camunda.zeebe.client.api.command.ClientStatusException
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.transformExecutionException(ZeebeClientFutureImpl.java:116)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:54)
	at io.camunda.zeebe.it.multitenancy.MultiTenancyOverIdentityIT.shouldDenyActivateJobWhenUnauthorized(MultiTenancyOverIdentityIT.java:712)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:[184](https://github.com/camunda/zeebe-process-test/actions/runs/7398812461/job/20295120674?pr=1018#step:10:185)3)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:[188](https://github.com/camunda/zeebe-process-test/actions/runs/7398812461/job/20295120674?pr=1018#step:10:189))
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: CANCELLED
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.camunda.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:52)
	... 8 more
Caused by: io.grpc.StatusRuntimeException: CANCELLED
	at io.grpc.Status.asRuntimeException(Status.java:537)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: Failed while requesting access token with status code 401 and message Unauthorized.
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsProvider.fetchCredentials(OAuthCredentialsProvider.java:162)
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsCache.computeIfMissingOrInvalid(OAuthCredentialsCache.java:100)
	at io.camunda.zeebe.client.impl.oauth.OAuthCredentialsProvider.applyCredentials(OAuthCredentialsProvider.java:84)
	at io.camunda.zeebe.client.impl.ZeebeCallCredentials.lambda$applyRequestMetadata$0(ZeebeCallCredentials.java:48)
	... 3 more
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

[Test results.zip](https://github.com/camunda/zeebe/files/13885090/Test.results.zip)

**Comment by npepinpe** [comment] 2024-01-11 13:14
ZDP: unrelated to our scope.

**Comment by korthout** [comment] 2024-01-15 13:40
ZPA:
- could be duplicate of https://github.com/camunda/zeebe/issues/14649
- could be infra related, want to discuss with zdp

**Comment by korthout** [comment] 2024-01-18 11:51
Some highlights from the test result logs:

> 2024-01-08 10:58:49,046 WARN  [org.keycloak.events] (executor-thread-1) type=CLIENT_LOGIN_ERROR, realmId=camunda-platform, clientId=zeebe-tenant-a-and-default, userId=null, ipAddress=172.21.0.1, error=client_not_found, grant_type=client_credentials

> 0:58:49.727 [] [] [grpc-executor-0] DEBUG io.camunda.zeebe.gateway.interceptors.impl.IdentityInterceptor - Denying call gateway_protocol.Gateway/DeployResource as the token could not be fully verified. Error message: the provided claims are invalid

```
10:58:52.547 [] [] [grpc-executor-0] DEBUG io.camunda.zeebe.gateway - Expected to handle gRPC request DeployResource with tenant identifier 'tenant-b', but tenant is not authorized to perform this request
io.camunda.zeebe.gateway.cmd.IllegalTenantRequestException: Expected to handle gRPC request DeployResource with tenant identifier 'tenant-b', but tenant is not authorized to perform this request
	at io.camunda.zeebe.gateway.RequestMapper.ensureTenantIdSet(RequestMapper.java:358) ~[zeebe-gateway-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.gateway.RequestMapper.toDeployResourceRequest(RequestMapper.java:104) ~[zeebe-gateway-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.gateway.EndpointManager.mapToBrokerRequest(EndpointManager.java:489) ~[zeebe-gateway-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.gateway.EndpointManager.sendRequest(EndpointManager.java:430) [zeebe-gateway-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.gateway.EndpointManager.deployResource(EndpointManager.java:270) [zeebe-gateway-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.gateway.GatewayGrpcService.deployResource(GatewayGrpcService.java:131) [zeebe-gateway-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.camunda.zeebe.gateway.protocol.GatewayGrpc$MethodHandlers.invoke(GatewayGrpc.java:2294) [zeebe-gateway-protocol-impl-8.5.0-SNAPSHOT.jar:8.5.0-SNAPSHOT]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) [grpc-stub-1.60.1.jar:1.60.1]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) [grpc-api-1.60.1.jar:1.60.1]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) [grpc-api-1.60.1.jar:1.60.1]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) [grpc-api-1.60.1.jar:1.60.1]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) [grpc-api-1.60.1.jar:1.60.1]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) [grpc-api-1.60.1.jar:1.60.1]
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) [grpc-api-1.60.1.jar:1.60.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351) [grpc-core-1.60.1.jar:1.60.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861) [grpc-core-1.60.1.jar:1.60.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.60.1.jar:1.60.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) [grpc-core-1.60.1.jar:1.60.1]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
```

**Comment by tmetzke** [comment] 2024-03-07 13:43
ZPA mob programming:
- We don't see any other prominent failures/errors in the logs except for what @korthout already mentions above.
- We suspect the test setup is causing the flakiness here, especially the `awaitCamundaRealmAvailabilityOnKeycloak` method that's supposed to ensure we're in the right state to make calls over identity and keycloak.
- We'd like to talk the setup over with an Identity engineer if possible.
- @berkaycanbc has an interest in exploring this and will reach out to the identity team to verify the test setup first.

**Comment by megglos** [comment] 2024-03-11 16:09
> We suspect the test setup is causing the flakiness here, especially the awaitCamundaRealmAvailabilityOnKeycloak method that's supposed to ensure we're in the right state to make calls over identity and keycloak.

This is used in `GatewayAuthenticationIdentityIT` which is flaky as well https://github.com/camunda/zeebe/issues/15429 which indicates as well that awaiting the realm isn't a good signal to await. I think it would be best if we could rely on some health check endpoint of identity to await its full initialization reliably.

**Closed** 2024-03-13 13:39 UTC
Labels: kind/flake, component/zeebe
