### ISSUE TITLE
Support S3 backup httpclient custom configuration.

### ISSUE THREAD

**Issue by codingman1990** [camunda/zeebe#12942] opened 2023-06-02 10:05 UTC
In our case，the directory of `/usr/local/zeebe/data/raft-partition/partitions/1` has about 60 .log files with each one has 128MB size data,and we have 3 patitions,so all the files‘s size almost reach 66GB.When we do backup api,it always failed by throwing exception like below:
![image](https://github.com/camunda/zeebe/assets/12196018/ea47d5f7-9fe6-40dc-9d62-92ece0445266)

`
{'backupId': 1685672012, 'status': 'FAILED', 'failureReason': "Backup on partition 3 failed due to java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.\nConsider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.\nIncreasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.\nIf the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.}
`
I also see the code source,S3BackupStore.java create NettyNioAsyncHttpClient with static number 45s of ConnectionAcquireTimeout,and other configuration used the default value.There is no any chance to customizing httpClient configurtation data .
I'm not sure if i have missing somthing important document.Could you help me with this problem?  Thanks.
@oleschoenburg 
![image](https://github.com/camunda/zeebe/assets/12196018/fd472cf0-be41-4d2f-ae4e-222a4b1725c9)

**Comment by oleschoenburg** [comment] 2023-06-05 13:59
Thanks for reporting @codingman1990 :+1: 

Please correct me if I'm wrong but the situation is basically this:
When a partition has a lot of log segments, uploading them in parallel will cause some uploads to wait for longer than 45 seconds on an available connection. This results in an exception and failure to complete the backup.

We should definitely improve this, although I'm not sure if just configuring the connection acquisition timeout is the right way to go about it.

In my opinion, the issue is rather that there is no limiting of parallel uploads. This is an issue here, with 66 log segments. It will also become an issue for large states, especially if #12483 is merged. So I would suggest to rather limit the number of concurrent uploads. The limit can be configurable of course.


@codingman1990 Slightly unrelated but I was a bit surprised when I read that you have >60 log segments. I'd have expected much lower numbers. Did you adjust the snapshot interval or know any other reasons why your brokers keep more segments than usual?

**Comment by codingman1990** [comment] 2023-06-06 02:12
> Thanks for reporting @codingman1990 👍
> 
> Please correct me if I'm wrong but the situation is basically this: When a partition has a lot of log segments, uploading them in parallel will cause some uploads to wait for longer than 45 seconds on an available connection. This results in an exception and failure to complete the backup.
> 
> We should definitely improve this, although I'm not sure if just configuring the connection acquisition timeout is the right way to go about it.
> 
> In my opinion, the issue is rather that there is no limiting of parallel uploads. This is an issue here, with 66 log segments. It will also become an issue for large states, especially if #12483 is merged. So I would suggest to rather limit the number of concurrent uploads. The limit can be configurable of course.
> 
> @codingman1990 Slightly unrelated but I was a bit surprised when I read that you have >60 log segments. I'd have expected much lower numbers. Did you adjust the snapshot interval or know any other reasons why your brokers keep more segments than usual?

In my situation,there are abount 200 running instances at the same time.I almost had not edit any configuration except something like ES,BackupStore.The full configuration data is like below(Some sensitive data are marsked):

`json
{
    "network": {
        "host": "0.0.0.0",
        "portOffset": 0,
        "maxMessageSize": "4MB",
        "advertisedHost": "***",
        "commandApi": {
            "host": "0.0.0.0",
            "port": 26501,
            "advertisedHost": "***",
            "advertisedPort": 26501,
            "address": "0.0.0.0:26501",
            "advertisedAddress": "***"
        },
        "internalApi": {
            "host": "0.0.0.0",
            "port": 26502,
            "advertisedHost": "***",
            "advertisedPort": 26502,
            "address": "0.0.0.0:26502",
            "advertisedAddress": "***"
        },
        "security": {
            "enabled": false,
            "certificateChainPath": null,
            "privateKeyPath": null
        },
        "maxMessageSizeInBytes": 4194304
    },
    "cluster": {
        "initialContactPoints": [
            "***",
            "***",
            "***"
        ],
        "partitionIds": [
            1,
            2,
            3
        ],
        "nodeId": 1,
        "partitionsCount": 3,
        "replicationFactor": 3,
        "clusterSize": 3,
        "clusterName": "camunda-zeebe",
        "heartbeatInterval": "PT0.25S",
        "electionTimeout": "PT2.5S",
        "membership": {
            "broadcastUpdates": false,
            "broadcastDisputes": true,
            "notifySuspect": false,
            "gossipInterval": "PT0.25S",
            "gossipFanout": 2,
            "probeInterval": "PT1S",
            "probeTimeout": "PT0.1S",
            "suspectProbes": 3,
            "failureTimeout": "PT10S",
            "syncInterval": "PT10S"
        },
        "raft": {
            "enablePriorityElection": true
        },
        "messageCompression": "NONE"
    },
    "threads": {
        "cpuThreadCount": 3,
        "ioThreadCount": 3
    },
    "data": {
        "directory": "/usr/local/zeebe/data",
        "logSegmentSize": "128MB",
        "snapshotPeriod": "PT5M",
        "logIndexDensity": 100,
        "diskUsageMonitoringEnabled": true,
        "diskUsageReplicationWatermark": 0.87,
        "diskUsageCommandWatermark": 0.85,
        "diskUsageMonitoringInterval": "PT1S",
        "backup": {
            "store": "S3",
            "s3": {
                "bucketName": "zeebe-proc",
                "endpoint": "***",
                "region": "cn-hangzhou",
                "accessKey": "***",
                "secretKey": "***",
                "apiCallTimeout": "PT3M"
            }
        },
        "logSegmentSizeInBytes": 134217728,
        "freeDiskSpaceCommandWatermark": 5052946022,
        "freeDiskSpaceReplicationWatermark": 4379219886
    },
    "exporters": {
        "elasticsearch": {
            "jarPath": null,
            "className": "io.camunda.zeebe.exporter.ElasticsearchExporter",
            "args": {
                "index": {
                    "prefix": "zeebe-record"
                },
                "authentication": {
                    "password": "***",
                    "username": "***"
                },
                "url": "***"
            },
            "external": false
        }
    },
    "gateway": {
        "network": {
            "host": "0.0.0.0",
            "port": 26500,
            "minKeepAliveInterval": "PT30S"
        },
        "cluster": {
            "initialContactPoints": [
                "0.0.0.0:26502"
            ],
            "requestTimeout": "PT15S",
            "clusterName": "zeebe-cluster",
            "memberId": "gateway",
            "host": "0.0.0.0",
            "advertisedHost": "0.0.0.0",
            "port": 26502,
            "advertisedPort": 26502,
            "membership": {
                "broadcastUpdates": false,
                "broadcastDisputes": true,
                "notifySuspect": false,
                "gossipInterval": "PT0.25S",
                "gossipFanout": 2,
                "probeInterval": "PT1S",
                "probeTimeout": "PT0.1S",
                "suspectProbes": 3,
                "failureTimeout": "PT10S",
                "syncInterval": "PT10S"
            },
            "security": {
                "enabled": false,
                "certificateChainPath": null,
                "privateKeyPath": null
            },
            "messageCompression": "NONE"
        },
        "threads": {
            "managementThreads": 1
        },
        "security": {
            "enabled": false,
            "certificateChainPath": null,
            "privateKeyPath": null
        },
        "longPolling": {
            "enabled": true
        },
        "interceptors": [],
        "initialized": true,
        "enable": false
    },
    "backpressure": {
        "enabled": true,
        "algorithm": "VEGAS",
        "aimd": {
            "requestTimeout": "PT1S",
            "initialLimit": 100,
            "minLimit": 1,
            "maxLimit": 1000,
            "backoffRatio": 0.9
        },
        "fixed": {
            "limit": 20
        },
        "vegas": {
            "alpha": 3,
            "beta": 6,
            "initialLimit": 20
        },
        "gradient": {
            "minLimit": 10,
            "initialLimit": 20,
            "rttTolerance": 2.0
        },
        "gradient2": {
            "minLimit": 10,
            "initialLimit": 20,
            "rttTolerance": 2.0,
            "longWindow": 600
        }
    },
    "experimental": {
        "maxAppendsPerFollower": 2,
        "maxAppendBatchSize": "32KB",
        "disableExplicitRaftFlush": false,
        "rocksdb": {
            "columnFamilyOptions": {},
            "enableStatistics": false,
            "memoryLimit": "512MB",
            "maxOpenFiles": -1,
            "maxWriteBufferNumber": 6,
            "minWriteBufferNumberToMerge": 3,
            "ioRateBytesPerSecond": 0,
            "disableWal": false
        },
        "raft": {
            "requestTimeout": "PT5S",
            "maxQuorumResponseTimeout": "PT0S",
            "minStepDownFailureCount": 3,
            "preferSnapshotReplicationThreshold": 100,
            "preallocateSegmentFiles": true
        },
        "partitioning": {
            "scheme": "ROUND_ROBIN",
            "fixed": []
        },
        "queryApi": {
            "enabled": false
        },
        "consistencyChecks": {
            "enablePreconditions": false,
            "enableForeignKeyChecks": false,
            "settings": {
                "enablePreconditions": false,
                "enableForeignKeyChecks": false
            }
        },
        "engine": {
            "messages": {
                "ttlCheckerBatchLimit": 2147483647,
                "ttlCheckerInterval": "PT1M"
            }
        },
        "features": {
            "enableYieldingDueDateChecker": false,
            "enableActorMetrics": false,
            "enableBackup": true,
            "enableMessageTtlCheckerAsync": false
        },
        "maxAppendBatchSizeInBytes": 32768
    },
    "executionMetricsExporterEnabled": false,
    "processing": {
        "maxCommandsInBatch": 1
    }
}
`

**Comment by megglos** [comment] 2023-06-08 12:35
ZDP-Triage:
- to be discussed at planning as flagged by Ole

**Comment by megglos** [comment] 2023-06-09 09:41
ZDP-Planning:
- will become more likely with sst partitioning enabled

**Closed** 2023-08-14 08:22 UTC
Labels: kind/feature
