### ISSUE TITLE
IllegalStateException: journal not open

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#10988] opened 2022-11-14 15:34 UTC
**Describe the bug**

Checking the error logs as a medic I encountered this error. It seems a broker died because of #10309. After which some leader transition happened, resulting in this exception.

**To Reproduce**

Unknown

**Expected behavior**

**Log/Stacktrace**

[gcloud](https://console.cloud.google.com/errors/detail/CJ_qqPOO14Om9AE;service=zeebe;time=P7D?project=camunda-cloud-240911)
[downloaded-logs-20221114-163124.json.zip](https://github.com/camunda/zeebe/files/10010740/downloaded-logs-20221114-163124.json.zip)

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: journal not open
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[guava-31.1-jre.jar:?]
	at io.camunda.zeebe.journal.file.SegmentedJournal.assertOpen(SegmentedJournal.java:175) ~[zeebe-journal-8.1.3.jar:8.1.3]
	at io.camunda.zeebe.journal.file.SegmentedJournal.getFirstSegment(SegmentedJournal.java:201) ~[zeebe-journal-8.1.3.jar:8.1.3]
	at io.camunda.zeebe.journal.file.SegmentedJournalReader.unsafeSeekToFirst(SegmentedJournalReader.java:178) ~[zeebe-journal-8.1.3.jar:8.1.3]
	at io.camunda.zeebe.journal.file.SegmentedJournalReader.unsafeSeek(SegmentedJournalReader.java:163) ~[zeebe-journal-8.1.3.jar:8.1.3]
	at io.camunda.zeebe.journal.file.SegmentedJournalReader.seekToAsqn(SegmentedJournalReader.java:122) ~[zeebe-journal-8.1.3.jar:8.1.3]
	at io.atomix.raft.storage.log.RaftLogUncommittedReader.seekToAsqn(RaftLogUncommittedReader.java:81) ~[zeebe-atomix-cluster-8.1.3.jar:8.1.3]
	at io.atomix.raft.storage.log.RaftLogCommittedReader.seekToAsqn(RaftLogCommittedReader.java:76) ~[zeebe-atomix-cluster-8.1.3.jar:8.1.3]
	at io.camunda.zeebe.broker.logstreams.AtomixLogStorageReader.seek(AtomixLogStorageReader.java:58) ~[zeebe-broker-8.1.3.jar:8.1.3]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamReaderImpl.seek(LogStreamReaderImpl.java:100) ~[zeebe-logstreams-8.1.3.jar:8.1.3]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamReaderImpl.seekToNextEvent(LogStreamReaderImpl.java:86) ~[zeebe-logstreams-8.1.3.jar:8.1.3]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.startActiveExportingMode(ExporterDirector.java:330) ~[zeebe-broker-8.1.3.jar:8.1.3]
	at io.camunda.zeebe.broker.exporter.stream.ExporterDirector.onActorStarted(ExporterDirector.java:212) ~[zeebe-broker-8.1.3.jar:8.1.3]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.1.3.jar:8.1.3]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.1.3.jar:8.1.3]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.1.3.jar:8.1.3]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.3.jar:8.1.3]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.3.jar:8.1.3]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.3.jar:8.1.3] 
```

</p>
</details>

**Environment:**
- OS: Cloud
- Zeebe Version: 8.1.3
- Cluster: cb245e99-a22a-4a9b-98ee-d4af667b6860

**Comment by Zelldon** [comment] 2022-11-15 08:37
I think we can only export in json, since we use json logging. Afaik this is ok, this is how we did it in the past :shrug: If the file is to large we normally put it into google drive.

**Comment by megglos** [comment] 2022-11-25 10:41
potential duplicate of #11070

**Comment by megglos** [comment] 2023-02-17 10:44
not seen for 30 days, will close for now

**Closed by megglos** 2023-02-17 10:44 UTC
Labels: kind/bug, component/partition-transitions, planning/discuss
