### ISSUE TITLE
RollingUpdateTest.shouldReplicateSnapshotAcrossVersions

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#12775] opened 2023-05-16 09:54 UTC
**Summary**

- How often does the test fail?  2
- Does it block your work? No
- Do we suspect that it is a real failure? No

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:  io.camunda.zeebe.test.RollingUpdateTest.shouldReplicateSnapshotAcrossVersions  Time elapsed: 55.149 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting actual:
  {}
to contain key:
  1
	at io.camunda.zeebe.test.RollingUpdateTest.assertBrokerHasAtLeastOneSnapshot(RollingUpdateTest.java:322)
	at io.camunda.zeebe.test.RollingUpdateTest.shouldReplicateSnapshotAcrossVersions(RollingUpdateTest.java:174)
</pre>
</details>

**Logs**

[Test results for [IT] QA Update Tests.zip](https://github.com/camunda/zeebe/files/11486395/Test.results.for.IT.QA.Update.Tests.zip)

**Comment by npepinpe** [comment] 2023-05-22 12:18
Duplicate of #10954 I think. Please reopen if not.

**Closed by npepinpe** 2023-05-22 12:18 UTC
Labels: kind/flake
