### ISSUE TITLE
Leaked message subscriptions cause constant processing load

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#14814] opened 2023-10-23 10:19 UTC
On a Zeebe 8.2.12 Cluster we observed the following load. This does not resolve itself and the load remains constant.

```
COMMAND PROCESS_MESSAGE_SUBSCRIPTION CORRELATE 22517998138010331 
COMMAND PROCESS_MESSAGE_SUBSCRIPTION CORRELATE 22517998139003162 
COMMAND PROCESS_MESSAGE_SUBSCRIPTION CORRELATE 22517998140261067 
COMMAND PROCESS_MESSAGE_SUBSCRIPTION CORRELATE 22517998142789239 
...
COMMAND_REJECTION PROCESS_MESSAGE_SUBSCRIPTION CORRELATE 22517998138010331 
COMMAND MESSAGE_SUBSCRIPTION REJECT 22517998138010331 
COMMAND_REJECTION MESSAGE_SUBSCRIPTION REJECT 22517998138010331 
COMMAND_REJECTION PROCESS_MESSAGE_SUBSCRIPTION CORRELATE 22517998139003162 
COMMAND MESSAGE_SUBSCRIPTION REJECT 22517998139003162 
COMMAND_REJECTION MESSAGE_SUBSCRIPTION REJECT 22517998139003162 
COMMAND_REJECTION PROCESS_MESSAGE_SUBSCRIPTION CORRELATE 22517998140261067 
COMMAND MESSAGE_SUBSCRIPTION REJECT 22517998140261067 
COMMAND_REJECTION MESSAGE_SUBSCRIPTION REJECT 22517998140261067 
COMMAND_REJECTION PROCESS_MESSAGE_SUBSCRIPTION CORRELATE 22517998142789239 
COMMAND MESSAGE_SUBSCRIPTION REJECT 22517998142789239 
COMMAND_REJECTION MESSAGE_SUBSCRIPTION REJECT 22517998142789239 
```

The `PendingMessageSubscriptionChecker` writes `PROCESS_MESSAGE_SUBSCRIPTION/CORRELATE` commands for entries in `MutablePendingMessageSubscriptionState`. While processing these commands, the `ProcessMessageSubscriptionCorrelateProcessor` doesn't find a matching subscription and writes a `COMMAND_REJECTION` and a `MESSAGE_SUBSCRIPTION/REJECT` command. The `MessageSubscriptionRejectProcessor` _also_ rejects the `MESSAGE_SUBSCRIPTION/REJECT` command by writing a `COMMAND_REJECTION` because it does not find a matching correlation in the message state.

The `PROCESS_MESSAGE_SUBSCRIPTION/CORRELATE` is rejected with cause `NOT_FOUND` and a matching message: "Expected to correlate process message subscription with element key '22517998206768899' and message name 'MY_MESSAGE_NAME', but no such subscription was found".
The `MESSAGE_SUBSCRIPTION/REJECT` is rejected with cause `INVALID_STATE` and message "Expected message '112589990754201722' to be correlated for process with BPMN process id 'MY_PROCESS_ID' but no correlation was found"

## Cause

On one partition we have the subscription column family containing a subscription with `correlating=true` so the `PROCESS_MESSAGE_SUBSCRIPTION/CORRELATE` is sent again and again. On the other partition, the subscription column family does not contain such an entry.
Hypothesis: A `MESSAGE_SUBSCRIPTION/CORRELATE` or  `MESSAGE_SUBSCRIPTION/DELETE`command was lost, leaking the subscription entry. `ProcessMessageSubscriptionCorrelateProcessor` handles non interrupting subscriptions by removing them from the state immediately and then sending `MESSAGE_SUBSCRIPTION/CORRELATE` just once. If that command is lost, nothing will resend it. The other partition keeps the partition in the state, tries to correlate again and again but only gets rejections because the receiving partition doesn't know about the subscription anymore.
 
## Related Notes

- It probably doesn't make sense to reject a `MESSAGE_SUBSCRIPTION/REJECT` command, can't we just clean up the subscription when the receiving partition rejected it?
- Why write `COMMAND_REJECTION`s for internal commands not sent by a user anyway? Especially since the rejection is already described with a `MESSAGE_SUBSCRIPTION/REJECT` command.
- To fully fix this, we need to find a way to recover from this broken state, not just prevent it from happening again.

**Comment by saig0** [comment] 2023-10-25 12:30
This issue is actually a duplicate of an older issue https://github.com/camunda/zeebe/issues/5750 that was closed a while ago. :sweat_smile:

**Comment by oleschoenburg** [comment] 2023-10-25 12:30
Actually a duplicate of https://github.com/camunda/zeebe/issues/5750 (thanks to @saig0 for finding it!) but let's keep this one open because it contains some more information on how a partition can get into this state

**Comment by remcowesterhoud** [comment] 2023-11-01 14:44
ZPA Triage:
- As there is already a PR open for this I've put it in our iteration and in review so it's visibly.
- The PR is in draft, I've asked @oleschoenburg for clarification on the status of the PR.

**Closed** 2023-11-03 15:14 UTC
Labels: kind/bug, area/performance, severity/high, incident, area/reliability, component/state
