### ISSUE TITLE
InvalidConfigurationException on development

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#12123] opened 2023-03-23 13:24 UTC
**Describe the bug**

An error was reported on `development-worker-1`:

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
Caused by: io.camunda.zeebe.broker.system.InvalidConfigurationException
Caused by: com.google.cloud.storage.StorageException
during io.camunda.zeebe.broker.system.SystemContext.validateBackupCfg
```

I don't think this is an actual bug, but I wanted to report it to make sure as we are getting close to releasing 8.2 and this happened on `8.2.0-alpha5`

**To Reproduce**

Nothing, this was an error reported by Google Error Reporting.

**Expected behavior**

That we don't encounter an invalid config on production.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner

at org.springframework.boot.SpringApplication.callRunner ( org/springframework.boot/SpringApplication.java:772 )
at org.springframework.boot.SpringApplication.callRunners ( org/springframework.boot/SpringApplication.java:753 )
at org.springframework.boot.SpringApplication.run ( org/springframework.boot/SpringApplication.java:317 )
at io.camunda.zeebe.broker.StandaloneBroker.main ( [io/camunda.zeebe.broker/StandaloneBroker.java:82](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.broker%2FStandaloneBroker.java&line=82&project=camunda-cloud-240911) )
Caused by: io.camunda.zeebe.broker.system.InvalidConfigurationException

at io.camunda.zeebe.broker.system.SystemContext.validateBackupCfg ( [SystemContext.java:132](https://console.cloud.google.com/debug?referrer=fromlog&file=SystemContext.java&line=132&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.system.SystemContext.validateDataConfig ( [SystemContext.java:116](https://console.cloud.google.com/debug?referrer=fromlog&file=SystemContext.java&line=116&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.system.SystemContext.validateConfiguration ( [SystemContext.java:71](https://console.cloud.google.com/debug?referrer=fromlog&file=SystemContext.java&line=71&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.system.SystemContext.initSystemContext ( [SystemContext.java:60](https://console.cloud.google.com/debug?referrer=fromlog&file=SystemContext.java&line=60&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.system.SystemContext.<init> ( [SystemContext.java:56](https://console.cloud.google.com/debug?referrer=fromlog&file=SystemContext.java&line=56&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.StandaloneBroker.run ( [StandaloneBroker.java:87](https://console.cloud.google.com/debug?referrer=fromlog&file=StandaloneBroker.java&line=87&project=camunda-cloud-240911) )
at org.springframework.boot.SpringApplication.callRunner ( [SpringApplication.java:769](https://console.cloud.google.com/debug?referrer=fromlog&file=SpringApplication.java&line=769&project=camunda-cloud-240911) )
Caused by: com.google.cloud.storage.StorageException

at com.google.cloud.storage.StorageException.translate ( [StorageException.java:165](https://console.cloud.google.com/debug?referrer=fromlog&file=StorageException.java&line=165&project=camunda-cloud-240911) )
at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate ( [HttpStorageRpc.java:297](https://console.cloud.google.com/debug?referrer=fromlog&file=HttpStorageRpc.java&line=297&project=camunda-cloud-240911) )
at com.google.cloud.storage.spi.v1.HttpStorageRpc.get ( [HttpStorageRpc.java:490](https://console.cloud.google.com/debug?referrer=fromlog&file=HttpStorageRpc.java&line=490&project=camunda-cloud-240911) )
at com.google.cloud.storage.StorageImpl.lambda$get$4 ( [StorageImpl.java:280](https://console.cloud.google.com/debug?referrer=fromlog&file=StorageImpl.java&line=280&project=camunda-cloud-240911) )
at com.google.api.gax.retrying.DirectRetryingExecutor.submit ( [DirectRetryingExecutor.java:103](https://console.cloud.google.com/debug?referrer=fromlog&file=DirectRetryingExecutor.java&line=103&project=camunda-cloud-240911) )
at com.google.cloud.RetryHelper.run ( [RetryHelper.java:76](https://console.cloud.google.com/debug?referrer=fromlog&file=RetryHelper.java&line=76&project=camunda-cloud-240911) )
at com.google.cloud.RetryHelper.runWithRetries ( [RetryHelper.java:50](https://console.cloud.google.com/debug?referrer=fromlog&file=RetryHelper.java&line=50&project=camunda-cloud-240911) )
at com.google.cloud.storage.Retrying.run ( [Retrying.java:60](https://console.cloud.google.com/debug?referrer=fromlog&file=Retrying.java&line=60&project=camunda-cloud-240911) )
at com.google.cloud.storage.StorageImpl.run ( [StorageImpl.java:1476](https://console.cloud.google.com/debug?referrer=fromlog&file=StorageImpl.java&line=1476&project=camunda-cloud-240911) )
at com.google.cloud.storage.StorageImpl.get ( [StorageImpl.java:278](https://console.cloud.google.com/debug?referrer=fromlog&file=StorageImpl.java&line=278&project=camunda-cloud-240911) )
at io.camunda.zeebe.backup.gcs.GcsBackupStore.validateConfig ( [GcsBackupStore.java:157](https://console.cloud.google.com/debug?referrer=fromlog&file=GcsBackupStore.java&line=157&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.system.SystemContext.validateBackupCfg ( [SystemContext.java:124](https://console.cloud.google.com/debug?referrer=fromlog&file=SystemContext.java&line=124&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.system.SystemContext.validateDataConfig ( [SystemContext.java:116](https://console.cloud.google.com/debug?referrer=fromlog&file=SystemContext.java&line=116&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.system.SystemContext.validateConfiguration ( [SystemContext.java:71](https://console.cloud.google.com/debug?referrer=fromlog&file=SystemContext.java&line=71&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.system.SystemContext.initSystemContext ( [SystemContext.java:60](https://console.cloud.google.com/debug?referrer=fromlog&file=SystemContext.java&line=60&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.system.SystemContext.<init> ( [SystemContext.java:56](https://console.cloud.google.com/debug?referrer=fromlog&file=SystemContext.java&line=56&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.StandaloneBroker.run ( [StandaloneBroker.java:87](https://console.cloud.google.com/debug?referrer=fromlog&file=StandaloneBroker.java&line=87&project=camunda-cloud-240911) )
at org.springframework.boot.SpringApplication.callRunner ( [SpringApplication.java:769](https://console.cloud.google.com/debug?referrer=fromlog&file=SpringApplication.java&line=769&project=camunda-cloud-240911) )
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException

at com.google.api.client.googleapis.json.GoogleJsonResponseException.from ( [GoogleJsonResponseException.java:146](https://console.cloud.google.com/debug?referrer=fromlog&file=GoogleJsonResponseException.java&line=146&project=camunda-cloud-240911) )
at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError ( [AbstractGoogleJsonClientRequest.java:118](https://console.cloud.google.com/debug?referrer=fromlog&file=AbstractGoogleJsonClientRequest.java&line=118&project=camunda-cloud-240911) )
at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError ( [AbstractGoogleJsonClientRequest.java:37](https://console.cloud.google.com/debug?referrer=fromlog&file=AbstractGoogleJsonClientRequest.java&line=37&project=camunda-cloud-240911) )
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$3.interceptResponse ( [AbstractGoogleClientRequest.java:466](https://console.cloud.google.com/debug?referrer=fromlog&file=AbstractGoogleClientRequest.java&line=466&project=camunda-cloud-240911) )
at com.google.api.client.http.HttpRequest.execute ( [HttpRequest.java:1111](https://console.cloud.google.com/debug?referrer=fromlog&file=HttpRequest.java&line=1111&project=camunda-cloud-240911) )
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed ( [AbstractGoogleClientRequest.java:552](https://console.cloud.google.com/debug?referrer=fromlog&file=AbstractGoogleClientRequest.java&line=552&project=camunda-cloud-240911) )
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed ( [AbstractGoogleClientRequest.java:493](https://console.cloud.google.com/debug?referrer=fromlog&file=AbstractGoogleClientRequest.java&line=493&project=camunda-cloud-240911) )
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute ( [AbstractGoogleClientRequest.java:603](https://console.cloud.google.com/debug?referrer=fromlog&file=AbstractGoogleClientRequest.java&line=603&project=camunda-cloud-240911) )
at com.google.cloud.storage.spi.v1.HttpStorageRpc.get ( [HttpStorageRpc.java:487](https://console.cloud.google.com/debug?referrer=fromlog&file=HttpStorageRpc.java&line=487&project=camunda-cloud-240911) )
at com.google.cloud.storage.StorageImpl.lambda$get$4 ( [StorageImpl.java:280](https://console.cloud.google.com/debug?referrer=fromlog&file=StorageImpl.java&line=280&project=camunda-cloud-240911) )
at com.google.api.gax.retrying.DirectRetryingExecutor.submit ( [DirectRetryingExecutor.java:103](https://console.cloud.google.com/debug?referrer=fromlog&file=DirectRetryingExecutor.java&line=103&project=camunda-cloud-240911) )
at com.google.cloud.RetryHelper.run ( [RetryHelper.java:76](https://console.cloud.google.com/debug?referrer=fromlog&file=RetryHelper.java&line=76&project=camunda-cloud-240911) )
at com.google.cloud.RetryHelper.runWithRetries ( [RetryHelper.java:50](https://console.cloud.google.com/debug?referrer=fromlog&file=RetryHelper.java&line=50&project=camunda-cloud-240911) )
at com.google.cloud.storage.Retrying.run ( [Retrying.java:60](https://console.cloud.google.com/debug?referrer=fromlog&file=Retrying.java&line=60&project=camunda-cloud-240911) )
at com.google.cloud.storage.StorageImpl.run ( [StorageImpl.java:1476](https://console.cloud.google.com/debug?referrer=fromlog&file=StorageImpl.java&line=1476&project=camunda-cloud-240911) )
at com.google.cloud.storage.StorageImpl.get ( [StorageImpl.java:278](https://console.cloud.google.com/debug?referrer=fromlog&file=StorageImpl.java&line=278&project=camunda-cloud-240911) )
at io.camunda.zeebe.backup.gcs.GcsBackupStore.validateConfig ( [GcsBackupStore.java:157](https://console.cloud.google.com/debug?referrer=fromlog&file=GcsBackupStore.java&line=157&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.system.SystemContext.validateBackupCfg ( [SystemContext.java:124](https://console.cloud.google.com/debug?referrer=fromlog&file=SystemContext.java&line=124&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.system.SystemContext.validateDataConfig ( [SystemContext.java:116](https://console.cloud.google.com/debug?referrer=fromlog&file=SystemContext.java&line=116&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.system.SystemContext.validateConfiguration ( [SystemContext.java:71](https://console.cloud.google.com/debug?referrer=fromlog&file=SystemContext.java&line=71&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.system.SystemContext.initSystemContext ( [SystemContext.java:60](https://console.cloud.google.com/debug?referrer=fromlog&file=SystemContext.java&line=60&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.system.SystemContext.<init> ( [SystemContext.java:56](https://console.cloud.google.com/debug?referrer=fromlog&file=SystemContext.java&line=56&project=camunda-cloud-240911) )
at io.camunda.zeebe.broker.StandaloneBroker.run ( [StandaloneBroker.java:87](https://console.cloud.google.com/debug?referrer=fromlog&file=StandaloneBroker.java&line=87&project=camunda-cloud-240911) )
at org.springframework.boot.SpringApplication.callRunner ( [SpringApplication.java:769](https://console.cloud.google.com/debug?referrer=fromlog&file=SpringApplication.java&line=769&project=camunda-cloud-240911) )
```

</p>
</details>

**Environment:**
- [Reported error](https://console.cloud.google.com/errors/detail/CIav_pyWubvVeQ;service=zeebe;time=P7D?project=camunda-cloud-240911)
- `development-worker-1`
- Version: `8.2.0-alpha5`

**Comment by koevskinikola** [comment] 2023-06-14 11:56
We seem to be facing this issue again on a production cluster ([internal logs link](https://console.cloud.google.com/logs/query;query=error_group%2528%22CP6s_Za8qIqakQE%22%2529%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.namespace_name%3D%2246a75740-dce6-44ad-a2b8-dc024f379f27-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22;timeRange=2023-06-13T16:24:16.780Z%2F2023-06-13T17:24:16.780Z;cursorTimestamp=2023-06-13T16:53:46.780342706Z?project=camunda-cloud-240911)).

**Comment by megglos** [comment] 2023-06-15 12:03
ZDP-Triage:
- this is a misconfiguration of the backup
- given it happened in prod we should reach out to SRE, @oleschoenburg will double-check

**Comment by oleschoenburg** [comment] 2023-06-15 12:19
Most recently caused by DNS resolution failure for www.googleapis.com :shrug: 

It's a bit unfortunate how this error shows up though, deeply nested in spring stuff.

**Comment by oleschoenburg** [comment] 2023-07-27 11:50
I'll close this for now, I don't think the error message is something that we have to improve.

**Closed by oleschoenburg** 2023-07-27 11:50 UTC
Labels: kind/bug, release/8.2.0
