### ISSUE TITLE
can not update  zeebe from 1.2 to 1.3 in local

### ISSUE THREAD

**Issue by jerry123888** [camunda/zeebe#12059] opened 2023-03-17 06:48 UTC
the action of set variable will not make sense

**Comment by jerry123888** [comment] 2023-03-19 02:56
@npepinpe

**Comment by jerry123888** [comment] 2023-03-19 02:57
@romansmirno

**Comment by korthout** [comment] 2023-03-22 10:23
Closing this as duplicate of https://github.com/camunda/zeebe/issues/12058

**Closed by korthout** 2023-03-22 10:23 UTC
Labels: kind/bug
