### ISSUE TITLE
8.3.x release benchmark - Authorization data unavailable: The Token can't be used before xxx

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#15047] opened 2023-11-06 14:26 UTC
**Describe the bug**

This error happened on Sat 03/11:

```
"StreamProcessor-1 failed, marking it as dead: StreamProcessor-1{status=DEAD, issue=HealthIssue[message=null, throwable=io.camunda.zeebe.util.exception.UnrecoverableException: Authorization data unavailable: The Token can't be used before 2023-11-03T14:46:52Z., cause=null]}"
```

You can find the logs [here](https://drive.google.com/drive/folders/1wJqLwgla0px44joF49Ve0bnW0WzZvtQC)

**Comment by megglos** [comment] 2023-11-09 13:11
ZDP-Triage:
- JWT token validation must relates to multi-tenancy, would delegate this to ZPA

**Comment by korthout** [comment] 2023-11-15 14:10
ZPA triage:
- marking it as high severity because it caused a DEAD partition
- we should investigate and fix it soon
- might make sense to work on this while multi-tenancy is fresh

@koevskinikola I heard that you may already have some thoughts about this issue. Could you share them in a comment?

**Comment by koevskinikola** [comment] 2023-11-17 12:22
Related to a [SUPPORT case](https://jira.camunda.com/browse/SUPPORT-19112) as well.

**Comment by koevskinikola** [comment] 2023-11-17 12:29
My hypothesis is that this is a time zone issue.

1. We're using `Instance.now()` to set the `JWT#issuedAt` (`iat`) claim [here](https://github.com/camunda/zeebe/blob/6a730a7bf57f0491cb0b29e5b2c90533330b6c1b/auth/src/main/java/io/camunda/zeebe/auth/impl/JwtAuthorizationEncoder.java#L66).
2. The `Instance.now()` method provides an `Instant` from the system UTC clock.
3. If the cluster is set on a different time zone, the JWT validation might throw an exception that `The Token can't be used before xxx`.

I will try to confirm this with a test.

**Comment by romansmirnov** [comment] 2023-11-17 14:31
@koevskinikola, just trying to understand the root cause of the issue, have you been able to validate your hypothesis? Isn't this "just" a clock syncing problem between the gateway node and broker node? By setting a leeway when verifying the token, would it help mitigate the issue?

However, please consider this just a question to get a better understanding of the root cause. Meaning, I agree with the decision above to solve the problem 😄

**Comment by koevskinikola** [comment] 2023-11-17 15:22
Hey @romansmirnov ,

I think you're right. It doesn't seem to be time-zone related, but just a matter of leeway.

That's because:
1. The JWT library that we use (`java-jwt`) also uses `Instant.now()` inside the `Verifier` to get the current time to compare against.
    * Since we're also using `Instant.now()` to set the `issuedAt` claim, this means the Verifier is always comparing UTC times.
2. The `defaultLeeway` value in `java-jwt` is set to `0`. This means that verifying this token even half a second earlier will cause an issue (this seems to be the case in one of the occurences).

So we can definitely adjust the `leeway` to compensate. However, as I pointed out, we're not really signing the JWT token, so the `issuedAt` claim is irrelevant here.

I would feel more confident in not verifying the `issuedAt` claim at all right now. If we ever decide to expose the JWT data to exported events, we can:
1. Sign it first.
2. Set and adjust the verification for the best-practice claims (like the `issuedAt`)

**Closed** 2023-11-17 17:19 UTC
Labels: kind/bug, severity/high, support, area/reliability

**Comment by Zelldon** [comment] 2023-11-23 10:13
Happened in 8.4.0-alpha1 https://console.cloud.google.com/errors/detail/CI_Y0MHF3fmnggE;service=zeebe;time=P7D?project=zeebe-io but I suspect this fix was not part of the release.

**Comment by korthout** [comment] 2023-11-23 10:20
Nope 0d600f736e6c1c6cc69cda38d40c78dc4d5abfea is not part of `8.4.0-alpha1`.
