### ISSUE TITLE
does the zeebe supports online upgrade from 1.2.x to 1.3.x

### ISSUE THREAD

**Issue by jerry123888** [camunda/zeebe#12107] opened 2023-03-22 10:41 UTC
Now i have a online zeebe cluster with 18 pods, the version is 1.2.4 and run as well. Now I want to update these pods from 1.2.4 to 1.3.7, how can i do? i meet some questions when upgrading 2 pods from 1.2.4 to 1.3.7 and then close 2 pods with 1.3.7 . The left 16 pods with 1.2.4 works well, but some Partition become unhealthy. So, does the zeebe supports online upgrade from 1.2.x to 1.3.x?

**Comment by jerry123888** [comment] 2023-03-22 10:41
@korthout

**Comment by korthout** [comment] 2023-03-22 10:50
@jerry123888 Please don't open new issues to continue an existing conversation elsewhere.

Closing this as duplicate of https://github.com/camunda/zeebe/issues/12058

**Closed by korthout** 2023-03-22 10:50 UTC
Labels: kind/toil
