### ISSUE TITLE
ZeebeWorker request ActivatedJob in zeebe but get no response 

### ISSUE THREAD

**Issue by jerry123888** [camunda/zeebe#9221] opened 2022-04-24 01:08 UTC
**Describe the bug**

Ramdomly and not often, a worker requesting ActivateJobs on Zeebe get an empty answer, but the job is activated in Zeebe so it will never be done.
I mentioned this bug in https://github.com/camunda/zeebe/issues/8759 and found it has been resolved in zeebe-1.3.6:https://github.com/camunda/zeebe/issues?q=label%3Arelease%2F1.3.6+is%3Aclosed。
@npepinpe @romansmirnov 

![image](https://user-images.githubusercontent.com/92800459/164953195-38982651-5763-462d-9980-94accc766df3.png)

Unfortunately  it also appears in this version. In-depth analysis of the solution to this problem, i guess this 1.3.6 just resolves the  issue about  "When the broker activates jobs and before sending them back to the gateway, the gateway potentially could close its connection (e.g., the request timed out, network interruption, gateway died, etc.)"， this bug fix maybe make sense.
But so i know, the parameter named "zeebe.client.request-timeout" which can affect the performance between the job worker client and zeebe-gateway may led to  the before mentioned issue. 
After a quickly code review, i found the code for zeebe-client-java has no changed from 1.3.5 to 1.3.6.
So I think the 1.3.6 can not  solve the problem when the job worker client miss the activated job in condition of it fails to receive the activated job and the gateway has received the activated job from the zeebe broker.

Looking forward to your reply. 

**To Reproduce**

![image](https://user-images.githubusercontent.com/92800459/164951367-b2697e72-0f26-4a3e-86fc-935ccb3dbd37.png)

1.deploy the BPMN process
![image](https://user-images.githubusercontent.com/92800459/164960106-80445c93-8acd-49b4-9301-cbee541f00a8.png)

2.create instance constantly by different QPS

**Expected behavior**
no job miss execution.

**Environment:**
zeebe 1.3.7
java-client sdk

PARTITIONSCOUNT=54
BROKER_CLUSTER_CLUSTERSIZE=18
request_time_out=10s

**Comment by Young200808** [comment] 2022-04-25 08:52
cloud anyone has a look at this issue? @npepinpe @romansmirnov

**Comment by romansmirnov** [comment] 2022-04-26 11:59
@Young200808,

Thanks for bringing up this issue! 

To ensure that we have the same understanding, as a first step, let me explain which situations are covered with the implementation of #3631. Typically, there are three parties involved when trying to activate jobs:

1. Zeebe Client
2. Gateway
3. Zeebe Broker

In the Zeebe Client, a user can start job workers who will steadily send requests to the Gateway to activate jobs for given job types. The Gateway handles a job activate request by sending another request to the Zeebe Broker to eventually activate jobs. The Gateway acts as a mediator between the Zeebe Client and Zeebe Broker, i.e., it receives a request from the Zeebe Client and sends a request in the name of the Zeebe Client to the Zeebe Broker:

1. The Zeebe Client sends a request `x` to activate jobs to the Gateway.
2. The Gateway receives request `x`.
3. In the context of the request `x`, the Gateway sends a request `y` to the Zeebe Broker (to activate jobs).
4. The Zeebe Broker receives request `y`.
5. The Zeebe Broker handles request `y` by activating jobs and sending a response back to the Gateway.
6. The Gateway receives the response from the Zeebe Broker, which completes the request `y`.
7. The Gateway forwards that response (containing the activated jobs) to the Zeebe Client, which completes the request `x`.

With this communication pattern, it might happen before executing step 7- the Zeebe Client's request `x` times out (or gets closed, or even the Zeebe Client crashes, etc.) so that the Gateway cannot forward the Broker's response back to the Zeebe Client.

With the implementation of #3631, the Gateway recognizes such situations (i.e., the Client's request timed out, or is not available anymore, etc.) and makes the job re-activatable. This implementation didn't require any changes in the Zeebe Client.

Now, my assumptions are that you are observing one of the following issues:

1. There are other situations that are not covered yet by the Gateway.
2. The Gateway request `y` times out before the Zeebe Broker can send back a response; see #8917.
3. There is another (unknown) issue that prevents the Zeebe Client from receiving the activated jobs.

To better understand and potentially reproduce the issue locally, can you please share more details on your setup?

1. Please share the BPMN Process Model (i.e., the `*.bpmn` file)
2. Can you please share the Zeebe Client configuration? (Depending on how the Client is bootstrapped, the `application.yaml` or the source code that configures and starts the Client)
3. Is the Gateway deployed separately as a Standalone Gateway? Or is the Gateway deployed along with the Zeebe Broker as an Embedded Gateway?
4. Can you please share the entire Zeebe Broker configuration?
5. How many instances are started constantly?
6. When do you start observing the issue? Immediately after starting the test run?

Thanks,
Roman

**Comment by romansmirnov** [comment] 2022-04-26 12:06
In addition, can you please share the log files from the Zeebe Client, Gateway, and Zeebe Broker?

**Comment by jerry123888** [comment] 2022-04-26 16:43
> * Please share the BPMN Process Model (i.e., the `*.bpmn` file)
> * Can you please share the Zeebe Client configuration? (Depending on how the Client is bootstrapped, the `application.yaml` or the source code that configures and starts the Client)
> * Is the Gateway deployed separately as a Standalone Gateway? Or is the Gateway deployed along with the Zeebe Broker as an Embedded Gateway?
> * Can you please share the entire Zeebe Broker configuration?
> * How many instances are started constantly?
> * When do you start observing the issue? Immediately after starting the test run?

Thank you very much for your quick reply. The three parties involved when trying to activate jobs you mentioned above is the same as my understanding, it is no question. And i finally understand  that the implementation of https://github.com/camunda/zeebe/issues/3631 is exactly the solution to the problem I mentioned the first time. But... as you said, the 1.3.7 cannot solve this scenario ——“The Gateway request y times out before the Zeebe Broker can send back a response”? Emm...the value in my test is 15s which i  think it is not is short.
If it is,  increasing the timeout  between gate and broker will make sense to avoid the job worker missing  the activated jobs?

And let me answer the above questions:
**Q:** Please share the BPMN Process Model (i.e., the *.bpmn file)
**A:** https://github.com/jerry123888/zeebe-test

**Q:** Can you please share the Zeebe Client configuration? (Depending on how the Client is bootstrapped, the application.yaml or the source code that configures and starts the Client)
**A:** the main code about client:
![image](https://user-images.githubusercontent.com/92800459/165346292-fcc96e3d-647c-4e65-9ca1-b7139161ce39.png)
the main Zeebe Client configuration:
zeebe.client.job.timeout: 900d
zeebe.client.request-timeout: 10s
zeebe.client.worker.threads: 2
zeebe.client.worker.max-jobs-active: 32

**Q:** Is the Gateway deployed separately as a Standalone Gateway? Or is the Gateway deployed along with the Zeebe Broker as an Embedded Gateway?
**A:**  The Gateway deployed separately as a Standalone Gateway.

**Q:** Can you please share the entire Zeebe Broker configuration?
**A:**the main Zeebe Broker configuration:
ZEEBE_STANDALONE_GATEWAY=false
ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=54
ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=18
ZEEBE_BROKER_GATEWAY_NETWORK_HOST=0.0.0.0
ZEEBE_BROKER_BACKPRESSURE_VEGAS_INITIALLIMIT=500
ZEEBE_BROKER_BACKPRESSURE_VEGAS_BETA=14
ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_PRODUCER_SERVERS=x.x.x.x:9092
ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=x.x.x.x:26502
ZEEBE_BROKER_BACKPRESSURE_VEGAS_ALPHA=7

**Q:** How many instances are started constantly?
**A:** It is ramdomly. By different qps for creating instance, for example, i create totally 100 instances, each instance has 30 jobs, so i expect there are 100*30=3000 jobs will be finished in the end, but someone jobs will standing always running state ramdomly in fact.
 
**Q:** When do you start observing the issue? Immediately after starting the test run?
**A:** About half a year ago，and this issue has always existed. After update my zeebe from 1.2.4 to 1.3.7, doing this test  proves that this problem still exists.

**Comment by romansmirnov** [comment] 2022-04-28 09:41
@Young200808,

Thanks for your reply; it is very helpful.

> But... as you said, the 1.3.7 cannot solve this scenario ——“The Gateway request y times out before the Zeebe Broker can send back a response”? Emm...the value in my test is 15s which i think it is not short.
> If it is, increasing the timeout between gate and broker will make sense to avoid the job worker missing the activated jobs?

By default, the timeout for requests between the gateway and the broker is set to 15s. And yes, I would agree that this is not that short. But, I would not recommend increasing that request timeout property, as we don't know if the timeout is too short yet. Also, the question would be: Why does the broker need more than 15s to process the request/command?

Based on that and what you shared, let's work with this assumption to prove: The request to activate jobs between the gateway and the broker times out after 15s, causing the broker to not be able to send the response to the broker. So that the activated jobs remain activated in the broker.

Typically, when the broker cannot process a request/command within this request timeout, the processing queue size is too big. Or in other words, the broker receives more requests than it can handle. I can see from the shared configuration that the backpressure settings have been adjusted (for example, the initial limit is set to 500). 

Another thought I have is that the broker reached a state with a huge backlog of active process instances and jobs. That backlog might cause a degradation in the processing time. But this is just a thought I have because from the shared information, I don't know how the client is scaled.

However, let's go through it step-by-step: With the assumption above (i.e., the request between the broker and gateway times out after 15s), the Gateway's logs should contain a warning saying that it failed to activate jobs because the request timed out:

https://github.com/camunda/zeebe/blob/2f4d8c859cfde20f7d203fea9141f6ed9ccfd305/gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/RoundRobinActivateJobsHandler.java#L257-L260

Based on that, could you please share the Gateway logs?

Thanks,
Roman

**Comment by romansmirnov** [comment] 2022-05-02 07:18
@Young200808 and @jerry123888, just wanted to reach out to see if you have any questions regarding my last https://github.com/camunda/zeebe/issues/9221#issuecomment-1111983424?

**Comment by jerry123888** [comment] 2022-05-02 10:01
> @Young200808 and @jerry123888, just wanted to reach out to see if you have any questions regarding my last [#9221 (comment)](https://github.com/camunda/zeebe/issues/9221#issuecomment-1111983424)?

Yeah, thanks for your comments. And i have already edited some settings about gateway and set up another test environment,  I will share the gateway logs for you.

**Comment by jerry123888** [comment] 2022-05-02 12:40
@romansmirnov  To get the more detail log for the gateway, I have finished another test, the environment is the same as the above test i mentioned except that i changed the value of "ZEEBE_LOG_LEVEL" from "info" to "trace".
I created totally 80010 instances in 200 seconds, each instance has 30 jobs, so i expect there are 80010  log records  about "testzeebefor137:job1 is end" which means the first job is finished successfully, and there are also 80010 log records about "testzeebefor137:job30 is end". in fact I really get 80010 log records which means the first job has  completed 80010 times, but there are only 79987 log records which means the last job in the instance has completed. The result like this:
![image](https://user-images.githubusercontent.com/92800459/166234651-a022909c-75ae-4491-a332-288dba0b2824.png)
However,  the Gateway's logs does not contain a warning saying that it failed to activate jobs because the request timed out.
The gateway log is here: https://github.com/jerry123888/zeebe-test/blob/main/zeebe-test-gateway-log.zip

**Comment by jerry123888** [comment] 2022-05-06 06:21
@romansmirnov  Do you  have any questions after reading  my last  comments, and could you reproduce this issue?

**Comment by romansmirnov** [comment] 2022-05-06 08:41
@jerry123888,

Sorry for not being responsive this week; it's a busy one.

> ...  and could you reproduce this issue?

So far, I am not able to reproduce the issue.

> Do you have any questions after reading my last comments...

I went through the shared logs, and as you already mentioned, I couldn't find any occurrence of the log statement:

> "Failed to activate jobs for type..."

Based on that data point, we can say that requests to activate jobs between gateway and broker do not timeout. But, I would even go further and say that the issue you are observing is not related to the usage of the `LongPolling` feature. Why do I think so? Whenever the Zeebe Broker creates a new job, it notifies the gateway about it. That's the reason, why we see in the Gateway's log a lot of these log statements:

> Received jobs available notification for type ...

Counting the occurrences of this log statement by job type, we can see that starting with job type `public-service-zeebe-pressure-execute.IvanyeTestPoll7` a gap between the expected number of jobs and the actual number of created jobs:

```
$ grep -Fr 'Received jobs available notification for type public-service-zeebe-pressure-execute.IvanyeTestPoll7.' zeebe-2022-05-02-*.log | wc -l
79998
```
Basically, for the job types `...IvanyeTestPoll1` to `...IvanyeTestPoll6`, we can see the expected number of 80,010. Starting with the job type `...IvanyeTestPoll7` up to `...IvanyeTestPoll30`, we can see a gap there growing up to 23 "missing" jobs.

With that, I can conclude, for example, the "missing" 23 jobs of job type `...IvanyeTestPoll30` never have been created, because the respective process instances haven't reached that service task yet. That's the reason, why the client didn't receive them so far. This applies to the job types `...IvanyeTestPoll7` up to `...IvanyeTestPoll30`.

Looking at the client configuration, I think, this is a potential bottleneck (with the assumption that there is only one client running and not being scaled):
* Per job type, the client will activate 32 jobs at maximum. That means, at some point, it potentially activated 960 (= 32 * 30).
* There are only 2 threads available. So, at the very same moment, the client handles only 2 jobs.
* When handling a job, it blocks the thread for a random amount of time.

Now doing some math, I think, it can take quite some time until the client completed all 2,400,300 jobs (= 30 * 80,010) - of course, the 2.4m jobs are not created at the same time.

That's why as a next step, let's check the client logs:
1. Could you please share the client logs for the same period of time as the gateway logs?
2. Could you please confirm my understanding of the client configuration? Especially, if the client is somehow scaled?
3. In addition, could you please share the Broker's logs for the same period?

Best,
Roman

**Comment by romansmirnov** [comment] 2022-05-06 09:17
Comment on this:

> But, I would even go further and say that the issue you are observing is not related to the usage of the `LongPolling` feature. 

Just for understanding, I don't exclude this completely from the ongoing investigation. But so far, there is no clear indication that there is an issue with `LongPolling`. To narrow it further down, we would need to understand what happened with the jobs of type `...IvanyeTestPoll30`: Did the client receive 80,010 jobs of type `...IvanyeTestPoll30`?
* If that's the case, then Broker hasn't processed the corresponding completion commands yet.
* If that's not the case, then I would expect the client received only 80,000 of those jobs.

Let's see 😄 That's why the client and broker logs would be very interesting to get.

**Comment by jerry123888** [comment] 2022-05-06 13:56
I have finished the test and reproduced this issue. 
I created totally 80000 instances in 200 seconds, each instance has 30 jobs, so i expect there are 80000 log records about "testzeebefor137:job1 is end" which means the first job is finished successfully, and there are also 80000 log records about "testzeebefor137:job30 is end".
 In fact I really get 80000 log records which means the first job has completed 80000 times, but there are only 79995 log records which means the last job in the instance has completed. The result like this:
![image](https://user-images.githubusercontent.com/92800459/167138025-8cb22d92-a03a-4f0b-b6f8-d4b57680e887.png)

In your last comments, you think  my client  is a potential bottleneck:
1) Per job type, the client will activate 32 jobs at maximum. That means, at some point, it potentially activated 960 (= 32 * 30).
2) There are only 2 threads available. So, at the very same moment, the client handles only 2 jobs.
3) When handling a job, it blocks the thread for a random amount of time.
Yes, i think what you said is right, but these bottlenecks just lead to an increase in time consuming and cannot led to miss job. It is right?

I upload the gateway and client log, and aslo upload my test source code to help you reproduce this issue.
https://github.com/jerry123888/zeebe-test/blob/main/test_on_20220506_part1.zip
https://github.com/jerry123888/zeebe-test/blob/main/test_on_20220506_part2.zip
https://github.com/jerry123888/zeebe-test/blob/main/test_on_20220506_part3.zip

**Comment by jerry123888** [comment] 2022-05-11 03:46
@romansmirnov  
Another question, I found the log marked "Failed to activate jobs for type ... from partition  ..."  in gateway, but no miss job in client. is it reasonable ?

**Comment by romansmirnov** [comment] 2022-05-11 07:08
@jerry123888, can you please share the logs, therefore?

**Comment by jerry123888** [comment] 2022-05-11 12:08
> @jerry123888, can you please share the logs, therefore?

@romansmirnov 
zeebe-gateway-log:
https://github.com/jerry123888/zeebe-test/blob/main/gw-log-1.rar
https://github.com/jerry123888/zeebe-test/blob/main/gw-log-2.rar
https://github.com/jerry123888/zeebe-test/blob/main/gw-log-3rar
https://github.com/jerry123888/zeebe-test/blob/main/gw-log-4rar
https://github.com/jerry123888/zeebe-test/blob/main/gw-log-5.rar

client-info-log:
https://github.com/jerry123888/zeebe-test/blob/main/client_info.log.gz

client-trace-log:
https://github.com/jerry123888/zeebe-test/blob/main/client_trace.log.gz

Please let me know if you have any questions about this.

**Comment by romansmirnov** [comment] 2022-05-11 14:36
@jerry123888,

The log statement `Failed to activate jobs for type...` is caused by by a connection failure:
```
2022-05-11 02:35:06.521 [ActivateJobsHandler] [gateway-scheduler-zb-actors-0] WARN 
      io.camunda.zeebe.gateway - Failed to activate jobs for type public-service-zeebe-pressure-execute.IvanyeTestPoll19 from partition 10
java.net.ConnectException: Failed to connect channel for address 30.46.151.81:26501
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$bootstrapClient$35(NettyMessagingService.java:685) ~[zeebe-atomix-cluster-1.3.7.jar:1.3.7]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:674) ~[netty-transport-classes-epoll-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:693) ~[netty-transport-classes-epoll-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[netty-transport-classes-epoll-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) ~[netty-transport-classes-epoll-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-classes-epoll-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

But there are no request timeouts between gateway and broker:
```
$ grep -rF 'Request timed out after' zeebe-2022-05-11-*.log | wc -l
0
```

And yes, I can see that there are no jobs are missing in this test run:
```
$ grep -rF 'Received jobs available notification for type public-service-zeebe-pressure-execute.IvanyeTestPoll30.' zeebe-2022-05-11-*.log | wc -l
80000
```

My questions would be:
1. Now, what changed in your setup so that there are no missing jobs anymore?
2. Do you still have the data available from the test run shared with this https://github.com/camunda/zeebe/issues/9221#issuecomment-1119650713? If so, can you please share the data of partition 4 from the broker? Typically, you will find a data folder in `$PATH_TO_ZEEBE/data/raft-partition/partitions/`.

Thanks,
Roman

**Comment by jerry123888** [comment] 2022-05-11 15:06
@romansmirnov 
Thanks for your quickly reply and I have some questions about what you said，please allow me to list a question:
The log statement Failed to activate jobs for type... is caused by a connection failure (which gets resolved after a while): this log appears in my gateway but not missing jobs, this performance is not related to this issue:https://github.com/camunda/zeebe/issues/8917? it just due to a connection failure,and it will be ok automatically？

**Q:** Now, what changed in your setup so that there are no missing jobs anymore?
**A:** I just reduce the number of zeebe-gateway from 3 to 1 which i think this phenomenon has nothing to do with it. So i will take more tests to see if it happens again.

**Q:**Do you still have the data available from the test run shared with this https://github.com/camunda/zeebe/issues/9221#issuecomment-1119650713? If so, can you please share the data of partition 4 from the broker? Typically, you will find a data folder in $PATH_TO_ZEEBE/data/raft-partition/partitions/.
**A:** I am sorry to miss that, and will try to reproduce the issue as best I can. If it reproduce, i will share you the data what you want to get.

Thanks.I appreciate your help.

**Comment by jerry123888** [comment] 2022-05-18 16:19
@npepinpe  If the timeout between client and gateway is smaller than the timeout between gateway and broker, what will happen? Maybe this situation can also lead to missing jobs.

**Comment by jerry123888** [comment] 2022-05-23 12:56
@romansmirnov  
In my old test, the timeout between client and gateway is smaller than the timeout between gateway and broker, and  it was easy to reproduce this issue. And now I change it, use the default settings about zeebe-1.3.7, I didn't  edit any timeout value.
But... after run about 400000 instances which including  12000000 jobs, the performance about missing jobs also appear like the below:
![image](https://user-images.githubusercontent.com/92800459/169820361-9b63a765-873b-4569-8cf8-03b4c4c43424.png)
After investigating , I found the the first missing job is in the partition 3. I have uploaded the data  of partition 3 from the broker:https://github.com/jerry123888/zeebe-test/blob/main/test_on_20220523/partition_3.tar.gz.
client log:https://github.com/jerry123888/zeebe-test/blob/main/test_on_20220523/client_info.log.gz
![image](https://user-images.githubusercontent.com/92800459/169820675-fe10b509-476e-4df8-9fe9-fbfc58f83490.png)

Please let me know if you have any questions about this. Looking forward to your reply
Best,
Jerry

**Comment by jerry123888** [comment] 2022-05-24 02:57
> 

In addition,in this test, just like the first missing job:job15, I find its log like this:
![image](https://user-images.githubusercontent.com/92800459/169937688-4d591a2f-56e6-49df-a490-d3b3b51ccf28.png)
You can see this job has not been sent to client from gateway:
![image](https://user-images.githubusercontent.com/92800459/169938020-e5a485f8-f876-46eb-bfe6-e8363849dc24.png)
![image](https://user-images.githubusercontent.com/92800459/169938060-9a4e4bc3-2ccf-4542-9719-eab6550889cb.png)
but from the above code, it will do "reactivateJobs" which you added  in the  version-1.3.6:
![image](https://user-images.githubusercontent.com/92800459/169938634-11309bd9-55fb-4b0c-bb27-5df9d0208fab.png)
from the zeebe-gateway's log, i didn't find these comments about "Failed to reactivate job xx due to xx", so it means that the above missing job:job15 should be reactivated successfully？ I think it is, but I didn't find it actually.

**Comment by Young200808** [comment] 2022-05-24 06:10
@romansmirnov
hi, our production environment are suffer from this issue for a long time ,could you put high priority on reproducing this issue and fix it?

**Comment by Young200808** [comment] 2022-07-25 08:52
any progress could update? @npepinpe @romansmirnov

**Comment by romansmirnov** [comment] 2022-08-09 12:20
Hi @jerry123888,

I apologize for not being responsive in the last months. Honestly, after being off for some time, I forgot to track this issue afterward. Sorry, therefore.

Of course, we want to understand what is causing the issue, and we are much thankful for reproducing and sharing the relevant data!

Regarding your [first comment](https://github.com/camunda/zeebe/issues/9221#issuecomment-1134642761) and [second comment](https://github.com/camunda/zeebe/issues/9221#issuecomment-1135345769):

Checking the provided data, the gateway actually behaves as expected. As pointed out by you, the gateway fails to send the activated jobs back to the client, and sends a request to the corresponding partition to make the job re-activatable. However, because the BPMN process under test declares the number of `retries` with `0`, the broker creates an incident and marks the job as failed. In that case, the job cannot be retried unless the incident gets resolved. This is expected behavior.

For reference
* The specified number of retries in the BPMN process model under test:
![Number of Retries in BPMN process model](https://user-images.githubusercontent.com/2368139/183643727-596100e1-d821-48ca-a4b4-56354f7c35a2.png)
* The incident referencing the job with key `6755399493052444`:
```
{
  "bpmnProcessId": "ProcessDemoTwo",
  "processDefinitionKey": 2251799819509038,
  "processInstanceKey": 6755399493051786,
  "elementInstanceKey": 6755399493052443,
  "elementId": "Activity_1nry6bp",
  "jobKey": 6755399493052444,
  "variablesScopeKey": 6755399493052443,
  "errorType": "JOB_NO_RETRIES",
  "errorMessage": "Failed to send activated jobs to client"
}
```
* [Documentation](https://docs.camunda.io/docs/components/concepts/incidents/) about incidents.

As a next step, could you please adjust your BPMN process model under test and change the number of retries to `1`, and run the test once again? 

Best,
Roman

**Comment by romansmirnov** [comment] 2022-08-09 12:30
> @romansmirnov If the timeout between client and gateway is smaller than the timeout between gateway and broker, what will happen? Maybe this situation can also lead to missing jobs?

In that case, the gateway would fail to send back the activated jobs to the client because the request got already closed. Thus, the gateway would send the broker a request to make the jobs re-activatable.

**Comment by jerry123888** [comment] 2022-08-09 13:00
Thanks for your reply.And I will change the number of retries to 1 and run the test again.

**Comment by romansmirnov** [comment] 2022-08-15 07:14
@jerry123888, did you already have the chance to run the test with the adjusted number of retries?

**Comment by jerry123888** [comment] 2022-08-15 13:02
> @jerry123888, did you already have the chance to run the test with the adjusted number of retries?

Yes, I have finished a test with the adjusted number of retries, but still appears missing jobs.
Just like the jobid=105834591320304216. And i put the data about broker on :https://github.com/jerry123888/zeebe-test/blob/main/47.tar.gz.

**Comment by romansmirnov** [comment] 2022-08-15 14:23
@jerry123888,

Apparently, the number of retries is still set to `0` (and not `1`), resulting in the same behavior as explained above. For reference, please check the following file, which shows the last deployed version of the process `ProcessDemoTwo`: [47-process.txt](https://github.com/camunda/zeebe/files/9337743/47-process.txt)

As a next step, please do the following:
1. For each service task, please change the number of retries from `0` to `1`:
![image](https://user-images.githubusercontent.com/2368139/184653535-1cf8d94f-f379-4ceb-996f-6ce8c622b4af.png)
2. Ensure that the new version of the BPMN process model gets deployed successfully
3. Start the test run once again

Thanks,
Roman

**Comment by jerry123888** [comment] 2022-08-16 02:01
> @jerry123888,
> 
> Apparently, the number of retries is still set to `0` (and not `1`), resulting in the same behavior as explained above. For reference, please check the following file, which shows the last deployed version of the process `ProcessDemoTwo`: [47-process.txt](https://github.com/camunda/zeebe/files/9337743/47-process.txt)
> 
> As a next step, please do the following:
> 
> 1. For each service task, please change the number of retries from `0` to `1`:
>    ![image](https://user-images.githubusercontent.com/2368139/184653535-1cf8d94f-f379-4ceb-996f-6ce8c622b4af.png)
> 2. Ensure that the new version of the BPMN process model gets deployed successfully
> 3. Start the test run once again
> 
> Thanks, Roman

Oh...Sorry  I know the reason why I also get the same error, the new bpmn process which  has adjusted number of retries was deployed successfully, but the test process used the before process id. 
I will start the test again. Thanks

**Comment by jerry123888** [comment] 2022-08-16 03:55
@romansmirnov 
Can I make sure the client has missed jobs  depend on the error message about "Failed to send activated jobs to client"?
Just  only this performance can led to that error message?
Because I want to determine to do retry or not , depend on if my code can match the above error message or not. Does is it right?

**Comment by romansmirnov** [comment] 2022-08-16 08:06
@jerry123888,

> Oh...Sorry I know the reason why I also get the same error, the new bpmn process which has adjusted number of retries was deployed successfully, but the test process used the before process id.
> I will start the test again. Thanks

Great. Please let me know what the result of the test is.

> Can I make sure the client has missed jobs depend on the error message about "Failed to send activated jobs to client"?
> Just only this performance can led to that error message?
> Because I want to determine to do retry or not , depend on if my code can match the above error message or not. Does is it right?

Not sure if I understand it completely. Can you please elaborate on why you want to match the error message in your client? Can you please explain the use case behind it?

Thanks,
Roman

**Comment by jerry123888** [comment] 2022-08-16 14:23
> @jerry123888,
> 
> > Oh...Sorry I know the reason why I also get the same error, the new bpmn process which has adjusted number of retries was deployed successfully, but the test process used the before process id.
> > I will start the test again. Thanks
> 
> Great. Please let me know what the result of the test is.
> 
> > Can I make sure the client has missed jobs depend on the error message about "Failed to send activated jobs to client"?
> > Just only this performance can led to that error message?
> > Because I want to determine to do retry or not , depend on if my code can match the above error message or not. Does is it right?
> 
> Not sure if I understand it completely. Can you please elaborate on why you want to match the error message in your client? Can you please explain the use case behind it?
> 
> Thanks, Roman

Thanks for your help, and  I am very happy to tell you the test result matches expectations. 
And the reason why I need to match the error message in my client is that I only want to the process retry in this situation about missing jobs, when the others incident  appears, I want to the process stop, it is no necessary to do retry in my production environment.
So...I need to check the error message from the zeebe when the broker make an incident , if it  is equals to "Failed to send activated jobs to client",  I need to change the value of retry from 0 to 1 for this situation in my code.

Besides, I find the code about 'Failed to send activated jobs to client' in zeebe gateway  is just useful for this scene about missing jobs.So I think the above solution will make sense. Is it right?

**Comment by romansmirnov** [comment] 2022-08-17 08:39
> And the reason why I need to match the error message in my client is that I only want to the process retry in this situation about missing jobs, when the others incident appears, I want to the process stop, it is no necessary to do retry in my production environment.
> So...I need to check the error message from the zeebe when the broker make an incident , if it is equals to "Failed to send activated jobs to client", I need to change the value of retry from 0 to 1 for this situation in my code.
> 
> Besides, I find the code about 'Failed to send activated jobs to client' in zeebe gateway is just useful for this scene about missing jobs.So I think the above solution will make sense. Is it right?

Thanks for explaining the use case! Yeah, it is a way of distinguishing the cases. Just for awareness, this approach has some drawbacks:
1. If a worker lets a job fail with the same type of error message (for whatever reason), then it wouldn't be possible to distinguish it from the situation when the gateway cannot send back the jobs.
2. The Gateway's error message might change in the future - although there is no plan currently to change it. This would require adjusting the client's code.

In general, I recommend implementing the workers' code idempotent that allows the code to be executed more than once for the same job, all while preserving the expected application state. For further details, please have a look at the [documention](https://docs.camunda.io/docs/next/components/concepts/job-workers/#timeouts). That way, it wouldn't be necessary to decide based on the job's error message if the job can be retried or not.

> Thanks for your help, and I am very happy to tell you the test result matches expectations.

Happy to hear that it finally behaves as expected. Hereby I am closing this issue. If you have any further questions, please please use our [forum](https://forum.camunda.io/).

Best,
Roman

**Closed by romansmirnov** 2022-08-17 08:39 UTC
Labels: kind/bug, scope/broker, blocker/info, severity/mid, scope/gateway

**Comment by jerry123888** [comment] 2022-08-17 09:26
> 

Yeah, but this method about https://docs.camunda.io/docs/next/components/concepts/job-workers/#timeouts make "at least once", but it  maybe take some time ,can not make a response to the missing job quickly .

**Comment by jerry123888** [comment] 2022-08-17 10:03
@romansmirnov  
Another question, if the value of job's reties is 3, and when the gateway failed to send activated jobs to client, it will reactivate this job by the reason of the value of retires bigger than zero, after reactivate the job successfully or not ,does this value of retries reduce  3 to 2? If it is, this feature avoid missing job will make impact on the user's retry value.

**Comment by lethe3000** [comment] 2022-08-29 03:50
> after reactivate the job successfully or not ,does this value of retries reduce 3 to 2

I think you should fail job with retries count - 1

`client.NewFailJobCommand().JobKey(job.GetKey()).Retries(job.Retries - 1).ErrorMessage(errorInfo).Send(ctx)`

**Comment by romansmirnov** [comment] 2022-08-30 08:16
@jerry123888,

No, the job retries are not changed when making the job re-activatable. When the number of retries is 3, then it will remain 3 and does not decrement it to 2.

**Comment by jerry123888** [comment] 2022-09-02 10:43
> @jerry123888,
> 
> No, the job retries are not changed when making the job re-activatable. When the number of retries is 3, then it will remain 3 and does not decrement it to 2.

OK. Thanks. I see
