### ISSUE TITLE
Module Integration Tests `s3.BackupUploadIT.shouldSaveBackupWithManyFiles` failed

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/zeebe#18185] opened 2024-05-02 13:47 UTC
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? 2 times.
- Does it block your work? Yes, couldn't merge into `main` branch.
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

From [merge queue run](https://github.com/camunda/zeebe/actions/runs/8924196237/job/24510026445#step:12:117) in `[IT] Module Integration Tests`
<details><summary>Logs</summary>
<pre>

+ flakyTests=' io.camunda.zeebe.backup.s3.BackupUploadIT.shouldSaveBackupWithManyFiles'
+ echo 'FLAKY_TESTS<<EOF'
+ echo io.camunda.zeebe.backup.s3.BackupUploadIT.shouldSaveBackupWithManyFiles
+ echo EOF
+ echo '::error::Found flaky tests!\n  io.camunda.zeebe.backup.s3.BackupUploadIT.shouldSaveBackupWithManyFiles'
Error: Found flaky tests!\n  io.camunda.zeebe.backup.s3.BackupUploadIT.shouldSaveBackupWithManyFiles

</pre>
</pre>
</details>

**Comment by rodrigo-lourenco-lopes** [comment] 2024-05-02 14:12
Hey @ralfpuchert  this seems to be a duplicate of https://github.com/camunda/zeebe/issues/18177

**Comment by megglos** [comment] 2024-05-02 14:30
it is, closing and linking this as another occurence

**Closed by megglos** 2024-05-02 14:30 UTC
Labels: kind/flake, component/zeebe
