### ISSUE TITLE
BPMN Parsing should ignore third-party namespaces

### ISSUE THREAD

**Issue by berndruecker** [camunda/zeebe#9438] opened 2022-05-23 08:28 UTC
**Is your feature request related to a problem? Please describe.**

Some other BPMN tools (e.g. Signavio) add extension attributes to a BPMN model, which should be kept (e.g. for roundtrips or the like). This is a valid use case with BPMN.

Zeebe throws an exception when it sees attributes it does not understand.

**Describe the solution you'd like**

Zeebe should ignore those attributes (like C7 did if I am not completely mistaken). 

**Additional context**

https://forum.camunda.io/t/could-zeebe-ignore-extension-tags-from-other-vendors/37752

**Comment by menski** [comment] 2022-07-22 11:53
Closing as duplicate of https://github.com/camunda/zeebe/issues/4817

**Closed by menski** 2022-07-22 11:53 UTC
Labels: kind/feature
