### ISSUE TITLE
"RuntimeException: Actor is closed" during shutdown

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#9176] opened 2022-04-20 07:16 UTC
**Describe the bug**

Following error occured while broker shutdown.

```
"Unexpected error on retrieving write buffer for partition 3"
java.lang.RuntimeException: Actor is closed
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.newLogStreamWriter(LogStreamImpl.java:193) ~[zeebe-logstreams-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.newLogStreamRecordWriter(LogStreamImpl.java:181) ~[zeebe-logstreams-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.broker.engine.impl.SubscriptionApiCommandMessageHandlerService.lambda$onBecomingLeader$2(SubscriptionApiCommandMessageHandlerService.java:73) ~[zeebe-broker-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-8.0.0.jar:8.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.0.jar:8.0.0]

```

Partition 3 was closing, but the listener for the leader role was invoked after the partition has closed.

```
2022-04-20T02:34:23.418669526Z 3 Transition to LEADER on term 23 requested.
2022-04-20T02:34:23.508886146Z 3 Transition to LEADER on term 23 starting
2022-04-20T02:34:23.514218096Z 3 Transition to LEADER on term 23 - transitioning LogStream
2022-04-20T02:34:23.608445293Z 3 Closing ZeebePartition 3
2022-04-20T02:34:24.418542718Z 3 Cancelling transition to LEADER on term 23
2022-04-20T02:34:24.517937850Z 3 Transition to INACTIVE on term 0 - transitioning LogStream
2022-04-20T02:34:24.608041829Z 3 Shutdown was called with context: io.camunda.zeebe.broker.system.partitions.PartitionStartupAndTransitionContextImpl@13aefebc
2022-04-20T02:34:24.613224169Z  Unexpected error on retrieving write buffer for partition 3

```

**Expected behavior**

* No exceptions while closing.
* The listener should not have been called as transitioning to leader role was cancelled.

**Log/Stacktrace**
[logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-04-20T02:34:24.707142540Z;pinnedLogId=2022-04-20T02:34:24.613224169Z%2Fxo9vfz3bppqrr2yr;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.namespace_name%3D%223294cf87-de74-4f56-bd89-e3f2af8424b6-zeebe%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Atimestamp%3D%222022-04-20T02:34:24.613224169Z%22%0AinsertId%3D%22xo9vfz3bppqrr2yr%22;summaryFields=jsonPayload%252Fcontext%252FpartitionId:false:32:beginning:false;timeRange=2022-04-20T02:04:54.613Z%2F2022-04-20T03:04:54.613Z?project=camunda-cloud-240911)

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

**Comment by npepinpe** [comment] 2022-04-26 07:43
Impact is considered minimal because we were shutting down, so this is mostly noise. Let's leave it in the backlog for now.

**Comment by oleschoenburg** [comment] 2023-08-02 07:15
I think this was a duplicate of https://github.com/camunda/zeebe/issues/13471, closing for now.

**Closed by oleschoenburg** 2023-08-02 07:15 UTC
Labels: kind/bug, scope/broker, severity/low, area/observability, component/partition-transitions
