### ISSUE TITLE
Bloated `DEADLINE_JOBS` column family; no way to recover

### ISSUE THREAD

**Issue by domq** [camunda/zeebe#8949] opened 2022-03-21 16:53 UTC
**Describe the bug**

In circumstances very similar to https://github.com/camunda-cloud/zeebe/issues/5925, a faulty client somehow caused tens of thousands of entries to be created inside the `DEADLINE_JOBS` column family. Under the current state of things, these entries cannot go away. Worse, they cause the JobTimeOutProcessor to overflow the available log space every time it runs, which results in only a fraction of the job time-outs actually being taken into account. The remaining jobs become “stuck,” i.e. they never get repeated to workers again.

**To Reproduce**

The [faulty client story](https://github.com/camunda/zeebe/issues/5925#issuecomment-796880239) is my best guess (i.e. we increased the client buffer size, and the runaway growth in the DEADLINE_JOBS table stopped). I'm therefore not sure about reproduction steps, however our RocksDB dumps are available on demand. Kindly send private email directly to dominique.quatravaux@epfl.ch.

**Expected behavior**

There should exist some kind of automated, or perhaps operator-initiated cleanup procedure, so that the `DEADLINE_JOBS` column family may be either shrunk over time, or better, resynced wholesale to the ground truth in `JOBS`. (I was thinking, perhaps naïvely, that we could take advantage of the snapshot rollover time to just empty the `DEADLINE_JOBS` column family, and reconstruct it from `JOBS`?)

**Log/Stacktrace**

A build of Zeebe from our [work branch](https://github.com/epfl-si/zeebe/tree/bug/overfull-DEADLINE_JOBS) produces the following, relevant excerpts:

<details><summary>Log excerpts</summary>

```
 for broker in $(seq 0 2); do oc -n phd-assess-test logs zeebe-broker-$broker-0|grep 'deactivate\|forEach'; done
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":307},"message":"forEachActivatableJobs: starting","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881373,"timestampNanos":108547275}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":325},"message":"forEachActivatableJobs: done, processed 13 jobs","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881373,"timestampNanos":169529866}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":307},"message":"forEachActivatableJobs: starting","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881373,"timestampNanos":171764111}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":325},"message":"forEachActivatableJobs: done, processed 0 jobs","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881373,"timestampNanos":172219141}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":307},"message":"forEachActivatableJobs: starting","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881376,"timestampNanos":967749123}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":325},"message":"forEachActivatableJobs: done, processed 0 jobs","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881376,"timestampNanos":968356521}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":307},"message":"forEachActivatableJobs: starting","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881376,"timestampNanos":969018562}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":325},"message":"forEachActivatableJobs: done, processed 0 jobs","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881376,"timestampNanos":969438570}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":307},"message":"forEachActivatableJobs: starting","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881396,"timestampNanos":15069073}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":325},"message":"forEachActivatableJobs: done, processed 0 jobs","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881396,"timestampNanos":15790841}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachTimedOutEntry","file":"DbJobState.java","line":252},"message":"forEachTimedOutEntry: starting","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881396,"timestampNanos":844718785}
{"severity":"ERROR","logging.googleapis.com/sourceLocation":{"function":"lambda$deactivateTimedOutJobs$0","file":"JobTimeoutTrigger.java","line":87},"message":"deactivateTimedOutJobs: unable to flush: key=2251799816453675, record={\"deadline\":1647881486986,\"worker\":\"c533b992-ffe5-4fa0-8811-c718a5f41620\",\"retries\":0,\"retryBackoff\":0,\"recurringTime\":-1,\"type\":\"phdAssessFillForm\",\"customHeaders\":[packed value (length=17960)],\"variables\":\"gA==\",\"errorMessage\":\"\",\"errorCode\":\"\",\"bpmnProcessId\":\"phdAssessProcess\",\"processDefinitionVersion\":4,\"processDefinitionKey\":2251799816451171,\"processInstanceKey\":2251799816453632,\"elementId\":\"Activity_PHD_fills_annual_report\",\"elementInstanceKey\":2251799816453671}","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","reportLocation":{"functionName":"lambda$deactivateTimedOutJobs$0","filePath":"JobTimeoutTrigger.java","lineNumber":87},"actor-name":"Broker-0-StreamProcessor-1"},"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","timestampSeconds":1647881396,"timestampNanos":855322735}
{"severity":"ERROR","logging.googleapis.com/sourceLocation":{"function":"lambda$forEachTimedOutEntry$1","file":"DbJobState.java","line":264},"message":"forEachTimedOutEntry: bailing out after failed visitJob at count = 443","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","reportLocation":{"functionName":"lambda$forEachTimedOutEntry$1","filePath":"DbJobState.java","lineNumber":264},"actor-name":"Broker-0-StreamProcessor-1"},"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","timestampSeconds":1647881396,"timestampNanos":855880235}
{"severity":"ERROR","logging.googleapis.com/sourceLocation":{"function":"forEachTimedOutEntry","file":"DbJobState.java","line":275},"message":"forEachTimedOutEntry: done at count = 443","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","reportLocation":{"functionName":"forEachTimedOutEntry","filePath":"DbJobState.java","lineNumber":275},"actor-name":"Broker-0-StreamProcessor-1"},"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","timestampSeconds":1647881396,"timestampNanos":856099294}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":307},"message":"forEachActivatableJobs: starting","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881401,"timestampNanos":22222435}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":325},"message":"forEachActivatableJobs: done, processed 13 jobs","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881401,"timestampNanos":69950298}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":307},"message":"forEachActivatableJobs: starting","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881401,"timestampNanos":84670641}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":325},"message":"forEachActivatableJobs: done, processed 0 jobs","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881401,"timestampNanos":168317382}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":307},"message":"forEachActivatableJobs: starting","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881405,"timestampNanos":687893084}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":325},"message":"forEachActivatableJobs: done, processed 0 jobs","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881405,"timestampNanos":688659261}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":307},"message":"forEachActivatableJobs: starting","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881405,"timestampNanos":689358301}
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"forEachActivatableJobs","file":"DbJobState.java","line":325},"message":"forEachActivatableJobs: done, processed 0 jobs","serviceContext":{"service":"zeebe","version":"development"},"context":{"threadId":32,"partitionId":"1","threadPriority":5,"loggerName":"io.camunda.zeebe.broker.process","threadName":"Broker-0-zb-actors-0","actor-name":"Broker-0-StreamProcessor-1"},"timestampSeconds":1647881405,"timestampNanos":689805874}
```

</details>

Reading RocksDB snapshots using our [home-grown Perl script](https://github.com/epfl-si/PhDAssess/blob/master/scripts/read-snapshot.pl) gives us the following stats:

- Number of entries in the `JOBS` column family: 39 (out of which, only 13 currently get presented to a worker)
- Number of entries in `DEADLINE_JOBS`: 47017

**Environment:**
- OS: Kubernetes
- Zeebe Version: 1.3.5, as well as today's 1.3.6-SNAPSHOT (built from [our branch](https://github.com/epfl-si/zeebe/tree/bug/overfull-DEADLINE_JOBS))
- Configuration: 3-way Kubernetes replication on OpenShift 3.11, integrated gateway + broker pods (one of the three being backed to NFS)

**Comment by npepinpe** [comment] 2022-03-22 09:11
Hey @domq, thanks for reporting! Can you elaborate what you mean by the following:

1. Faulty client - what was the fault that was corrected? This might help us reproduce the issue.
2. The JobTimeOutProcessor overloads the log - do you mean there are too many time out commands to process? While that's a lot, and it will prevent other things from happening, it should eventually process them all such that the column will be cleared, and things should go back to normal (as you mentioned you fixed the original cause).

In order for us to see what's happening, we would need the complete `data/` folder for Zeebe, not just the RocksDB dumps. But maybe already your answers might shed some light here.

**Comment by domq** [comment] 2022-03-22 12:05
Hi @npepinpe , many thanks for your reply!

1. Faulty client: I have reason to believe (but no proof alas) that we had the same issue as [#5925](https://github.com/camunda-cloud/zeebe/issues/5925), i.e. the client ([zeebe-node](https://www.npmjs.com/package/zeebe-node), itself using [@grpc/grpc-js](https://www.npmjs.com/package/@grpc/grpc-js)) would close the connection in the middle of a large `ActivateJobsResponse`. We patched it [like this](https://github.com/epfl-si/PhDAssess/blob/master/patches/%40grpc%2Bgrpc-js%2B1.5.7.patch) and it appears to have fixed the root cause, i.e. the `DEADLINE_JOBS` column family size has been stable at ~47k entries for a couple of days (in our drained production instance that still receives periodic `ActivateJobsRequest`s, but no data mutation or workflow progress is taking place).
2. Unfortunately, there are hundreds of `DEADLINE_JOBS` entries for the same job currently, i.e. the implicit “unicity constraint” per job in this column family is being violated, so to speak. Observation suggests that for any given (non-stuck) job, only the last deadline entry gets updated. Indeed, as I understand it from reading the code, the [JobTimedOutApplier](https://github.com/camunda-cloud/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/state/appliers/JobTimedOutApplier.java#L26) calls [DbJobState#timeout](https://github.com/camunda-cloud/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java#L140), which calls [removeDeadline](https://github.com/camunda-cloud/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbJobState.java#L398), which only deletes one deadline entry, namely the “real” one (i.e. the one that the `deadline` field in the job state points to).

From the code instrumentation that I set up (in my test instance, using a data backup from production), I do think that the timeout commands overflow some kind of log space. (I'm not sure that I am using the right terminology or concept here, i.e. this could be the Raft log or something else.) As you can see from the logs excerpt I provided, [this code path](https://github.com/epfl-si/zeebe/commit/4aae18638b93bfd3d953c91592dc0370dc8fdac8#diff-2f8e3e4d083884ac76f137856ec0391e10ee4ad9d52646712cc9a38bcc5655c6R87) is being taken.

I will gladly share our complete `data/` directory. We can do this over e-mail using that [SWITCHfilesender](https://www.switch.ch/services/filesender/) thing that we have; kindly send me your email address privately to dominique.quatravaux@epfl.ch (or suggest another way).

I am in the process of writing a [crude fix](https://github.com/epfl-si/PhDAssess/blob/master/scripts/normalize-deadlines.pl) to get our production instance back up and running, and I will let you know the outcome.

**Comment by domq** [comment] 2022-03-22 20:35
Update: I ran into the checksumming logic and therefore my crude fix is taking longer than expected ☺

**Comment by domq** [comment] 2022-03-22 22:08
Update²: I managed to [forge](https://github.com/epfl-si/PhDAssess/blob/master/scripts/perllib/ZeebeDB.pm#L125) the `foo.checksum` file, and thereafter to load my doctored snapshot (on top of which the pristine Raft log applies fine).  The symptoms seem to have subsided i.e. all eligible jobs get presented to workers again.

Pro memoria, the dump / transform / restore operation consists of [emptying](https://github.com/epfl-si/PhDAssess/blob/master/scripts/normalize-deadlines.pl#L85) the `DEADLINE_JOBS` column family, and regenerating its data from the ground truth in `JOBS` and `JOB_STATES` column families.

We will be performing a more thorough check on our restored test instance tomorrow. Yours truly, Dominique

**Comment by npepinpe** [comment] 2022-03-23 13:06
I have to say, it's been fun reading your Perl scripts and seeing how you deal with this :smile: Kudos for that

I thought you might run into the dispatcher limitation - the dispatcher is a ring buffer which is used to synchronize writing from multiple producers. But as we flush every command separately, I would expect that you never run into the limits of the dispatcher, since we'll clear the memory on every flush. The Raft log is only limited by the disk size. Technically, once you reach a certain threshold, writes are stopped to allow processing to catch up, so you also shouldn't run into this issue (except a small edge case where you write too fast for the threshold checker to kick in).

It's possible to fill up the dispatcher by writing faster to it - it's an in memory structure after all - than we can flush it to disk. But that should eventually also resolve itself as this gets retried. :thinking:

**Comment by domq** [comment] 2022-03-25 06:52
So, what are the next steps? Do you want to take a look at our data directory? Should I work to create a reproduction scenario?

**Comment by npepinpe** [comment] 2022-04-26 14:05
I'm wondering if this might not be related to https://github.com/camunda/zeebe/issues/8991 to some extent.

I could take a look at the data directory. It's easier/better if you have a reproducer of course, but I imagine that can take some time for you to make.

**Comment by domq** [comment] 2022-05-11 15:22
Just a clarification as, while discussing this issue in our backlog meeting, I realize that a key point got left out of the bug description — I just fixed it retrospectively, but I would like to restate it here for the record.

What we fixed in the client is its gRPC receive buffer size (we bumped it from 4 Mb to 10 Mb). Just like in [this comment of @npepinpe on the other bug](https://github.com/camunda/zeebe/issues/5925#issuecomment-796880239), we can imagine (again — With no proof!) that the Zeebe master got sidetracked by a failure in the RPC reply code path, which caused it to forget to delete the `DEADLINE_JOBS` entry it should have been working on.

**Comment by aleksander-dytko** [comment] 2022-07-15 14:04
Hi @domq, 

Question about a bit different thing: 
In Q3 we're planning to work on the official support for OpenShift Helm Charts for Camunda 8. I wanted to validate the idea with you:

Proposition: For each release of new minor of Camunda 8.x self-managed to support all the minor version of the current major version (4.x) that are not end of life (Full Support and Maintenance Support status).
Example - This would mean to support versions 4.6-4.10, if we would release new minor version on July 1st 2022. New minor versions of OpenShift are officially supported for 18 months in total for a release (https://access.redhat.com/support/policy/updates/openshift#ocp4_phases)

Would that make sense for you, taking into consideration your OpenShift policies? 

Thanks,
Aleksander

**Comment by Zelldon** [comment] 2023-09-19 06:29
@oleschoenburg I think this is fixed right? I remember you implemented something to clean up the column families?

**Comment by oleschoenburg** [comment] 2023-09-19 06:31
Yes, this should be fixed by https://github.com/camunda/zeebe/issues/12797 and https://github.com/camunda/zeebe/issues/13881

**Closed by oleschoenburg** 2023-09-19 06:31 UTC
Labels: kind/bug, blocker/info, area/reliability, component/engine
