### ISSUE TITLE
Unable to process unknown element with name executionListener

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#9041] opened 2022-04-01 06:01 UTC
**Describe the bug**

In production an error was reported when an user tried out a model with an execution listener, likely a cam 7 model.

Error Group: https://console.cloud.google.com/errors/detail/CPae5afjtYD0qQE;service=zeebe;time=P7D?project=camunda-cloud-240911

**To Reproduce**

I guess deploying a process with an execution listener.

**Expected behavior**
I wouldn't expect that this is logged as an error. It is likely that users deploy unusable models, as long we handle it gracefully and sent an error back I don't think we need to log it.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: Unable to process unknown element with name executionListener
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.lambda$walk$0(ModelWalker.java:69) ~[zeebe-bpmn-model-1.3.6.jar:1.3.6]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.model.bpmn.traversal.ModelWalker.walk(ModelWalker.java:63) ~[zeebe-bpmn-model-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnValidator.validate(BpmnValidator.java:40) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:119) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:96) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:100) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:54) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$3(ProcessingStateMachine.java:297) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction(ProcessingStateMachine.java:287) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:252) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:212) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:188) ~[zeebe-workflow-engine-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79) [zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44) [zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) [zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) [zeebe-util-1.3.6.jar:1.3.6]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) [zeebe-util-1.3.6.jar:1.3.6]
Caused by: java.lang.ClassCastException
```

</p>
</details>

**Environment:**
- saas
- Zeebe Version: 1.3.6
- Configuration: https://console.cloud.camunda.io/admin/cluster-plan/plans/2955c05b-2073-4258-9430-e781b4879a32

**Comment by npepinpe** [comment] 2022-04-07 07:48
Duplicate of #4817

**Closed by npepinpe** 2022-04-07 07:48 UTC
Labels: Type: Bug, Severity: Low
