### ISSUE TITLE
`LeaderRoleTest.shouldNotAppendFollowingEntryOnException` is flaky

### ISSUE THREAD

**Issue by korthout** [camunda/zeebe#14541] opened 2023-09-29 10:07 UTC
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? [once](https://github.com/camunda/zeebe/actions/runs/6349896776/job/17248791903?pr=14539)
- Does it block your work? nope
- Do we suspect that it is a real failure? ..

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<p>

```
Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.485 s <<< FAILURE! -- in io.atomix.raft.roles.LeaderRoleTest
Error:  io.atomix.raft.roles.LeaderRoleTest.shouldNotAppendFollowingEntryOnException -- Time elapsed: 1.051 s <<< FAILURE!
org.mockito.exceptions.verification.TooManyActualInvocations: 

raftContext.transition(FOLLOWER);
Wanted 1 time:
-> at io.atomix.raft.impl.RaftContext.transition(RaftContext.java:778)
But was 2 times:
-> at io.atomix.raft.roles.LeaderRole.appendEntry(LeaderRole.java:598)
-> at io.atomix.raft.roles.LeaderRole.appendEntry(LeaderRole.java:598)


	at io.atomix.raft.impl.RaftContext.transition(RaftContext.java:778)
	at io.atomix.raft.roles.LeaderRoleTest.shouldNotAppendFollowingEntryOnException(LeaderRoleTest.java:300)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

</p>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

[io.atomix.raft.roles.LeaderRoleTest-1-output.txt](https://github.com/camunda/zeebe/files/12763580/io.atomix.raft.roles.LeaderRoleTest-1-output.txt)
[io.atomix.raft.roles.LeaderRoleTest-2-output.txt](https://github.com/camunda/zeebe/files/12763583/io.atomix.raft.roles.LeaderRoleTest-2-output.txt)

**Comment by Zelldon** [comment] 2023-10-10 08:14
Locally I'm not able to reproduce it.

**Comment by Zelldon** [comment] 2023-10-11 07:42
I checked the code and it is unclear to me how this could happen.

 * We submit two appends, both are async (they are submitted in the queue)
 * We await the latch (the error of the last append)
 * On the first append the failure happens, this [causes the step-down ](https://github.com/camunda/zeebe/blob/main/atomix/cluster/src/main/java/io/atomix/raft/roles/LeaderRole.java#L598)
 * The step down is mostly synchronous (even if we use futures 🤷🏼 )
 * The next submit will be executed and should fail since the leader role is closed.

I don't see how the transition could be triggered twice 🤔  

But in the logs, we can clearly see that the exception of the append is printed twice:

```
09:56:13.628 [] ERROR io.atomix.raft.roles.LeaderRole - RaftServer{leader}{role=LEADER} - Failed to append to local log, stepping down
java.lang.RuntimeException: expected
	at io.atomix.raft.storage.log.RaftLog.append(RaftLog.java:144) ~[classes/:?]
	at io.atomix.raft.roles.LeaderRole.append(LeaderRole.java:647) ~[classes/:?]
	at io.atomix.raft.roles.LeaderRole.appendWithRetry(LeaderRole.java:611) ~[classes/:?]
	at io.atomix.raft.roles.LeaderRole.appendEntry(LeaderRole.java:595) ~[classes/:?]
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:705) ~[classes/:?]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$14(LeaderRole.java:668) ~[classes/:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:178) [zeebe-atomix-utils-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
09:56:13.646 [] ERROR io.atomix.raft.roles.LeaderRole - RaftServer{leader}{role=LEADER} - Failed to append to local log, stepping down
java.lang.RuntimeException: expected
	at io.atomix.raft.storage.log.RaftLog.append(RaftLog.java:144) ~[classes/:?]
	at io.atomix.raft.roles.LeaderRole.append(LeaderRole.java:647) ~[classes/:?]
	at io.atomix.raft.roles.LeaderRole.appendWithRetry(LeaderRole.java:611) ~[classes/:?]
	at io.atomix.raft.roles.LeaderRole.appendEntry(LeaderRole.java:595) ~[classes/:?]
	at io.atomix.raft.roles.LeaderRole.safeAppendEntry(LeaderRole.java:705) ~[classes/:?]
	at io.atomix.raft.roles.LeaderRole.lambda$appendEntry$14(LeaderRole.java:668) ~[classes/:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:178) [zeebe-atomix-utils-8.3.0-SNAPSHOT.jar:8.3.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

We use a single thread context so this should not happen. 🤔 

Maybe @deepthidevaki or @npepinpe has some idea

**Comment by Zelldon** [comment] 2023-11-07 08:04
I run it yesterday over 20k times or was it 200k anyway I was not able to reproduce it locally. I will try to run it repeatedly in CI

**Comment by Zelldon** [comment] 2023-11-09 16:10
Loop in CI https://github.com/camunda/zeebe/actions/runs/6814387699/job/18531136808

**Comment by Zelldon** [comment] 2023-11-09 17:34
Ok the CI timed out after 30 min https://github.com/camunda/zeebe/actions/runs/6814387699 without any failure. I would say the test is not reproducible. I will close this.

**Closed by Zelldon** 2023-11-09 17:34 UTC
Labels: kind/flake, component/raft
