### ISSUE TITLE
OpenSearch Exporter

### ISSUE THREAD

**Issue by nothingworkss** [camunda/zeebe#16545] opened 2024-02-25 23:16 UTC
I'm trying to setup a camunda-zeebe cluster using the camunda-platform version 9.0.2 via helm package, choosing OpenSearch as exporter. Sending the logs to an external existing OpenSearch Instance. All okay, no problem until here.

OpenSearch SSL Certificate I'm using is self-signed.

I'm using this option on my values file as suggested on the doc.
zeebe:
  …
  javaOpts: >-
    …
    -Djavax.net.ssl.trustStore=/path/to/certificates/opensearch.jks

Once I trigger a test starts generating these logs.

camunda.zeebe.exporter.opensearch.OpensearchExporterException: Failed to put component template
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Helm values file
zeebe:
  broker:
    volumes:
    - name: os
      secret:
        secretName: os

    debug: true
    containerSecurityContext:
      readOnlyRootFilesystem: false

    volumeMounts:
    - name: os
      readOnly: true
      mountPath: /usr/local/zeebe/os.jks

    javaOpts: >-
      -XX:+HeapDumpOnOutOfMemoryError
      -XX:HeapDumpPath=/usr/local/zeebe/data
      -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log
      -XX:+ExitOnOutOfMemoryError
      -Djavax.net.ssl.trustStore=/usr/local/zeebe/os.jks
      -Djavax.net.ssl.trustStorePassword=changeit

    env:
      - name: ZEEBE_BROKER_EXPORTERS_OPENSEARCH_CLASSNAME
        value: "io.camunda.zeebe.exporter.opensearch.OpensearchExporter"
      - name: ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_URL
        value: "https://URL:9200"
      - name: ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_AUTHENTICATION_USERNAME
        value: "USER"
      - name: ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_AUTHENTICATION_PASSWORD
        value: "PASSWORD"
      - name: ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_INDEX_PREFIX
        value: "EXISTING INDEX"
      - name: ZEEBE_LOG_LEVEL
        value: "info"
      - name: ZEEBE_BROKER_GATEWAY_SECURITY_ENABLED
        value: "false"
        
zeebe-gateway:
  containerSecurityContext:
    readOnlyRootFilesystem: false

global:
  ingress:
    enabled: false
  elasticsearch:
    disableExporter: true
  identity:
    auth:
      enabled: false

connectors: 
  enabled: false
elasticsearch:
  enabled: false
identity:
  enabled: false
keycloak:
  enabled: false
tasklist:
  enabled: false
optimize:
  enabled: false
  
Package camunda/camunda-platform

**Comment by korthout** [comment] 2024-02-26 13:56
Hi @nothingworkss 👋 Thanks for reporting this.

We wonder whether the issue is in our helm charts rather than our OpenSearch exporter. @aabouzaid Could you have a look at the provided configurations? Perhaps there's something you can spot.

>unable to find valid certification path to requested target

This reads as if the keystore could be found but that it does not contain a valid certificate for the request that's made. Are you sure it's available? If it is, are you sure it matches the path specified by: `camunda.operate.zeebeOpenSearch.ssl.certificatePath`?

PS: If you're a paying customer, you could take this via a support case for faster responses.

**Comment by nothingworkss** [comment] 2024-02-26 14:20
Thanks for the quick response,

I tried to add that on my helm definition and I'm not sure if operate supports OpenSearch.

++added section

operate:
  zeebeOpenSearch:
    ssl:
      certificatePath: /usr/local/zeebe/os.jks
      selfSigned: true
    authentication:
      username: USER
      password: PASSWORD

Checked the logs on the operate pod:
java.util.concurrent.ExecutionException: java.net.UnknownHostException: zeebe-elasticsearch: Try again

org.elasticsearch.ElasticsearchException: java.util.concurrent.ExecutionException: java.net.UnknownHostException: zeebe-elasticsearch: Try again

Also I don't know how accurate is this on the documentation but its says Operate requires ElasticSearch
https://docs.camunda.io/docs/self-managed/platform-deployment/overview/#components

**Comment by korthout** [comment] 2024-02-26 14:43
>Also I don't know how accurate is this on the documentation but its says Operate requires ElasticSearch
https://docs.camunda.io/docs/self-managed/platform-deployment/overview/#components

That page seems out of date. //cc @akeller 

I believe Operate 8.4 should function with OpenSearch 2.5, just like Zeebe: https://docs.camunda.io/docs/reference/supported-environments/#camunda-8-self-managed

See config options for Operate with OpenSearch:
- https://docs.camunda.io/docs/self-managed/operate-deployment/operate-configuration/#settings-for-opensearch

Still, this doesn't seem to resolve your issue 🤔 I'd suggest looking at the certificate in the keystore and verifying it's cert path. You could also consider enabling the SSL debug logs. Perhaps this shares exactly the host it's trying to connect to and the cert path it's looking for.

Also, let's wait for @aabouzaid perhaps he spots something in the configs.

**Comment by korthout** [comment] 2024-02-26 14:47
@nothingworkss As an alternative idea, you could also search for the question or ask it on our [forums](https://forum.camunda.io). There are many experts there that may be able to help; perhaps the topic has been discussed before.

**Comment by aabouzaid** [comment] 2024-02-28 04:24
We are still working on the support for OpenSearch in our Helm chart.
It's expected to be released with the 8.5 apps.

**Comment by aabouzaid** [comment] 2024-02-28 04:24
@hamza-m-masood FYI.

**Comment by korthout** [comment] 2024-02-28 12:15
Thanks @aabouzaid 🙇 Do you have an issue that @nothingworkss can use to track progress on supporting OpenSearch in our Helm chart?

Since this is not supported by our Helm chart yet, I'm closing this bug report.

**Closed by korthout** 2024-02-28 12:15 UTC
Labels: kind/bug

**Comment by aabouzaid** [comment] 2024-02-28 12:22
This should be the GH issue to follow
https://github.com/camunda/camunda-platform-helm/issues/473

It's for ES but it will be also for OS.

**Comment by Ruivalim** [comment] 2024-03-27 14:00
Hey @nothingworkss, did you managed to make it work with OpenSearch?

**Comment by nothingworkss** [comment] 2024-03-27 14:53
yes, for zeebe add opensearch certificate option as here https://docs.camunda.io/docs/self-managed/operate-deployment/operate-configuration/#settings-to-connect-and-import

for operate you have to fork the helm chart, operate template, check configmap -- zeebeElasticSearch/elasticseach change them.
check logs, will be able to solve it

**Comment by eins** [comment] 2024-03-27 16:59
Hey @nothingworkss  Do you have an example that you can share? 

[#443](https://github.com/camunda/camunda-platform-helm/issues/473) is a mess and it has only reference to elastic search .

this is an old ticket without a clear solution for opensearch [#440](https://github.com/camunda/camunda-platform-helm/issues/440)

I'm trying to understand how can I setup the opensearch values for elasticsearch. At this current time it looks my only option is to do a helm install but the docs aren't clear and the values.yml hasn't the values that I suppose to  override [opensearch tasklist](https://docs.camunda.io/docs/self-managed/tasklist-deployment/tasklist-configuration/#elasticsearch-or-opensearch)

Helm upgrade to opensearch isn't possible based on url [opensearch](https://docs.camunda.io/docs/self-managed/operate-deployment/operate-configuration/#elasticsearch-or-opensearch)

:cowboy_hat_face:

**Comment by nothingworkss** [comment] 2024-03-28 08:24
Its not possible to do the setup for opensearch with some update command or just updating the values.
You have to modify the helm chart.
Pull the helm chart into a local folder --> helm pull --untar --untardir FOLDER camunda/camunda-platform
Go to template of the service you want to adapt for OpenSearch, check deployment, configmap what ever they have.
Modify the sections where elasticSearch is defined.
Install the chart using the local folder where the changes were done.
Check the logs when the pod starts, logs will provide more hints what its missing.

for example if you check the configmap of the tasklist you will find the default as below
camunda.tasklist:
  elasticsearch:
    # Cluster name
    clusterName: elasticsearch
    # Url
    url: https://localhost:9200
    ssl:
      selfSigned: true
      
   replace the elasticsSeach with openSearch, also replace default values with variables {{.values.global.opensearch.XXX}}

**Comment by eins** [comment] 2024-03-28 11:29
@nothingworkss thanks for the reply. I will test it.
