### ISSUE TITLE
Behavior change causes to no longer create incidents

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#14761] opened 2023-10-17 10:44 UTC
**Describe the bug**

There was a behavior change in the underlying feel engine (see [slack thread](https://camunda.slack.com/archives/CSQ2E3BT4/p1695632576865299)), which causes the Zeebe engine to no longer create incidents when a variable is not set.

This is quite confusing and can also lead to more problematic issues, since workers will retrieve the jobs with variables that are set to null, instead of raising an incident. This is a severe behavior change, since before it was clear what the problem is now it is hidden and can lead to problematic situations. 

I ran into it when migrating zdb to 8.3.0

**To Reproduce**

[Reproducer repo](https://github.com/Zelldon/zeebe-engine-test-template)

When you run the following with 8.2.x it will work, but not with 8.3.0
```
@ZeebeProcessTest
public class PullRequestProcessTest {

  // injected by ZeebeProcessTest annotation
  private ZeebeTestEngine engine;
  // injected by ZeebeProcessTest annotation
  private ZeebeClient client;

  private static final BpmnModelInstance process =
          Bpmn.createExecutableProcess("process")
                  .startEvent()
                  .parallelGateway("gw")
                  .serviceTask("task")
                  .zeebeJobType("type")
                  .endEvent()
                  .moveToLastGateway()
                  .serviceTask("incidentTask")
                  .zeebeInputExpression("=foo", "bar")
                  .zeebeJobType("type")
                  .endEvent()
                  .done();

  @BeforeEach
  void deployProcess() {
    client.newDeployCommand().addProcessModel(process, "process.bpmn").send().join();
  }

  @Test
  void shouldRunIntoAnIncident() throws InterruptedException, TimeoutException {
    // given
    // when
    final var returnedProcessInstance = client
            .newCreateInstanceCommand()
            .bpmnProcessId("process")
            .latestVersion()
            .variables(Map.of("var1", "1", "var2", "12", "var3", "123"))
            .send()
            .join();

    // then
    engine.waitForIdleState(Duration.ofSeconds(5));
    BpmnAssert.assertThat(returnedProcessInstance)
            .hasAnyIncidents()
            ;
  }
}

```

**Expected behavior**

We are still creating incidents for such.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
[main] INFO io.camunda.zeebe.process.test.filters.logger.RecordStreamLogger - 
The following records have been recorded during this test:
| COMMAND             DEPLOYMENT                         CREATE                        | (Processes: [process.bpmn])
| EVENT               PROCESS                            CREATED                       | (Process: process.bpmn)
| EVENT               DEPLOYMENT                         CREATED                       | 
| COMMAND             PROCESS_INSTANCE_CREATION          CREATE                        | (Process id: process), (Variables: [var3 -> 123, var2 -> 12, var1 -> 1]), (default start)
| EVENT               VARIABLE                           CREATED                       | (Name: var1), (Value: "1")
| EVENT               VARIABLE                           CREATED                       | (Name: var2), (Value: "12")
| EVENT               VARIABLE                           CREATED                       | (Name: var3), (Value: "123")
| COMMAND             PROCESS_INSTANCE                   ACTIVATE_ELEMENT              | (Element id: process), (Element type: PROCESS), (Event type: UNSPECIFIED), (Process id: process)
| EVENT               PROCESS_INSTANCE_CREATION          CREATED                       | (Process id: process), (Variables: [var3 -> 123, var2 -> 12, var1 -> 1]), (default start)
| EVENT               PROCESS_INSTANCE                   ELEMENT_ACTIVATING            | (Element id: process), (Element type: PROCESS), (Event type: UNSPECIFIED), (Process id: process)
| EVENT               PROCESS_INSTANCE                   ELEMENT_ACTIVATED             | (Element id: process), (Element type: PROCESS), (Event type: UNSPECIFIED), (Process id: process)
| COMMAND             PROCESS_INSTANCE                   ACTIVATE_ELEMENT              | (Element id: startEvent_198686a3-0baa-4d33-a6a6-ce6fe5b0abac), (Element type: START_EVENT), (Event type: NONE), (Process id: process)
| EVENT               PROCESS_INSTANCE                   ELEMENT_ACTIVATING            | (Element id: startEvent_198686a3-0baa-4d33-a6a6-ce6fe5b0abac), (Element type: START_EVENT), (Event type: NONE), (Process id: process)
| EVENT               PROCESS_INSTANCE                   ELEMENT_ACTIVATED             | (Element id: startEvent_198686a3-0baa-4d33-a6a6-ce6fe5b0abac), (Element type: START_EVENT), (Event type: NONE), (Process id: process)
| COMMAND             PROCESS_INSTANCE                   COMPLETE_ELEMENT              | (Element id: startEvent_198686a3-0baa-4d33-a6a6-ce6fe5b0abac), (Element type: START_EVENT), (Event type: NONE), (Process id: process)
| EVENT               PROCESS_INSTANCE                   ELEMENT_COMPLETING            | (Element id: startEvent_198686a3-0baa-4d33-a6a6-ce6fe5b0abac), (Element type: START_EVENT), (Event type: NONE), (Process id: process)
| EVENT               PROCESS_INSTANCE                   ELEMENT_COMPLETED             | (Element id: startEvent_198686a3-0baa-4d33-a6a6-ce6fe5b0abac), (Element type: START_EVENT), (Event type: NONE), (Process id: process)
| EVENT               PROCESS_INSTANCE                   SEQUENCE_FLOW_TAKEN           | (Element id: sequenceFlow_7d85d9aa-fa96-4c8d-8397-51f229c257c3), (Element type: SEQUENCE_FLOW), (Event type: UNSPECIFIED), (Process id: process)
| COMMAND             PROCESS_INSTANCE                   ACTIVATE_ELEMENT              | (Element id: gw), (Element type: PARALLEL_GATEWAY), (Event type: UNSPECIFIED), (Process id: process)
| EVENT               PROCESS_INSTANCE                   ELEMENT_ACTIVATING            | (Element id: gw), (Element type: PARALLEL_GATEWAY), (Event type: UNSPECIFIED), (Process id: process)
| EVENT               PROCESS_INSTANCE                   ELEMENT_ACTIVATED             | (Element id: gw), (Element type: PARALLEL_GATEWAY), (Event type: UNSPECIFIED), (Process id: process)
| EVENT               PROCESS_INSTANCE                   ELEMENT_COMPLETING            | (Element id: gw), (Element type: PARALLEL_GATEWAY), (Event type: UNSPECIFIED), (Process id: process)
| EVENT               PROCESS_INSTANCE                   ELEMENT_COMPLETED             | (Element id: gw), (Element type: PARALLEL_GATEWAY), (Event type: UNSPECIFIED), (Process id: process)
| EVENT               PROCESS_INSTANCE                   SEQUENCE_FLOW_TAKEN           | (Element id: sequenceFlow_d99832d1-0c6b-41f2-8112-529c73aa909f), (Element type: SEQUENCE_FLOW), (Event type: UNSPECIFIED), (Process id: process)
| COMMAND             PROCESS_INSTANCE                   ACTIVATE_ELEMENT              | (Element id: incidentTask), (Element type: SERVICE_TASK), (Event type: UNSPECIFIED), (Process id: process)
| EVENT               PROCESS_INSTANCE                   SEQUENCE_FLOW_TAKEN           | (Element id: sequenceFlow_2808143d-0e0f-48c0-a73e-5bba8ec9e411), (Element type: SEQUENCE_FLOW), (Event type: UNSPECIFIED), (Process id: process)
| COMMAND             PROCESS_INSTANCE                   ACTIVATE_ELEMENT              | (Element id: task), (Element type: SERVICE_TASK), (Event type: UNSPECIFIED), (Process id: process)
| EVENT               PROCESS_INSTANCE                   ELEMENT_ACTIVATING            | (Element id: incidentTask), (Element type: SERVICE_TASK), (Event type: UNSPECIFIED), (Process id: process)
| EVENT               VARIABLE                           CREATED                       | (Name: bar), (Value: null)
| EVENT               JOB                                CREATED                       | (Element id: incidentTask), (Job type: type)
| EVENT               PROCESS_INSTANCE                   ELEMENT_ACTIVATED             | (Element id: incidentTask), (Element type: SERVICE_TASK), (Event type: UNSPECIFIED), (Process id: process)
| EVENT               PROCESS_INSTANCE                   ELEMENT_ACTIVATING            | (Element id: task), (Element type: SERVICE_TASK), (Event type: UNSPECIFIED), (Process id: process)
| EVENT               JOB                                CREATED                       | (Element id: task), (Job type: type)
| EVENT               PROCESS_INSTANCE                   ELEMENT_ACTIVATED             | (Element id: task), (Element type: SERVICE_TASK), (Event type: UNSPECIFIED), (Process id: process)

org.opentest4j.AssertionFailedError: No incidents were raised for this process instance
Expected :true
Actual   :false
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.3.0
- Configuration:

**Comment by Madanpurohit** [comment] 2023-10-23 12:09
I can take this , can you assign me?

**Comment by saig0** [comment] 2023-10-24 03:49
I understand that this change doesn't fit everyone and it's different from before. 

However, the new behavior is intended - it is not a bug. :sweat_smile:  

The change is mentioned in the [Update guide to 8.3](https://docs.camunda.io/docs/next/self-managed/operational-guides/update-guide/820-to-830/). If you prefer to raise incidents like before then [assertions](https://docs.camunda.io/docs/next/components/modeler/feel/language-guide/feel-error-handling/#assertions) are the way to go. :wink:

**Comment by remcowesterhoud** [comment] 2023-11-01 14:40
ZPA Triage:
- As @saig0 said it's not a bug but a feature 🙃 
- Closing as not-planned

**Closed by remcowesterhoud** 2023-11-01 14:40 UTC
Labels: kind/bug, severity/high, component/engine, regression, impact/high
