### ISSUE TITLE
How do I know if the exporter is abnormal

### ISSUE THREAD

**Issue by zxiaozhou** [camunda/zeebe#11229] opened 2022-12-09 08:14 UTC
**Is your feature request related to a problem? Please describe.**
1. zeebe monitors whether the system can provide indicator information when the exporter hangs up
2. If the exporter hangs up but does not monitor metrics. Is that because of the large amount of data causing the cluster to crash
3. If the query fails, will the jobworker system data not be updated for a long time without knowing why

**Comment by zxiaozhou** [comment] 2022-12-09 14:40
@npepinpe I want to know whether the exporter is abnormal during the topology check so that an alarm can be generated for the export exception

**Comment by Zelldon** [comment] 2023-01-04 14:30
@zxiaozhou when I understand you correctly you want to see in the prometheus metrics whether for example the elastic search is still exporting?

You could see this via failure rate, or whether the exporting records decreased, or the exported position doesn't increase.

Does this help?

**Comment by zxiaozhou** [comment] 2023-01-09 01:52
@Zelldon zeebe must share an exporter. I want the exporter, once used, to be able to query for exceptions in the topology.

**Comment by korthout** [comment] 2023-01-11 09:33
>I want the exporter, once used, to be able to query for exceptions in the topology.

@zxiaozhou I'm assuming that you're talking about the Topology we provide to clients on request. While the topology shows the health of the partitions on each of the brokers, I don't think it should explicitly show the health of exporters. 

The health of a partition shown in the Topology is already a composition of the health of the components that make up that partition. This health is only meant to quickly check whether your system is up and running and generally looks okay. If it's unhealthy, you should investigate the root cause. Typically, this would require you to look at the Prometheus metrics, which provide much more detail.

💡 [Zeebe's Prometheus metrics](https://github.com/camunda/zeebe/tree/main/monitor) already contain details about all the exporters. I recommend you have a look at those. As @Zelldon described, there are metrics available that show the rate at which records are exported. If this drops to zero, it would indicate that exporting has stopped. 

> so that an alarm can be generated for the export exception

You could set up [alerts using Prometheus](https://prometheus.io/docs/alerting/latest/overview/), but another idea is to use [Grafana Alterting](https://grafana.com/docs/grafana/latest/alerting/) for this. 

I'm closing this issue, as I believe the problem can be resolved with the tools already available today. Please reopen it if I missed something or if you feel otherwise.

🙇 Also, please let us know if any metrics are missing.

**Closed by korthout** 2023-01-11 09:33 UTC
Labels: kind/question, component/exporter
