### ISSUE TITLE
NPE in QueryAPI while shutting down

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/zeebe#12776] opened 2023-05-16 10:22 UTC
**Describe the bug**

```
java.lang.NullPointerException: value cannot be null
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:602) ~[agrona-1.18.1.jar:1.18.1]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:588) ~[agrona-1.18.1.jar:1.18.1]
	at org.agrona.collections.Int2ObjectHashMap.put(Int2ObjectHashMap.java:44) ~[agrona-1.18.1.jar:1.18.1]
	at io.camunda.zeebe.broker.transport.queryapi.QueryApiRequestHandler.lambda$addPartition$0(QueryApiRequestHandler.java:62) ~[zeebe-broker-8.3.0-alpha1.jar:8.3.0-alpha1]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.3.0-alpha1.jar:8.3.0-alpha1]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-alpha1.jar:8.3.0-alpha1]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-alpha1.jar:8.3.0-alpha1]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.3.0-alpha1.jar:8.3.0-alpha1]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-alpha1.jar:8.3.0-alpha1]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.3.0-alpha1.jar:8.3.0-alpha1]

```
No impact as it was during shutdown. Shutdown was completed with no issues.

Might be related to https://github.com/camunda/zeebe/issues/9176. "Actor Is Closed" error occurred just before this.

**Environment:**
- Zeebe Version: 8.3.0-alpha1

**Comment by korthout** [comment] 2023-07-03 12:53
I think this is a duplicate of https://github.com/camunda/zeebe/issues/8041

**Comment by oleschoenburg** [comment] 2023-08-02 07:16
I think this was a duplicate of https://github.com/camunda/zeebe/issues/13471, closing for now.

**Closed by oleschoenburg** 2023-08-02 07:16 UTC
Labels: kind/bug, severity/low
