### ISSUE TITLE
Expected to find a process deployed but not found

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#14448] opened 2023-09-25 10:02 UTC
**Describe the bug**

Exception is thrown during processing, apparently while creating an event scope.
This results in a stopped stream processor and a leader change. The exception occurs repeatedly on multiple brokers.

**To Reproduce**

I don't know.

**Expected behavior**

The exception doesn't occur in the first place or it is handled if it is expected.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.RuntimeException: java.lang.IllegalStateException: Expected to find a process deployed with key '2251799813685267' but not found.
at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$4 ( io/camunda.zeebe.stream.impl/ReplayStateMachine.java:168 )
at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run ( io/camunda.zeebe.scheduler.future/FutureContinuationRunnable.java:33 )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( io/camunda.zeebe.scheduler/ActorJob.java:94 )
at io.camunda.zeebe.scheduler.ActorJob.execute ( io/camunda.zeebe.scheduler/ActorJob.java:45 )
at io.camunda.zeebe.scheduler.ActorTask.execute ( io/camunda.zeebe.scheduler/ActorTask.java:119 )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( io/camunda.zeebe.scheduler/ActorThread.java:109 )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( io/camunda.zeebe.scheduler/ActorThread.java:87 )
at io.camunda.zeebe.scheduler.ActorThread.run ( io/camunda.zeebe.scheduler/ActorThread.java:204 )

Caused by: java.lang.IllegalStateException
…
at io.camunda.zeebe.engine.state.deployment.DbProcessState.getFlowElement ( DbProcessState.java:366 )
at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementActivatingApplier.createEventScope ( ProcessInstanceElementActivatingApplier.java:267 )
at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementActivatingApplier.applyState ( ProcessInstanceElementActivatingApplier.java:51 )
at io.camunda.zeebe.engine.state.appliers.ProcessInstanceElementActivatingApplier.applyState ( ProcessInstanceElementActivatingApplier.java:32 )
at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState ( EventAppliers.java:334 )
at io.camunda.zeebe.engine.Engine.replay ( Engine.java:95 )
at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayEvent$7 ( ReplayStateMachine.java:231 )
at io.camunda.zeebe.stream.impl.ReplayStateMachine.replayEvent ( ReplayStateMachine.java:231 )
at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$tryToReplayBatch$5 ( ReplayStateMachine.java:207 )
at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run ( ZeebeTransaction.java:98 )
at io.camunda.zeebe.stream.impl.ReplayStateMachine.tryToReplayBatch ( ReplayStateMachine.java:205 )
at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$3 ( ReplayStateMachine.java:164 )
at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run ( ActorRetryMechanism.java:28 )
at io.camunda.zeebe.scheduler.retry.RecoverableRetryStrategy.run ( RecoverableRetryStrategy.java:48 )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( ActorJob.java:92 ) 
```

</p>
</details>

**Environment:**
- Zeebe Version: Snapshot
- Error group: https://console.cloud.google.com/errors/detail/CMH1stjhs8vV7AE;service=zeebe;time=P7D?project=camunda-saas-int
- Data: https://drive.google.com/file/d/1YTIax-BlVyiV_yVhIswMcLeuYxYTZXIW/view?usp=drive_link

**Comment by oleschoenburg** [comment] 2023-09-25 10:17
@Zelldon mentioned that this is likely caused by upgrading snapshot versions where we don't yet have a migration for data that now needs to be tenant-aware.

**Comment by remcowesterhoud** [comment] 2023-10-04 07:43
I agree with @Zelldon that this is more than likely the cause. The [migration for this was](https://github.com/camunda/zeebe/pull/14460) merged a day after this issue occurred.

As we have the migration now I will close this issue.

**Closed by remcowesterhoud** 2023-10-04 07:43 UTC
Labels: kind/bug, severity/high, component/engine
