### ISSUE TITLE
Feature Request: On Timer events add scheduling at specific time

### ISSUE THREAD

**Issue by dinilv** [camunda/zeebe#3038] opened 2019-09-02 06:14 UTC
Hi,

we are looking at automating all our user workflows using Zeebe-IO, We are a e-commerce analytics company and we are supposed to deliver reports at US time . we would like to have the capability of configuring and running the report analytic workflows at UTC 12:30 AM. Kindly consider adding timer-events on specific time as well. We use Zee-Be for repeated timer events.

**Comment by saig0** [comment] 2019-09-13 07:25
Thank you for opening this feature request. Triggering timers at a given time is an important feature. We will implement this eventually. 

In the meantime, you could implement a worker which simulates the timer for you. 

In order to speed up the implementation, you can also provide a pull request. We would guide you through the implementation. Are you interested in implementing this feature?

**Comment by dinilv** [comment] 2019-09-16 06:42
Thanks. Does this implementation is in Java Capability ?

**Comment by saig0** [comment] 2019-09-16 09:56
Yes. This needs to be implemented in the broker.

**Comment by dinilv** [comment] 2019-09-16 12:56
will it be then available as part of BPMNmodeler as well ? later may be

**Comment by jasonconkey** [comment] 2019-11-18 18:49
Hi @saig0, I'm interested in this same feature, and would possibly be interested in working on a PR. Could I please get any information you have on implementation? Also if possible, could you provide an example of how a worker would simulate the timer? Thank yo

**Comment by saig0** [comment] 2019-11-19 07:32
@jasonconkey, happy to hear that you want to contribute :+1:

First of all, we should clarify what we want to build. 
As far as I understand, @dinilv wants to create a new workflow instance every day at 00:30:00Z. 

**Proposal**: time cycle with start time and duration `R[n]/<start>/<duration>` (see [ISO 8601 Repeating Intervals](https://en.wikipedia.org/wiki/ISO_8601#Repeating_intervals))

The timer event definition of the timer start event could look like this:
```
  <bpmn:timerEventDefinition>
    <bpmn:timeCycle>R/2019-12-01T00:30:00Z/P1D</bpmn:timeCycle>
  </bpmn:timerEventDefinition>
```

Meaning: starting from 2019-12-01 at 00:30:00Z, trigger the timer every day 

What do you think? Any other proposal?

---

Using a worker, you could pass the timer configuration via custom headers. The worker schedules a timer when a new job is polled (e.g. using Cron). When the timer is due then it completes the corresponding job.

**Comment by ceefour** [comment] 2020-04-19 09:31
I also need this feature :)

@saig0 `R/2019-12-01T00:30:00Z/P1D` yes I agree this is good syntax.

**Comment by npepinpe** [comment] 2020-05-26 15:08
I think this is a duplicate of https://github.com/zeebe-io/zeebe/issues/1834 - correct me if I'm wrong @saig0 ?

**Comment by saig0** [comment] 2020-05-27 04:52
@npepinpe that's correct. I closed the other one.

**Comment by sergeylebed** [comment] 2020-07-21 12:13
I also vote for this feature. We need more extended scheduler, so it should support running on certain days of a week, e.g. Monday and Wednesday? or a certain day of a Month, e.g. every 5th day. It does not seems to be covered by ISO standard but it might be worth considering.

**Comment by jwulf** [comment] 2020-09-24 03:41
I also need this feature. Camunda BPM supports [cron scheduling as a syntax](https://docs.camunda.org/manual/7.6/reference/bpmn20/events/timer-events/#time-cycle), which would be very flexible. Although, it would depend on the timezone of the server (I'm thinking Camunda Cloud here). You could make the broker always evaluate in UTC.

**Comment by rbgigo** [comment] 2021-09-01 18:10
Is there any move at all with the feature request?

**Comment by inghak** [comment] 2021-11-10 12:50
Also need this. In Camunda BPM it seems to work as expected in example : <timeCycle>R4/2016-03-11T12:13/PT5M</timeCycle> 
 (https://docs.camunda.org/manual/7.6/reference/bpmn20/events/timer-events/#time-cycle).
 A typical scenario would be to run each night regardless of start date, so the following should work: R/T03:00:00/P1D (repeat each night at 03:00 indefinitely, server time.  Or R/T03:00:00Z/P1D (Zulu time).

**Comment by lienvdsteen** [comment] 2022-02-01 14:56
Also interested in being able to schedule daily at a specific hour. Current specific use case is to run reporting from a HR system into Slack in the morning every weekday at 8AM UTC.

**Comment by skayliu** [comment] 2022-05-05 03:55
Need Help，when I deployed a bpmn with zeebe 1.3.7 , got the an error，what's wrong? 
![screenshot-20220505-112555](https://user-images.githubusercontent.com/26370117/166861463-102f6ebe-7101-44e0-99ca-7382cb5c14cc.png)

**Comment by saig0** [comment] 2022-05-05 04:08
@skayliu the feature is not supported yet. The issue is still open. For now, you can specify the start time of a cycle expression.

**Comment by McAlm** [comment] 2022-05-06 13:06
A work around is explained here: https://forum.camunda.io/t/timer-event-that-needs-to-start-every-tuesday/36370/4

**Comment by McAlm** [comment] 2022-05-13 11:21
Hi @felix-mueller: The suggested work around is actually not working. 
The feel expression is correct (returns the next 365 days at 09:00 PM) 
`= for x in 1..365 return date and time(today(),time("21:00:00Z")) + duration("P"+string(x)+"D")`
but deployment fails:
`Invalid timer cycle expression (Expected result of the expression ' for x in 1..365 return date and time(today(),time("21:00:00Z")) + duration("P"+string(x)+"D")' to be 'STRING', but was 'ARRAY'.)`

**Comment by saig0** [comment] 2022-05-16 03:51
@McAlm please share more details about your concrete use case and how you want to use the expression.

If you want to use the expression in a timer event with a cycle definition then the expression must return a cycle expression (i.e. a string value following the pattern `R/<duration>`). For example:

```
= {
  triggerTime: time("21:00:00Z"),
  date: if time(now()) < triggerTime then today() else today() + duration("P1D"),
  duration: date and time(date, triggerTime) - now(),
  cycle: cycle(duration)
}.cycle
```

**Comment by McAlm** [comment] 2022-05-17 10:41
Hi @saig0 : The use case is exactly as described several times above:  A process needs to be started cyclic at a given time, e.g. to run an automated batch process all night at 09:00:00 PM.

Your FEEL expression does not work for this use case, it returns a value like "R/PT-0.519S", or "R/PT-54M-16.221S" which does not look like the ISO 8601 standard. Though it looks not ISO conform (at least to me) it is being interpreted by the engine in a way that every second 1..6 (!) instances are being kicked off (which is not the expected result here).

The cycle method is not documented (where does it come from?), I cannot play around with it as I don't know which params it takes.

Obviously there is no valid workaround available (except creating a scheduled worker that starts an instance in needed intervals like you mentioned above...).

**Comment by saig0** [comment] 2022-05-25 05:07
> Your FEEL expression does not work for this use case, it returns a value like "R/PT-0.519S", or "R/PT-54M-16.221S"

Yes, the duration should not be negative :sweat_smile: It seems like a timing issue for the first case. The second case looks like an issue with the timezone. 

To avoid the timing issue, we could simplify the expression and schedule the timer for the next day.

```
{
  tomorrow: today() + duration("P1D"),
  tomorrowAt9pm: date and time(tomorrow, time("21:00:00Z")),
  duration: tomorrowAt9pm - now(),
  cycle: cycle(duration)
}.cycle
```

Please check the default timezone of our environment. In SaaS, it should be UTC (i.e. `Z`).

> The cycle method is not documented (where does it come from?), I cannot play around with it as I don't know which params it takes.

Good point. The `cycle()` function is currently not documented. At the moment, it is implemented in Zeebe (see [here](https://github.com/camunda/zeebe/blob/main/feel/src/main/scala/io/camunda/zeebe/feel/impl/FeelFunctionProvider.scala#L18)). 

We may move the function to the FEEL engine and document it properly. 
Or, we find a better way to describe cycle expressions. Happy to hear suggestions.

At the moment, @lzgabel is contributing a PR #9418 to support a start time for a cycle :rocket:

**Closed** 2022-06-27 04:23 UTC
Labels: kind/feature, scope/broker, blocker/stakeholder, team/process-automation, area/bpmn-support

**Comment by Rakeshanand19** [comment] 2023-01-17 09:34
![Screenshot (1)](https://user-images.githubusercontent.com/110818738/212861857-4af32132-f6fb-4da8-a068-98c89c0cdb00.png)
i need help

**Comment by saig0** [comment] 2023-01-19 08:03
@Rakeshanand19 please look at the [docs](https://docs.camunda.io/docs/components/modeler/bpmn/timer-events/#time-cycle) on how to configure the timer event. 

If you still have a problem, please open a new issue and share all relevant information (i.e. the BPMN process, the Camunda Platform version, logs, etc.).
