### ISSUE TITLE
8.3.0,8.3.1 zeebe cluster process definition are repeatedly exported

### ISSUE THREAD

**Issue by zxuanhong** [camunda/zeebe#14868] opened 2023-10-26 08:00 UTC
**Describe the bug**

1. 8.3.0,8.3.1 zeebe Cluster process definition are repeatedly exported
2. using the redis exporter to export data, it is indeed two duplicate data, but the partition is different
4. 8.3.0
![iShot_2023-10-26_16 59 59](https://github.com/camunda/zeebe/assets/62740686/7a1f77f5-71b4-4a01-89b9-0789e7c8723d)
![iShot_2023-10-26_17 00 12](https://github.com/camunda/zeebe/assets/62740686/88a7e77d-ca57-49b4-a829-aac0a8124377)
5. 8.3.1
![iShot_2023-10-26_17 11 42](https://github.com/camunda/zeebe/assets/62740686/b9b8bbae-ae7c-4fb5-98b9-b841bfafd6d5)
![iShot_2023-10-26_17 11 54](https://github.com/camunda/zeebe/assets/62740686/1bb9a38e-bb2f-4360-a978-33fac08b4478)

6. repeated exports are bad for external analysis
7. external systems should only care about the process definition, not the partition on which the process is deployed. Repeated exports also add to the hassle of exporting data to a relational database.

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS:  linux
- Zeebe Version:  8.3.1
- Configuration:

**Comment by koevskinikola** [comment] 2023-11-08 14:51
ZPA triage:
- @korthout can you have a look at this issue?

**Comment by korthout** [comment] 2023-11-08 15:27
Hi @zxuanhong 👋 Thanks for reporting, and sorry for the delayed response.

**Regarding seeing process records on all partitions**, this is expected behavior. Each partition must be aware of deployed resources like processes. Therefore, deployments are distributed over the partitions. In 8.3, deployments are distributed over the partitions [differently than in 8.2](https://docs.camunda.io/docs/next/self-managed/operational-guides/update-guide/820-to-830/#changes-to-exported-records) and before. So, this is why you're now seeing the process record exported for each partition.

Each record refers to an entity by its unique key. If you're interested in tracking a specific process, then you can consume all events for that process. As processes exist on all partitions, you can filter on `partitionId` if you want to know whether the process exists on a specific partition. If you simply want to know whether a process exists at all, then just filter on partition 1 (which is the partition that receives the deployed process first).

**Regarding re-exporting of records from previous versions**, this is also [expected behavior](https://docs.camunda.io/docs/next/self-managed/concepts/exporters/#processing).

>Zeebe only guarantees at-least-once semantics. That is, a record is seen at least once by an exporter, maybe more.

An exporter exists per partition, so all records on all partitions are exported. That is, each record with a position on a partition is exported at least once.

**I'm closing this issue**, because there is nothing to change for us. Both exporters and processes distribution behave as expected.

**Closed by korthout** 2023-11-08 15:27 UTC
Labels: kind/bug
