### ISSUE TITLE
MultiTenancyOverIdentityIT is flaky

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#14649] opened 2023-10-09 14:58 UTC
**Summary**

See: https://github.com/camunda/zeebe/actions/runs/6452176605/job/17513814947?pr=14641

> Try to answer the following as best as possible

- How often does the test fail? **Once, as far as I know**
- Does it block your work? **Not really**
- Do we suspect that it is a real failure? **No**

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
MultiTenancyOverIdentityIT ? Execution org.testcontainers.containers.ContainerLaunchException: Container startup failed for image bitnami/keycloak:22.0.1
</pre>
</details>

**Logs**

[Link in case logs expire](https://drive.google.com/file/d/1IfdUzDZ2XqSLYnuUoTCSK64gg-uYigs2/view?usp=drive_link)

**Comment by korthout** [comment] 2024-01-19 12:45
After discussion with ZDP, this is considered unlikely to be infra related. We should inspect the logs for more details

**Comment by megglos** [comment] 2024-03-12 06:59
closing as duplicate of #15827 (this is older but the other has more activity)

**Closed by megglos** 2024-03-12 06:59 UTC
Labels: kind/flake, component/zeebe
