### ISSUE TITLE
Timer thundering herd issue

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#14882] opened 2023-10-28 20:07 UTC
**Describe the bug**

It's possible that the DueDateTimeChecker ends up causing a sort of thundering issue in Zeebe which leads to partitions becoming unavailable and eventually running out of disk space.

The following happens:

- Lots of timers are triggered at the same time, causing a large back log (note: the backlog could be caused by other things too)
- Since the Timer.TRIGGER command is not processed fast enough, the next time the `DueDateTimeChecker` runs, it appends the same TRIGGER commands again

This is then repeated until your log is full of these commands.

This occurred in a L1 incident where one segment had ~550k Timer.TRIGGER commands, and about ~2.5k on average for the same timer instances - all in a single segment (and there were tons of them, over 40GB).

Support issue: https://jira.camunda.com/browse/SUPPORT-18997

**To Reproduce**

Trigger a large number of timers, or build up a back log of other commands (internal load to avoid back pressure). The same timers are then re-triggered over and over.

**Expected behavior**

When the Timer.TRIGGER command was written and committed, we don't need to rewrite it again. An interim TRIGGERING state would be great, but that obviously has no associated command to trigger the state change =/

At least an in-memory cache would help, even if elections would disrupt that and cause the commands to be rewritten.

**Comment by Zelldon** [comment] 2023-10-29 09:09
Duplicate of https://github.com/camunda/zeebe/issues/13870

**Comment by npepinpe** [comment] 2023-10-29 09:15
Thanks, I was sure we had discussed it before but couldn't find it!

**Closed** 2023-10-29 09:16 UTC
Labels: kind/bug, severity/high, support, area/reliability, component/engine
