### ISSUE TITLE
As a user, I see that sometimes a job activation timing is too high in the long polling mode

### ISSUE THREAD

**Issue by aivinog1** [camunda/zeebe#8796] opened 2022-02-16 11:41 UTC
**Describe the bug**

Origination of the issue: https://camunda-cloud.slack.com/archives/C6WGNHV2A/p1644316881028989

So, sometimes (a frequency depends on the job timeout configured on a worker) our process instances were executed for more than 10 seconds. Sometimes that spike pops out early when we are running instances, sometimes later, but always within an hour constantly load test our cluster (5 process definitions, 2 threads for creating instances, in one of them, exists a message receive task in the middle of the process definition, 3(instances of Spring Boot Application with workers) * 14(methods that have `@ZeebeWorker` annotation) workers + 3*8 workers = 66 worker methods (2 Spring Boot applications in 3 instances), 3 Zeebe Gateways + 3 Zeebe Brokers with 5 partitions). The load is pretty small and is about 12 instances per minute (plus sending messages - is about 3 calls per minute). But when I disable long polling on our Zeebe Gateways there is no such issue: all process instances are executed normally without spikes. I'll attach some Grafana dashboards to see the picture.
![image](https://user-images.githubusercontent.com/25925932/154256917-9773f654-a997-4802-805b-b3e459be7d8c.png)
![image](https://user-images.githubusercontent.com/25925932/154256961-b3e27f96-8aca-4b27-9b3a-e4bf757c0719.png)
![image](https://user-images.githubusercontent.com/25925932/154257006-df3c0fc1-d1fe-41f7-a6be-8339687cc124.png)
![image](https://user-images.githubusercontent.com/25925932/154257031-06cdac97-c826-476b-89de-cdd08e8496b1.png)
![image](https://user-images.githubusercontent.com/25925932/154257071-faf6b68c-c109-45cb-9166-9a6bb4a12cf6.png)
![image](https://user-images.githubusercontent.com/25925932/154257096-b4a7dd2a-45c3-4842-87f1-8330071393ae.png)
![image](https://user-images.githubusercontent.com/25925932/154257248-1d55cf6d-540f-4c00-a989-c05c01b3b68e.png)
![image](https://user-images.githubusercontent.com/25925932/154257268-232968df-6a94-42cf-962b-e0fbda96fdfe.png)
![image](https://user-images.githubusercontent.com/25925932/154257288-35ac74d3-ba4c-46cf-93e0-7c1b4036de3b.png)

**To Reproduce**
1. Set up a cluster with a Zeebe Gateway and Broker
2. Create the same amount (66) of workers
2. Deploy about 5-6 BPMNs
3. Create some instances within an hour and see the Job Activation Time dashboard.
4. As soon you can see that some of the jobs have more than 10 seconds Job Activation Time - the problem was reproduced

**Expected behavior**

I expect that the job activation timing was the same (or better) in long polling mode and round-robin mode.

**Log/Stacktrace**

N/A

**Environment:**
- OS: Linux
- Zeebe Version: 1.2.9
- Configuration: 3 Gateway + 3 Brokers with 5 partitions, Elastic exporter.

**Comment by npepinpe** [comment] 2022-02-16 12:44
Could be related to the root cause of https://github.com/camunda-cloud/zeebe/issues/8622

**Comment by aivinog1** [comment] 2022-02-21 05:32
There is reproducible example: https://github.com/aivinog1/zeebe-long-polling-timeout-8796

**Comment by npepinpe** [comment] 2022-02-22 08:37
Thanks for the reproducer and the information! I think this might be related to known issues (e.g. those discussed in #8622), so I would focus on that at the moment. We can circle back here then and see if this is fixed at that point, and if not we can dig into it. But gut feeling is these are all related.

**Comment by npepinpe** [comment] 2022-04-14 07:44
Could you try reproducing it again now that https://github.com/camunda/zeebe/pull/8879 was merged?

**Comment by aivinog1** [comment] 2022-04-17 11:59
Hey @npepinpe! 
I can confirm it is not reproducing in the [my reproducible example](https://github.com/camunda/zeebe/issues/8796#:~:text=https%3A//github.com/aivinog1/zeebe%2Dlong%2Dpolling%2Dtimeout%2D8796), let me try to load test it :)

**Comment by jerry123888** [comment] 2022-04-18 07:45
> 

@npepinpe  in the test evn, i can update zeebe from 1.2.4 to 1.3.7, and works well。But when i downgrade it from 1.3.7 to 1.2.4,the zeebe broker can not start up.  More information :https://github.com/camunda/zeebe/issues/9160

**Comment by npepinpe** [comment] 2022-04-18 09:26
Thanks both! I'll mark this as solved then. Regarding downgrading, it's not possible in Zeebe to downgrade between major or minor versions, primarily because newer versions may use new features which older ones do not know, producing data an older version would not know how to process.

**Closed** 2022-04-18 09:26 UTC
Labels: kind/bug
