### ISSUE TITLE
ReplayStateTest.shouldRestoreState[TestCase{expired buffered message}] is flaky

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#14104] opened 2023-09-01 10:38 UTC
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
- Does it block your work?
- Do we suspect that it is a real failure?

```
Warning:  Flakes: 
Warning:  io.camunda.zeebe.engine.state.ReplayStateTest.shouldRestoreState[TestCase{expired buffered message}]
Error:    Run 1: ReplayStateTest.shouldRestoreState:361->lambda$testRecords$4:92 ? StreamWrapper No event found matching the criteria
[INFO]   Run 2: PASS
```

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:  Tests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 43.12 s <<< FAILURE! -- in io.camunda.zeebe.engine.state.ReplayStateTest
Error:  io.camunda.zeebe.engine.state.ReplayStateTest.shouldRestoreState[TestCase{expired buffered message}] -- Time elapsed: 5.921 s <<< ERROR!
io.camunda.zeebe.test.util.stream.StreamWrapperException: No event found matching the criteria
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.camunda.zeebe.test.util.stream.StreamWrapper.getFirst(StreamWrapper.java:91)
	at io.camunda.zeebe.engine.state.ReplayStateTest.lambda$testRecords$4(ReplayStateTest.java:92)
	at io.camunda.zeebe.engine.state.ReplayStateTest.shouldRestoreState(ReplayStateTest.java:361)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

```Error:    Run 1: ReplayStateTest.shouldRestoreState:361->lambda$testRecords$4:92 » StreamWrapper No event found matching the criteria```

[logs](https://github.com/camunda/zeebe/actions/runs/6048167898/job/16413024159?pr=14102)
[logs_87701.zip](https://github.com/camunda/zeebe/files/12497077/logs_87701.zip)

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

**Comment by abbasadel** [comment] 2023-11-10 13:18
ZPA Planning:
- This is a good candidate for mob-programming session

**Comment by korthout** [comment] 2023-11-16 14:41
While the full logs are no longer available, I think the test is flaky by nature. We also see that in [other related flaky tests](https://github.com/camunda/zeebe/issues/14596#issuecomment-1803984227).

The test works like this:
- it runs some scenario on the engine until finished
- collects the state at that time
- stops and restarts the engine
- awaits replay to finish
- collects and compares the state at this time with the previously collected state

The problem is that between collecting the state initially and collecting the state again, the engine may have made progress on new commands (e.g. those appended by scheduled tasks). 

We can make the test stable by only replaying to the last processed position of the initially collected state. However, we don't have this ability at this time. I'll open an issue to discuss adding this capability with ZDP.

**Comment by nicpuppa** [comment] 2023-11-30 14:02
ZPA Mob-Programming:

- We weren't able to reproduce the error
- Seems related to a timing issue
- We think this issue is not related to the state as @korthout mention above, because that part of the test code is not reached. The test fail at this [line](https://github.com/camunda/zeebe/blob/7a4bb2a460bf4e51e952fd05055c5afaacdf018a/engine/src/test/java/io/camunda/zeebe/engine/state/ReplayStateTest.java#L380)
- We should wait and see if the error happen again, otherwise we can close this issue

**Comment by abbasadel** [comment] 2023-12-08 13:18
ZPA planning, let's close this and open it if it happens again

**Closed by abbasadel** 2023-12-08 13:18 UTC
Labels: kind/flake
