### ISSUE TITLE
Failed to recover from snapshot

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11356] opened 2023-01-03 10:13 UTC
**Describe the bug**
> Note: not sure whether this issue is already known, haven't found it in the backlog

Error group: https://console.cloud.google.com/errors/detail/CNa4vu-PqpD--QE;service=zeebe;time=P7D?project=camunda-cloud-240911 

Leader (?) is not able to install partition, because failed to restore from snapshot with: `Caused by: java.io.FileNotFoundException`. In the error message it says leader, but [before](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22zeebe-1%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.namespace_name%3D%22699e14f0-4209-48eb-82f7-84350f87f048-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-1%22;timeRange=2023-01-03T03:18:41.131Z%2F2023-01-03T04:18:41.131Z;pinnedLogId=2023-01-03T03:48:11.033015339Z%2Fu8a0z5g0426ouw7j;summaryFields=jsonPayload%252Fcontext%252F%2522actor-name%2522:false:32:beginning;cursorTimestamp=2023-01-03T03:48:11.124249643Z?project=camunda-cloud-240911) we can see that it starts to transition to follower

```
INFO 2023-01-03T03:48:11.033015339Z [jsonPayload.context."actor-name": Broker-1-ZeebePartition-2] [resource.labels.containerName: zeebe] Transition to FOLLOWER on term 7 requested.
```

Before the error happens we see that it starts to recover the snapshot:

```
Recovering state from available snapshot: FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/511-3-729-736, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/511-3-729-736.checksum, checksum=1691091449, metadata=FileBasedSnapshotMetadata{index=511, term=3, processedPosition=729, exporterPosition=736}}
```

Partition becomes inactive.

**To Reproduce**
Not sure. But this happened during chaos experiment execution for stable/8.0 https://bru-3.operate.ultrawombat.com/7b2cd3f5-cfcc-4a65-ab22-0ccaa071e68e/processes/2251799952522165

**Expected behavior**

No issue on installing partition.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Unexpected error occurred while recovering snapshot controller during leader partition install for partition 2
	at io.camunda.zeebe.broker.system.partitions.impl.steps.ZeebeDbPartitionTransitionStep.lambda$recoverDb$0(ZeebeDbPartitionTransitionStep.java:77) ~[zeebe-broker-8.0.10-SNAPSHOT.jar:8.0.10-SNAPSHOT]
	at io.camunda.zeebe.util.sched.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-util-8.0.10-SNAPSHOT.jar:8.0.10-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:74) ~[zeebe-util-8.0.10-SNAPSHOT.jar:8.0.10-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:42) ~[zeebe-util-8.0.10-SNAPSHOT.jar:8.0.10-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:125) ~[zeebe-util-8.0.10-SNAPSHOT.jar:8.0.10-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97) ~[zeebe-util-8.0.10-SNAPSHOT.jar:8.0.10-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80) ~[zeebe-util-8.0.10-SNAPSHOT.jar:8.0.10-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189) ~[zeebe-util-8.0.10-SNAPSHOT.jar:8.0.10-SNAPSHOT]
Caused by: java.lang.RuntimeException: Failed to recover from snapshot 511-3-729-736
	at io.camunda.zeebe.broker.system.partitions.impl.StateControllerImpl.lambda$recoverInternal$3(StateControllerImpl.java:122) ~[zeebe-broker-8.0.10-SNAPSHOT.jar:8.0.10-SNAPSHOT]
	... 7 more
Caused by: java.io.FileNotFoundException
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.lambda$copySnapshot$9(FileBasedSnapshotStore.java:301) ~[zeebe-snapshots-8.0.10-SNAPSHOT.jar:8.0.10-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:72) ~[zeebe-util-8.0.10-SNAPSHOT.jar:8.0.10-SNAPSHOT]
	... 5 more
```

</p>
</details>

Logs https://drive.google.com/drive/u/0/folders/18kO6RxJjwMqnObm0z5RMXBLaRkkirxLS

**Environment:**
- OS: 
- Zeebe Version: [zeebe:8.0.10-SNAPSHOT-b5a229df56c78a809d2d6c8bd7e801edb8ab9725](https://console.cloud.google.com/errors/detail/CNa4vu-PqpD--QE;service=zeebe;version=8.0.10-SNAPSHOT-b5a229df56c78a809d2d6c8bd7e801edb8ab9725;time=P7D?project=camunda-cloud-240911) 
- Configuration:

**Comment by deepthidevaki** [comment] 2023-01-03 10:21
Same as #11334

**Comment by megglos** [comment] 2023-02-03 08:19
Just to confirm my understanding, this is suspected to be related to #11334 due to the fact that files were manipulated, leading to the FileNotFoundException. The assumption is that this must have been another broker instance concurrently accessing the data dir?
Would move it to the backlog as of now as well, it would be good to protect from such conflicts but I wouldn't consider it a prio right now.

**Comment by deepthidevaki** [comment] 2023-02-03 08:48
You can also close this issue as #11334 covers this case.

**Comment by megglos** [comment] 2023-02-03 08:49
closing as duplicate of #11334

**Closed by megglos** 2023-02-03 08:49 UTC
Labels: kind/bug, severity/low, component/partition-transitions
