### ISSUE TITLE
Benchmark CW43 stuck in restart

### ISSUE THREAD

**Issue by nicpuppa** [camunda/zeebe#14904] opened 2023-10-30 14:12 UTC
**Describe the bug**

We observe that there is less throughput in CW43. We see that one of the pod is stuck in restarting

Have a look at the [grafana dashboard](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=Prometheus&var-cluster=All&var-namespace=medic-y-2023-cw-43-978e69c-benchmark&var-pod=All&var-partition=All&from=now-3h&to=now&refresh=10s)

Here the link to the [logs](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22medic-y-2023-cw-43-978e69c-benchmark%22%0Alabels.k8s-pod%2Fapp%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22zeebe-broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22medic-y-2023-cw-43-978e69c-benchmark%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fpart-of%3D%22camunda-platform%22%0Alabels.%22k8s-pod%2Fstatefulset_kubernetes_io%2Fpod-name%22%3D%22medic-y-2023-cw-43-978e69c-benchmark-zeebe-0%22;cursorTimestamp=2023-10-30T12:04:02.722362961Z;startTime=2023-10-30T12:02:56.000Z;endTime=2023-10-30T12:04:08.000Z?project=zeebe-io), also available on [GDrive](https://drive.google.com/drive/folders/1S6bnBgyN46m7AuGDJZf1-Uz81uIb3Gbq) 

![Screenshot 2023-10-30 at 15 08 53](https://github.com/camunda/zeebe/assets/72783243/09caf37a-14a3-4bd1-8b78-7790e29ab709)

**Comment by deepthidevaki** [comment] 2023-11-02 07:24
Could be the DNS issue https://camunda.slack.com/archives/C05DH1F5TAR/p1698657187605209

**Comment by npepinpe** [comment] 2023-11-02 13:04
We'll treat it as a duplicate of https://github.com/camunda/zeebe/issues/14885 for now

**Closed by npepinpe** 2023-11-02 13:04 UTC
Labels: kind/bug
