### ISSUE TITLE
CI: Performance Build Fails with SBE Parse Errors

### ISSUE THREAD

**Issue by berkaycanbc** [camunda/zeebe#16182] opened 2024-02-01 14:38 UTC
**Summary**

There are recent failures in our CI. It indicates that some fields are not found.
> Try to answer the following as best as possible

- How often does the test fail? 2
- Does it block your work? no
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Failure 1</summary>
<pre>
```
ERROR: at <sbe:message name="SnapshotChunk"> <data name="snapshotId"> could not find type: varDataEncoding
ERROR: at <sbe:message name="SnapshotChunk"> <data name="chunkName"> could not find type: varDataEncoding
Warning:  
java.lang.IllegalStateException: had 2 errors
    at uk.co.real_logic.sbe.xml.ErrorHandler.checkIfShouldExit (ErrorHandler.java:107)
    at uk.co.real_logic.sbe.xml.XmlSchemaParser.parse (XmlSchemaParser.java:141)
    at uk.co.real_logic.sbe.SbeTool.parseSchema (SbeTool.java:349)
    at uk.co.real_logic.sbe.SbeTool.main (SbeTool.java:250)
    at org.codehaus.mojo.exec.ExecJavaMojo.lambda$execute$0 (ExecJavaMojo.java:283)
    at java.lang.Thread.run (Thread.java:1583)
```
</pre>
</details>

Build link: https://github.com/camunda/zeebe/actions/runs/7738038413/job/21098091741
<details><summary>Failure 2</summary>
<pre>
```
[INFO] Building Zeebe Msgpack Value 8.5.0-SNAPSHOT                      [27/52]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]   from msgpack-value/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
WARNING: at <sbe:message name="RaftLogEntry"> <field name="type"> name is not valid for Golang: type
ERROR: at <sbe:message name="ConfigurationEntry"> <group name="newMembers"> could not find dimensionType: groupSizeEncoding
WARNING: at <group name="newMembers"> <field name="type"> name is not valid for Golang: type
ERROR: at <group name="newMembers"> <data name="memberId"> could not find type: varDataEncoding
ERROR: at <sbe:message name="ConfigurationEntry"> <group name="oldMembers"> could not find dimensionType: groupSizeEncoding
WARNING: at <group name="oldMembers"> <field name="type"> name is not valid for Golang: type
ERROR: at <group name="oldMembers"> <data name="memberId"> could not find type: varDataEncoding
ERROR: at <sbe:message name="Configuration"> <group name="newMembers"> could not find dimensionType: groupSizeEncoding
WARNING: at <group name="newMembers"> <field name="type"> name is not valid for Golang: type
ERROR: at <group name="newMembers"> <data name="memberId"> could not find type: varDataEncoding
ERROR: at <sbe:message name="Configuration"> <group name="oldMembers"> could not find dimensionType: groupSizeEncoding
WARNING: at <group name="oldMembers"> <field name="type"> name is not valid for Golang: type
ERROR: at <group name="oldMembers"> <data name="memberId"> could not find type: varDataEncoding
ERROR: at <sbe:message name="Meta"> <data name="votedFor"> could not find type: varDataEncoding
Warning:  
java.lang.IllegalStateException: had 9 errors
    at uk.co.real_logic.sbe.xml.ErrorHandler.checkIfShouldExit (ErrorHandler.java:107)
    at uk.co.real_logic.sbe.xml.XmlSchemaParser.parse (XmlSchemaParser.java:141)
    at uk.co.real_logic.sbe.SbeTool.parseSchema (SbeTool.java:349)
    at uk.co.real_logic.sbe.SbeTool.main (SbeTool.java:250)
    at org.codehaus.mojo.exec.ExecJavaMojo.lambda$execute$0 (ExecJavaMojo.java:283)
    at java.lang.Thread.run (Thread.java:1583)
```
</pre>
</details>

Build link: https://github.com/camunda/zeebe/actions/runs/7689834075/job/20952827631#step:7:1617

**Comment by npepinpe** [comment] 2024-02-01 14:39
Duplicate of https://github.com/camunda/zeebe/issues/16029

**Closed by npepinpe** 2024-02-01 14:39 UTC
Labels: kind/bug, area/build, component/build-pipeline
