### ISSUE TITLE
Major sudden performance drop after running for some time

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#9862] opened 2022-07-22 07:53 UTC
**Describe the bug**

A user opened a support issue about a major performance drop (going from ~460 PI/s throughput to ~3 PI/s) after running for 2 days with constant load.

**To Reproduce**

They run a benchmark with 4 brokers, 15 partitions, replication factor 3, using our benchmark worker/starter. One special config is that RocksDB is only given 128MB per partition, and there is no Elasticsearch exporter involved. The process deployed is the `ten_tasks.bpmn` and the payload the workers use is the `small_payload.json`. There are 6 starters and 16 workers.

Starter config:

```yaml
          - name: JAVA_OPTIONS
            value: >-
              -Dapp.starter.rate=75
              -Dapp.starter.durationLimit=0
              -Dapp.starter.burst=1
              -Dapp.starter.bpmnXmlPath=bpmn/ten_tasks.bpmn
              -Dapp.starter.processId=benchmark
              -Dapp.starter.threads=50
              -Dzeebe.client.requestTimeout=62000
```

Worker config:

```yaml
          - name: JAVA_OPTIONS
            value: >-
              -Dzeebe.client.requestTimeout=62000
              -Dapp.worker.capacity=50
              -Dapp.worker.pollingDelay=1ms
              -Dapp.worker.completionDelay=1ms
              -Dapp.worker.completeJobAsync=false
              -Dapp.worker.payloadPath=bpmn/small_payload.json
              -XX:+HeapDumpOnOutOfMemoryError
```

**Expected behavior**

Performance remains constant.

**Log/Stacktrace**

You can find more in the support ticket: https://jira.camunda.com/browse/SUPPORT-14046

**Comment by npepinpe** [comment] 2022-07-25 15:55
I've started reproducing the test. The `ten_tasks.bpmn` process is modified and the timers are dropped.

**Comment by npepinpe** [comment] 2022-08-01 09:23
So the problem happened now last night, we can hopefully make progress and root cause it.

**Comment by npepinpe** [comment] 2022-08-04 11:27
Some notes:

The benchmark is `np-swift` on the long running cluster. I had to heavily customize the Helm charts for this, so if you need to reproduce it ask me (I can write down later what I did).

The problem occurred on the 2022-07-31 around 22:45 CEST.

There were some pod restarts before the problem occurred. I failed to discover why exactly the pods restarted - I confirmed the nodes were _not_ restarted/pre-empted, the application was not shutdown, and there is logs indicating anything happened. There is a lot of activity coming from `RemoteConnection` about requests not having matching handlers, which can happen when someone sends a response to via the inter-cluster transport and to node X, and node X fails to correlate the request ID to any handler. Other than that, nothing special seems to happen and the pods are simply...killed? Evicted? I looked at the GKE events and nothing special popped out. The only events around that time are that the mirror pods are deleted, which makes sense, but nothing indicates why the pod would have been removed in the first place.

Anyhow, once this happens, the interesting parts are:

- Backpressure sky rockets
- # of job related requests goes way down (as expected)
- # of create instance requests remains the same (since the client doesn't care about RESOURCE_EXHAUSTED)
- # of keys in RocksDB also sky rockets. the memory usage remains more or less the same, but the size of the live data also increases fast
- processing duration increases, but not by a ridiculous amount. it goes from 100-250ms to ~500ms
- write & commit latency remains pretty much the same, suggesting I/O is not a bottleneck. indeed write/read I/O goes down, but that could simply indicate not much is happening anymore at that level
- overall processing cycle time, job activation time, all increase and are in the 10+, inf bucket, so hard to say what the real times are. however there is no big backlog of unprocessed records, but as mentioned, processing duration increased. perhaps a 2x-3x times increase per command is enough to cause this drop in performance? it would be surprising, but I didn't do the math there. perhaps it's enough to cause the vegas limit to drop so low.
- CPU is still very much in use, so it's definitely doing something. Overall memory usage is fine, as the pods have 32GiB each, and only a fraction is in use.
- looking at the heap dump, not much stands out. the stream processors are processing (as you can also see in the metrics), everything is healthy. actor queues are very small, which is supported by the async-profiler analysis we ran which shows we try often to steal jobs from other actor queues. this would also support the idea that the few jobs we have enqueued are just, well, slow.
- I thought it could be the snapshot replication loop issue which occurs on leader change in older versions, but according to logs/metrics no replication is ongoing. I didn't dig into the heap dump to verify this, however.


Attached below are two flamegraphs from yesterday, one using `itimer` mode and one `wall` mode.

itimer

![flamegraph-2022-08-03_14-05-08](https://user-images.githubusercontent.com/43373/182836089-17c1cac6-3f43-4b71-96ce-82546c5a81bd.svg)

wall

![flamegraph-2022-08-03_15-27-27](https://user-images.githubusercontent.com/43373/182836103-96681d14-d152-46d6-a363-5afc53cc6d8e.svg)

**Comment by Zelldon** [comment] 2022-08-04 11:35
Just small input:

![metric](https://user-images.githubusercontent.com/2758593/182837373-44169412-f416-447f-b971-94767d2c3241.png)

At the point where the latency spikes and never comes back the queue size went up again and never comes back, which might be the reason why the latency never comes back. 

Maybe we have a hick up which causes the queue to grow, like long gc pause? Can you verify that?

**Comment by Zelldon** [comment] 2022-08-04 11:37
There was GC activity at this point. 

Maybe we need to check whether the values are correctly calculated and maybe higher than shown?

![Uploading gc.png…]()

**Comment by romansmirnov** [comment] 2022-08-08 14:41
Some notes from my investigations on "what causes the performance drop?". Therefore, I focused on 2022-07-31 between 11:10 pm to 11:59 pm.

When looking at the "Processing per Partition" graph, this timeframe can be divided into 3 different throughput patterns (yellow arrows) and 5 different phases:
![image](https://user-images.githubusercontent.com/2368139/183425496-ad419015-d85f-49de-9a06-1f2cd5c8e77e.png)

In a nutshell, the overall performance drops at 10:32 pm, eventually reaching its "plateau" at around 11:30 pm.

Re `p1`: Each throughput pattern (yellow arrows) can be assigned to a specific Zeebe broker. It can be observed that the throughput differs and is not evenly distributed across the brokers. However, the throughput remains stable in this phase (since many days).

Re `p2`:  At around 10:32 pm, the throughput drops, i.e., the processing per partition decreases, the overall processing latency increases, the Grpc request latency increases, job activation time, and others increase as well.

![image](https://user-images.githubusercontent.com/2368139/183428796-1e9b1ef9-9cf9-48ab-8d72-cb77a3e95bc9.png)
![image](https://user-images.githubusercontent.com/2368139/183428600-1d35bfe7-90c0-443b-8055-f8c0fb5a9235.png)

Most affected by this drop is the broker `np-swift-zeebe-0`. The records written and processed decreased from ~11k to ~7.5k.

![image](https://user-images.githubusercontent.com/2368139/183430213-ed29a408-59c0-45e0-94d0-486c1e7836d7.png)

Around that time, on this node, the following can be observed:

* The "Record Processing Duration" is a bit more spread and can take up 50 ms (and in some cases, it reaches ~750ms):
![image](https://user-images.githubusercontent.com/2368139/183430821-66929986-aac6-4280-9073-5877e8b434a3.png)
* The Commit Latency increases; for example, the 99-quantile increases from 49.5ms to 73.7ms
![image](https://user-images.githubusercontent.com/2368139/183431237-c3259617-2909-4b40-b316-4e5194274c4f.png)
* Also, the "Record Write Latency" increases; for example, the 90-quantile increases from 9ms to 20ms
![image](https://user-images.githubusercontent.com/2368139/183431865-1f9f6293-2978-4f12-bf75-29073c46ec13.png)

On the other nodes, it can be observed that the "Overall processing latency" increases as well, and the commit latency fluctuates much more during this time, but the overall processed and written records per partition remain stable in this phase.

Re `p3`: At around 10:45 pm, the nodes get restarted, leading to leader changes, etc. It is not clear why the nodes got restarted. Also, it took a while until the system went back into a stable state (i.e., all partitions have a leader, records are replicated, ...).

Most noticeable, during this phase, there is some GC activity (but it is not clear if this caused the node restarts):
![image](https://user-images.githubusercontent.com/2368139/183435541-48d6a020-26b2-41ea-a0cf-e6abadfd7f49.png)

Re `p4`: With a few exceptions, the system is back on track

![image](https://user-images.githubusercontent.com/2368139/183436269-040f1368-88b2-4915-9940-cfb7f22c1429.png)

But the system starts more process instances as it compltes which potentially means the amount of inflight process instances increases in the system.

Re `p5`: At around 11:30 pm, the performance drops further. Again around this time, the overall processing latency increases further, the record processing duration is spread more widely, etc. 

![image](https://user-images.githubusercontent.com/2368139/183440720-2408ff3f-5bad-446c-99ff-55b164167b2e.png)
![image](https://user-images.githubusercontent.com/2368139/183440799-a03074d5-4633-4e63-bfff-268c75009fd3.png)

In this phase, all node/partitions are affected by that drop. However, this results in the following latencies:

![image](https://user-images.githubusercontent.com/2368139/183441553-56b222de-a3a1-4a4a-a010-b180abfab439.png)
![image](https://user-images.githubusercontent.com/2368139/183441695-b7494abf-2290-4a2b-bae3-2a5644cab140.png)

Basically, the overall processing latency increases slowly over time. And in terms of record processing duration, there are two types of duration clusters, i.e., there are some records which processing takes around 500ms and other records that are just executed in a few milliseconds.

However, according to the Grafana dashboard, there is nothing obvious that could potentially be correlated to this phase (or which caused it).

---

Unfortunately, the data does not provide any option to drill down into the data, for example, to understand which commands takes much of the time to get executed, etc. My current assumption is that the execution duration of some commands increases over time, causing an increase in the overall processing latency, etc.

@npepinpe, to get such insights, would be okay if I implement some more metrics and start another test run? WDYT?

**Comment by romansmirnov** [comment] 2022-08-08 14:42
Sorry, forgot to mention that @Zelldon and I also checked some of the Google Cloud metrics to understand if there is any kind of throttling happening. But we couldn't find anything obvious.

**Comment by npepinpe** [comment] 2022-08-08 14:44
I also wanted to get more granular processing metrics, specifically the value type + intent, to know exactly what is using up all the time :+1: The only problem is that reproducing this took a week last time, and I don't have many ideas on how to speed this up =/ We don't lose anything from starting a new load test however, so let's do it :+1:

**Comment by romansmirnov** [comment] 2022-08-10 06:14
@npepinpe, I opened a temporary PR to sync on the metrics, see #10051. Just to confirm, are you okay with that? If so, then I would build an Docker image to run a new test (next week, as I am off for two day) 😄

**Comment by Zelldon** [comment] 2022-08-10 06:47
Sorry to interfere here but might make sense to add some more fine granular metrics as well, like:

* how long does it take to write to the dispatcher (we maybe have loops here https://github.com/camunda/zeebe/pull/10051/files#diff-f7f005cc99c7e4b3bde9aed2a12c3d77a49f3eea8ab217be4a37586382cd8b01R383-R411
* how long does rocksdb commit take https://github.com/camunda/zeebe/pull/10051/files#diff-f7f005cc99c7e4b3bde9aed2a12c3d77a49f3eea8ab217be4a37586382cd8b01R418

**Comment by npepinpe** [comment] 2022-08-11 08:23
> how long does writing to disk in general take

Don't we already have this in the Raft metrics? Or do you mean something else?

Other than that I agree, more engine metrics would be useful to really pin point where we spend time in the engine.

**Comment by npepinpe** [comment] 2022-08-15 08:41
Adding some more reproduction steps, as it's not currently possible to use the Helm charts to reproduce the benchmark completely.

You can deploy the Helm chart with the set up already available on the branch `medic-cw-benchmarks` under `benchmarks/setup/np-swift`. There's some extra steps required after an install though:

1. Edit the zeebe statefulset:
  - remove the Elasticsearch exporter from the container spec's environment variables
  - add the gateway port to the container spec
2. Delete the Elastic cronjob
3. Edit the gateway service to grab the zeebe-broker nodes

**Comment by romansmirnov** [comment] 2022-08-15 09:04
@Zelldon & @npepinpe, thanks for your input. I've updated the PR #10051 by adding additional metrics to measure each state in `ProcessingStateMachine`. (I haven't added any additional metrics to measure writing to disk, as to my understanding, this is already covered by the Raft metrics.)

Unless there aren't any remarks, I would start another test run of the benchmark tomorrow morning. @npepinpe, I most likely will need your support to start the benchmark. I will approach you then 😄

**Comment by Zelldon** [comment] 2022-08-15 09:36
Just to make it easier to reproduce you could also run `helm template` and adjust the generated manifests :) \cc @npepinpe

**Comment by npepinpe** [comment] 2022-08-16 12:56
There's a manifest.yml in there which you can apply now. It deploys Zeebe, but not the worker/starter. To install, you run `kubectl apply -n np-swift -f manifest.yml`, and to clean, you'd have to run `kubectl delete -n np-swift -f manifest.yml && kubectl delete -n np-swift pvc -l app.kubernetes.io/instance=np-swift`.

**Comment by npepinpe** [comment] 2022-08-16 12:58
I also added a Grafana alert for when average processing dips below 1500 records processed per minute (e.g. 25 records per second) per partition.

**Comment by romansmirnov** [comment] 2022-08-24 11:21
With the additional metrics (provided with #10051), there are two types of commands with an increasing processing duration:
1. The command to activate jobs whereby.
![image](https://user-images.githubusercontent.com/2368139/186355758-efec7a94-857f-49a7-8caf-358336fc5a0c.png)
2. The command to complete an element.
![image](https://user-images.githubusercontent.com/2368139/186356161-5d6c2b3e-fa60-4aa1-ad97-908ed80e3330.png)

Most of the time to process these commands is spent in the actual processor. When looking at the command activate jobs, the processor does two things:
1. Iterate over the column family `activatableColumnFamily` to get the next jobs to activate in RocksDB.
2. For each job to activate, it collects the necessary variables by going through the scope up to the process instance scope. Therefore, it needs to access the `variablesColumnFamily` to find the variables in RocksDB.

According to that, the command to activate jobs is mostly interacting with the RocksDB. So to get a better understanding of what is happening in RocksDB, I have introduced further metrics:
* `rocksdb_mem_table_hit_ratio`: When reading data from RocksDB, it first looks up the data in the `memtable`.  This metric measures the ratio of hits to all look-ups; the formula for this metric is: `hits/(hits + misses)`.
* Block Cache Metrics: If data is not found in the `memtable`, the block cache is accessed.
  * `rocksdb_block_cache_filter_hit_ratio`: Measures the hit ratio for filter blocks.
  * `rocksdb_block_cache_index_hit_ratio`: Measures the hit ratio for index blocks.
  * `rocksdb_block_data_cache_hit_ratio`: Measures the hit ratio for data blocks.
* `rocksdb_l0_hit_count`: Number of `Get()` queries served L0.
* `rocksdb_l1_hit_count`: Number of `Get()` queries served L1.
* `rocksdb_l2_and_up_hit_count`: Number of `Get()` queries served L2 and up.

Just for context, when RocksDB reads data it follows roughly this access pattern, if the data was not found in the `memtable(s)` (some pseudo-code):
```
for each (level) {
  for each (sst in current level) {
    1. Get filter block to check if the key is present in sst or not
      a. Get filter block from block cache;
      b. If filter not found in cache -> retrieve and cache the filter from the sst by accessing the file
      c. If filter found in cache-> check if key is potentially present in the sst
      d. If the key is not present -> continue (i.e., check the next sst)
    2. Get index block to get the block's position which includes the requested key
      a. Get index block from block cache
      b. If index not found in cache -> retrieve and cache the index from the sst by accessing the file
      c. If index found in cache -> get the block's position which contains the key
    3. Get data block
      a. Get data block from block cache
      b. If data block not found in cache -> retrieve and cache block from the sst by accessing the file
      c. If data block is found in cache -> return data for the requested key
  }
}
```

In addition to that, Zeebe configures RocksDB in a way, that
1. The cached filter and index blocks are part of the block cache.
2. L0 filter and index blocks are pinned to the block cache, meaning the block cache will treat them with priority and evict filter and index blocks of > L0 if the block cache's capacity is reached
3. The block cache uses 30% of the configured memory limit. In this case, the memory limit is set 128MB resulting ~42MB block cache capacity.

https://github.com/camunda/zeebe/blob/9850804ff4b196943b8a27bcebb454e62237abb1/zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/ZeebeRocksDbFactory.java#L253-L258

However, with these metrics, we see the following
![image](https://user-images.githubusercontent.com/2368139/186364071-9cbbecbc-ff71-4ad7-873c-bd818fdbd6e7.png)

* The `memtable` hit ratio drops very quickly to ~30%, meaning only ~30% of the reads are served by the `memtable`.
* At 1:37 pm, the filter block cache hits ratio drops for a moment to ~63%, and thus, the number of activated and completed jobs drops as well.
* The index and data block ratio remains stable at ~100% at this moment, meaning the necessary blocks could be found in the block cache (no additional file access was necessary).
* At ~1:50 pm, the situation changes, and the filter block cache hit ratio drops first to ~48%, then ~15%, and then ~0%. With that, the performance of Zeebe drops significantly. Only when the filter block cache hit ratio increases for a moment, we also see an increase in Zeebe's performance - which doesn't stay long.
* Already before 1:50 pm, we see that the most hits are in L2 and up. After 1:50 pm almost all hits are in L2 and up, and only a few in L0.

Moving the time forward, we also see that the index and data block cache hit ratio drops over time:
![image](https://user-images.githubusercontent.com/2368139/186366483-c71c6d0d-d872-467b-8ad1-6575a0ae36f9.png)

When checking the stats that RocksDB dumps regularly to the logs, we can see that roughly ~98% of data is in L2 and above (and only ~2% of the data is in L1). That corresponds with the hits in L2 and above.
![image](https://user-images.githubusercontent.com/2368139/186373087-2e4d74da-0673-4505-b09e-482d8253300c.png)

**What causes the performance drop?**

The `activatableColumnFamily` behaves as a FIFO queue, meaning jobs to activate are retrieved from the head of the queue, and new jobs are added to the tail of the queue. When more process instances are started than completed, Zeebe creates more jobs than it actually completes (by considering that the workers don't bottleneck in any way).
![image](https://user-images.githubusercontent.com/2368139/186378565-78260140-2383-4136-9809-6c4bc5f48ac5.png)

That again causes the following
* The job's queue grows so that the job activation latency increases (i.e., it takes longer until a job gets activated).
* The longer it takes to activate a job, the more likely it is that the job's data ends up in L2 or above in RocksDB.
* The more data ends up in L2 or above, the more it is likely that the sst's filter block is not in a cache because the filter block got evicted from the cache. This results, in reading the filter block from the file multiple times. Hence, reading jobs to activate becomes slow.
* And last but not least, this increases job activation latency again. So, Zeebe is now in a kind of loop where the state is steadily growing, and the job activation latency is also increasing further.

**Why does does the state grow in the first place?**

With tests we have run in the past few days, I was able to identify these scenarios:
1. Iterating over 15 partitions to activate jobs takes too long
2. Increasing record write and commit latency
3. Failover scenarios

Please note, some of tests ran for many days without any issue (i.e., the number of started and completed process instance were equal), and then suddenly, the situation changed. But there were also test runs in which already from beginning there was a gap between started and completed process instances. So that, in these tests the performance drop was already after a few hours. Nevertheless, the causes for these happenings are more or less the same.

*Re 1- Iterating over 15 partitions to activate jobs takes too long*

See #4696 

*Re 2- Increasing record write and commit latency*

When a node/pod gets write throttled, then the record write and commit latency increases. So that, the latency between receiving a command and executing the command increases. With that latency increase, the back pressure for that partition also increases. Hence, more requests are rejected with the resource exhausted status on that partition.

This has at least two implications:
* The partition got slower, impacting the activate jobs request latency (see 1).
* The rejected requests are forwarded to the next partition. 

In the latter case, when receiving resources exhausted as a response, the gateway will forward the request to the next partition, for example, when starting a process instance. Consequently, other partitions receive more commands/requests (i.e., the load increases). With a higher load per partition, the latency between receiving and processing a command also increases on other partitions. Which again leads to an increase in back pressure, etc.

Due to high back pressure, fewer jobs are activated - and completed - so that fewer process instances are completed eventually. But since the starters are aggressively trying to start new instances, a relatively high number of process instances still get started. This results in a gap between started and completed process instances.

*Re 3- Failover scenarios*

There were some failover scenarios causing a back pressure of 100% what again caused the cycle described previously (see 2.):
* For partition `x`, both followers where restarted so that newly received commands could not get committed. Resulting in 100% back pressure.
* After getting leader for partition `x`, the leader had to replay the last ~15 minutes as the last snapshot is already ~15 minutes old. It could take a few minutes up to ~10 minutes. During that time, the backpressure was at 100%.

**Comment by npepinpe** [comment] 2022-11-16 17:48
I believe we have a solid understand of the issue, but no real solution planned as of yet. I'm putting this back in the backlog as I don't think we're tackling this at the moment, and I'll bring it up when it comes to our upcoming performance hackweek.

**Comment by megglos** [comment] 2022-11-17 08:24
@npepinpe sounds good to me
From my understanding part of the problem is high job activation latency which we are continuing with this epic https://github.com/camunda/product-hub/issues/540
the other being throttling may also get mitigated by making progress on the epic focuses on disk latency/reduction of performed IOPS https://github.com/camunda/product-hub/issues/642

While or once we make progress on those we should reassess their impact on this problem.

**Comment by npepinpe** [comment] 2023-02-07 19:41
I thought about this a bit more, and I think we could offer more configurable memory distribution for customers. The memory allocation right now is made to be simple, and based on recommendations from the RocksDB team, e.g. 30% of the total memory budget is allocated for the cache.

While this works pretty well when we mostly deal with data in L0, for long living instances we may want to have a different allocation, or at least allow users to configure different things. Since the write path for SWIFT seems fine with the current memtable config, we could allow them to configure the cache/index separately from the memtable. This increases the complexity of our API/UI/UX/whatever you want to call it, but it may alleviate the issue here. It won't completely solve it due to how we prioritize older data, but it may still help.

**Comment by npepinpe** [comment] 2023-02-07 20:41
I thought about this a bit more, and I think we could offer more configurable memory distribution for customers. The memory allocation right now is made to be simple, and based on recommendations from the RocksDB team, e.g. 30% of the total memory budget is allocated for the cache.

While this works pretty well when we mostly deal with data in L0, for long living instances we may want to have a different allocation, or at least allow users to configure different things. Since the write path for the user seems fine with the current memtable config, we could allow them to configure the cache/index separately from the memtable. This increases the complexity of our API/UI/UX/whatever you want to call it, but it may alleviate the issue here. It won't completely solve it due to how we prioritize older data, but it may still help.

**Comment by npepinpe** [comment] 2023-02-13 13:56
I would like to test a few things here:

- Remove the memory pinning behavior, hopefully provide more cache space when fetching "old" data
- Different cache/buffer memory sharing ratio

This would possibly mitigate the issue.

**Comment by megglos** [comment] 2023-04-28 09:47
ZDP-Planning:
closing for now as we have similar topics ongoing such as https://github.com/camunda/zeebe/issues/11813

**Closed by megglos** 2023-04-28 09:47 UTC
Labels: kind/bug, severity/high, support, component/engine, component/gateway
