### ISSUE TITLE
`UnsupportedOperationException: null` on Broker shutdown

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#11027] opened 2022-11-17 09:24 UTC
**Describe the bug**

During Broker shutdown an `UnsupportedOperationException` was thrown. This happened in the `ActorTask` where we have a `Queue` of `ActorJobs`, named `submittedJobs`. When the `ActorTask` is closed this queue is set to a `ClosedQueue`. This is a queue of which all operations are not implemented.

**To Reproduce**

I don't know

**Expected behavior**

It would be nice of no exception is thrown. It doesn't matter much as this is during shutdown.

**Log/Stacktrace**

[downloaded-logs-20221117-102328.json.zip](https://github.com/camunda/zeebe/files/10029819/downloaded-logs-20221117-102328.json.zip)

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.lang.UnsupportedOperationException: null
	at io.camunda.zeebe.scheduler.ClosedQueue.isEmpty(ClosedQueue.java:24) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorTask.tryWait(ActorTask.java:351) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorTask.onAllJobsDone(ActorTask.java:184) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:159) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.2.jar:8.1.2]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.2.jar:8.1.2] 
```

</p>
</details>

**Environment:**
- OS: SaaS
- Zeebe Version: 8.1.2

**Comment by megglos** [comment] 2022-11-25 10:42
moving to backlog as impact is not severe

**Comment by korthout** [comment] 2023-08-25 09:56
Closing as duplicate of:
- https://github.com/camunda/zeebe/issues/8025

**Closed** 2023-08-25 09:56 UTC
Labels: kind/bug, component/partition-transitions
