### ISSUE TITLE
Advise OS on mmap usage

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#11377] opened 2023-01-08 15:09 UTC
**Description**

I ran a test which showed a clear performance improvement when advising the OS on how we would use the memory mapped segment files using [madvise](https://man7.org/linux/man-pages/man2/madvise.2.html).

> **Note** There's also a POSIX variant which is more portable called [posix_madvise](https://linux.die.net/man/3/posix_madvise). Note however that it has less flags/options.

In my test, I used only `MADV_SEQUENTIAL`. I would recommend we implement the following:

- [ ] Add native LibC bindings to `madvise` via jnr-ffi (feel free to use something else if it makes sense)
- [ ] When we load a segment (new or existing), advise the OS of the `MADV_SEQUENTIAL`. **This yields a notable performance improvement**. This is likely due to reducing read I/O (via more aggressive read-ahead), thereby reducing read/write I/O contention.

If possible, evaluate the following as well:

- [ ] When a reader/writer is pointing to a segment, advise the OS about the `MADV_WILLNEED` flag to trigger read-ahead immediately.
- [ ] When no readers/writers are pointing to a segment, advise the OS about the `MADV_DONTNEED` (or on Linux, `MADV_PAGEOUT`/`MADV_COLD`). This will advise the OS to free those pages first (I believe `MADV_PAGEOUT` is to free immediately).

The latter two can be done as a follow up depending on how much time is spent in the first two.

**Comment by npepinpe** [comment] 2023-01-14 17:10
One thing to note, which I came across while working on something else: using `MADV_SEQUENTIAL` when the backing file is already in memory (e.g. tmpfs) will result in worse performance and way more minor page faults. When the file is in tmpfs, using `MADV_RANDOM` yields better performance actually.

**Comment by npepinpe** [comment] 2023-01-16 16:29
Before going on, I'll quickly recap how mmap works, and how paging works. Processes work by accessing virtual memory, which is often larger than the physical memory available. The memory (both virtual and physical) is divided into pages (typically on Linux, these are 4KB, but you can find out by running `getconf PAGESIZE`). Since not all the memory for your process will be present in main memory at any given time, the MMU holds a mapping of virtual pages to physical pages.

> **Note** This is grossly simplified, and ignores things like CPU caches.

When you memory map a file into your process, it's entirely mapped into virtual memory. This doesn't mean it's in actual physical memory, or that it's even mapped to your process' physical memory. When you start accessing it, if its contents are not in physical memory, a major page-fault will occur. This will cause the OS to load a page (or more), which in most systems in 4KB (you can find out by running `getconf PAGESIZE`). Sometimes, the file contents may be in physical memory already but not assigned to your process in the MMU (e.g. this is a shared mapping, and another process has already caused loading of the page in physical memory). In this case, you will get a minor page fault, and the MMU has to map the virtual page with the existing physical page. In this case however, no I/O will occur.

**Comment by npepinpe** [comment] 2023-01-16 16:37
Anyway, so it really bothered me that I saw no difference in page faults regardless of the madvise setting used.

I ran more tests, both with and without the solution described in #11416. I could not reproduce the initial results which indicated improved latency/throughput.

I can still reliably reproduce that read I/O is noticeably reduced on higher load (with madvise it never goes above the hundreds of KB/s, whereas without it regularly stays above a few MB/s), but that's the only really noticeable change I'm confident in.

I also ran smaller scoped, unit tests to try and understand why we were not seeing less page-faults (neither major nor minor) when using `MADV_SEQUENTIAL`. There is a process in the kernel, especially when paging files from disk, called fault-around (you can read some performance data about it [here](https://lwn.net/Articles/588802/)). This process will eagerly about 16 pages whenever a page fault occurs (you can find out what the setting is on your kernel by running `cat /sys/kernel/debug/fault_around_bytes`).

This could explain how we already benefit from read-ahead in general without any special setting. But it could also be that generally we're bottlenecked not by I/O (as we discovered with our experiments with async flush) but by commit latencies, and so this approach simply doesn't show immediate benefits (yet).

I would keep it open but in the backlog.

Further things to look into that we not in the above:

- [ ] If segments are small, we may consider mapping them with `MAP_POPULATE`, which will load the entire file in memory immediately and create the page mappings (i.e. prefault the file). This does require new LibC bindings however as Java does not provide this with its standard library.

**Comment by Zelldon** [comment] 2023-01-16 16:57
Thanks for All the details @npepinpe quite interesting 👍

Just a thought regarding not able to reproduce, can this be related to using smaller nodes now with the recent helm chart release?

**Comment by npepinpe** [comment] 2023-01-16 17:00
It could be either this, or smaller disks, or a combination. As we saw during the hack week, in our environment/workload, I/O is not a bottleneck, so it's possible we hit something else :shrug: I didn't dig deeper. I think it's unlikely we will see a big difference anyway even on customer use cases, but we could always try again there after the upcoming improvements - at the very least it may make the application more I/O and memory friendly, which isn't such a bad thing in general.

**Comment by npepinpe** [comment] 2023-02-16 13:21
As a first test, try using the existing methods `#load` and `#unload` methods of the buffer, which call `madvise` under the hood with [MADV_WILLNEED](https://github.com/openjdk/jdk/blob/c29a13678744522503f899bdf5f4c13f130942f7/src/java.base/unix/native/libnio/MappedMemoryUtils.c#L107) and [MADV_DONTNEED](https://github.com/openjdk/jdk/blob/c29a13678744522503f899bdf5f4c13f130942f7/src/java.base/unix/native/libnio/MappedMemoryUtils.c#L118) respectively.

**Comment by deepthidevaki** [comment] 2023-03-01 07:46
We evaluated this again. 
1. Advice `MADV_SEQUENTIAL` when loading a segment. Cherry-picked comment from previous POC - https://github.com/camunda/zeebe/commit/5c3ec6dea753562f3f0bf8bc42335b6b46fbc4c6 
2. Remove MADV_SEQUENTIAL. Advice `MADV_WILLNEED` when a reader move to next segment, and when the writer for the segment is created.

Throughput
Base: 190 PI/s
M_Sequential: 175-188 PI/s (more fluctuating compared to base)
M_WillNeed: 175 PI/s

Read Bytes:
Base: > 20MB/s
M_Sequential: ~1KB/s
M_WillNeed:: < 20MB/s

We didn't observe any improvement with madvice, instead there was a slight negative impact on throughput. 

It might help if we use madvice more intelligently, instead of always advising when a reader/writer is created. But we decided not to invest more time on this.

I'm closing this issue for now. Please re-open or open another issue, if you find anything interesting related to this and would like to evaluate.

**Closed by deepthidevaki** 2023-03-01 07:46 UTC
Labels: kind/toil, area/performance
