### ISSUE TITLE
`RaftTest.testDemoteLeader` is unstable

### ISSUE THREAD

**Issue by oleschoenburg** [camunda/zeebe#14548] opened 2023-09-29 12:32 UTC
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Once that I know of
- Does it block your work? No
- Do we suspect that it is a real failure? Probably not but we should investigate

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Error:    Run 1: RaftTest.testDemoteLeader:238->ConcurrentTestCase.await:110 ? Timeout Test timed out while waiting for an expected result, expectedResumes: 2, actualResumes: 1
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

[Flaky RaftTest.zip](https://github.com/camunda/zeebe/files/12765358/Flaky.RaftTest.zip)

**Comment by npepinpe** [comment] 2023-10-09 10:22
One weird thing that popped up in the logs:

```
05:41:41.193 [] DEBUG io.atomix.raft.roles.LeaderAppender - RaftServer{1} - Failed to configure 4
```

Now this comes from LeaderAppender.java:325, and the 4 is supposedly the member ID...except the test explicitly only creates 3 servers - 1, 2, and 3. So why would we try and configure 4? :shrug:

**Comment by npepinpe** [comment] 2023-10-09 10:29
The test does plenty of weird things that confuse me. The nodes are restarted multiple times, it appends tons of entries...but this doesn't match what it should be doing.

**Comment by npepinpe** [comment] 2023-10-09 12:32
Extracted the relevant logs: https://gist.github.com/npepinpe/2b4c2356a4e1bb43a7afa65ae1897d29

**Comment by npepinpe** [comment] 2023-10-09 12:39
The question is: which resume did not run? Was it because the follower never transitioned its own view of the old leader to passive? Or was it because the `demote` request never completed?

Let's build a timeline:

- [Member 1 became leader initially](https://gist.github.com/npepinpe/2b4c2356a4e1bb43a7afa65ae1897d29#file-gistfile1-txt-L50)
- [Demotion occurs](https://gist.github.com/npepinpe/2b4c2356a4e1bb43a7afa65ae1897d29#file-gistfile1-txt-L157)

**Comment by npepinpe** [comment] 2023-10-09 13:35
Super easy way to reproduce (maybe?) : if you set the configure timeout to a high value (e.g. 1 hour), it consistently fails. So the configure request only completed before by timing out and retrying? That doesn't sound expected for me... :thinking:

**Comment by oleschoenburg** [comment] 2023-10-10 15:38
Thanks for your analysis and fix @npepinpe  :+1: 

While I was going through the logs, I noticed several related issues that contributed to this test breaking. Rejecting append requests made while the leader role is closed is "just" a workaround.

Firstly, the joint configuration entry is wrong!
```
05:41:46.245 [] TRACE io.atomix.raft.roles.LeaderAppender - RaftServer{1} - Sending ConfigureRequest{term=1, leader='1', index=2, timestamp=1695966106223, newMembers=[DefaultRaftMember{id=3, type=ACTIVE, updated=2023-09-29T05:41:44.974602303Z}, DefaultRaftMember{id=2, type=ACTIVE, updated=2023-09-29T05:41:44.974602303Z}, DefaultRaftMember{id=1, type=PASSIVE, updated=2023-09-29T05:41:44.974602303Z}], oldMembers=[DefaultRaftMember{id=3, type=ACTIVE, updated=2023-09-29T05:41:44.974602303Z}, DefaultRaftMember{id=2, type=ACTIVE, updated=2023-09-29T05:41:44.974602303Z}, DefaultRaftMember{id=1, type=PASSIVE, updated=2023-09-29T05:41:46.223Z}]} to 2
```

:lady_beetle:  `oldMembers` should contain member 1 with type `ACTIVE`. Instead, member 1 appears as `PASSIVE` in both `oldMembers` and `newMembers`. This is caused by not copying `DefaultRaftMember`s, these objects are mutable.

 :lady_beetle: Secondly, I think it's unexpected that the demoted leader steps down as soon as it has committed the joint configuration entry, it should only step down once it is completely removed from the configuration, i.e. once it has committed a normal configuration entry where `oldMembers` is empty and `newMembers` has the leader as `PASSIVE`. This is caused by a bug where we just update member types based on the order of members in the configuration. We probably need to use the highest type of the member, regardless of whether that is from `oldMembers` or `newMembers`.

:lady_beetle: Thirdly, after the previous leader was demoted to `PASSIVE`, the other members request votes. This is caused by a bug where we don't remove demoted members from the list of active, remote members.

**Comment by npepinpe** [comment] 2023-10-10 16:14
Considering this code was heavily modified during the dynamic scaling epic, does it makes sense to investigate those as part of that epic?

**Comment by oleschoenburg** [comment] 2023-10-10 16:15
@npepinpe Yes, I'm preparing an independent fix now. I think rejecting appends when the leader role is close still makes sense though - I would just say it doesn't close this issue here.

**Comment by npepinpe** [comment] 2023-10-10 16:16
I updated the PR description to not close the issue on merge :+1:

**Closed** 2023-10-11 11:33 UTC
Labels: kind/flake, component/raft
