### ISSUE TITLE
Worker receiving writer is full instead of resource exhausted

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#15235] opened 2023-11-16 12:27 UTC
**Describe the bug**

I was running a benchmark and looked at[ the workers log ](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22ck-poc-blocking-executor-wip-benchmark%22%0Alabels.k8s-pod%2Fapp%3D%22worker%22;pinnedLogId=2023-11-16T11:50:53.298693876Z%2F6bvjxgcy1zw9g1f5;cursorTimestamp=2023-11-16T11:50:53.298693876Z;duration=PT1H?project=zeebe-io)(quite a while since I did this last time).

There were many logs, and some indicated an INTERNAL error. Taking a look at the stacktrace and message it showed to me that this should be more a resource exhausted instead of a INTERNAL error.

It is a bit unclear for the user/client what to do with this message to be honest.

**To Reproduce**

Run a benchmark I guess? See PR for which I run the benchmark https://github.com/camunda/zeebe/pull/15234

**Expected behavior**

Returning an Resource exhausted exception instead of a general INTERNAL error.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: Unexpected error occurred between gateway and broker (code: INTERNAL_ERROR) (message: Failed to write client request to partition '1', because the writer is full.)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.camunda.zeebe.ResponseChecker.run(ResponseChecker.java:43) [classes/:?]
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Unexpected error occurred between gateway and broker (code: INTERNAL_ERROR) (message: Failed to write client request to partition '1', because the writer is full.)
	at io.grpc.Status.asRuntimeException(Status.java:537) ~[grpc-api-1.59.0.jar:1.59.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481) ~[grpc-stub-1.59.0.jar:1.59.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-api-1.59.0.jar:1.59.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-api-1.59.0.jar:1.59.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-api-1.59.0.jar:1.59.0]
	at io.micrometer.core.instrument.binder.grpc.MetricCollectingClientCallListener.onClose(MetricCollectingClientCallListener.java:57) ~[micrometer-core-1.12.0.jar:1.12.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574) ~[grpc-core-1.59.0.jar:1.59.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72) ~[grpc-core-1.59.0.jar:1.59.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742) ~[grpc-core-1.59.0.jar:1.59.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[grpc-core-1.59.0.jar:1.59.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.59.0.jar:1.59.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.59.0.jar:1.59.0]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.4.x, 8.3.x, etc
- Configuration:

**Comment by npepinpe** [comment] 2023-11-16 13:20
Closed as duplicate of https://github.com/camunda/zeebe/issues/13018

**Closed by npepinpe** 2023-11-16 13:20 UTC
Labels: kind/bug, scope/broker, severity/mid, area/ux
