### ISSUE TITLE
NoSuchElementException when looking up transformed definition during deployment

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#11734] opened 2023-02-17 13:11 UTC
**Describe the bug**

It seems like during a deployment, after transforming the definitions, there was a case (twice) where we were unable to find the deployment in the transformed definitions.

Link to error group: https://console.cloud.google.com/errors/detail/CM_e_rP419icrgE;service=zeebe;time=P7D?project=camunda-cloud-240911

I'm classing it as mid, as it impacts that specific deployment, though the user would most likely not know what to do with this cryptic error message.

**To Reproduce**

Unclear as the deployment failed, so I don't know how to get the process itself. We could try asking the user if we can't figure out anything else.

**Expected behavior**

After transforming a set of process definitions for a given process, I would expect to be able to find the process by ID in the transformed definitions. I assume we opted for a `orElseThrow` because this is a case which essentially shouldn't happen.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.util.NoSuchElementException: No value present
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.updateInMemoryState(DbProcessState.java:180) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.lookupProcessByIdAndPersistedVersion(DbProcessState.java:314) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getLatestProcessVersionByProcessId(DbProcessState.java:217) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.transformProcessResource(BpmnResourceTransformer.java:138) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$transformResource$0(BpmnResourceTransformer.java:77) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.util.Either$Right.map(Either.java:355) ~[zeebe-util-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.lambda$transformResource$1(BpmnResourceTransformer.java:75) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:366) ~[zeebe-util-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.transform.BpmnResourceTransformer.transformResource(BpmnResourceTransformer.java:65) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transformResource(DeploymentTransformer.java:120) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.transform.DeploymentTransformer.transform(DeploymentTransformer.java:97) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.processing.deployment.DeploymentCreateProcessor.processRecord(DeploymentCreateProcessor.java:96) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:264) ~[zeebe-stream-platform-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:260) ~[zeebe-stream-platform-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:209) ~[zeebe-stream-platform-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:185) ~[zeebe-stream-platform-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.2.0-alpha4.jar:8.2.0-alpha4]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.2.0-alpha4.jar:8.2.0-alpha4] 
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.2.0-alpha4
- Configuration: SaaS

**Comment by korthout** [comment] 2023-02-17 16:18
Duplicate of #11414

**Comment by npepinpe** [comment] 2023-02-17 16:23
If you're confident, then let's close it :+1:

**Comment by korthout** [comment] 2023-02-17 16:24
Problem is that we cannot reproduce that issue.

I was quickly investigating if there's any new info we can take from this. But it's not possible to retrieve the actual process model from here. So, IMO we can close this.

Thanks for reporting though 👍

**Closed by korthout** 2023-02-17 16:24 UTC
Labels: kind/bug, severity/mid
