### ISSUE TITLE
Parallel Multiple Instance Service Task Worker hangs for 5 minutes

### ISSUE THREAD

**Issue by berndruecker** [camunda/zeebe#8622] opened 2022-01-20 11:21 UTC
**Describe the bug**
When running one BPMN process instance with a MI Service Task with 5,000 instances in parallel you can see that the Java worker pauses for 5 minutes:
![grafik](https://user-images.githubusercontent.com/1217596/150328960-6134acdc-553f-48bf-b3e7-1ac65e4520ab.png)

Also visibible in Grafana:
![grafik](https://user-images.githubusercontent.com/1217596/150328765-f91f48a2-fb33-4ff2-8f50-a0c58f7fb286.png)

Current observations suggest:

- This only happens with long polling enabled in the Gateway (I just tested with CC SaaS, so I always have this enabled, but @dominikhorn93 tested with CCSM and long polling deactivated => no problems
- It happens only with the Java client, they reported it works with NodeJS without problems (this puzzles me a bit)
- It only happens with the MI task, if you run 5,000 process instances with one MI in parallel -> no problem.

**To Reproduce**

- Check out this project: https://github.com/FlowSquad/zeebe-benchmark
- Start and go to HTTP://localhost:8081/swagger-ui.html
- Start test:

![grafik](https://user-images.githubusercontent.com/1217596/150328697-cf7e5fdc-2701-49d3-bdef-54a30a0ab9ad.png)

I did this on this cluster: https://bru-2.operate.camunda.io/c8114adc-cea1-4bf9-9aaa-c91be1360359/instances/4503599627494386

**Expected behavior**

No pause in the worker

**Environment:**
 - Zeebe Version:1.3.0
 - Configuration: CC SaaS

**Comment by Zelldon** [comment] 2022-01-20 11:52
Hey @berndruecker I think the 5 minutes are because of the default job timeout.

In general it can happen that jobs are activated and blocked for the defined timeout. One reason is for example client closed the connection, there is an open issue to fix such problems https://github.com/camunda-cloud/zeebe/issues/3631

I think the nodejs has a smaller default job timeout

**Comment by berndruecker** [comment] 2022-01-20 13:22
The customer confirmed that reducing the job & connection timeout does help for this case:

```
          - name: ZEEBE_CLIENT_REQUEST_TIMEOUT
            value: "10s"
          - name: ZEEBE_CLIENT_JOB_TIMEOUT
            value: "10s"
```

**Comment by Zelldon** [comment] 2022-01-20 15:51
If we open the worker later, this doesn't happen so it seems to be related to the long polling.

```

    // when
    final var processInstanceKey =
        clientRule.createProcessInstance(
            deployedProcessKey, Map.of("parallelAmount", parallelAmount));

    clientRule
        .getClient()
        .newWorker()
        .jobType("firstJob")
        .handler((c, j) -> c.newCompleteCommand(j).send())
        .fetchVariables("")
        .open();
```

Test also succeeds if we disable long polling (request timeout is negative)

```
    clientRule
        .getClient()
        .newWorker()
        .jobType("firstJob")
        .handler((c, j) -> c.newCompleteCommand(j).send())
        .fetchVariables("")
        .requestTimeout(Duration.ofMillis(-1))
        .open();
```

**Comment by Zelldon** [comment] 2022-01-21 05:49
Looking deeper into the issue. The problem is the following:

We can see [in the log](https://github.com/camunda-cloud/zeebe/files/7910697/io.camunda.zeebe.it.clustering.JobActivationTest-output.txt) that the first successful activated job batch, is immediately followed with another job batch. The first job batch is completely ignored. The COMPLETE commands start with the job keys of the second job batch. For the jobs in the first job batch we see no complete commands in the whole log.

```
...
E JOB                CREATED        - #30029->#05023 K20011 - K20011 "firstJob" @"Activity_0xi8cz5"[K05008] 3 retries, in <process "benchmark"[K00003]> (no vars)
E PROC_INST          ACTIVATED      - #30030->#05023 K05008 - SERVICE_TASK "Activity_0xi8cz5" in <process "benchmark"[K00003]>
E JOB_BATCH          ACTIVATED      - #30031->#05032 K20012 - "firstJob" 32/32
                         K05014 "firstJob" @"Activity_0xi8cz5"[K00009] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05017 "firstJob" @"Activity_0xi8cz5"[K00010] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05020 "firstJob" @"Activity_0xi8cz5"[K00011] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05023 "firstJob" @"Activity_0xi8cz5"[K00012] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05026 "firstJob" @"Activity_0xi8cz5"[K00013] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05029 "firstJob" @"Activity_0xi8cz5"[K00014] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05032 "firstJob" @"Activity_0xi8cz5"[K00015] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05035 "firstJob" @"Activity_0xi8cz5"[K00016] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05038 "firstJob" @"Activity_0xi8cz5"[K00017] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05041 "firstJob" @"Activity_0xi8cz5"[K00018] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05044 "firstJob" @"Activity_0xi8cz5"[K00019] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05047 "firstJob" @"Activity_0xi8cz5"[K00020] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05050 "firstJob" @"Activity_0xi8cz5"[K00021] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05053 "firstJob" @"Activity_0xi8cz5"[K00022] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05056 "firstJob" @"Activity_0xi8cz5"[K00023] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05059 "firstJob" @"Activity_0xi8cz5"[K00024] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05062 "firstJob" @"Activity_0xi8cz5"[K00025] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05065 "firstJob" @"Activity_0xi8cz5"[K00026] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05068 "firstJob" @"Activity_0xi8cz5"[K00027] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05071 "firstJob" @"Activity_0xi8cz5"[K00028] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05074 "firstJob" @"Activity_0xi8cz5"[K00029] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05077 "firstJob" @"Activity_0xi8cz5"[K00030] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05080 "firstJob" @"Activity_0xi8cz5"[K00031] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05083 "firstJob" @"Activity_0xi8cz5"[K00032] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05086 "firstJob" @"Activity_0xi8cz5"[K00033] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05089 "firstJob" @"Activity_0xi8cz5"[K00034] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05092 "firstJob" @"Activity_0xi8cz5"[K00035] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05095 "firstJob" @"Activity_0xi8cz5"[K00036] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05098 "firstJob" @"Activity_0xi8cz5"[K00037] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05101 "firstJob" @"Activity_0xi8cz5"[K00038] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05104 "firstJob" @"Activity_0xi8cz5"[K00039] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05107 "firstJob" @"Activity_0xi8cz5"[K00040] 3 retries, in <process "benchmark"[K00003]> (no vars)
E JOB_BATCH          ACTIVATED      - #30032->#25868 K20013 - "finish" max: 32
E JOB_BATCH          ACTIVATED      - #30033->#25869 K20014 - "firstJob" 32/32
                         K05110 "firstJob" @"Activity_0xi8cz5"[K00041] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05113 "firstJob" @"Activity_0xi8cz5"[K00042] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05116 "firstJob" @"Activity_0xi8cz5"[K00043] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05119 "firstJob" @"Activity_0xi8cz5"[K00044] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05122 "firstJob" @"Activity_0xi8cz5"[K00045] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05125 "firstJob" @"Activity_0xi8cz5"[K00046] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05128 "firstJob" @"Activity_0xi8cz5"[K00047] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05131 "firstJob" @"Activity_0xi8cz5"[K00048] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05134 "firstJob" @"Activity_0xi8cz5"[K00049] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05137 "firstJob" @"Activity_0xi8cz5"[K00050] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05140 "firstJob" @"Activity_0xi8cz5"[K00051] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05143 "firstJob" @"Activity_0xi8cz5"[K00052] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05146 "firstJob" @"Activity_0xi8cz5"[K00053] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05149 "firstJob" @"Activity_0xi8cz5"[K00054] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05152 "firstJob" @"Activity_0xi8cz5"[K00055] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05155 "firstJob" @"Activity_0xi8cz5"[K00056] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05158 "firstJob" @"Activity_0xi8cz5"[K00057] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05161 "firstJob" @"Activity_0xi8cz5"[K00058] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05164 "firstJob" @"Activity_0xi8cz5"[K00059] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05167 "firstJob" @"Activity_0xi8cz5"[K00060] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05170 "firstJob" @"Activity_0xi8cz5"[K00061] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05173 "firstJob" @"Activity_0xi8cz5"[K00062] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05176 "firstJob" @"Activity_0xi8cz5"[K00063] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05179 "firstJob" @"Activity_0xi8cz5"[K00064] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05182 "firstJob" @"Activity_0xi8cz5"[K00065] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05185 "firstJob" @"Activity_0xi8cz5"[K00066] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05188 "firstJob" @"Activity_0xi8cz5"[K00067] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05191 "firstJob" @"Activity_0xi8cz5"[K00068] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05194 "firstJob" @"Activity_0xi8cz5"[K00069] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05197 "firstJob" @"Activity_0xi8cz5"[K00070] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05200 "firstJob" @"Activity_0xi8cz5"[K00071] 3 retries, in <process "benchmark"[K00003]> (no vars)
                         K05203 "firstJob" @"Activity_0xi8cz5"[K00072] 3 retries, in <process "benchmark"[K00003]> (no vars)
E JOB_BATCH          ACTIVATED      - #30034->#25870 K20015 - "secondJob" max: 32
C JOB                COMPLETE       - #30035->    -1 K05110 - K05110 -1 retries, in <process ?[?]> (no vars)
C JOB                COMPLETE       - #30036->    -1 K05113 - K05113 -1 retries, in <process ?[?]> (no vars)
...
```

**Comment by Zelldon** [comment] 2022-01-21 07:07
### End of Analysis

I added new log statements and run the test several times. 

```
07:48:03.487 [GatewayLongPollingJobHandler] [-zb-actors-0] ERROR io.camunda.zeebe.gateway - ACTIVATE JOBS FOR REQ 1 [complete: false, canceled: false, timedout: false]
07:48:03.557 [GatewayLongPollingJobHandler] [-zb-actors-0] ERROR io.camunda.zeebe.gateway - ENQUE REQ 1 DUE TO INCOMPLETION
07:48:04.417 [GatewayLongPollingJobHandler] [-zb-actors-0] ERROR io.camunda.zeebe.gateway - ACTIVATE JOBS FOR REQ 1 [complete: false, canceled: false, timedout: false]
07:48:13.557 [GatewayLongPollingJobHandler] [-zb-actors-0] ERROR io.camunda.zeebe.gateway - REMOVE REQ 1 DUE TO TIMEOUT 
07:48:24.378 [io.camunda.zeebe.gateway.impl.broker.BrokerRequestManager] [gateway-scheduler-zb-actors-0] ERROR io.camunda.zeebe.gateway - GOT RESPONSE FOR REQ 1. SUBMIT JOB. [completed: true, canceled: false, isTimedout: true]
07:48:24.379 [GatewayLongPollingJobHandler] [-zb-actors-0] ERROR io.camunda.zeebe.gateway - HANDLE RESPONSE FOR REQ 1. SUBMIT JOB. [completed: true, canceled: false, isTimedout: true]
07:48:24.379 [GatewayLongPollingJobHandler] [-zb-actors-0] ERROR io.camunda.zeebe.gateway - NOT SEND RESPONSE FOR REQ 1, [completed: true, canceled: false, isTimedout: true]
07:48:24.379 [GatewayLongPollingJobHandler] [-zb-actors-0] ERROR io.camunda.zeebe.gateway - MARK REQ 1 AS COMPLETE
07:48:24.379 [GatewayLongPollingJobHandler] [-zb-actors-0] ERROR io.camunda.zeebe.gateway - REQ 1 IS ALREADY COMPLETE. [completed: true, canceled: false, isTimedout: true]
```

As written before the first job batch activation is always the one which is ignored. The problem here is that the job request timeout is reached, before we get a response from the broker. This is because the broker has such a big backlog, with a huge multiinstance collection that sending a response for an activate command can take > 10 seconds, which is bigger then our request timeout.


### Possible Workarounds and Solutions

**Workarounds:**

 * User could configure the `requestTimeout` to be high enough to over come this issue
 * User could configure the job timeout smaller so that the impact is not that high

**Solutions**

 * We implement https://github.com/camunda-cloud/zeebe/issues/3631 to give jobs back
 * Or we implement another solution to give the activated jobs to another request, if it is a worker it is likely it that it will request another time (soon)

**Comment by korthout** [comment] 2022-01-21 07:28
>Or we implement another solution to give the activated jobs to another request, if it is a worker it is likely it that it will request another time (soon)

I guess this is fine as long as it is the same worker, because the jobs have been activated for a specific worker (stored in the job record value).

**Comment by Zelldon** [comment] 2022-01-21 07:33
Yep this I wanted to say. We should only give it to the same worker. I think we can keep the response in the gateway as long as the job timeout is. If the worker comes back in the meantime we can directly send the response back.

**Comment by korthout** [comment] 2022-01-21 07:36
I agree, it has a better feeling and will be more performant than #3631, but if there is no open request at that time, you'll still run into this issue. #3631 is a more general solution although not optimal in case another request is open. IMO we should first focus on resolving the problem as broadly as we can, and then optimize.

**Comment by Zelldon** [comment] 2022-01-21 07:40
>  IMO we should first focus on resolving the problem as broadly as we can, and then optimize.

Not 100% sure what this means. What would be the resolution and what the optimization in your opinion?

BTW who really needs the job worker name in the record? Afaik operate doesn't care. If we would be able to remove that property or not set it anymore we could give the response to any worker/activate request with the same job type.

**Comment by npepinpe** [comment] 2022-01-21 08:33
Regarding buffering the jobs in the gateway and returning them to the next worker request - this is semi OK, but not sure how it works with multiple gateway instances. I think it could also be problematic with low job time outs.

Removing the worker name wouldn't make each request interchangeable, since different workers will have different settings like job time out. You could argue, well, why would you have two workers configured differently consuming the same jobs? And I'd say you probably wouldn't, but I can guarantee someone somewhere will do that at some point, and conceptually there's nothing in our API that prevents or even hints you shouldn't do that, so they would be right to do so.

In the end, all the solutions are mitigations though - that the client closed the call and the gateway knows about it is a best case scenario, sometimes the gateway thinks it did send those jobs. The only correct thing would be for the client to acknowledge the jobs were received (before they're processed) - if the client call is closed before, then the gateway can re-activate those jobs. That's a pretty complex solution though (compared to the existing one anyway).

Regardless, all ideas so far aren't things we can do in between current KRs, so unfortunately all we can do is bring it up to our stakeholders and hope it gets planned.

**Comment by korthout** [comment] 2022-01-21 09:45
> >MO we should first focus on resolving the problem as broadly as we can, and then optimize.
> 
> Not 100% sure what this means. What would be the resolution and what the optimization in your opinion?

You proposed 2 solutions:
>- We implement Make activated jobs which were not send to clients re-activatable #3631 to give jobs back
>- Or we implement another solution to give the activated jobs to another request, if it is a worker it is likely it that it will request another time (soon)

I meant to give my opinion on which of these should have higher priority.

**Comment by npepinpe** [comment] 2022-04-14 07:44
Marking as tentatively fixed by https://github.com/camunda/zeebe/pull/8879

**Closed by npepinpe** 2022-04-14 07:44 UTC
Labels: kind/bug, scope/broker, area/performance, severity/high, scope/gateway
