### ISSUE TITLE
Missing resourceKey property when deleting a resource causes an endless error loop

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#16429] opened 2024-02-16 17:43 UTC
**Describe the bug**

See the following report: https://console.cloud.google.com/errors/detail/CI7Z3fDnpK-ZOw;service=zeebe;time=P7D?project=camunda-saas-prod

**Expected behavior**

Validation is performed on the command preemptively such that no exception is thrown.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 io.camunda.zeebe.msgpack.MsgpackPropertyException: Property 'resourceKey' is invalid: Expected a value or default value to be specified, but has nothing
at io.camunda.zeebe.msgpack.property.BaseProperty.resolveValue ( io/camunda.zeebe.msgpack.property/BaseProperty.java:65 )
at io.camunda.zeebe.msgpack.property.BaseProperty.getEncodedLength ( io/camunda.zeebe.msgpack.property/BaseProperty.java:71 )
at io.camunda.zeebe.msgpack.value.ObjectValue.getEncodedLength ( io/camunda.zeebe.msgpack.value/ObjectValue.java:203 )
at io.camunda.zeebe.msgpack.value.ObjectValue.getEncodedLength ( io/camunda.zeebe.msgpack.value/ObjectValue.java:141 )
at io.camunda.zeebe.protocol.impl.record.UnifiedRecordValue.getEncodedLength ( io/camunda.zeebe.protocol.impl.record/UnifiedRecordValue.java:36 )
at io.camunda.zeebe.msgpack.UnpackedObject.getLength ( io/camunda.zeebe.msgpack/UnpackedObject.java:57 )
at io.camunda.zeebe.protocol.impl.record.UnifiedRecordValue.getLength ( io/camunda.zeebe.protocol.impl.record/UnifiedRecordValue.java:30 )
at io.camunda.zeebe.stream.impl.records.RecordBatchEntry.createEntry ( io/camunda.zeebe.stream.impl.records/RecordBatchEntry.java:35 )
at io.camunda.zeebe.stream.impl.records.RecordBatch.appendRecord ( io/camunda.zeebe.stream.impl.records/RecordBatch.java:46 )
at io.camunda.zeebe.stream.impl.BufferedProcessingResultBuilder.appendRecordReturnEither ( io/camunda.zeebe.stream.impl/BufferedProcessingResultBuilder.java:59 )
at io.camunda.zeebe.stream.api.ProcessingResultBuilder.appendRecord ( io/camunda.zeebe.stream.api/ProcessingResultBuilder.java:33 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryRejectingIfUserCommand ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:523 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.onError ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:442 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:309 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:232 )
at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord ( io/camunda.zeebe.stream.impl/ProcessingStateMachine.java:208 )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( io/camunda.zeebe.scheduler/ActorJob.java:94 )
at io.camunda.zeebe.scheduler.ActorJob.execute ( io/camunda.zeebe.scheduler/ActorJob.java:47 )
at io.camunda.zeebe.scheduler.ActorTask.execute ( io/camunda.zeebe.scheduler/ActorTask.java:122 )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( io/camunda.zeebe.scheduler/ActorThread.java:130 )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( io/camunda.zeebe.scheduler/ActorThread.java:108 )
at io.camunda.zeebe.scheduler.ActorThread.run ( io/camunda.zeebe.scheduler/ActorThread.java:227 ) 
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.4.3

**Affected Versions:**
- Zeebe Version: 8.4.3
- Zeebe Version: 8.1.24
- Zeebe Version: 8.2.23
- Zeebe Version: 8.3.7

**Workaround:**
- restart affected broker

**Comment by berkaycanbc** [comment] 2024-02-20 13:22
@npepinpe I couldn't find information about the related cluster, did this happen on benchmark a cluster? I am asking to better assess the severity of it.

**Comment by oleschoenburg** [comment] 2024-02-20 14:24
@berkaycanbc You can click on the error reporting link and then look at the logs from there. These include namespace names etc.

**Comment by oleschoenburg** [comment] 2024-02-20 15:49
In the process of validating https://github.com/camunda/zeebe/pull/16491, I think I've come up with a very easy way to reproduce this: Send a `DeleteResource` request with a wrong `resourceKey`.

**Comment by npepinpe** [comment] 2024-02-20 16:51
My bad, I missed that as the cluster where this originally occurred was already bricked thanks to call activity recursion

**Comment by megglos** [comment] 2024-02-20 16:53
@berkaycanbc as you are assigned currently, can you take this right away and work on a fix, please?

**Comment by oleschoenburg** [comment] 2024-02-20 16:54
May have been caused by recent refactorings here: https://github.com/camunda/zeebe/issues/16107
However, the fact that I was only able to reproduce this in a benchmark environment makes me suspect that it's not.

**Comment by berkaycanbc** [comment] 2024-02-21 08:19
> @berkaycanbc You can click on the error reporting link and then look at the logs from there. These include namespace names etc.

@oleschoenburg Yeah, but the cluster was not available, so I couldn't gather cluster information.

**Comment by rodrigo-lourenco-lopes** [comment] 2024-02-21 09:53
@berkaycanbc This has occurred again in our benchmarks here: https://console.cloud.google.com/errors/detail/CI7Z3fDnpK-ZOw;service=zeebe;time=P7D?project=zeebe-io

**Comment by deepthidevaki** [comment] 2024-02-21 15:09
Me and @berkaycanbc  had a short look at this. There are two issues.

1. Hypothesis: Engine.error handling was never called. Instead it directly was handled by the new "error loop prevention" logic. To be validated and root cause.
2. While handling the error in the error loop prevention logic, we reset the record value before writing the rejection record. It seems this can fail, because not all record values set a default which fails writing the rejection record => thus entering the error loop. The assumption that "empty" records can be written successfuly was wrong. So we have to handle that differently.

**Comment by ludanfeng** [comment] 2024-02-22 07:12
So, is it safe to use version 8.4.1?

**Comment by berkaycanbc** [comment] 2024-02-22 11:12
We root caused the issue with @deepthidevaki. Our hypothesis was correct and the second issue that Deepthi mentioned is still valid. There are two issues to be resolved:

1) Engine error handling was never called because we reset `errorOnRetries` too early. 

While processing the first delete resource command, the `errorOnRetries` is increased and `errorHandlingPhase` is updated to `ErrorHandlingPhase.USER_COMMAND_PROCESSING_FAILED`. In the meantime, if scheduler tries to read next record, it resets the `errorOnRetries` value here:
https://github.com/camunda/zeebe/blob/86828ff3fd3caef48b3229c1f717466b35c955eb/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java#L208-L215
without necessarily processing the next command. That leads to `errorHandlingPhase` got stuck in value `ErrorHandlingPhase.USER_COMMAND_PROCESSING_FAILED` value until the next error.

That leads to incorrect behaviour and the expectation is to reset it after each processing.

2) As @deepthidevaki mentioned above:
> While handling the error in the error loop prevention logic, we reset the record value before writing the rejection record. It seems this can fail, because not all record values set a default which fails writing the rejection record => thus entering the error loop. The assumption that "empty" records can be written successfully was wrong. So we have to handle that differently.

This issue still needs to be fixed because even if the first case is fixed, there is still possibility to end up with attempting to write empty records.

@deepthidevaki started working on a fix. 👍

**Comment by deepthidevaki** [comment] 2024-02-22 13:34
https://github.com/camunda/zeebe/pull/16520 fixes the root cause (issue 1) mentioned above. The second issue is not critical (it is not a regression). It would be fixed in a follow up.

**Comment by skayliu** [comment] 2024-02-23 07:45
It's there necessary to provide a default value for `resourceKey` in L19, like L20 did?

https://github.com/camunda/zeebe/blob/main/protocol-impl/src/main/java/io/camunda/zeebe/protocol/impl/record/value/resource/ResourceDeletionRecord.java#L19-L20

**Closed** 2024-02-26 09:28 UTC
Labels: kind/bug, severity/critical, impact/high, likelihood/low

**Comment by garima-camunda** [comment] 2024-02-26 10:03
Customer faced this issue in https://jira.camunda.com/browse/SUPPORT-20798
