### ISSUE TITLE
Can this project run on the arm64 platform?

### ISSUE THREAD

**Issue by aisong** [camunda/zeebe#10578] opened 2022-09-30 06:16 UTC
It got the error when run StandaloneBroker in IDEA:

java.util.concurrent.CompletionException: java.lang.UnsatisfiedLinkError: /private/var/folders/4w/586x04kx6nxdgj4w6b13030h0000gn/T/librocksdbjni16549020263278982060.jnilib: dlopen(/private/var/folders/4w/586x04kx6nxdgj4w6b13030h0000gn/T/librocksdbjni16549020263278982060.jnilib, 0x0001): tried: '/private/var/folders/4w/586x04kx6nxdgj4w6b13030h0000gn/T/librocksdbjni16549020263278982060.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]

What can I do?

os: macos 12.4 
chip: Apple M1 Pro

<img width="1400" alt="QQ20220930-141358@2x" src="https://user-images.githubusercontent.com/8147898/193202968-296880cb-d2d9-4e59-bdb4-28ec2d4f9c36.png">

**Comment by Zelldon** [comment] 2022-09-30 06:17
Duplicate of  https://github.com/camunda/zeebe/issues/6155, please add your comment their.

**Closed by Zelldon** 2022-09-30 06:17 UTC
