### ISSUE TITLE
Can't get patition statub because partition is `null`

### ISSUE THREAD

**Issue by koevskinikola** [camunda/zeebe#15241] opened 2023-11-16 15:03 UTC
**Describe the bug**

A `NullPointerException` is thrown when `BrokerAdminServiceImpl#getPartitionStatus()` is called.

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.broker.system.partitions.ZeebePartition.getCurrentRole()" because "partition" is null

at io.camunda.zeebe.broker.system.management.BrokerAdminServiceImpl.getPartitionStatus ( io/camunda.zeebe.broker.system.management/BrokerAdminServiceImpl.java:115 )
at io.camunda.zeebe.broker.system.management.BrokerAdminServiceImpl.lambda$getPartitionStatus$1 ( io/camunda.zeebe.broker.system.management/BrokerAdminServiceImpl.java:92 )
at io.camunda.zeebe.broker.system.management.BrokerAdminServiceImpl.lambda$getPartitionStatus$4 ( io/camunda.zeebe.broker.system.management/BrokerAdminServiceImpl.java:99 )
at io.camunda.zeebe.scheduler.ActorControl.lambda$call$0 ( io/camunda.zeebe.scheduler/ActorControl.java:75 )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( io/camunda.zeebe.scheduler/ActorJob.java:88 )
at io.camunda.zeebe.scheduler.ActorJob.execute ( io/camunda.zeebe.scheduler/ActorJob.java:47 )
at io.camunda.zeebe.scheduler.ActorTask.execute ( io/camunda.zeebe.scheduler/ActorTask.java:120 )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( io/camunda.zeebe.scheduler/ActorThread.java:130 )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( io/camunda.zeebe.scheduler/ActorThread.java:108 )
at io.camunda.zeebe.scheduler.ActorThread.run ( io/camunda.zeebe.scheduler/ActorThread.java:227 )
```

</p>
</details>

**Environment:**
- OS:  Camunda SaaS Dev
- Zeebe Version:  `8.3.2`
- Configuration: 
- [GCP logs (internal)](https://drive.google.com/file/d/1RJczowG-ZXIm6Wxspvd9Jt0f5mPd5PJt/view?usp=sharing)

**Comment by oleschoenburg** [comment] 2023-11-16 15:04
Duplicate of https://github.com/camunda/zeebe/issues/14819

**Closed by oleschoenburg** 2023-11-16 15:04 UTC
Labels: kind/bug
