### ISSUE TITLE
Flaky BrokerReprocessingTest.shouldResolveIncidentAfterRestart

### ISSUE THREAD

**Issue by npepinpe** [camunda/zeebe#14165] opened 2023-09-05 15:57 UTC
**Summary**

- How often does the test fail? once
- Does it block your work? no
- Do we suspect that it is a real failure? probably not

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
BrokerReprocessingTest.shouldResolveIncidentAfterRestart:339->deleteSnapshotsAndRestart:644 ? TestTimedOut test timed out after 120 seconds
</pre>
</details>

**Logs**

[io.camunda.zeebe.it.startup.BrokerReprocessingTest-1-output.txt](https://github.com/camunda/zeebe/files/12525760/io.camunda.zeebe.it.startup.BrokerReprocessingTest-1-output.txt)

**Context**

https://github.com/camunda/zeebe/actions/runs/6086831488

**Comment by berkaycanbc** [comment] 2023-09-06 10:38
Marking as upcoming since we prioritise flaky tests. Good candidate for our mob-programming sessions.

**Comment by ana-vinogradova-camunda** [comment] 2024-03-01 14:45
I couldn't reproduce the issue locally (run the all tests in BrokerReprocessingTest class around 1000 times).

The issues seems to be unrelated to `shouldResolveIncidentAfterRestart` test logic, the logic itself looks correct to me.

This test is run with parameters:

- Broker is restarted for the first test run
- Snapshots are deleted and broker is restarted for the second test run

The issue occurred during second broker restart (`EmbeddedBrokerRule` -> `startBroker`). The following error occured:
`Broker was not started in 15 seconds`

The below exception occurred in `ActorControl` -> `call` method:
`java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: Incorrect usage of actor.call(...) cannot be called from current actor.`

As this was observed only once and is not test logic related, I will closed the issue. Please feel free to re-open if this happens again and we'll investigate further.

**Closed by ana-vinogradova-camunda** 2024-03-01 14:45 UTC
Labels: kind/flake
