### ISSUE TITLE
Expand button of the sub process (collapsed) is hidden by comments button

### ISSUE THREAD

**Issue by takumi-miyajima** [camunda/zeebe#14288] opened 2023-09-13 01:27 UTC
**Describe the bug**

Expand button of the sub process (collapsed) is hidden by comments button.
This problem is CSS bug.

If the repository is more appropriate for `camunda/camunda-bpm-platform`, please move the issue.
(I didn't know which way to post the version8 issue.)

**To Reproduce and Expected behavior**

Please watch the video.

https://github.com/camunda/zeebe/assets/73204221/ceb5e0ce-0184-4078-981f-cf53c6614219

**Environment:**
- Zeebe Version: 8.2

**Comment by qhnu** [comment] 2023-09-13 04:11
This is a proposal for a modification.

Instead of "comment button css fixed", how about "move hierarchy by clicking plus button"?

If the plus button can be used to move through the hierarchy, this would solve this bug and at the same time allow for one-click hierarchies.

It would be a great UX experience to be able to move through the hierarchy with one click.

<img width="129" alt="スクリーンショット 2023-09-13 13 01 27" src="https://github.com/camunda/zeebe/assets/73204221/6afa35da-9ede-4840-8928-047fceb757ac">

**Comment by npepinpe** [comment] 2023-10-20 09:23
@nikku - I'm not sure what's the appropriate repo for this either, if it's bpmn-js or the modeler. Could you transfer this issue to the right one? Thanks!

**Comment by nikku** [comment] 2023-10-20 10:24
@qhnu This does not look like an engine issue, but an issue in the [modeling tools](https://docs.camunda.io/docs/components/modeler/about-modeler/) that support it.

In this sense could you please make clear which modeler you use? We're happy to look into this issue.

**Comment by qhnu** [comment] 2023-10-20 12:22
@nikku
The problem is happening with `Web Modeler`
It is happening on [camunda](https://camunda.com/) cloud service.

**Comment by remcowesterhoud** [comment] 2023-11-08 14:18
@nikku Did you follow up on this issue? As it's on the modeler side I will close it here

**Closed by remcowesterhoud** 2023-11-08 14:18 UTC
Labels: kind/bug

**Comment by nikku** [comment] 2023-11-08 14:38
@takumi-miyajima I've forwarded your report to the web modeler folks. Thanks!
