### ISSUE TITLE
Performance regression in 1.3.0-alpha2

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#8425] opened 2021-12-17 14:55 UTC
**Describe the bug**

It looks like we have a performance regression in our latest alpha release, at least this can be seen in the long running benchmarks.

### Alpha 2

![perf](https://user-images.githubusercontent.com/2758593/146561847-77de9298-c5fa-4717-920e-491dd0d9d390.png)

We can see that the throughput is much lower than on alpha1 and we have a high fluctuation of the current events and handled requests.

#### Latency

The latency seems to be much higher and be unstable as well.

![alpha2-latency](https://user-images.githubusercontent.com/2758593/146562983-ec1e785e-5ff9-40a0-ac1e-f4060c6e2c87.png)
![alpha2-latency2](https://user-images.githubusercontent.com/2758593/146562987-46c7099c-399a-480a-8bbb-8bd49d8edecc.png)

#### Leader

I can't see any related leader changes or similar things

![alpha2-leader](https://user-images.githubusercontent.com/2758593/146563037-abab06a6-7a4f-4225-86a2-d4b6bd56bfde.png)

### Previous alpha version:

![perfalpa1](https://user-images.githubusercontent.com/2758593/146562015-0932b9a0-e895-45f7-bfab-90144f6c3076.png)

#### Latency

![alpha1-latency](https://user-images.githubusercontent.com/2758593/146562827-068317a8-1d63-411b-8445-5627f859504c.png)
![alpha1-latency2](https://user-images.githubusercontent.com/2758593/146562831-4c138894-ec2a-47f5-830f-8cfd0e863eba.png)

**To Reproduce**

Run a long running benchmark?

**Expected behavior**

Similar throughput and latency, then in previous version. E.g. 200 PI/s.

**Environment:**
 - OS: 
 - Zeebe Version: 1.3.0-alpha2
 - Configuration:

**Comment by npepinpe** [comment] 2021-12-20 09:12
@Zelldon are you already looking into it?

**Comment by Zelldon** [comment] 2021-12-20 09:12
Nope @npepinpe

**Comment by Zelldon** [comment] 2021-12-21 10:25
Still the case:

![general](https://user-images.githubusercontent.com/2758593/146914355-b1957407-1702-4233-a26a-d998cb2106f9.png)

**Comment by oleschoenburg** [comment] 2021-12-21 10:26
Pattern reminds me of this: https://github.com/camunda-cloud/zeebe/issues/8244

**Comment by Zelldon** [comment] 2021-12-21 10:31
True @oleschoenburg just the difference that we only running normal starters and worker

When we zoom in it looks really similar
![zoom](https://user-images.githubusercontent.com/2758593/146915036-9b0b1e9b-d8e6-4779-be1a-128a64cc88ae.png)

**Comment by korthout** [comment] 2021-12-23 16:04
We've not seen this pattern again on benchmarks for `release-1.3.0` like [release-1-3-0](http://34.77.165.228/d/I4lo7_EZk/zeebe?orgId=1&refresh=10s&var-DS_PROMETHEUS=Prometheus&var-namespace=release-1-3-0&var-pod=All&var-partition=All) (preemptible nodes on zeebe cluster) and [zell-test-release-1-3](http://35.189.240.202/d/I4lo7_EZk/zeebe?orgId=1&refresh=10s&var-DS_PROMETHEUS=Prometheus&var-namespace=zell-test-release-1-3&var-pod=All&var-partition=All&from=now-1h&to=now) (non-preemptible nodes on long-running cluster). We also did not encounter it on [long-running-v1-for-minor-updates](http://35.189.240.202/d/I4lo7_EZk/zeebe?orgId=1&refresh=10s&from=now-1h&to=now&var-DS_PROMETHEUS=Prometheus&var-namespace=long-running-v1-for-minor-updates&var-pod=All&var-partition=All) (which is currently running on 1.2.7).

We should still investigate what is going wrong with [release-1-3-alpha2](http://35.189.240.202/d/I4lo7_EZk/zeebe?orgId=1&refresh=10s&from=now-1h&to=now&var-DS_PROMETHEUS=Prometheus&var-namespace=release-1-3-alpha2&var-pod=All&var-partition=All) (non-preemptible nodes on long running cluster)

**Comment by Zelldon** [comment] 2022-01-05 12:35
@npepinpe it seems the alpha2 benchmark has recovered also the release benchmark on stable nodes look okish.

## Alpha2
![alpha2](https://user-images.githubusercontent.com/2758593/148218200-01868fa6-636f-4f73-b007-511e26578466.png)

## Release 1.3

![release](https://user-images.githubusercontent.com/2758593/148218205-cf595bb4-e95f-47ff-abbe-b8ce26237e45.png)

## Preemptable Nodes
On preemptable nodes it looks different and seems that we degrading performance. But this might also be related to our benchmark resources. I will start one benchmark with higher resources. 

### Release
![preempt-release](https://user-images.githubusercontent.com/2758593/148218361-979ed5e5-7340-42f1-b809-6f4bd565b0e9.png)

### Medic CW 51

![medic51](https://user-images.githubusercontent.com/2758593/148218359-ff79b1eb-41e2-40a6-8dec-e4b3269e7640.png)

### Medic CW 50

As a comparison to show how latency and throughput looked before.

![medic50](https://user-images.githubusercontent.com/2758593/148218427-c44b51b5-9305-4bf6-9ac5-20a491754f3b.png)

![medic50-latency](https://user-images.githubusercontent.com/2758593/148218430-c8e38d32-1d46-43ac-9d2d-147b45582028.png)


### Medic CW 01

What we can see is that the latency increased by factor two at least. The throughput graph looks also whether it will slowly decreasing.

![medic01](https://user-images.githubusercontent.com/2758593/148218476-df42a7fa-8be8-4b21-a430-71ad36b3af0c.png)
![medic01-latency](https://user-images.githubusercontent.com/2758593/148218480-aac9ce16-63b5-4ad2-ad33-993601fb7bac.png)

\cc @korthout

**Comment by Zelldon** [comment] 2022-01-06 07:25
I run two new benchmarks. One with the resource reduction (our current develop) and one without (revert the merge of #8268").

What we can see is that on both the performance is degraded (we not reaching our expected throughput of ~200 PI/s). 

With the old setup (No resource reduction) we reach ~184 PI/s, which is better than with the resource reduction (~177 PI/s). But we need to be aware that on the other benchmark one node is leader for all partitions, so it is not completely comparable. For better comparability we could run a benchmark with one partition. To be able to compare we need to run the current setup, the old setup with develop and an older release with both configurations.

## No resource reduction

![withoutresreduction](https://user-images.githubusercontent.com/2758593/148344660-80576205-ef4d-4de9-a7e9-5e3e588e32f8.png)

![withoutresreduction-latency](https://user-images.githubusercontent.com/2758593/148344665-6b535b5c-cf90-4599-ba04-eb8d565fac94.png)

## Current Develop

![devwithresreduction](https://user-images.githubusercontent.com/2758593/148343435-2112b94a-4de0-4d66-aa07-f7cf36814901.png)

![devwithresreduction-latency](https://user-images.githubusercontent.com/2758593/148343438-1f55e404-89d4-4f4c-a112-f3d8850b6f1b.png)

**Comment by Zelldon** [comment] 2022-01-06 07:36
New benchmarks configuration: 

 * 3 Worker a 120 max activation count
 * 1 Starter 100 PI/s
 * 1 Partition
 * Clustersize 3
 * Replication 3

With that we can make sure that only one node is leader for one partition. First we need to verify whether the benchmark with resource reduction (on dev) reaches 100 PI/s. If this is the case we need to increase the load until we reach a limit (where it is not able to keep up with the load). Then we can start with the other benchmarks, otherwise if all reach the 100 PI/s the tests would be useless.

_**I will update this comment over the day.**_

**Comment by npepinpe** [comment] 2022-01-06 12:47
I'm convinced, we don't need to prove more that there is a performance degradation. What're the next steps then to identify what happened? Do we have any leads? Is the performance constantly degraded or is it over time?

**Comment by Zelldon** [comment] 2022-01-06 12:56
@npepinpe it seems to be constant. I will try the alphas first and then try to go over to the medic week benchmarks.

**Comment by Zelldon** [comment] 2022-01-06 15:11
Currently it seems to be introduced between alpha1 and alpha2, I will write an update tomorrow morning I think I have to run it a bit longer.

## Alpha1
![alpha1](https://user-images.githubusercontent.com/2758593/148404431-d1b4fef0-65db-4b86-b875-52c32bec24d9.png)

## Alpha2
![alpha2](https://user-images.githubusercontent.com/2758593/148404436-0bf729b4-2aad-493b-9e10-086c08846731.png)

**Comment by Zelldon** [comment] 2022-01-07 08:32
I have run the benchmarks over night, and have some more insights.

In general it seems that the degrade of performance is caused by higher commit latency. It seems that from time to time the commit latency goes up to 100-250 ms, if this happens the throughtput goes down. This can also happen on 1.2.9 it seems. But in 1.2.9 it is not so likely (?). 

## Benchmarks last 24h

### 1.2.9


The throughput dropped in 1.2.9 for a short period of time to the same level we see in other benchmarks, which seems to be an indicator for me that we had the issue already before @npepinpe 
![129-general-24h](https://user-images.githubusercontent.com/2758593/148513762-e6360729-669f-4dc5-91a7-c3527307a362.png)

![129-latency-24h](https://user-images.githubusercontent.com/2758593/148513770-0fcd37fe-f55a-4353-8e2c-679c876f008f.png)

We can see in the metrics that 1.2.9 has most of the time a commit latency of 25-50 (and partly 50-70). If we reach 100-250 then the throughput reaches the same level as on the other benchmarks. 

![129-latency-2-24h](https://user-images.githubusercontent.com/2758593/148513768-91b681f8-64de-4942-8fe3-115fc1a9fce8.png)

### Alpha 1

Alpha1 seems to show a similar pattern. If we reach the high latency bucket 100-250 the throughput reaches the level of ~74 PI/s. If we are in the 25-50 bucket the throughput seems to be ~90 and in 50-100 (which is most of the time) we reach ~80 PI/s.

![alpha1-general-24h](https://user-images.githubusercontent.com/2758593/148513832-2a4f1a89-676d-4287-9653-bb78fe44f1d5.png)
![alpha1-latency-24h](https://user-images.githubusercontent.com/2758593/148513835-c638fbd1-07f6-4421-8a35-648a3a7700e2.png)

### Alpha 2

This benchmark is interesting because we see here most of the time a really high commit latency and the low throughput, here it seems not to become better. I think we currently have some issues with the resolution of the latency metrics. The bucket 100-250 ms is quite large. I think it make sense to adjust the defined bucket to have a bitter better and fine granular view.

![alpha2-general-24h](https://user-images.githubusercontent.com/2758593/148513858-1ac820ca-30b2-47a3-8e08-b6e13573b76f.png)
![alpha2-latency-24h](https://user-images.githubusercontent.com/2758593/148513862-b206d3d4-6d1c-400b-b0e2-2430982ced56.png)

### Alpha 2 - 2

I started a second alpha2 benchmark to make sure that this happen again. This and the next benchmark show similar pattern (unstable latency).

![alpha2-2-general-24h](https://user-images.githubusercontent.com/2758593/148513948-32211b6b-9e66-49ab-8a55-da8df3b92052.png)
![alpha2-2-latency-24h](https://user-images.githubusercontent.com/2758593/148513950-6e70b27d-617e-4ec4-b009-0b5d6b30bcdc.png)

### Develop (1.3)

![dev-general-24h](https://user-images.githubusercontent.com/2758593/148515143-4a2e6d69-66e1-4a57-8d1e-0619f2024de2.png)
![dev-latency-24h](https://user-images.githubusercontent.com/2758593/148515149-ba42ce48-48c6-4bac-b301-2af8ef72c192.png)

## Conclusion

I think it makes sense to look into the commit latency, why it is sometimes fluctuating so much, what can affect this etc. Since this was already before the case, I would propose to close this issue and create a new issue, which concentrates on the commit latency. Wdyt? @npepinpe 

Furthermore I would like to improve our current metrics to make it more fine granular (reduce the bucket range).

**Comment by npepinpe** [comment] 2022-01-07 08:34
Create a new issue and leave this issue open. We can put this one back into planned for now, and work on the new one. But until we've fixed the performance issue then I would leave it open, as right now the commit latency is just a theory.

**Comment by npepinpe** [comment] 2022-01-19 14:10
Moving to the backlog until Q2. We'll accept a 15% throughput loss for now, as we could not pinpoint a single root cause, implying it may be simply an accumulation of things. Reverting each is not exactly worth it, and instead we'll commit on improving performance in Q2, as well as commit to no further performance loss for 1.4. That means throughput losses between 1.3 and 1.4 would be release blockers, and medics should pay close attention to the weekly benchmarks until then so we catch these as fast as possible.

**Comment by Zelldon** [comment] 2022-01-22 19:23
I did some benchmarks with 1.2.9 and develop, with one partition and only the simple starter (which starts a process with start and end event). In both benchmarks we can see that the throughput is almost the same. It seems that it might be more related to tasks or jobs, or it is more visible with them?

We see in both the same pattern, up and down of the throughput and quite high (with really high spikes in commit latency). The backlog is also really high most of the time.

### 1.2.9

![simple129](https://user-images.githubusercontent.com/2758593/150652665-676c5963-078d-4533-999b-a9e18fda023c.png)

### Develop 

![simple](https://user-images.githubusercontent.com/2758593/150652664-7e78f556-2b1f-4c93-afa6-f8d5f781480c.png)

**Comment by Zelldon** [comment] 2022-06-02 12:25
Long running benchmarks are back to ~200 pi/s

![longrun](https://user-images.githubusercontent.com/2758593/171628634-ecee8ca6-a888-4ddb-b54c-b37610955aae.png)

Medic benchmarks are around ~180

![medicrun](https://user-images.githubusercontent.com/2758593/171628646-dd4e717a-06ec-4295-84d2-a7c8b1b1dcfb.png)

**Closed** 2022-06-02 12:25 UTC
Labels: kind/bug, area/performance, severity/mid
