### ISSUE TITLE
IllegalStateException: found snapshot 0. A previous snapshot is most likely corrupted

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/zeebe#14699] opened 2023-10-12 13:04 UTC
**Describe the bug**

During startup of the broker Zeebe encounters snapshot 0. Likely an indication of some corruption.

We encountered this before on prod. The solution was to delete the partition data and restart the broker. After this the broker recovers. When we first found it https://github.com/camunda/zeebe/issues/14486 was created. This was released in 8.3.0. However, today it occurred again on 8.3.0. 

**To Reproduce**

Unclear, but it's probably hard to do as you'd need to introduce some corruption.

**Expected behavior**

It is handled more gracefully and doesn't prevent the broker from reaching a bootloop.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: In partition 1 expected to find a snapshot at index >= log's first index 30443521, but found snapshot 0. A previous snapshot is most likely corrupted.
at io.atomix.raft.utils.StateUtil.verifySnapshotLogConsistent ( io/atomix.raft.utils/StateUtil.java:33 )
at io.atomix.raft.impl.RaftContext.<init> ( io/atomix.raft.impl/RaftContext.java:223 )
at io.atomix.raft.impl.DefaultRaftServer$Builder.build ( io/atomix.raft.impl/DefaultRaftServer.java:242 )
at io.atomix.raft.impl.DefaultRaftServer$Builder.build ( io/atomix.raft.impl/DefaultRaftServer.java:216 )
at io.atomix.raft.partition.impl.RaftPartitionServer.buildServer ( io/atomix.raft.partition.impl/RaftPartitionServer.java:159 )
at io.atomix.raft.partition.impl.RaftPartitionServer.<init> ( io/atomix.raft.partition.impl/RaftPartitionServer.java:91 )
at io.atomix.raft.partition.RaftPartition.createServer ( io/atomix.raft.partition/RaftPartition.java:127 )
at io.atomix.raft.partition.RaftPartition.initServer ( io/atomix.raft.partition/RaftPartition.java:110 )
at io.atomix.raft.partition.RaftPartition.bootstrap ( io/atomix.raft.partition/RaftPartition.java:94 )
at io.camunda.zeebe.broker.partitioning.startup.steps.RaftBootstrapStep.startup ( io/camunda.zeebe.broker.partitioning.startup.steps/RaftBootstrapStep.java:31 )
at io.camunda.zeebe.broker.partitioning.startup.steps.RaftBootstrapStep.startup ( io/camunda.zeebe.broker.partitioning.startup.steps/RaftBootstrapStep.java:14 )
at io.camunda.zeebe.scheduler.startup.StartupProcess.proceedWithStartupSynchronized ( io/camunda.zeebe.scheduler.startup/StartupProcess.java:161 )
at io.camunda.zeebe.scheduler.startup.StartupProcess.lambda$proceedWithStartupSynchronized$3 ( io/camunda.zeebe.scheduler.startup/StartupProcess.java:169 )
at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run ( io/camunda.zeebe.scheduler.future/FutureContinuationRunnable.java:28 )
at io.camunda.zeebe.scheduler.ActorJob.invoke ( io/camunda.zeebe.scheduler/ActorJob.java:94 )
at io.camunda.zeebe.scheduler.ActorJob.execute ( io/camunda.zeebe.scheduler/ActorJob.java:45 )
at io.camunda.zeebe.scheduler.ActorTask.execute ( io/camunda.zeebe.scheduler/ActorTask.java:119 )
at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask ( io/camunda.zeebe.scheduler/ActorThread.java:130 )
at io.camunda.zeebe.scheduler.ActorThread.doWork ( io/camunda.zeebe.scheduler/ActorThread.java:108 )
at io.camunda.zeebe.scheduler.ActorThread.run ( io/camunda.zeebe.scheduler/ActorThread.java:227 )
```

</p>
</details>

**Environment:**
- OS: SaaS
- Zeebe Version: 8.3.0

https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22%0Aresource.labels.namespace_name%3D%22f2275ddc-b3a0-44b4-bc8a-cdfc242514f1-zeebe%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22;pinnedLogId=2023-10-12T12:31:31.413159098Z%2Fa7opurgfpm3zpxtj;cursorTimestamp=2023-10-12T12:53:35.349727194Z;duration=PT3H?project=camunda-saas-int-chaos

**Comment by oleschoenburg** [comment] 2023-10-12 13:44
Since this is not fixed by https://github.com/camunda/zeebe/issues/14486 we need to investigate this!

**Comment by npepinpe** [comment] 2023-10-12 13:49
Did anyone check what was on disk? Did we save the "corrupted" snapshot?

**Comment by deepthidevaki** [comment] 2023-10-16 07:13
related #14594

**Comment by rodrigo-lourenco-lopes** [comment] 2023-10-17 07:59
This issue also happened again in a trial cluster also with the 8.3.0 version. [Alert](https://camunda.slack.com/archives/C04D5HLFP24/p1697503341553379), [Logs](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.cluster_name%3D%22prod-worker-3%22%0Aresource.labels.namespace_name%3D%2236891658-b31b-4efa-bbbc-7dbef6acec10-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Aresource.labels.container_name%3D%22zeebe%22%0A;pinnedLogId=2023-10-17T06:45:28.130308499Z%2Fldkhiotcmp0x0y7s;cursorTimestamp=2023-10-17T06:45:28.213227478Z;duration=PT12H?project=camunda-cloud-240911).

**Comment by Zelldon** [comment] 2023-10-17 16:11
Happened again.

Was not able to connect to the failing pod had to delete the PVC and pod:

```
  k delete pvc data-zeebe-2 & k delete pod zeebe-2
```

**Comment by npepinpe** [comment] 2023-10-18 13:08
Thinking out loud...

Immediate hypothesis: the broker was shutdown right before this happened, without apparent error (so graceful shutdown).

We already have a regression where we delete pending snapshots concurrently, outside of the snapshot store actor. What if we had been persisting the snapshot (on the actor) while the Raft partition was shutting down (thus deleting pending snapshots on the Raft thread)?

Hm, I don't think that's possible actually, since the Raft thread waits for the persist operation to finish before doing anything else...

So the changes we did to snapshot:

- No integrity check after the move - if the move is not done completely, then the snapshot may be corrupted.
- However, we only write the checksum file once the move is done, so if the node crashed during the move we would have no checksum file and would not consider the snapshot persisted.

**Comment by npepinpe** [comment] 2023-10-18 13:09
It's currently happening on a cluster, so I had a chance to look at the data. I've uploaded the partition's snapshot directory here:

https://drive.google.com/file/d/10cMGw7QPepM5euTNl3tWfuaLHVnuQ5YI/view?usp=share_link

The snapshot itself looks fine. But we can see the checksum file is completely empty :scream:

**Comment by npepinpe** [comment] 2023-10-18 13:29
Hm, this happened right after this bug: https://github.com/camunda/zeebe/issues/14776

I wonder if it's not related. We open the checksum file, but crash before we can write. The file now exists, but it's empty.

Oops.

**Closed** 2023-10-19 15:54 UTC
Labels: kind/bug, severity/critical, component/snapshot
