### ISSUE TITLE
Stuck modification of failed subprocess

### ISSUE THREAD

**Issue by jdurcik** [camunda/zeebe#11177] opened 2022-12-05 09:21 UTC
**Describe the bug**

If the mapping of variables from a subprocess fails and then I modify the process using operate, the modification operation remains stuck. I tried a similar case of modification - moving a process from a failed external task, but it was successful.

**To Reproduce**

- Deploy two definitions - [definitions.zip](https://github.com/camunda/zeebe/files/10152423/definitions.zip).
- Run instance of "parent".
- It fails because the mapping of the child variables is incorrect (the variable is missing in the child process).
- After it fails, make a modification, moving the process to its end.
<img width="2560" alt="Snímek obrazovky 2022-12-05 v 9 57 55" src="https://user-images.githubusercontent.com/98015044/205595744-89dea94e-5b3b-4e21-a00d-353cca19cfcf.png">

- Modification gets stuck.

**Expected behavior**

The modification does not get stuck.

**Environment:**
- OS: oficial docker image on k8s 1.20 on debian 10
- Zeebe Version: 8.1.4

**Comment by remcowesterhoud** [comment] 2022-12-05 13:24
Thanks for reporting @jdurcik! This is a duplicate of #10606. I'm happy to tell you that this is already fixed and will be part of the `8.1.5` patch release this week 🙂 

I will close this issue.

**Closed by remcowesterhoud** 2022-12-05 13:24 UTC
Labels: kind/bug
